In [1]:
import pandas as pd
import numpy as np
import paramiko
from scp import SCPClient
from isd import Batch
from meteostat import Stations, Hourly
from timezonefinder import TimezoneFinder
from datetime import datetime, timedelta, date
import pytz
import os

Define parameters

In [4]:
import pandas as pd
import numpy as np
import paramiko
from scp import SCPClient
from isd import Batch
from meteostat import Stations, Hourly
from timezonefinder import TimezoneFinder
from datetime import datetime, timedelta, date
import pytz
import requests
import ssl
import io
import sys
import os


def convert_utc_to_local(df, local_tz):
    """
    Convert the datetime index of the DataFrame from UTC to a local timezone.

    Args:
    df : pandas.DataFrame
        DataFrame with a datetime index in UTC.
    local_tz : str
        A timezone string (e.g., 'America/Chicago').

    Returns:
    pandas.DataFrame
        DataFrame with datetime index converted to the specified local timezone.
    """
    if not pd.api.types.is_datetime64_any_dtype(df.index):
        df = df.reset_index(level='station', drop=True)
        df.index = pd.to_datetime(df.index)

    if df.index.tz is None:
        df.index = df.index.tz_localize('UTC')
    
    df.index = df.index.tz_convert(local_tz)
    return df

def filter_dataframe_by_date(df, start_date, end_date, timezone=None):
    """
    Filter the DataFrame to include rows between the specified start and end dates,
    handling timezone differences appropriately.
    """
    start_date = pd.to_datetime(start_date)
    end_date = pd.to_datetime(end_date)

    if timezone:
        start_date = start_date.tz_localize(timezone)
        end_date = end_date.tz_localize(timezone)
    else:
        df.index = df.index.tz_localize(None)

    return df.loc[(df.index >= start_date) & (df.index <= end_date)]

def get_parameters_MERRA2(lat, lon, year):
    api_endpoint = f"https://power.larc.nasa.gov/api/temporal/hourly/point?community=SB&parameters=&longitude={lon}&latitude={lat}&start={year}0101&end={year}1231&format=EPW"
    response = requests.get(api_endpoint)
    csv_data = io.StringIO(response.text)
    df = pd.read_csv(csv_data, skiprows=8, header=None)
    header = '\n'.join(response.text.splitlines()[:8])

    # Check if the dataframe has more than 8761 rows and truncate if necessary
    # Sometimes MERRA2 erroneously provides extra rows
    if len(df) > 8760:
        df = df.iloc[:8760]


    return df, header

# def merge_data(df, data):
#     """
#     Merges two datasets, replacing specific columns in `df` with corresponding values from `data`.
#     """

#     print(df.head(5))
#     for col in [6, 7, 8, 33, 30, 21, 20, 9]:  # Replace indices with more descriptive names if possible
#         if not df[col].isna().all():
#             df[col] = list(data['temp'][1:])
#     print(df.head(5))
#     return df


def merge_data(df, data):
    # Tdb
    if not data['temp'].isna().all():
        df[6] = list(data['temp'][1:])
    # Tdew
    if not data['dwpt'].isna().all():
        df[7] = list(data['dwpt'][1:])
    # RH
    if not data['rhum'].isna().all():
        df[8] = list(data['rhum'][1:])
    # Precep
    if not data['prcp'].isna().all():
        df[33] = list(data['prcp'][1:])
    # Snow
    if not data['snow'].isna().all():
        df[30] = list(data['snow'][1:])
    # Wspeed
    if not data['wspd'].isna().all():
        df[21] = list(data['wspd'][1:])
    # Wdir
    if not data['wdir'].isna().all():
        df[20] = list(data['wdir'][1:])
    # P, go from hPa to Pa
    if not data['pres'].isna().all():
        df[9] = [x * 100 for x in list(data['pres'][1:])]

    return df

def check_missing_hours(year, df):
    """
    Checks for missing hours in the DataFrame's datetime index for a specified year.
    """
    full_index = pd.date_range(start=f"{year}-01-01", end=f"{year+1}-01-01", freq="H")
    missing_hours = full_index.difference(df.index)
    missing_hours_num = len(missing_hours)

    if missing_hours_num > 0:
        diffs = missing_hours.to_series().diff().dt.total_seconds().div(3600)
        largest_consecutive_group = (diffs != 1).cumsum().value_counts().max()
    else:
        largest_consecutive_group = 0

    return missing_hours_num, largest_consecutive_group

def get_noaa_merra2_data(lat, lon, year, file_type, save_folder):
    """
    Retrieves NOAA and MERRA2 data for a specific location and year.
    """
    retrieve_status = True
    data_noaa, tz, distance, elevation, wmo, station_name, state, country, latitude_station, longitude_station, epw_exists, incomplete_timeseries = get_data_noaa(lat, lon, year, save_folder)
    if epw_exists:
        df_merged = ''
        retrieve_status = False
        distance = ''
        hdd = ''
        cdd = ''
        latitude_station = ''
        longitude_station = ''
        info_dict = ''
        epw_exists = True
        return df_merged, retrieve_status, info_dict, distance, hdd, cdd, wmo, latitude_station, longitude_station, epw_exists
    elif incomplete_timeseries:
        df_merged = ''
        retrieve_status = False
        distance = np.nan
        hdd = ''
        cdd = ''
        latitude_station = ''
        longitude_station = ''
        info_dict = '' 
        wmo = ''
        epw_exists = False
        return df_merged, retrieve_status, info_dict, distance, hdd, cdd, wmo, latitude_station, longitude_station, epw_exists

    try:
        data_noaa_tz_adj = filter_dataframe_by_date(convert_utc_to_local(data_noaa, tz), datetime(year, 1, 1), datetime(year+1, 1, 1))
    except AttributeError:
        # print("We don't have NOAA data for this location/year")
        df_merged = ''
        retrieve_status = False
        distance = np.nan
        hdd = ''
        cdd = ''
        latitude_station = ''
        longitude_station = ''
        info_dict = '' 
        epw_exists = False
        return df_merged, retrieve_status, info_dict, distance, hdd, cdd, wmo, latitude_station, longitude_station, epw_exists

    info_dict = {
    'timeshift': get_time_shift(tz),
    'elevation': elevation,
    'wmo': wmo,
    'station_name': station_name,
    'state': state,
    'country': country,
    'lat': latitude_station,
    'lon': longitude_station,
    'weather_file_type': file_type
    }

    data_noaa_tz_adj_h = data_noaa_tz_adj.resample('H').mean()
    data_noaa_tz_adj_h_interpolated = data_noaa_tz_adj_h.interpolate(method='linear', limit=3, limit_direction='forward')
    hdd, cdd = calculate_hdd_cdd(data_noaa_tz_adj_h_interpolated, 'temp')
    df_merra2, header_merra2 = get_parameters_MERRA2(latitude_station, longitude_station, year)

    df_merged = merge_data(df_merra2, data_noaa_tz_adj_h_interpolated)

    return df_merged, retrieve_status, info_dict, distance, hdd, cdd, wmo, latitude_station, longitude_station, epw_exists

def run_individual_location(lat, lon, year, file_type, save_folder, save_name):
    """
    Processes a single location, fetching data and handling errors.
    """
    data_meteostat_merra2, retrieve_status, info_dict, distance, hdd, cdd, wmo, latitude_station, longitude_station, epw_exists = get_noaa_merra2_data(lat, lon, year, file_type, save_folder)
    if epw_exists:
        retrieve_status = False
        distance = ''
        hdd = ''
        cdd = ''
        latitude_station = ''
        longitude_station = ''
        retrieve_info_closest_other_locations = True
        # return retrieve_status, distance, info_dict['wmo'], hdd, cdd, latitude_station, longitude_station, retrieve_info_closest_other_locations
    elif retrieve_status:
        retrieve_info_closest_other_locations = False
        #Save the EPW file
        if save_name != None:
            output_path = os.path.join(save_folder, f"{save_name.replace(' ', '_').replace('.', '_')}_{year}.epw")
        else:
            output_path = os.path.join(save_folder, f"{wmo}_{year}.epw")
        data_meteostat_merra2.to_csv(output_path, header=False, index=False)
        with open(output_path, 'r') as original_file:
            data_content = original_file.read()
        header_lines = create_header(data_meteostat_merra2, year, info_dict)
        with open(output_path, 'w') as new_file:
            new_file.write("\n".join(header_lines) + "\n" + data_content)
    else:
        retrieve_info_closest_other_locations = False
        retrieve_status = False
        print('No data available for this location/year.')

    return retrieve_status, distance, wmo, hdd, cdd, latitude_station, longitude_station, retrieve_info_closest_other_locations

def get_time_shift(timezone_name):
    """
    Calculates the time shift for a given timezone from UTC.
    """
    timezone = pytz.timezone(timezone_name)
    now = datetime.now(timezone)
    utc_offset = now.utcoffset()
    return int(utc_offset.total_seconds() // 3600)  # Return hours offset only

def calculate_hdd_cdd(df, temperature_column):
    """
    Calculate Heating Degree Days (HDD) and Cooling Degree Days (CDD) from hourly temperature data in Celsius.
    """
    df[temperature_column + '_F'] = df[temperature_column] * 9 / 5 + 32
    base_temperature = 65

    df['date'] = df.index.to_series().dt.date
    daily_mean_temp = df.groupby('date')[temperature_column + '_F'].mean().reset_index()
    daily_mean_temp.columns = ['date', 'mean_temp']

    daily_mean_temp['HDD'] = (base_temperature - daily_mean_temp['mean_temp']).clip(lower=0)
    daily_mean_temp['CDD'] = (daily_mean_temp['mean_temp'] - base_temperature).clip(lower=0)

    total_hdd = daily_mean_temp['HDD'].sum()
    total_cdd = daily_mean_temp['CDD'].sum()

    return int(total_hdd), int(total_cdd)

def check_epw_exists(save_folder, year, wmo):
    return os.path.exists(f'{save_folder}/{wmo}_{year}.epw')

def create_header(df, year, info_dict):
    header_lines = []

    #Calculated parameters 
    first_day_year = pd.to_datetime(date.min.replace(year=year)).day_name()
    leap_status = lambda year: 'Yes' if year % 4 == 0 and (year % 100 != 0 or year % 400 == 0) else 'No'
    dst_start, dst_end = get_dst_start_end(year, info_dict['lat'], info_dict['lon'])
    design_conditions_file = 'resources/design_conditions.csv'
    design_conditions_line = find_closest_design_condition(float(info_dict['lat']), float(info_dict['lon']), design_conditions_file)
    #Hardcoded parameters
    number_of_holidays = 0
    number_of_data_periods = 1
    number_of_records_per_hour = 1

    # line_1
    header_lines.append(f"LOCATION,{info_dict['station_name']},{info_dict['state']},{info_dict['country']},{info_dict['weather_file_type']},{info_dict['wmo']},{info_dict['lat']},{info_dict['lon']},{info_dict['timeshift']},{info_dict['elevation']}")
    # line_2
    header_lines.append(design_conditions_line)
    # line_3
    header_lines.append(f"TYPICAL/EXTREME PERIODS,0")
    # line_4
    header_lines.append(f"GROUND TEMPERATURES,0")
    # header_lines.append(f"GROUND TEMPERATURES,3,.5,,,,-16.34,-17.80,-15.22,-11.16,-0.57,7.61,13.13,14.81,11.95,5.60,-2.89,-10.76,2,,,,-10.97,-13.57,-13.04,-10.89,-3.80,2.61,7.74,10.49,9.90,6.30,0.46,-5.74,4,,,,-6.53,-9.19,-9.78,-8.97,-4.96,-0.64,3.32,6.08,6.72,5.16,1.73,-2.4")
    # line_5
    try:
        header_lines.append(f"HOLIDAYS/DAYLIGHT SAVINGS,{leap_status(year)},{dst_start.month}/{dst_start.day},{dst_end.month}/{dst_end.day},{number_of_holidays}")
    except AttributeError:
        #We cannot retrieve DST dates, let's set them to 0
        header_lines.append(f"HOLIDAYS/DAYLIGHT SAVINGS,{leap_status(year)},0,0,{number_of_holidays}")
    # line_6
    header_lines.append(f"COMMENTS 1, ")
    # line_7
    header_lines.append(f"COMMENTS 2, ")
    # line_8
    header_lines.append(f"DATA PERIODS,{number_of_data_periods},{number_of_records_per_hour},Data,{first_day_year},{df.iloc[0, 1]}/{df.iloc[0, 2]},{df.iloc[-1, 1]}/{df.iloc[-1, 2]}")

    return header_lines

def fix_wmo(wmo):
    """
    Attempts to fix or standardize the WMO code format.
    """
    try:
        return str(int(wmo))
    except ValueError:
        icao = wmo
        icao_converted = get_wmo_from_icao_NOAA(icao)
        if isinstance(icao_converted, type(None)):
            return icao
        else:
            return icao_converted

    # return wmo

def get_data_noaa(lat, lon, year, save_folder):
    """
    Fetches NOAA data for a given location and year, handling timezones and missing data.
    """
    # Disable SSL verification
    ssl._create_default_https_context = ssl._create_unverified_context

    start = datetime(year - 1, 12, 31)
    end = datetime(year + 1, 1, 2)

    stations = Stations().nearby(lat, lon)

    epw_exists = False
    station_number = 0
    len_data = 0

    incomplete_timeseries = True
    while incomplete_timeseries:
        station_number += 1
        wmo = fix_wmo(str(stations.fetch(station_number).index.values[-1]))
        # First check if EPW already exists
        if check_epw_exists(save_folder, year, wmo):
            epw_exists = True
            incomplete_timeseries = False
            break
        data = Hourly(stations.fetch(station_number), start, end, model=True).fetch()
        if (len(data.index) >100) & (station_number>1):
            data = data.loc[data.index.get_level_values('station').unique()[-1]]


        # Fetching hourly data for those stations
        # data = Hourly(stations.fetch(2), start, end, model=True).fetch()
        # Hourly(stations.fetch(2), start, end, model=True).fetch().loc[Hourly(stations.fetch(2), start, end, model=True).fetch().index.get_level_values('station').unique()[-1]]



        # print('+++++++')
        # print(lat)
        # print(lon)
        # print(start)
        # print(end)
        
        len_data = len(data.index)
        missing_hours_num, largest_consecutive_group = check_missing_hours(year, data)
        if (len_data > 8000) & (largest_consecutive_group <= 3):
            incomplete_timeseries = False
        distance = stations.fetch(station_number)['distance'].values[-1]
        # print('distance')
        # print(distance)
        # print('len_data')
        # print(len(data.index))
        # print(largest_consecutive_group)
        # print(incomplete_timeseries)
        # Let's stop after 100mi
        if distance > 16093400:
            break
        
    try:
        if distance is not None:
            print('Distance')
            print(distance)
    except UnboundLocalError:
        print("Distance variable is not defined yet.")


    if epw_exists | incomplete_timeseries:
        data = ''
        timezone = ''
        distance = ''
        elevation = ''
        station_name = ''
        state = ''
        country = ''
        latitude_station = ''
        longitude_station = ''
                
    else:
        station_info = stations.fetch(station_number)
        timezone = station_info['timezone'].values[-1]
        elevation = station_info['elevation'].values[-1]
        distance = stations.fetch()['distance'].values[-1]
        wmo = fix_wmo(str(station_info.index.values[-1]))
        station_name = station_info['name'].values[-1]
        state = station_info['region'].values[-1]
        country = station_info['country'].values[-1]
        latitude_station = station_info['latitude'].values[-1]
        longitude_station = station_info['longitude'].values[-1]

    return data, timezone, distance, elevation, wmo, station_name, state, country, latitude_station, longitude_station, epw_exists,incomplete_timeseries

# Helper function to check and update missing data
def update_if_missing(df, index, col_name, new_value):
    if pd.isna(df.at[index, col_name]) or not df.at[index, col_name]:
        df.at[index, col_name] = new_value

def retrieve_info_other_location(wmo, zipcodes, year):
    retrieve_status = zipcodes[zipcodes[f"weather_station_wmo_{year}"]==str(wmo)][f"Do we have data for {year}?"].values[0]
    distance = zipcodes[zipcodes[f"weather_station_wmo_{year}"]==str(wmo)][f"distance_location_station_miles_{year}"].values[0]
    hdd = zipcodes[zipcodes[f"weather_station_wmo_{year}"]==str(wmo)][f"hdd_base65F_{year}"].values[0]
    cdd = zipcodes[zipcodes[f"weather_station_wmo_{year}"]==str(wmo)][f"cdd_base65F_{year}"].values[0]
    return retrieve_status, distance, hdd, cdd

def get_wmo_from_icao_NOAA(icao_code):
    # Path to the local CSV file in the resource folder
    csv_file_path = os.path.join(os.path.join(os.getcwd(), 'resources'), 'isd-history.csv')

    # Read the CSV file
    try:
        with open(csv_file_path, 'r', encoding='utf-8') as file:
            lines = file.readlines()
            headers = lines[0].split(',')
            icao_index = headers.index('"ICAO"')
            wmo_index = headers.index('"USAF"')

            for line in lines[1:]:
                fields = line.split(',')
                if fields[icao_index].strip('"') == icao_code.upper():
                    return fields[wmo_index].strip('"')

    except FileNotFoundError:
        print(f"CSV file not found at path: {csv_file_path}")
        return None
    except Exception as e:
        # print(f"An error occurred: {e}")
        return None

def get_dst_start_end(year, latitude, longitude):
    # Get the timezone for the given latitude and longitude
    tf = TimezoneFinder()
    timezone_str = tf.timezone_at(lat=latitude, lng=longitude)
    
    if timezone_str is None:
        raise ValueError("Could not find timezone for the given coordinates.")
    
    # Get the timezone object
    timezone = pytz.timezone(timezone_str)
    
    # Define the dates for the beginning and end of the year (naive datetime)
    start_of_year = datetime(year, 1, 1)
    end_of_year = datetime(year, 12, 31)
    
    dst_start = None
    dst_end = None

    # Start by localizing the first date
    previous_offset = timezone.localize(start_of_year).dst()

    # Loop through each day of the year
    for dt in [start_of_year + timedelta(days=i) for i in range((end_of_year - start_of_year).days + 1)]:
        localized_dt = timezone.localize(dt)  # Localize naive datetime
        current_offset = localized_dt.dst()
        
        if previous_offset == timedelta(0) and current_offset != timedelta(0):
            dst_start = localized_dt
        elif previous_offset != timedelta(0) and current_offset == timedelta(0):
            dst_end = localized_dt
            break
        
        previous_offset = current_offset
    
    return dst_start, dst_end

def find_closest_design_condition(lat,lon,design_conditions_file):
    """
    Finds the closest design condition from the CSV file based on the given latitude and longitude.

    Parameters:
    lat (float): The latitude of the target location.
    lon (float): The longitude of the target location.
    csv_file (str): The path to the CSV file containing design conditions.

    Returns:
    str: The 2021 design condition string for the closest location.
    """

    # Function to calculate the distance between two points given their latitudes and longitudes
    def haversine_distance(lat1, lon1, lat2, lon2):
        # Convert latitude and longitude from degrees to radians
        lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
        
        # Haversine formula
        dlat = lat2 - lat1 
        dlon = lon2 - lon1 
        a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
        c = 2 * np.arcsin(np.sqrt(a)) 
        r = 6371  # Radius of Earth in kilometers. Use 3956 for miles. Determines return value units.
        return c * r

    
    # Read the CSV file
    df = pd.read_csv(design_conditions_file)

    # Calculate distance from target coordinates to each row in the dataframe
    df['distance'] = df.apply(lambda row: haversine_distance(lat, lon, row['latitude'], row['longitude']), axis=1)

    # Find the row with the minimum distance
    closest_row = df.loc[df['distance'].idxmin()]

    # Return the design conditions for 2021
    return closest_row['2021_design_conditions']


# Define constants
year = 2022
file_type = 'AMY'
save_folder = 'epws_wmo'

# Check if the 'zipcodes' variable is already defined
if 'zipcodes' not in globals():
    # Load the zip codes CSV only if 'zipcodes' is not already defined
    zipcodes = pd.read_csv('resources/zip_code_list.csv', dtype={f'Do we have data for {year}?': str, f'weather_station_wmo_{year}': str})

# Initialize a counter for iterations
counter = 0

# Process each row in the DataFrame starting from the specified index
for index, row in zipcodes.iloc[8472:].iterrows():
    # if float(row.get(f"distance_location_station_miles_{year}")) < 50:
    #     continue
    print(index)


    zip_code = str(row['zip0']).zfill(5)  # Ensure the zip code is a string and pad with leading zeros if needed
    print(zip_code)
    lat = row['lat']
    lon = row['lng']
    save_name = None

    # print(lat)
    # print(lon)
    # print(row['city'])

    # Retrieve data for the current location
    retrieve_status, distance, wmo, hdd, cdd, latitude_station, longitude_station, retrieve_info_closest_other_locations = run_individual_location(lat, lon, year, file_type, save_folder, save_name)
    if retrieve_info_closest_other_locations:
        try:
            retrieve_status, distance, hdd, cdd = retrieve_info_other_location(wmo, zipcodes, year)
        except IndexError:
            print(wmo)
            retrieve_status, distance, hdd, cdd = retrieve_info_other_location(wmo, zipcodes, year)


    # Update the DataFrame only if the cell is empty or contains a placeholder (like 'nan')
    update_if_missing(zipcodes, index, f"Do we have data for {year}?", retrieve_status)
    update_if_missing(zipcodes, index, f"distance_location_station_miles_{year}", distance * 0.000621371)  # Convert from meters to miles
    update_if_missing(zipcodes, index, f"weather_station_wmo_{year}", wmo)
    update_if_missing(zipcodes, index, f"hdd_base65F_{year}", hdd)
    update_if_missing(zipcodes, index, f"cdd_base65F_{year}", cdd)

    # Increment the counter
    counter += 1

    # Every 10 iterations, save the DataFrame and reopen it
    if counter % 10 == 0:
        # Save the DataFrame to the CSV file
        zipcodes.to_csv('resources/zip_code_list.csv', index=False)

        # Reopen the file to ensure the latest version is loaded
        # zipcodes = pd.read_csv('resources/zip_code_list.csv', dtype={f'Do we have data for {year}?': str, f'weather_station_wmo_{year}': str})

# After the loop is done, ensure the latest state is saved
zipcodes.to_csv('resources/zip_code_list.csv', index=False)

# KVHN0
# KSUN
# 74611

8472
20899
Distance
30343.45220590613
8473
54666
Distance variable is not defined yet.
8474
51011
Distance variable is not defined yet.
8475
15532
Distance variable is not defined yet.
8476
95464
Distance variable is not defined yet.
8477
17403
Distance
13950.417188101213
8478
50104
Distance variable is not defined yet.
8479
35070
Distance variable is not defined yet.
8480
50619
Distance variable is not defined yet.
8481
40063
Distance
11311.96085368961
8482
47114
Distance variable is not defined yet.
8483
57024
Distance variable is not defined yet.
8484
20879
Distance
30321.557209302187
8485
16680
Distance variable is not defined yet.
8486
49340
Distance variable is not defined yet.
8487
81225
Distance variable is not defined yet.
8488
46943
Distance
30309.288502393687
8489
47457
Distance variable is not defined yet.
8490
74001
Distance
28056.799871180538
8491
95364
Distance variable is not defined yet.
8492
29453
Distance variable is not defined yet.
8493
96094
Distance
28969.929674384235
8494
99801
Distance
30292.896744868463
8495
32626
Distance variable is not defined yet.
8496
47384
Distance
21818.26737841805
8497
79538
Distance variable is not defined yet.
8498
25545
Distance variable is not defined yet.
8499
65230
Distance variable is not defined yet.
8500
39428
Distance variable is not defined yet.
8501
44811
Distance variable is not defined yet.
8502
75832
Distance variable is not defined yet.
8503
70444
Distance variable is not defined yet.
8504
78833
Distance variable is not defined yet.
8505
56684
Distance variable is not defined yet.
8506
46377
Distance variable is not defined yet.
8507
15316
Distance variable is not defined yet.
8508
54120
Distance variable is not defined yet.
8509
25537
Distance variable is not defined yet.
8510
54123
Distance variable is not defined yet.
8511
21640
Distance
25086.164508985185
8512
24184
Distance variable is not defined yet.
8513
47683
Distance variable is not defined yet.
8514
64647
Distance variable is not defined yet.
8515
29932
Distance
20931.497847491988
8516
25054
Distance variable is not defined yet.
8517
98272
Distance variable is not defined yet.
8518
63460
Distance variable is not defined yet.
8519
97873
Distance variable is not defined yet.
8520
21005
Distance variable is not defined yet.
8521
05061
Distance variable is not defined yet.
8522
86327
Distance variable is not defined yet.
8523
57239
Distance variable is not defined yet.
8524
80426
Distance variable is not defined yet.
8525
87722
Distance variable is not defined yet.
8526
44839
Distance variable is not defined yet.
8527
74359
Distance variable is not defined yet.
8528
77484
Distance variable is not defined yet.
8529
99156
Distance
29482.22971058999
8530
75657
Distance variable is not defined yet.
8531
54734
Distance variable is not defined yet.
8532
06241
Distance variable is not defined yet.
8533
71772
Distance variable is not defined yet.
8534
70356
Distance variable is not defined yet.
8535
73724
Distance variable is not defined yet.
8536
92285
Distance variable is not defined yet.
8537
47833
Distance variable is not defined yet.
8538
08831
Distance
30199.61439091846
8539
96029
Distance variable is not defined yet.
8540
48762
Distance variable is not defined yet.
8541
76534
Distance variable is not defined yet.
8542
86433
Distance variable is not defined yet.
8543
67649
Distance variable is not defined yet.
8544
71078
Distance
22438.823483534896
8545
51560
Distance variable is not defined yet.
8546
66020
Distance
17512.76750114544
8547
12144
Distance variable is not defined yet.
8548
46772
Distance
30161.21600745544
8549
56574
Distance variable is not defined yet.
8550
39861
Distance
17561.438029755293
8551
06377
Distance variable is not defined yet.
8552
75496
Distance variable is not defined yet.
8553
43435
Distance variable is not defined yet.
8554
71040
Distance variable is not defined yet.
8555
43451
Distance variable is not defined yet.
8556
75119
Distance
30142.116675793895
8557
04254
Distance variable is not defined yet.
8558
03886
Distance variable is not defined yet.
8559
72530
Distance variable is not defined yet.
8560
63463
Distance variable is not defined yet.
8561
71744
Distance variable is not defined yet.
8562
15022
Distance
24807.6074175544
8563
45813
Distance variable is not defined yet.
8564
95690
Distance variable is not defined yet.
8565
85535
Distance variable is not defined yet.
8566
22711
Distance
30123.438355444803
8567
60424
Distance
30122.157622502276
8568
98827
Distance variable is not defined yet.
8569
17321
Distance variable is not defined yet.
8570
46962
Distance variable is not defined yet.
8571
65075
Distance variable is not defined yet.
8572
30293
Distance variable is not defined yet.
8573
12933
Distance
22185.931007583644
8574
52163
Distance variable is not defined yet.
8575
03605
Distance variable is not defined yet.
8576
25606
Distance
13156.254603998583
8577
70712
Distance variable is not defined yet.
8578
27935
Distance
30100.709748136207
8579
42635
Distance
21707.127596217106
8580
43466
Distance variable is not defined yet.
8581
59450
Distance variable is not defined yet.
8582
14879
Distance variable is not defined yet.
8583
95703
Distance
9586.947915692956
8584
31211
Distance variable is not defined yet.
8585
12814
Distance variable is not defined yet.
8586
48884
Distance variable is not defined yet.
8587
50115
Distance variable is not defined yet.
8588
67637
Distance variable is not defined yet.
8589
45678
Distance variable is not defined yet.
8590
60942
Distance variable is not defined yet.
8591
24088
Distance variable is not defined yet.
8592
25140
Distance variable is not defined yet.
8593
37657
Distance variable is not defined yet.
8594
14171
Distance variable is not defined yet.
8595
24185
Distance variable is not defined yet.
8596
61733
Distance variable is not defined yet.
8597
70435
Distance variable is not defined yet.
8598
66852
Distance variable is not defined yet.
8599
30650
Distance
30075.232527418917
8600
12041
Distance variable is not defined yet.
8601
31050
Distance variable is not defined yet.
8602
68946
Distance variable is not defined yet.
8603
16750
Distance variable is not defined yet.
8604
05772
Distance variable is not defined yet.
8605
52147
Distance variable is not defined yet.
8606
49402
Distance variable is not defined yet.
8607
97014
Distance
14970.163842966926
8608
25444
Distance variable is not defined yet.
8609
60474
Distance variable is not defined yet.
8610
47957
Distance variable is not defined yet.
8611
72927
Distance
26048.558888998676
8612
31079
Distance variable is not defined yet.
8613
56214
Distance
24404.970443249105
8614
51347
Distance variable is not defined yet.
8615
36471
Distance variable is not defined yet.
8616
13136
Distance
27125.940621193058
8617
35576
Distance variable is not defined yet.
8618
77973
Distance variable is not defined yet.
8619
72137
Distance variable is not defined yet.
8620
53507
Distance
30040.144451211912
8621
25608
Distance variable is not defined yet.
8622
17845
Distance variable is not defined yet.
8623
27011
Distance variable is not defined yet.
8624
18602
Distance variable is not defined yet.
8625
03872
Distance variable is not defined yet.
8626
75058
Distance
30032.2693052756
8627
93313
Distance variable is not defined yet.
8628
83628
Distance variable is not defined yet.
8629
27919
Distance
30023.14789267218
8630
81147
Distance
5126.373353410095
8631
68812
Distance variable is not defined yet.
8632
70662
Distance variable is not defined yet.
8633
12018
Distance variable is not defined yet.
8634
42256
Distance variable is not defined yet.
8635
75158
Distance variable is not defined yet.
8636
53931
Distance
30011.759201288656
8637
49010
Distance variable is not defined yet.
8638
56034
Distance variable is not defined yet.
8639
31327
Distance variable is not defined yet.
8640
25634
Distance
15095.074012247049
8641
18701
Distance variable is not defined yet.
8642
43467
Distance variable is not defined yet.
8643
65453
Distance variable is not defined yet.
8644
66534
Distance variable is not defined yet.
8645
49330
Distance variable is not defined yet.
8646
29743
Distance
30000.805353940345
8647
76687
Distance variable is not defined yet.
8648
41817
Distance variable is not defined yet.
8649
68878
Distance variable is not defined yet.
8650
95237
Distance variable is not defined yet.
8651
31307
Distance
29997.01024144891
8652
41512
Distance
25769.121420441646
8653
15536
Distance variable is not defined yet.
8654
05456
Distance
27849.389261014123
8655
55784
Distance variable is not defined yet.
8656
38829
Distance variable is not defined yet.
8657
83468
Distance variable is not defined yet.
8658
14480
Distance variable is not defined yet.
8659
78413
Distance
29984.016791205082
8660
27960
Distance variable is not defined yet.
8661
26224
Distance variable is not defined yet.
8662
69046
Distance variable is not defined yet.
8663
17884
Distance variable is not defined yet.
8664
64848
Distance variable is not defined yet.
8665
60013
Distance
27987.107925306245
8666
37680
Distance variable is not defined yet.
8667
66964
Distance variable is not defined yet.
8668
67140
Distance
27306.569512782073
8669
98593
Distance
17082.37506671234
8670
30124
Distance
29965.372232001602
8671
74651
Distance variable is not defined yet.
8672
62967
Distance variable is not defined yet.
8673
98936
Distance
27772.152559168342
8674
13687
Distance variable is not defined yet.
8675
16845
Distance variable is not defined yet.
8676
56729
Distance variable is not defined yet.
8677
98051
Distance variable is not defined yet.
8678
39752
Distance variable is not defined yet.
8679
52583
Distance
24841.05883659048
8680
39346
Distance
20632.751434716112
8681
36875
Distance variable is not defined yet.
8682
41763
Distance variable is not defined yet.
8683
58476
Distance variable is not defined yet.
8684
38348
Distance variable is not defined yet.
8685
35180
Distance variable is not defined yet.
8686
39897
Distance variable is not defined yet.
8687
95558
Distance variable is not defined yet.
8688
32702
Distance variable is not defined yet.
8689
08804
Distance variable is not defined yet.
8690
57265
Distance variable is not defined yet.
8691
04657
Distance variable is not defined yet.
8692
32420
Distance variable is not defined yet.
8693
29471
Distance variable is not defined yet.
8694
61734
Distance variable is not defined yet.
8695
14536
Distance variable is not defined yet.
8696
17363
Distance variable is not defined yet.
8697
52253
Distance variable is not defined yet.
8698
47123
Distance variable is not defined yet.
8699
81649
Distance variable is not defined yet.
8700
17763
Distance variable is not defined yet.
8701
01026
Distance variable is not defined yet.
8702
28662
Distance variable is not defined yet.
8703
61911
Distance variable is not defined yet.
8704
21871
Distance
29908.494716268764
8705
77861
Distance variable is not defined yet.
8706
14070
Distance variable is not defined yet.
8707
50063
Distance
23435.457835346235
8708
65725
Distance variable is not defined yet.
8709
84330
Distance
28999.639110446064
8710
56450
Distance
29904.3500641445
8711
23129
Distance variable is not defined yet.
8712
79541
Distance variable is not defined yet.
8713
59640
Distance variable is not defined yet.
8714
39836
Distance variable is not defined yet.
8715
79382
Distance
15481.645244714118
8716
17349
Distance
24883.021466977098
8717
12057
Distance
11535.437614446519
8718
22448
Distance variable is not defined yet.
8719
17532
Distance variable is not defined yet.
8720
60930
Distance variable is not defined yet.
8721
78580
Distance variable is not defined yet.
8722
04624
Distance variable is not defined yet.
8723
31014
Distance
6653.344213280403
8724
25110
Distance variable is not defined yet.
8725
16442
Distance variable is not defined yet.
8726
69140
Distance variable is not defined yet.
8727
35747
Distance variable is not defined yet.
8728
24811
Distance variable is not defined yet.
8729
74860
Distance variable is not defined yet.
8730
15020
Distance
13967.699813827698
8731
82715
Distance variable is not defined yet.
8732
16222
Distance variable is not defined yet.
8733
37779
Distance
29880.012975042686
8734
31096
Distance variable is not defined yet.
8735
77027
Distance
23535.136614851555
8736
21657
Distance
18907.293163329476
8737
72447
Distance variable is not defined yet.
8738
50055
Distance
29874.300391517467
8739
63845
Distance variable is not defined yet.
8740
84520
Distance variable is not defined yet.
8741
31331
Distance variable is not defined yet.
8742
17949
Distance variable is not defined yet.
8743
04088
Distance variable is not defined yet.
8744
16929
Distance variable is not defined yet.
8745
57769
Distance
19482.538953651274
8746
43843
Distance variable is not defined yet.
8747
84072
Distance variable is not defined yet.
8748
15502
Distance
19673.14317048775
8749
95680
Distance variable is not defined yet.
8750
54854
Distance
29858.480460896015
8751
63051
Distance variable is not defined yet.
8752
74038
Distance variable is not defined yet.
8753
10922
Distance
20479.516948263295
8754
16912
Distance variable is not defined yet.
8755
16054
Distance variable is not defined yet.
8756
61417
Distance
19732.01085381369
8757
48720
Distance variable is not defined yet.
8758
04435
Distance variable is not defined yet.
8759
60935
Distance variable is not defined yet.
8760
58021
Distance variable is not defined yet.
8761
64843
Distance variable is not defined yet.
8762
84036
Distance variable is not defined yet.
8763
36854
Distance
27835.21428647966
8764
72450
Distance variable is not defined yet.
8765
59263
Distance variable is not defined yet.
8766
35618
Distance variable is not defined yet.
8767
31304
Distance variable is not defined yet.
8768
61943
Distance variable is not defined yet.
8769
98537
Distance variable is not defined yet.
8770
27052
Distance
29832.661856604536
8771
58831
Distance variable is not defined yet.
8772
40036
Distance variable is not defined yet.
8773
98597
Distance
29825.26477310963
8774
65078
Distance variable is not defined yet.
8775
71450
Distance variable is not defined yet.
8776
54836
Distance
29823.07467919631
8777
28423
Distance variable is not defined yet.
8778
36916
Distance variable is not defined yet.
8779
08248
Distance variable is not defined yet.
8780
23163
Distance
29806.69429241451
8781
21540
Distance
26637.344597811607
8782
50147
Distance variable is not defined yet.
8783
50060
Distance variable is not defined yet.
8784
13335
Distance
27031.810271022903
8785
62289
Distance
10026.06807917826
8786
47879
Distance variable is not defined yet.
8787
40311
Distance variable is not defined yet.
8788
30816
Distance
27981.69225674441
8789
12981
Distance
26091.791054234625
8790
22520
Distance variable is not defined yet.
8791
75966
Distance variable is not defined yet.
8792
34137
Distance variable is not defined yet.
8793
94523
Distance
28398.449608749845
8794
56071
Distance
29782.90596286664
8795
62952
Distance variable is not defined yet.
8796
03231
Distance variable is not defined yet.
8797
13863
Distance variable is not defined yet.
8798
47567
Distance variable is not defined yet.
8799
51230
Distance
29771.959165772067
8800
68314
Distance variable is not defined yet.
8801
30004

Warning: Cannot load hourly/2021/K47A0.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/K47A0.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/K47A0.csv.gz from https://bulk.meteostat.net/v2/

Distance
21910.169754817434
8802
35063
Distance variable is not defined yet.
8803
32693
Distance variable is not defined yet.
8804
35579
Distance variable is not defined yet.
8805
31744
Distance
29763.777336007086
8806
72129
Distance variable is not defined yet.
8807
10596
Distance
29560.57747628495
8808
72903
Distance
25163.22316201514
8809
26412
Distance
22897.02160715369
8810
71653
Distance variable is not defined yet.
8811
48472
Distance variable is not defined yet.
8812
60931
Distance variable is not defined yet.
8813
46996
Distance
29754.77051807348
8814
61321
Distance variable is not defined yet.
8815
62860
Distance
29753.457025243668
8816
63441
Distance variable is not defined yet.
8817
57646
Distance variable is not defined yet.
8818
65035
Distance variable is not defined yet.
8819
30568
Distance variable is not defined yet.
8820
61553
Distance variable is not defined yet.
8821
29569
Distance
29738.22097264095
8822
78107
Distance variable is not defined yet.
8823
24836
Distance variable is not defined yet.
8824
44064
Distance variable is not defined yet.
8825
63383
Distance variable is not defined yet.
8826
24884
Distance variable is not defined yet.
8827
15424
Distance
26621.019865859478
8828
83636
Distance variable is not defined yet.
8829
72624
Distance variable is not defined yet.
8830
28360
Distance
7312.4441882266665
8831
16656
Distance variable is not defined yet.
8832
79119
Distance variable is not defined yet.
8833
93562
Distance variable is not defined yet.
8834
81625
Distance
29715.972056537186
8835
14859
Distance variable is not defined yet.
8836
15618
Distance variable is not defined yet.
8837
59412
Distance
7576.298634475163
8838
78003
Distance variable is not defined yet.
8839
03230
Distance variable is not defined yet.
8840
67629
Distance variable is not defined yet.
8841
63966
Distance
23672.62820000176
8842
97543
Distance
20727.07598597871
8843
22827
Distance
29703.512468765948
8844
71247
Distance variable is not defined yet.
8845
98855
Distance variable is not defined yet.
8846
42134
Distance
16646.041384698146
8847
37074
Distance
24137.7225177538
8848
93221
Distance variable is not defined yet.
8849
14028
Distance variable is not defined yet.
8850
16217
Distance variable is not defined yet.
8851
22820
Distance
27933.605264195263
8852
76874
Distance variable is not defined yet.
8853
66868
Distance variable is not defined yet.
8854
25062
Distance variable is not defined yet.
8855
54491
Distance variable is not defined yet.
8856
72631
Distance variable is not defined yet.
8857
40115
Distance
27214.824538066045
8858
56011
Distance
29681.79815030572
8859
12035
Distance variable is not defined yet.
8860
41640
Distance variable is not defined yet.
8861
83833
Distance variable is not defined yet.
8862
54174
Distance variable is not defined yet.
8863
77615
Distance variable is not defined yet.
8864
97426
Distance
4191.0425020744315
8865
03036
Distance
29675.086639608577
8866
40759
Distance
12882.28648011464
8867
03077
Distance
22482.604717904152
8868
83120
Distance
28950.08665498838
8869
61531
Distance variable is not defined yet.
8870
25156
Distance variable is not defined yet.
8871
77455
Distance
29666.06946762312
8872
75412
Distance
24399.262349699813
8873
31803
Distance variable is not defined yet.
8874
76930
Distance variable is not defined yet.
8875
65644
Distance variable is not defined yet.
8876
84761
Distance variable is not defined yet.
8877
92220
Distance
29654.024208450777
8878
65637
Distance variable is not defined yet.
8879
83522
Distance variable is not defined yet.
8880
16920
Distance variable is not defined yet.
8881
75669
Distance
29646.649671193136
8882
29067
Distance
29646.590820142184
8883
54028
Distance
29645.932218769565
8884
73658
Distance variable is not defined yet.
8885
74570
Distance variable is not defined yet.
8886
61491
Distance variable is not defined yet.
8887
28711
Distance variable is not defined yet.
8888
57481
Distance variable is not defined yet.
8889
36265
Distance variable is not defined yet.
8890
13733
Distance
29480.252223882217
8891
30513
Distance
28711.61917008177
8892
77356
Distance variable is not defined yet.
8893
52134
Distance variable is not defined yet.
8894
15770
Distance variable is not defined yet.
8895
32038
Distance variable is not defined yet.
8896
35148
Distance variable is not defined yet.
8897
42164
Distance variable is not defined yet.
8898
10579
Distance
24963.755892604288
8899
55919
Distance
24151.781770575715
8900
12440
Distance variable is not defined yet.
8901
60481

Warning: Cannot load hourly/2021/7XHBS.csv.gz from https://bulk.meteostat.net/v2/

Distance
26391.80483661688
8902
25514
Distance variable is not defined yet.
8903
95242
Distance variable is not defined yet.
8904
67071
Distance variable is not defined yet.
8905
59833
Distance variable is not defined yet.
8906
63943
Distance variable is not defined yet.
8907
41531
Distance
27857.436915536146
8908
30576
Distance variable is not defined yet.
8909
54466
Distance variable is not defined yet.
8910
94576
Distance variable is not defined yet.
8911
98572
Distance variable is not defined yet.
8912
95922
Distance variable is not defined yet.
8913
17352
Distance variable is not defined yet.
8914
77417
Distance variable is not defined yet.
8915
60468
Distance variable is not defined yet.
8916
62615
Distance variable is not defined yet.
8917
35184
Distance
26021.047872227227
8918
36264
Distance variable is not defined yet.
8919
24941
Distance variable is not defined yet.
8920
68332
Distance variable is not defined yet.
8921
98253
Distance
19821.536198786544
8922
17362
Distance
7532.83361770525
8923
17740
Distance variable is not defined yet.
8924
10547
Distance variable is not defined yet.
8925
72132
Distance variable is not defined yet.
8926
42566
Distance variable is not defined yet.
8927
83344
Distance variable is not defined yet.
8928
66070
Distance variable is not defined yet.
8929
69220
Distance variable is not defined yet.
8930
84002
Distance variable is not defined yet.
8931
23015
Distance
11315.733201337785
8932
61426
Distance variable is not defined yet.
8933
49881
Distance variable is not defined yet.
8934
37843
Distance variable is not defined yet.
8935
30457
Distance variable is not defined yet.
8936
71356
Distance variable is not defined yet.
8937
81124
Distance variable is not defined yet.
8938
17013
Distance variable is not defined yet.
8939
67520
Distance variable is not defined yet.
8940
38569
Distance variable is not defined yet.
8941
15535
Distance variable is not defined yet.
8942
40481
Distance variable is not defined yet.
8943
95918
Distance variable is not defined yet.
8944
61368
Distance variable is not defined yet.
8945
18436
Distance variable is not defined yet.
8946
50604
Distance variable is not defined yet.
8947
76831
Distance variable is not defined yet.
8948
13319
Distance
16678.57866796574
8949
44076
Distance variable is not defined yet.
8950
51345
Distance
29546.121026362394
8951
68785
Distance variable is not defined yet.
8952
73042
Distance variable is not defined yet.
8953
39337
Distance variable is not defined yet.
8954
14530
Distance variable is not defined yet.
8955
65529
Distance variable is not defined yet.
8956
41002
Distance variable is not defined yet.
8957
97478
Distance
21708.28516912704
8958
81146
Distance variable is not defined yet.
8959
26376
Distance
19637.5699115761
8960
13143
Distance variable is not defined yet.
8961
72168
Distance variable is not defined yet.
8962
15615
Distance
15901.314007180445
8963
15531
Distance
17094.817636619984
8964
56644
Distance variable is not defined yet.
8965
50853
Distance
29523.942220089997
8966
40409
Distance variable is not defined yet.
8967
57355
Distance variable is not defined yet.
8968
58015
Distance variable is not defined yet.
8969
45622
Distance variable is not defined yet.
8970
04976
Distance variable is not defined yet.
8971
40012
Distance variable is not defined yet.
8972
80449
Distance variable is not defined yet.
8973
25837
Distance variable is not defined yet.
8974
35677
Distance variable is not defined yet.
8975
73945
Distance variable is not defined yet.
8976
35619
Distance variable is not defined yet.
8977
71961
Distance variable is not defined yet.
8978
68407
Distance variable is not defined yet.
8979
51431
Distance variable is not defined yet.
8980
56634
Distance variable is not defined yet.
8981
41010
Distance variable is not defined yet.
8982
72717
Distance variable is not defined yet.
8983
21641
Distance
16960.852072079037
8984
38345
Distance variable is not defined yet.
8985
93924
Distance
29156.71209927327
8986
15737
Distance variable is not defined yet.
8987
84098
Distance variable is not defined yet.
8988
42716
Distance variable is not defined yet.
8989
47327
Distance variable is not defined yet.
8990
73759
Distance variable is not defined yet.
8991
29074
Distance variable is not defined yet.
8992
45746
Distance variable is not defined yet.
8993
75441
Distance variable is not defined yet.
8994
78616
Distance variable is not defined yet.
8995
84782
Distance variable is not defined yet.
8996
42157
Distance variable is not defined yet.
8997
29922
Distance variable is not defined yet.
8998
27924
Distance variable is not defined yet.
8999
83535
Distance variable is not defined yet.
9000
62859
Distance variable is not defined yet.
9001
52778
Distance variable is not defined yet.
9002
18427
Distance variable is not defined yet.
9003
67548
Distance variable is not defined yet.
9004
79086
Distance variable is not defined yet.
9005
35652
Distance variable is not defined yet.
9006
84651
Distance
21586.745223180442
9007
37048
Distance
21174.20841260406
9008
59732
Distance variable is not defined yet.
9009
58338
Distance variable is not defined yet.
9010
51105
Distance variable is not defined yet.
9011
95550
Distance
29468.454745019568
9012
56591
Distance
20114.786886943763
9013
08886
Distance variable is not defined yet.
9014
83554
Distance variable is not defined yet.
9015
99563
Distance
29466.72971181802
9016
65459
Distance variable is not defined yet.
9017
58275
Distance variable is not defined yet.
9018
49078
Distance variable is not defined yet.
9019
57279
Distance variable is not defined yet.
9020
40953
Distance variable is not defined yet.
9021
73432
Distance variable is not defined yet.
9022
68866
Distance variable is not defined yet.
9023
24426
Distance variable is not defined yet.
9024
97530
Distance variable is not defined yet.
9025
53521
Distance variable is not defined yet.
9026
62806
Distance
29450.54312961848
9027
29321
Distance
29449.93309179544
9028
36078
Distance variable is not defined yet.
9029
61065
Distance variable is not defined yet.
9030
16641
Distance variable is not defined yet.
9031
37642
Distance variable is not defined yet.
9032
52220
Distance variable is not defined yet.
9033
58260
Distance variable is not defined yet.
9034
61036
Distance
29430.709571591346
9035
83637
Distance variable is not defined yet.
9036
31077
Distance variable is not defined yet.
9037
56292
Distance variable is not defined yet.
9038
10511
Distance
29405.60508102734
9039
37340
Distance variable is not defined yet.
9040
93436

Warning: Cannot load hourly/2021/QX6JS.csv.gz from https://bulk.meteostat.net/v2/

Distance
19832.8788897715
9041
04271
Distance variable is not defined yet.
9042
24574
Distance variable is not defined yet.
9043
97031
Distance
26559.028229471678
9044
45647
Distance variable is not defined yet.
9045
76652
Distance variable is not defined yet.
9046
82432
Distance variable is not defined yet.
9047
73662
Distance variable is not defined yet.
9048
16946
Distance variable is not defined yet.
9049
16852
Distance variable is not defined yet.
9050
59727
Distance variable is not defined yet.
9051
78619
Distance variable is not defined yet.
9052
78385
Distance variable is not defined yet.
9053
40046
Distance variable is not defined yet.
9054
56347
Distance
29400.940640471625
9055
96015
Distance variable is not defined yet.
9056
43756
Distance variable is not defined yet.
9057
54651
Distance
29393.864263052637
9058
68874
Distance
26772.784982055666
9059
05775
Distance variable is not defined yet.
9060
82941
Distance variable is not defined yet.
9061
64643
Distance variable is not defined yet.
9062
23405
Distance variable is not defined yet.
9063
25607
Distance
13717.57026486202
9064
27844
Distance
29389.049603845546
9065
28623
Distance variable is not defined yet.
9066
80453
Distance variable is not defined yet.
9067
38940
Distance variable is not defined yet.
9068
10567
Distance
28889.932862252546
9069
24243
Distance variable is not defined yet.
9070
42259
Distance variable is not defined yet.
9071
27020
Distance
29380.143112393205
9072
32456
Distance variable is not defined yet.
9073
76233
Distance variable is not defined yet.
9074
78830
Distance variable is not defined yet.
9075
94965
Distance
29373.983365311808
9076
98952
Distance variable is not defined yet.
9077
91390
Distance
28999.540489822706
9078
16020
Distance variable is not defined yet.
9079
66429
Distance
19991.71099598769
9080
04785

Warning: Cannot load hourly/2021/71703.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/71703.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/71703.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2021/71019.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/71019.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/71019.csv.gz from https://bulk.meteostat.net/v2/

Distance
29368.217852858186
9081
85603
Distance variable is not defined yet.
9082
61951
Distance variable is not defined yet.
9083
74340
Distance variable is not defined yet.
9084
40350
Distance
27149.956621050653
9085
85540
Distance variable is not defined yet.
9086
17035
Distance variable is not defined yet.
9087
74467
Distance variable is not defined yet.
9088
12428
Distance variable is not defined yet.
9089
49079
Distance variable is not defined yet.
9090
63056
Distance variable is not defined yet.
9091
04673
Distance variable is not defined yet.
9092
67120
Distance
15655.376986433837
9093
53932
Distance variable is not defined yet.
9094
62931
Distance
26481.949511749295
9095
15135
Distance
10783.190754204938
9096
10952
Distance
29344.89919157575
9097
54748
Distance variable is not defined yet.
9098
47142
Distance variable is not defined yet.
9099
95363
Distance
11314.292975642462
9100
54810
Distance
29335.70529783726
9101
36523
Distance variable is not defined yet.
9102
71667
Distance variable is not defined yet.
9103
61744
Distance variable is not defined yet.
9104
72531
Distance variable is not defined yet.
9105
63760
Distance variable is not defined yet.
9106
99929
Distance
29325.466045941637
9107
62811
Distance variable is not defined yet.
9108
61559
Distance variable is not defined yet.
9109
77418
Distance variable is not defined yet.
9110
85141
Distance
21836.658776478052
9111
51019
Distance variable is not defined yet.
9112
31544
Distance variable is not defined yet.
9113
45120
Distance variable is not defined yet.
9114
12887
Distance variable is not defined yet.
9115
30233
Distance variable is not defined yet.
9116
62610
Distance variable is not defined yet.
9117
50103
Distance
29304.993480239897
9118
55971
Distance variable is not defined yet.
9119
68792
Distance variable is not defined yet.
9120
17835
Distance variable is not defined yet.
9121
72640
Distance variable is not defined yet.
9122
06277
Distance
29301.288824291725
9123
64001
Distance variable is not defined yet.
9124
41766
Distance
29298.784058730937
9125
64074
Distance variable is not defined yet.
9126
58847
Distance variable is not defined yet.
9127
77856
Distance variable is not defined yet.
9128
27840
Distance
29293.63540073965
9129
21737
Distance
15713.826407079605
9130
43968
Distance variable is not defined yet.
9131
28447
Distance variable is not defined yet.
9132
34655
Distance
29283.54194277013
9133
68665
Distance variable is not defined yet.
9134
38226
Distance variable is not defined yet.
9135
49401
Distance variable is not defined yet.
9136
37305
Distance variable is not defined yet.
9137
06777
Distance variable is not defined yet.
9138
47451
Distance variable is not defined yet.
9139
42368
Distance variable is not defined yet.
9140
15047
Distance
11183.54540876736
9141
62923
Distance variable is not defined yet.
9142
57077
Distance variable is not defined yet.
9143
34760
Distance
29266.794865808406
9144
12132
Distance variable is not defined yet.
9145
96023
Distance variable is not defined yet.
9146
12472
Distance variable is not defined yet.
9147
26801
Distance variable is not defined yet.
9148
26405
Distance variable is not defined yet.
9149
01081
Distance
29256.62517498597
9150
69028
Distance
26412.594468777865
9151
27018
Distance
27531.283350273538
9152
80467
Distance variable is not defined yet.
9153
63015
Distance variable is not defined yet.
9154
40077
Distance variable is not defined yet.
9155
67621
Distance variable is not defined yet.
9156
81423
Distance variable is not defined yet.
9157
58277
Distance variable is not defined yet.
9158
96087
Distance variable is not defined yet.
9159
47110
Distance variable is not defined yet.
9160
38240
Distance variable is not defined yet.
9161
25154
Distance variable is not defined yet.
9162
74056
Distance variable is not defined yet.
9163
40445
Distance variable is not defined yet.
9164
68445
Distance variable is not defined yet.
9165
06750
Distance variable is not defined yet.
9166
98326
Distance variable is not defined yet.
9167
01084
Distance variable is not defined yet.
9168
29810
Distance
9888.493266628126
9169
55724
Distance
29226.202545208496
9170
12123
Distance variable is not defined yet.
9171
57022
Distance variable is not defined yet.
9172
62947
Distance variable is not defined yet.
9173
68964
Distance variable is not defined yet.
9174
62094
Distance variable is not defined yet.
9175
35572
Distance variable is not defined yet.
9176
73756
Distance variable is not defined yet.
9177
36314
Distance
25564.278168988974
9178
60920
Distance variable is not defined yet.
9179
28586
Distance variable is not defined yet.
9180
05072
Distance variable is not defined yet.
9181
17931
Distance variable is not defined yet.
9182
28634
Distance
29194.928123637725
9183
24826
Distance variable is not defined yet.
9184
73541
Distance variable is not defined yet.
9185
29661
Distance variable is not defined yet.
9186
16354
Distance variable is not defined yet.
9187
95335
Distance variable is not defined yet.
9188
58384
Distance variable is not defined yet.
9189
24879
Distance variable is not defined yet.
9190
80733
Distance variable is not defined yet.
9191
68368
Distance variable is not defined yet.
9192
16933
Distance variable is not defined yet.
9193
80440
Distance variable is not defined yet.
9194
51041
Distance
4168.431554524424
9195
12514
Distance
18506.214310379146
9196
70611
Distance
15203.85904275881
9197
47969
Distance
29160.540790021732
9198
25567
Distance variable is not defined yet.
9199
13681
Distance variable is not defined yet.
9200
48852
Distance variable is not defined yet.
9201
61377
Distance variable is not defined yet.
9202
74430
Distance variable is not defined yet.
9203
67737
Distance variable is not defined yet.
9204
61364
Distance variable is not defined yet.
9205
72104
Distance
29147.002778633603
9206
39096
Distance variable is not defined yet.
9207
37379
Distance variable is not defined yet.
9208
96714

Warning: Cannot load hourly/2021/91164.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/91164.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/91164.csv.gz from https://bulk.meteostat.net/v2/

Distance
17121.47780269121
9209
16601
Distance variable is not defined yet.
9210
80736
Distance variable is not defined yet.
9211
25241
Distance variable is not defined yet.
9212
26823
Distance variable is not defined yet.
9213
27028
Distance variable is not defined yet.
9214
47860
Distance variable is not defined yet.
9215
74367
Distance variable is not defined yet.
9216
49799
Distance variable is not defined yet.
9217
18651
Distance variable is not defined yet.
9218
08810
Distance
29125.881989645557
9219
87713
Distance variable is not defined yet.
9220
34756
Distance variable is not defined yet.
9221
67038
Distance variable is not defined yet.
9222
83857
Distance variable is not defined yet.
9223
54745
Distance variable is not defined yet.
9224
43554
Distance
29114.027900238943
9225
31066
Distance variable is not defined yet.
9226
40997
Distance variable is not defined yet.
9227
65556
Distance variable is not defined yet.
9228
27557
Distance
29110.325016904157
9229
21610
Distance variable is not defined yet.
9230
28735
Distance variable is not defined yet.
9231
49719
Distance
29107.753707284453
9232
03278
Distance variable is not defined yet.
9233
92394
Distance
15401.600256007257
9234
31542
Distance variable is not defined yet.
9235
04924
Distance variable is not defined yet.
9236
77950
Distance variable is not defined yet.
9237
04443
Distance variable is not defined yet.
9238
51062
Distance variable is not defined yet.
9239
79068
Distance variable is not defined yet.
9240
98832
Distance variable is not defined yet.
9241
63660
Distance variable is not defined yet.
9242
26582
Distance variable is not defined yet.
9243
10977
Distance variable is not defined yet.
9244
47855
Distance variable is not defined yet.
9245
03579
Distance variable is not defined yet.
9246
39827
Distance
29086.195340937178
9247
65712
Distance
26382.174939702378
9248
62050
Distance variable is not defined yet.
9249
39361
Distance variable is not defined yet.
9250
12833
Distance variable is not defined yet.
9251
15348
Distance variable is not defined yet.
9252
26273
Distance variable is not defined yet.
9253
46049
Distance
29070.950181621836
9254
33946
Distance variable is not defined yet.
9255
13110
Distance
12872.763279580518
9256
27825
Distance variable is not defined yet.
9257
61419
Distance variable is not defined yet.
9258
38627
Distance variable is not defined yet.
9259
20877
Distance
3747.4130411173383
9260
62891
Distance variable is not defined yet.
9261
81623
Distance
24544.779464424504
9262
77024
Distance
16403.278745680498
9263
17408
Distance
6501.585989710958
9264
50457
Distance
29056.145343546563
9265
52135
Distance variable is not defined yet.
9266
58445
Distance variable is not defined yet.
9267
95230
Distance
29052.928824302646
9268
97632
Distance variable is not defined yet.
9269
14815
Distance variable is not defined yet.
9270
44057
Distance variable is not defined yet.
9271
41667
Distance
23816.518357878456
9272
49055
Distance variable is not defined yet.
9273
57039
Distance variable is not defined yet.
9274
52037
Distance variable is not defined yet.
9275
65040
Distance variable is not defined yet.
9276
98631
Distance variable is not defined yet.
9277
79838
Distance variable is not defined yet.
9278
55749
Distance variable is not defined yet.
9279
14139
Distance variable is not defined yet.
9280
47443
Distance variable is not defined yet.
9281
12986
Distance variable is not defined yet.
9282
70516
Distance variable is not defined yet.
9283
47125
Distance variable is not defined yet.
9284
10975
Distance
27607.888341577345
9285
65759
Distance variable is not defined yet.
9286
54129
Distance
29020.007172756104
9287
63053
Distance variable is not defined yet.
9288
77532
Distance variable is not defined yet.
9289
67550
Distance
4127.3369953624515
9290
76641
Distance
29016.72546843149
9291
64457
Distance variable is not defined yet.
9292
05060
Distance variable is not defined yet.
9293
27922
Distance
29014.94730139896
9294
73559
Distance
29014.860457345356
9295
85356
Distance variable is not defined yet.
9296
29426
Distance variable is not defined yet.
9297
15067
Distance
16646.10209769864
9298
99770
Distance
29012.12491029669
9299
76365
Distance variable is not defined yet.
9300
68354
Distance variable is not defined yet.
9301
16427
Distance variable is not defined yet.
9302
05058
Distance variable is not defined yet.
9303
92256
Distance variable is not defined yet.
9304
63369
Distance variable is not defined yet.
9305
04983
Distance variable is not defined yet.
9306
23125
Distance variable is not defined yet.
9307
67030
Distance variable is not defined yet.
9308
19975
Distance
17181.67035658458
9309
35745
Distance variable is not defined yet.
9310
31041
Distance
22852.68735736095
9311
29717
Distance variable is not defined yet.
9312
77580
Distance
28573.406403599176
9313
83855
Distance variable is not defined yet.
9314
50638
Distance variable is not defined yet.
9315
25169
Distance variable is not defined yet.
9316
45642
Distance variable is not defined yet.
9317
72633
Distance variable is not defined yet.
9318
34652
Distance variable is not defined yet.
9319
41764
Distance
28976.040167675434
9320
59725
Distance variable is not defined yet.
9321
76639
Distance variable is not defined yet.
9322
63014
Distance variable is not defined yet.
9323
94801
Distance
19341.56423268169
9324
63077
Distance variable is not defined yet.
9325
75156
Distance variable is not defined yet.
9326
93626
Distance variable is not defined yet.
9327
36374
Distance variable is not defined yet.
9328
12180
Distance variable is not defined yet.
9329
79543
Distance variable is not defined yet.
9330
67545
Distance variable is not defined yet.
9331
63072
Distance variable is not defined yet.
9332
31815
Distance variable is not defined yet.
9333
49420
Distance variable is not defined yet.
9334
74572
Distance variable is not defined yet.
9335
15359
Distance variable is not defined yet.
9336
15368
Distance variable is not defined yet.
9337
49760
Distance variable is not defined yet.
9338
49896
Distance variable is not defined yet.
9339
15362
Distance variable is not defined yet.
9340
25208
Distance
23746.400564164367
9341
57718
Distance
21364.96316371992
9342
17325
Distance variable is not defined yet.
9343
59485
Distance
13785.684931566362
9344
41630
Distance variable is not defined yet.
9345
64017
Distance variable is not defined yet.
9346
73073
Distance variable is not defined yet.
9347
48465
Distance variable is not defined yet.
9348
95978
Distance variable is not defined yet.
9349
26426
Distance variable is not defined yet.
9350
72773
Distance variable is not defined yet.
9351
50582
Distance variable is not defined yet.
9352
24563
Distance
24621.510239417003
9353
38471
Distance variable is not defined yet.
9354
44256
Distance
28908.32385857779
9355
68943
Distance variable is not defined yet.
9356
01373
Distance variable is not defined yet.
9357
95638
Distance variable is not defined yet.
9358
16127
Distance variable is not defined yet.
9359
42320
Distance variable is not defined yet.
9360
98848
Distance variable is not defined yet.
9361
62298
Distance variable is not defined yet.
9362
93311
Distance variable is not defined yet.
9363
77873
Distance variable is not defined yet.
9364
18235
Distance
5855.050502739699
9365
15346
Distance variable is not defined yet.
9366
56572
Distance variable is not defined yet.
9367
62995
Distance variable is not defined yet.
9368
73463
Distance variable is not defined yet.
9369
83826

Warning: Cannot load hourly/2021/HYJ40.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/HYJ40.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/HYJ40.csv.gz from https://bulk.meteostat.net/v2/

Distance
25451.343912734035
9370
36744
Distance variable is not defined yet.
9371
50255
Distance variable is not defined yet.
9372
17946
Distance variable is not defined yet.
9373
22976
Distance variable is not defined yet.
9374
63851
Distance variable is not defined yet.
9375
45326
Distance
28871.140507312753
9376
73566
Distance
28870.696260939192
9377
77988
Distance variable is not defined yet.
9378
53949
Distance variable is not defined yet.
9379
61024
Distance variable is not defined yet.
9380
65744
Distance variable is not defined yet.
9381
36761
Distance variable is not defined yet.
9382
55951
Distance variable is not defined yet.
9383
22931
Distance variable is not defined yet.
9384
95006
Distance variable is not defined yet.
9385
57379
Distance variable is not defined yet.
9386
31091
Distance variable is not defined yet.
9387
29353
Distance
15862.318163885855
9388
23138
Distance variable is not defined yet.
9389
93651
Distance variable is not defined yet.
9390
25971
Distance variable is not defined yet.
9391
92061
Distance variable is not defined yet.
9392
29477
Distance variable is not defined yet.
9393
32113
Distance variable is not defined yet.
9394
49047
Distance
28845.49273347863
9395
48048
Distance
15633.854512373668
9396
06281
Distance variable is not defined yet.
9397
20689
Distance variable is not defined yet.
9398
50074
Distance variable is not defined yet.
9399
95227
Distance variable is not defined yet.
9400
49631
Distance variable is not defined yet.
9401
12936
Distance variable is not defined yet.
9402
04922
Distance variable is not defined yet.
9403
17052
Distance variable is not defined yet.
9404
53930
Distance variable is not defined yet.
9405
56662
Distance variable is not defined yet.
9406
73546
Distance variable is not defined yet.
9407
81143
Distance variable is not defined yet.
9408
43783
Distance
28824.3067255664
9409
18469
Distance variable is not defined yet.
9410
74931
Distance variable is not defined yet.
9411
68444
Distance variable is not defined yet.
9412
65443
Distance variable is not defined yet.
9413
81429
Distance variable is not defined yet.
9414
28761
Distance
28818.408177348094
9415
95494
Distance variable is not defined yet.
9416
48650
Distance
28816.090547979726
9417
21028
Distance variable is not defined yet.
9418
61957
Distance variable is not defined yet.
9419
21794
Distance
28811.18230028098
9420
82335
Distance variable is not defined yet.
9421
38738
Distance variable is not defined yet.
9422
56735
Distance variable is not defined yet.
9423
15538
Distance
24361.291939344366
9424
56142
Distance variable is not defined yet.
9425
38012
Distance
28801.381714501607
9426
12729
Distance variable is not defined yet.
9427
31518
Distance
28796.15431484346
9428
28515
Distance variable is not defined yet.
9429
74766
Distance variable is not defined yet.
9430
47862
Distance variable is not defined yet.
9431
75631
Distance
16760.427971136156
9432
61421
Distance variable is not defined yet.
9433
42371
Distance
18566.864466064566
9434
54858
Distance variable is not defined yet.
9435
85118
Distance variable is not defined yet.
9436
79364
Distance variable is not defined yet.
9437
16364
Distance variable is not defined yet.
9438
10517
Distance variable is not defined yet.
9439
71973
Distance variable is not defined yet.
9440
41669
Distance
24344.683579051045
9441
04955
Distance variable is not defined yet.
9442
15742
Distance variable is not defined yet.
9443
75481
Distance variable is not defined yet.
9444
81237
Distance variable is not defined yet.
9445
65452
Distance variable is not defined yet.
9446
72003
Distance variable is not defined yet.
9447
40348
Distance
27069.112751480854
9448
36266
Distance variable is not defined yet.
9449
74427
Distance variable is not defined yet.
9450
47971
Distance variable is not defined yet.
9451
12059
Distance variable is not defined yet.
9452
03814
Distance variable is not defined yet.
9453
68944
Distance variable is not defined yet.
9454
12834
Distance variable is not defined yet.
9455
31063
Distance variable is not defined yet.
9456
55962
Distance variable is not defined yet.
9457
50593
Distance variable is not defined yet.
9458
61349
Distance
28750.77545481953
9459
13736
Distance variable is not defined yet.
9460
60917
Distance variable is not defined yet.
9461
79093
Distance
16307.872240747944
9462
24595
Distance variable is not defined yet.
9463
38553
Distance variable is not defined yet.
9464
99130
Distance variable is not defined yet.
9465
49125
Distance
28738.751837708587
9466
46047
Distance variable is not defined yet.
9467
10923
Distance variable is not defined yet.
9468
37137
Distance variable is not defined yet.
9469
66071
Distance
28733.122996083544
9470
22722
Distance
28731.984087408182
9471
98638
Distance variable is not defined yet.
9472
75477
Distance variable is not defined yet.
9473
29036
Distance variable is not defined yet.
9474
17201
Distance variable is not defined yet.
9475
08087
Distance variable is not defined yet.
9476
60557
Distance variable is not defined yet.
9477
87939
Distance variable is not defined yet.
9478
75494
Distance variable is not defined yet.
9479
41819
Distance variable is not defined yet.
9480
26750
Distance
27866.454795735826
9481
21652
Distance
20707.75499998228
9482
15940
Distance variable is not defined yet.
9483
76449
Distance variable is not defined yet.
9484
47436
Distance variable is not defined yet.
9485
75639
Distance
17589.195793934992
9486
28020
Distance variable is not defined yet.
9487
51058
Distance
28695.95860759827
9488
12866
Distance variable is not defined yet.
9489
55943
Distance variable is not defined yet.
9490
74727
Distance variable is not defined yet.
9491
16645
Distance variable is not defined yet.
9492
43836
Distance variable is not defined yet.
9493
50039
Distance
12848.452840045797
9494
55972
Distance variable is not defined yet.
9495
07863
Distance variable is not defined yet.
9496
75760
Distance variable is not defined yet.
9497
48416
Distance variable is not defined yet.
9498
36319
Distance
16264.311356133216
9499
54853
Distance variable is not defined yet.
9500
30537
Distance variable is not defined yet.
9501
92536
Distance
28675.25450966404
9502
95984
Distance variable is not defined yet.
9503
68057
Distance variable is not defined yet.
9504
38321
Distance variable is not defined yet.
9505
98602
Distance variable is not defined yet.
9506
56283
Distance
28670.442204216284
9507
97374
Distance variable is not defined yet.
9508
14839
Distance variable is not defined yet.
9509
60929
Distance variable is not defined yet.
9510
72561
Distance variable is not defined yet.
9511
87574
Distance variable is not defined yet.
9512
25160
Distance variable is not defined yet.
9513
33922
Distance variable is not defined yet.
9514
13636
Distance variable is not defined yet.
9515
36041
Distance variable is not defined yet.
9516
41735
Distance variable is not defined yet.
9517
68347
Distance variable is not defined yet.
9518
12850
Distance variable is not defined yet.
9519
65605
Distance
18511.13836294714
9520
75157
Distance variable is not defined yet.
9521
49305
Distance variable is not defined yet.
9522
14843
Distance
28227.780158806516
9523
73062
Distance variable is not defined yet.
9524
38230
Distance variable is not defined yet.
9525
38751
Distance variable is not defined yet.
9526
65730
Distance variable is not defined yet.
9527
87560
Distance variable is not defined yet.
9528
10588
Distance variable is not defined yet.
9529
83421
Distance variable is not defined yet.
9530
26228
Distance
25517.22009967823
9531
97462
Distance variable is not defined yet.
9532
56440
Distance
27897.23548110305
9533
32533
Distance
19910.999088886543
9534
81425
Distance variable is not defined yet.
9535
48519
Distance variable is not defined yet.
9536
72001
Distance variable is not defined yet.
9537
62883
Distance variable is not defined yet.
9538
75101
Distance variable is not defined yet.
9539
61477
Distance variable is not defined yet.
9540
59821
Distance variable is not defined yet.
9541
70301
Distance variable is not defined yet.
9542
75495
Distance
28607.2699366025
9543
71677
Distance variable is not defined yet.
9544
54945
Distance
28605.729268178762
9545
80117
Distance
28603.508354380465
9546
50222
Distance variable is not defined yet.
9547
24271
Distance variable is not defined yet.
9548
43158
Distance variable is not defined yet.
9549
24523
Distance variable is not defined yet.
9550
66032
Distance variable is not defined yet.
9551
17061
Distance variable is not defined yet.
9552
48770
Distance variable is not defined yet.
9553
62243
Distance
14937.097621379678
9554
26271
Distance variable is not defined yet.
9555
67491
Distance variable is not defined yet.
9556
43511
Distance variable is not defined yet.
9557
46781
Distance variable is not defined yet.
9558
38927
Distance variable is not defined yet.
9559
58781
Distance variable is not defined yet.
9560
38723
Distance variable is not defined yet.
9561
58576
Distance variable is not defined yet.
9562
57213
Distance variable is not defined yet.
9563
78954
Distance variable is not defined yet.
9564
42275
Distance variable is not defined yet.
9565
05846
Distance variable is not defined yet.
9566
68834
Distance variable is not defined yet.
9567
61358
Distance variable is not defined yet.
9568
58632
Distance variable is not defined yet.
9569
13051
Distance variable is not defined yet.
9570
04472
Distance variable is not defined yet.
9571
98392
Distance variable is not defined yet.
9572
96121
Distance variable is not defined yet.
9573
25109
Distance variable is not defined yet.
9574
49653
Distance variable is not defined yet.
9575
08346
Distance variable is not defined yet.
9576
16689
Distance variable is not defined yet.
9577
57073
Distance variable is not defined yet.
9578
76824
Distance
28554.01474913989
9579
39168
Distance variable is not defined yet.
9580
75440
Distance variable is not defined yet.
9581
51003
Distance
6222.44363655572
9582
65764
Distance variable is not defined yet.
9583
64865
Distance variable is not defined yet.
9584
25102
Distance variable is not defined yet.
9585
84069
Distance variable is not defined yet.
9586
50680
Distance variable is not defined yet.
9587
84076
Distance
21883.615418619967
9588
62530
Distance variable is not defined yet.
9589
41840
Distance variable is not defined yet.
9590
66933
Distance variable is not defined yet.
9591
66053
Distance variable is not defined yet.
9592
53585
Distance variable is not defined yet.
9593
59754
Distance
8500.449718629085
9594
81222
Distance variable is not defined yet.
9595
98590
Distance variable is not defined yet.
9596
42782
Distance variable is not defined yet.
9597
54870
Distance
28519.764729493036
9598
21915
Distance variable is not defined yet.
9599
78947
Distance
28516.732400920682
9600
46392
Distance variable is not defined yet.
9601
55092
Distance
28513.984690695255
9602
04006
Distance variable is not defined yet.
9603
06057
Distance variable is not defined yet.
9604
58484
Distance variable is not defined yet.
9605
36010
Distance variable is not defined yet.
9606
44275
Distance variable is not defined yet.
9607
27551
Distance
28505.963970451307
9608
50440
Distance
28502.74624902823
9609
14592
Distance variable is not defined yet.
9610
59454
Distance variable is not defined yet.
9611
77021
Distance
9817.165823245059
9612
78881
Distance variable is not defined yet.
9613
25611
Distance
19269.553183983982
9614
50541
Distance variable is not defined yet.
9615
37151
Distance variable is not defined yet.
9616
55769
Distance variable is not defined yet.
9617
59338
Distance variable is not defined yet.
9618
52214
Distance variable is not defined yet.
9619
68372
Distance variable is not defined yet.
9620
72749
Distance variable is not defined yet.
9621
57348
Distance variable is not defined yet.
9622
16691
Distance variable is not defined yet.
9623
87049
Distance variable is not defined yet.
9624
40949
Distance variable is not defined yet.
9625
44491
Distance variable is not defined yet.
9626
80723
Distance variable is not defined yet.
9627
20608
Distance variable is not defined yet.
9628
55763
Distance variable is not defined yet.
9629
56569
Distance
20704.230083064165
9630
15680
Distance variable is not defined yet.
9631
62672
Distance variable is not defined yet.
9632
29564
Distance
28469.581252630578
9633
95018
Distance variable is not defined yet.
9634
31825
Distance variable is not defined yet.
9635
19964
Distance
22639.807793989996
9636
68836
Distance variable is not defined yet.
9637
15038
Distance
11619.218192071972
9638
35466
Distance variable is not defined yet.
9639
49822
Distance variable is not defined yet.
9640
56097
Distance variable is not defined yet.
9641
12780
Distance variable is not defined yet.
9642
61913
Distance variable is not defined yet.
9643
29727
Distance
28450.58467718743
9644
14818
Distance variable is not defined yet.
9645
13672
Distance variable is not defined yet.
9646
41861
Distance
28289.83897084591
9647
64726
Distance variable is not defined yet.
9648
97410
Distance variable is not defined yet.
9649
22534
Distance
14204.634827581023
9650
79058
Distance variable is not defined yet.
9651
27510
Distance
28445.35680395615
9652
61561
Distance variable is not defined yet.
9653
36578
Distance
14166.82588111672
9654
81044
Distance variable is not defined yet.
9655
41572
Distance
21955.62088351819
9656
35981
Distance variable is not defined yet.
9657
40372
Distance variable is not defined yet.
9658
78055
Distance variable is not defined yet.
9659
03777
Distance variable is not defined yet.
9660
54740
Distance variable is not defined yet.
9661
96776
Distance
14557.5136735216
9662
32102
Distance
28424.984477614624
9663
68358
Distance variable is not defined yet.
9664
53956
Distance variable is not defined yet.
9665
67466
Distance variable is not defined yet.
9666
48506
Distance variable is not defined yet.
9667
53061
Distance
28413.10877332336
9668
72837
Distance variable is not defined yet.
9669
88048
Distance variable is not defined yet.
9670
67016
Distance variable is not defined yet.
9671
89815
Distance variable is not defined yet.
9672
26236
Distance variable is not defined yet.
9673
50240
Distance variable is not defined yet.
9674
71839
Distance variable is not defined yet.
9675
34787
Distance variable is not defined yet.
9676
61338
Distance variable is not defined yet.
9677
58773
Distance variable is not defined yet.
9678
28366
Distance
28392.483483106436
9679
40906
Distance variable is not defined yet.
9680
28466
Distance variable is not defined yet.
9681
46056
Distance
14553.307184577812
9682
17045
Distance variable is not defined yet.
9683
42764
Distance variable is not defined yet.
9684
83433
Distance variable is not defined yet.
9685
65667
Distance variable is not defined yet.
9686
62938
Distance variable is not defined yet.
9687
05487
Distance
28297.69137828881
9688
40111
Distance variable is not defined yet.
9689
12741
Distance variable is not defined yet.
9690
49680
Distance variable is not defined yet.
9691
12154
Distance variable is not defined yet.
9692
68768
Distance variable is not defined yet.
9693
48437
Distance variable is not defined yet.
9694
63454
Distance variable is not defined yet.
9695
54462
Distance variable is not defined yet.
9696
20714
Distance variable is not defined yet.
9697
44830
Distance variable is not defined yet.
9698
87531
Distance variable is not defined yet.
9699
58385
Distance variable is not defined yet.
9700
47958
Distance variable is not defined yet.
9701
14781
Distance variable is not defined yet.
9702
71724
Distance variable is not defined yet.
9703
48532
Distance variable is not defined yet.
9704
49819
Distance variable is not defined yet.
9705
66542
Distance
12130.872862800274
9706
24054
Distance variable is not defined yet.
9707
68810
Distance variable is not defined yet.
9708
62017
Distance
19513.583369358224
9709
71638
Distance variable is not defined yet.
9710
43788
Distance variable is not defined yet.
9711
75127
Distance variable is not defined yet.
9712
27050
Distance
19532.172870646395
9713
99590
Distance
28343.84307114934
9714
74535
Distance variable is not defined yet.
9715
55717
Distance
28340.588982141297
9716
54426
Distance variable is not defined yet.
9717
98536
Distance variable is not defined yet.
9718
73054
Distance variable is not defined yet.
9719
13674
Distance variable is not defined yet.
9720
48554
Distance variable is not defined yet.
9721
61064
Distance variable is not defined yet.
9722
45658
Distance
28332.318467051748
9723
28443
Distance variable is not defined yet.
9724
76882
Distance variable is not defined yet.
9725
27107
Distance
13830.28513358578
9726
97412
Distance variable is not defined yet.
9727
45861
Distance variable is not defined yet.
9728
52336
Distance variable is not defined yet.
9729
56183
Distance variable is not defined yet.
9730
36024
Distance variable is not defined yet.
9731
64683
Distance
21542.020111754926
9732
46714
Distance variable is not defined yet.
9733
24472
Distance variable is not defined yet.
9734
19549
Distance variable is not defined yet.
9735
70344
Distance variable is not defined yet.
9736
16671
Distance variable is not defined yet.
9737
50426
Distance variable is not defined yet.
9738
36439
Distance variable is not defined yet.
9739
66872
Distance variable is not defined yet.
9740
43731
Distance variable is not defined yet.
9741
70653
Distance
26140.659187793994
9742
50563
Distance variable is not defined yet.
9743
42050
Distance variable is not defined yet.
9744
99363
Distance variable is not defined yet.
9745
71424
Distance variable is not defined yet.
9746
20611
Distance variable is not defined yet.
9747
04267
Distance variable is not defined yet.
9748
35006
Distance variable is not defined yet.
9749
43501
Distance variable is not defined yet.
9750
61284
Distance variable is not defined yet.
9751
14549
Distance variable is not defined yet.
9752
49310
Distance variable is not defined yet.
9753
17953
Distance variable is not defined yet.
9754
28583
Distance variable is not defined yet.
9755
03243
Distance variable is not defined yet.
9756
76858
Distance variable is not defined yet.
9757
44689
Distance variable is not defined yet.
9758
47102
Distance variable is not defined yet.
9759
37882
Distance
28282.340151543005
9760
53813
Distance variable is not defined yet.
9761
18405
Distance variable is not defined yet.
9762
48829
Distance variable is not defined yet.
9763
54486
Distance
28266.20770755141
9764
35053
Distance variable is not defined yet.
9765
45688
Distance
26570.425367274027
9766
73491
Distance variable is not defined yet.
9767
10928
Distance
18395.301460846003
9768
58058
Distance variable is not defined yet.
9769
42602
Distance variable is not defined yet.
9770
38965
Distance variable is not defined yet.
9771
96722
Distance
28251.032688679938
9772
55742
Distance variable is not defined yet.
9773
81144
Distance
25398.70256384446
9774
70339
Distance variable is not defined yet.
9775
31557
Distance variable is not defined yet.
9776
29580
Distance variable is not defined yet.
9777
97110
Distance variable is not defined yet.
9778
31620
Distance
28234.50544713989
9779
40927
Distance variable is not defined yet.
9780
45636
Distance
8410.943538790418
9781
01070
Distance variable is not defined yet.
9782
62685
Distance variable is not defined yet.
9783
72419
Distance variable is not defined yet.
9784
53948
Distance
10064.593854320121
9785
42206
Distance variable is not defined yet.
9786
62812
Distance variable is not defined yet.
9787
25512
Distance variable is not defined yet.
9788
76008
Distance variable is not defined yet.
9789
87553
Distance variable is not defined yet.
9790
83871
Distance variable is not defined yet.
9791
71433
Distance variable is not defined yet.
9792
36311
Distance variable is not defined yet.
9793
57472
Distance variable is not defined yet.
9794
45716
Distance variable is not defined yet.
9795
46181

Warning: Cannot load hourly/2021/TOFHW.csv.gz from https://bulk.meteostat.net/v2/

Distance
22952.290895270657
10444
71234
Distance variable is not defined yet.
10445
44693
Distance variable is not defined yet.
10446
25007
Distance variable is not defined yet.
10447
99030
Distance variable is not defined yet.
10448
50102
Distance variable is not defined yet.
10449
98953
Distance
23468.1713121506
10450
81022
Distance variable is not defined yet.
10451
60470
Distance variable is not defined yet.
10452
04281
Distance variable is not defined yet.
10453
48042
Distance
10928.64092724851
10454
23882
Distance
27227.739504431414
10455
78146
Distance
24806.543991408063
10456
47633
Distance variable is not defined yet.
10457
47359
Distance variable is not defined yet.
10458
12978
Distance
23835.867889413505
10459
62950
Distance variable is not defined yet.
10460
37762
Distance
25185.62262833516
10461
95645
Distance
27221.244148968668
10462
17822
Distance variable is not defined yet.
10463
34987
Distance
27219.320048303834
10464
92268
Distance variable is not defined yet.
10465
99561
Distance
27218.324064693978
10466
40069
Distance
9269.836471863948
10467
55712
Distance variable is not defined yet.
10468
29676
Distance variable is not defined yet.
10469
01083
Distance variable is not defined yet.
10470
12471
Distance variable is not defined yet.
10471
45332
Distance variable is not defined yet.
10472
96116
Distance variable is not defined yet.
10473
04613
Distance variable is not defined yet.
10474
48748
Distance variable is not defined yet.
10475
51354
Distance variable is not defined yet.
10476
87750
Distance variable is not defined yet.
10477
29114
Distance variable is not defined yet.
10478
72169
Distance variable is not defined yet.
10479
62547
Distance variable is not defined yet.
10480
40361
Distance
18391.795709157133
10481
58521
Distance variable is not defined yet.
10482
52046
Distance variable is not defined yet.
10483
54909
Distance variable is not defined yet.
10484
28523
Distance variable is not defined yet.
10485
58641
Distance variable is not defined yet.
10486
75651
Distance variable is not defined yet.
10487
75852
Distance variable is not defined yet.
10488
28439
Distance variable is not defined yet.
10489
37060
Distance
27189.218114346113
10490
60120
Distance
12404.977669314068
10491
60437
Distance variable is not defined yet.
10492
27563
Distance variable is not defined yet.
10493
31326
Distance variable is not defined yet.
10494
48097
Distance variable is not defined yet.
10495
27888
Distance
27186.521239086378
10496
62916
Distance
26978.059964985783
10497
74039
Distance variable is not defined yet.
10498
14485
Distance
22661.119209942444
10499
50854
Distance variable is not defined yet.
10500
26260
Distance variable is not defined yet.
10501
32058
Distance
17693.682656441742
10502
65653
Distance variable is not defined yet.
10503
24476
Distance variable is not defined yet.
10504
24844
Distance variable is not defined yet.
10505
44021
Distance variable is not defined yet.
10506
97135
Distance variable is not defined yet.
10507
81140
Distance variable is not defined yet.
10508
69171
Distance
6029.768530503909
10509
88254
Distance variable is not defined yet.
10510
16345
Distance variable is not defined yet.
10511
77664
Distance variable is not defined yet.
10512
62047
Distance variable is not defined yet.
10513
53911
Distance variable is not defined yet.
10514
42232
Distance variable is not defined yet.
10515
38621
Distance variable is not defined yet.
10516
25985
Distance variable is not defined yet.
10517
47140
Distance variable is not defined yet.
10518
62663
Distance variable is not defined yet.
10519
41773
Distance variable is not defined yet.
10520
29047
Distance variable is not defined yet.
10521
15678
Distance
18185.960655149636
10522
47525
Distance variable is not defined yet.
10523
62376
Distance variable is not defined yet.
10524
30546
Distance variable is not defined yet.
10525
80651
Distance variable is not defined yet.
10526
32259
Distance
19557.675133453868
10527
52249
Distance variable is not defined yet.
10528
22815
Distance
27127.38264601922
10529
78944
Distance variable is not defined yet.
10530
31643
Distance variable is not defined yet.
10531
58365
Distance variable is not defined yet.
10532
18072
Distance variable is not defined yet.
10533
73002
Distance variable is not defined yet.
10534
37722
Distance variable is not defined yet.
10535
70637
Distance variable is not defined yet.
10536
14057
Distance
27116.536621764757
10537
04932
Distance variable is not defined yet.
10538
56715
Distance variable is not defined yet.
10539
41563
Distance variable is not defined yet.
10540
52170
Distance variable is not defined yet.
10541
48727
Distance variable is not defined yet.
10542
73572
Distance variable is not defined yet.
10543
77983
Distance variable is not defined yet.
10544
42565
Distance variable is not defined yet.
10545
86326
Distance variable is not defined yet.
10546
08092
Distance
20082.343827017696
10547
61933
Distance variable is not defined yet.
10548
75757
Distance variable is not defined yet.
10549
12746
Distance variable is not defined yet.
10550
47975
Distance variable is not defined yet.
10551
95664
Distance
17664.878291478548
10552
16731
Distance variable is not defined yet.
10553
15322
Distance variable is not defined yet.
10554
78650
Distance variable is not defined yet.
10555
06243
Distance variable is not defined yet.
10556
18327
Distance variable is not defined yet.
10557
17020
Distance variable is not defined yet.
10558
15366
Distance
22193.489032756184
10559
24251
Distance variable is not defined yet.
10560
16137
Distance variable is not defined yet.
10561
96790

Warning: Cannot load hourly/2021/91191.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/91191.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/91191.csv.gz from https://bulk.meteostat.net/v2/

Distance
27072.751901438125
10562
46037
Distance
8798.607408774156
10563
38674
Distance variable is not defined yet.
10564
72453
Distance
13373.663650486073
10565
27979
Distance variable is not defined yet.
10566
61849
Distance variable is not defined yet.
10567
41503
Distance variable is not defined yet.
10568
49632
Distance variable is not defined yet.
10569
50545
Distance variable is not defined yet.
10570
12920
Distance variable is not defined yet.
10571
67732
Distance
27067.248818895812
10572
18058
Distance
24334.53924538071
10573
15423
Distance variable is not defined yet.
10574
81067
Distance variable is not defined yet.
10575
45659
Distance
16322.365606964357
10576
19550
Distance variable is not defined yet.
10577
47619
Distance variable is not defined yet.
10578
62550
Distance variable is not defined yet.
10579
15642
Distance
17495.91567711107
10580
65802
Distance variable is not defined yet.
10581
75790
Distance variable is not defined yet.
10582
50476
Distance variable is not defined yet.
10583
50650
Distance variable is not defined yet.
10584
04042
Distance variable is not defined yet.
10585
95075
Distance variable is not defined yet.
10586
94971
Distance variable is not defined yet.
10587
70780
Distance
25995.76269958979
10588
81645
Distance variable is not defined yet.
10589
59913
Distance variable is not defined yet.
10590
14042
Distance variable is not defined yet.
10591
25126
Distance variable is not defined yet.
10592
86329
Distance variable is not defined yet.
10593
05454
Distance variable is not defined yet.
10594
95041
Distance variable is not defined yet.
10595
15054
Distance variable is not defined yet.
10596
50701
Distance variable is not defined yet.
10597
59647
Distance variable is not defined yet.
10598
15724
Distance variable is not defined yet.
10599
49230
Distance
27014.686308526376
10600
68415
Distance variable is not defined yet.
10601
16930
Distance variable is not defined yet.
10602
37023
Distance variable is not defined yet.
10603
32619
Distance variable is not defined yet.
10604
62428
Distance variable is not defined yet.
10605
36022
Distance
22504.368455798805
10606
14709
Distance variable is not defined yet.
10607
87072
Distance variable is not defined yet.
10608
56438
Distance
26737.12461236209
10609
43442
Distance variable is not defined yet.
10610
13403
Distance
9371.440928389742
10611
86406
Distance variable is not defined yet.
10612
17566
Distance variable is not defined yet.
10613
45827
Distance variable is not defined yet.
10614
72567
Distance variable is not defined yet.
10615
68405
Distance variable is not defined yet.
10616
27591
Distance
26985.70391124183
10617
62345
Distance variable is not defined yet.
10618
54839
Distance variable is not defined yet.
10619
24122
Distance variable is not defined yet.
10620
94573
Distance variable is not defined yet.
10621
57716
Distance variable is not defined yet.
10622
57218
Distance variable is not defined yet.
10623
83237
Distance variable is not defined yet.
10624
47654
Distance variable is not defined yet.
10625
13825
Distance variable is not defined yet.
10626
84760
Distance variable is not defined yet.
10627
05076
Distance variable is not defined yet.
10628
94558
Distance variable is not defined yet.
10629
18415
Distance variable is not defined yet.
10630
84746
Distance
26701.362258477435
10631
51241
Distance variable is not defined yet.
10632
32305
Distance variable is not defined yet.
10633
65810
Distance variable is not defined yet.
10634
14481
Distance variable is not defined yet.
10635
67859
Distance variable is not defined yet.
10636
73843
Distance
12367.799195143978
10637
28587
Distance variable is not defined yet.
10638
35974
Distance variable is not defined yet.
10639
50056
Distance variable is not defined yet.
10640
49668
Distance variable is not defined yet.
10641
69360
Distance variable is not defined yet.
10642
12170
Distance variable is not defined yet.
10643
25951
Distance variable is not defined yet.
10644
55960
Distance
14052.009394083403
10645
29125
Distance variable is not defined yet.
10646
76577
Distance variable is not defined yet.
10647
32966
Distance
24368.114344199264
10648
46072
Distance variable is not defined yet.
10649
35188
Distance variable is not defined yet.
10650
51060
Distance variable is not defined yet.
10651
56549
Distance variable is not defined yet.
10652
74061
Distance variable is not defined yet.
10653
80726
Distance
17309.250605303077
10654
49825
Distance variable is not defined yet.
10655
64637
Distance variable is not defined yet.
10656
43804
Distance variable is not defined yet.
10657
29458
Distance variable is not defined yet.
10658
91931
Distance variable is not defined yet.
10659
15459
Distance
23377.011868003436
10660
40014
Distance variable is not defined yet.
10661
20144
Distance variable is not defined yet.
10662
84037
Distance
9620.085660775712
10663
76689
Distance variable is not defined yet.
10664
95698
Distance variable is not defined yet.
10665
38259
Distance variable is not defined yet.
10666
06065
Distance variable is not defined yet.
10667
52569
Distance variable is not defined yet.
10668
49682
Distance variable is not defined yet.
10669
79407
Distance
5070.153769939086
10670
99111
Distance variable is not defined yet.
10671
97122
Distance variable is not defined yet.
10672
05069
Distance variable is not defined yet.
10673
41612
Distance
23191.462045184922
10674
49855
Distance
7847.620996283157
10675
75765
Distance variable is not defined yet.
10676
45770
Distance variable is not defined yet.
10677
85749
Distance variable is not defined yet.
10678
60960
Distance variable is not defined yet.
10679
79535
Distance variable is not defined yet.
10680
71303
Distance variable is not defined yet.
10681
27233
Distance variable is not defined yet.
10682
36320
Distance variable is not defined yet.
10683
62533
Distance variable is not defined yet.
10684
30559
Distance variable is not defined yet.
10685
24830
Distance variable is not defined yet.
10686
71358
Distance variable is not defined yet.
10687
04063
Distance variable is not defined yet.
10688
67643
Distance variable is not defined yet.
10689
70070
Distance
25149.016384833118
10690
48622
Distance variable is not defined yet.
10691
49341
Distance variable is not defined yet.
10692
49878
Distance variable is not defined yet.
10693
44601
Distance variable is not defined yet.
10694
74428
Distance variable is not defined yet.
10695
93220
Distance variable is not defined yet.
10696
61816
Distance variable is not defined yet.
10697
47040
Distance variable is not defined yet.
10698
04461
Distance variable is not defined yet.
10699
32681
Distance variable is not defined yet.
10700
28702
Distance variable is not defined yet.
10701
74436
Distance variable is not defined yet.
10702
15622
Distance
26209.129044002715
10703
68883
Distance variable is not defined yet.
10704
37385
Distance
26856.940675223483
10705
93553

Warning: Cannot load hourly/2021/72289.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/72289.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/72289.csv.gz from https://bulk.meteostat.net/v2/

Distance
25716.81515322111
10706
73439
Distance variable is not defined yet.
10707
42273
Distance variable is not defined yet.
10708
39654
Distance variable is not defined yet.
10709
76265
Distance variable is not defined yet.
10710
39851
Distance variable is not defined yet.
10711
15320
Distance variable is not defined yet.
10712
17981
Distance variable is not defined yet.
10713
66966
Distance variable is not defined yet.
10714
65790
Distance
23728.709379081756
10715
54559
Distance variable is not defined yet.
10716
76486
Distance variable is not defined yet.
10717
21653
Distance
11117.083308166455
10718
43420
Distance variable is not defined yet.
10719
12921
Distance
23656.575594559352
10720
65766
Distance variable is not defined yet.
10721
63821
Distance variable is not defined yet.
10722
45828
Distance variable is not defined yet.
10723
92629
Distance
21155.69545476269
10724
52765
Distance variable is not defined yet.
10725
58429
Distance variable is not defined yet.
10726
28469
Distance variable is not defined yet.
10727
18353
Distance variable is not defined yet.
10728
04061
Distance variable is not defined yet.
10729
46349
Distance variable is not defined yet.
10730
04055
Distance variable is not defined yet.
10731
47393
Distance variable is not defined yet.
10732
82712
Distance variable is not defined yet.
10733
78941
Distance variable is not defined yet.
10734
51108
Distance variable is not defined yet.
10735
83638
Distance variable is not defined yet.
10736
16630
Distance variable is not defined yet.
10737
58759
Distance variable is not defined yet.
10738
98670
Distance variable is not defined yet.
10739
46115
Distance variable is not defined yet.
10740
25174
Distance variable is not defined yet.
10741
56113
Distance variable is not defined yet.
10742
26263
Distance variable is not defined yet.
10743
12160
Distance variable is not defined yet.
10744
92604
Distance
7091.782779635325
10745
04038
Distance variable is not defined yet.
10746
23153
Distance variable is not defined yet.
10747
72067
Distance variable is not defined yet.
10748
39478
Distance variable is not defined yet.
10749
17866
Distance variable is not defined yet.
10750
01253
Distance variable is not defined yet.
10751
21660
Distance
23101.65567928351
10752
10535
Distance variable is not defined yet.
10753
47390
Distance
26776.241917668143
10754
58012
Distance variable is not defined yet.
10755
27024
Distance variable is not defined yet.
10756
62681
Distance variable is not defined yet.
10757
47574
Distance variable is not defined yet.
10758
50472
Distance variable is not defined yet.
10759
53583
Distance variable is not defined yet.
10760
98570
Distance
22129.343253600655
10761
92694
Distance
15829.626883357194
10762
61876
Distance variable is not defined yet.
10763
32466
Distance
25334.767815059346
10764
40023
Distance variable is not defined yet.
10765
71033
Distance variable is not defined yet.
10766
70355
Distance variable is not defined yet.
10767
12885
Distance variable is not defined yet.
10768
77336
Distance variable is not defined yet.
10769
63539
Distance variable is not defined yet.
10770
88231
Distance variable is not defined yet.
10771
18340
Distance variable is not defined yet.
10772
72139
Distance variable is not defined yet.
10773
61345
Distance variable is not defined yet.
10774
72521
Distance variable is not defined yet.
10775
64066
Distance variable is not defined yet.
10776
77447
Distance variable is not defined yet.
10777
43332
Distance variable is not defined yet.
10778
71417
Distance variable is not defined yet.
10779
59344
Distance variable is not defined yet.
10780
82214
Distance
2570.9354367996157
10781
14037
Distance variable is not defined yet.
10782
31031
Distance
26738.55810119946
10783
31556
Distance variable is not defined yet.
10784
95219
Distance
26735.673345934858
10785
93065
Distance
22389.159527777454
10786
67526
Distance variable is not defined yet.
10787
75432
Distance variable is not defined yet.
10788
52588
Distance variable is not defined yet.
10789
54552
Distance
10709.859544182931
10790
75472
Distance variable is not defined yet.
10791
82060
Distance
22013.056865283346
10792
57741
Distance variable is not defined yet.
10793
47388
Distance
18111.46074002642
10794
42085
Distance variable is not defined yet.
10795
72630
Distance variable is not defined yet.
10796
57065
Distance variable is not defined yet.
10797
89060
Distance variable is not defined yet.
10798
72073
Distance variable is not defined yet.
10799
41554
Distance
19576.393079773723
10800
01346
Distance variable is not defined yet.
10801
15926
Distance
16300.594675761235
10802
97357
Distance variable is not defined yet.
10803
55983
Distance variable is not defined yet.
10804
26570
Distance variable is not defined yet.
10805
28555
Distance
26705.80516484685
10806
56170
Distance variable is not defined yet.
10807
19970
Distance
26705.026529155053
10808
28622
Distance variable is not defined yet.
10809
73762
Distance variable is not defined yet.
10810
70726
Distance variable is not defined yet.
10811
03582
Distance variable is not defined yet.
10812
98263
Distance variable is not defined yet.
10813
32712
Distance
26691.820702652632
10814
34484
Distance
26691.381199521504
10815
61728
Distance variable is not defined yet.
10816
66753
Distance variable is not defined yet.
10817
64854
Distance variable is not defined yet.
10818
68301
Distance variable is not defined yet.
10819
57035
Distance variable is not defined yet.
10820
94970
Distance variable is not defined yet.
10821
35614
Distance
26685.32410969757
10822
78560
Distance variable is not defined yet.
10823
81415
Distance variable is not defined yet.
10824
75647
Distance
20016.720200301097
10825
89166
Distance variable is not defined yet.
10826
15146
Distance
15758.492810480397
10827
52069
Distance variable is not defined yet.
10828
15832
Distance variable is not defined yet.
10829
16263
Distance variable is not defined yet.
10830
01230
Distance variable is not defined yet.
10831
25437
Distance variable is not defined yet.
10832
04263
Distance variable is not defined yet.
10833
21036
Distance
15745.246077166787
10834
56152
Distance variable is not defined yet.
10835
45735
Distance variable is not defined yet.
10836
58580
Distance variable is not defined yet.
10837
29536
Distance variable is not defined yet.
10838
16401
Distance variable is not defined yet.
10839
81632
Distance variable is not defined yet.
10840
68305
Distance variable is not defined yet.
10841
38548
Distance variable is not defined yet.
10842
97378
Distance variable is not defined yet.
10843
67850
Distance variable is not defined yet.
10844
45761
Distance variable is not defined yet.
10845
42724
Distance
12372.258635612277
10846
53538
Distance variable is not defined yet.
10847
52305
Distance variable is not defined yet.
10848
85924
Distance variable is not defined yet.
10849
98541
Distance variable is not defined yet.
10850
12121
Distance variable is not defined yet.
10851
17023
Distance variable is not defined yet.
10852
25840
Distance variable is not defined yet.
10853
62356
Distance variable is not defined yet.
10854
52339
Distance variable is not defined yet.
10855
76043
Distance variable is not defined yet.
10856
30218
Distance
26651.87713621718
10857
47946
Distance variable is not defined yet.
10858
54827
Distance variable is not defined yet.
10859
27127
Distance
13516.853298848835
10860
40868
Distance variable is not defined yet.
10861
98643
Distance variable is not defined yet.
10862
51243
Distance variable is not defined yet.
10863
59638
Distance variable is not defined yet.
10864
72044
Distance variable is not defined yet.
10865
49630
Distance variable is not defined yet.
10866
04668
Distance variable is not defined yet.
10867
58036
Distance variable is not defined yet.
10868
78411
Distance
10176.38526145426
10869
57623
Distance variable is not defined yet.
10870
05359
Distance variable is not defined yet.
10871
38746
Distance variable is not defined yet.
10872
35033
Distance variable is not defined yet.
10873
24464
Distance variable is not defined yet.
10874
72331
Distance variable is not defined yet.
10875
24910
Distance variable is not defined yet.
10876
24174
Distance variable is not defined yet.
10877
28675
Distance variable is not defined yet.
10878
67664
Distance variable is not defined yet.
10879
72384
Distance variable is not defined yet.
10880
67054
Distance variable is not defined yet.
10881
65326
Distance variable is not defined yet.
10882
61953
Distance variable is not defined yet.
10883
03602
Distance variable is not defined yet.
10884
47584
Distance variable is not defined yet.
10885
75105
Distance variable is not defined yet.
10886
98382
Distance
26616.57582003237
10887
26337
Distance variable is not defined yet.
10888
68063
Distance variable is not defined yet.
10889
94923
Distance variable is not defined yet.
10890
78412
Distance
5265.437970490749
10891
78011
Distance variable is not defined yet.
10892
71949
Distance variable is not defined yet.
10893
16229
Distance variable is not defined yet.
10894
20646
Distance variable is not defined yet.
10895
87020
Distance variable is not defined yet.
10896
64847
Distance variable is not defined yet.
10897
26059
Distance
11904.124844968279
10898
30633
Distance
26602.88035880048
10899
62880
Distance variable is not defined yet.
10900
47118
Distance variable is not defined yet.
10901
77614
Distance variable is not defined yet.
10902
62214
Distance variable is not defined yet.
10903
49646
Distance variable is not defined yet.
10904
37061
Distance variable is not defined yet.
10905
15741
Distance variable is not defined yet.
10906
94550
Distance
22653.32380138397
10907
46310
Distance variable is not defined yet.
10908
96773
Distance variable is not defined yet.
10909
49807
Distance variable is not defined yet.
10910
36263
Distance variable is not defined yet.
10911
12910
Distance
24591.123550419867
10912
41132
Distance variable is not defined yet.
10913
24630
Distance variable is not defined yet.
10914
37643
Distance
3350.8942256476107
10915
44450
Distance variable is not defined yet.
10916
64648
Distance variable is not defined yet.
10917
33947
Distance
26571.854910237846
10918
56477
Distance variable is not defined yet.
10919
38341
Distance variable is not defined yet.
10920
57640
Distance variable is not defined yet.
10921
37335
Distance
14515.507973682623
10922
62885
Distance
17716.8473907523
10923
59258
Distance variable is not defined yet.
10924
40065
Distance variable is not defined yet.
10925
74347
Distance variable is not defined yet.
10926
03284
Distance variable is not defined yet.
10927
38722
Distance variable is not defined yet.
10928
79343
Distance variable is not defined yet.
10929
47431
Distance variable is not defined yet.
10930
72947
Distance variable is not defined yet.
10931
72026
Distance variable is not defined yet.
10932
55025
Distance
19988.11298974009
10933
17813
Distance variable is not defined yet.
10934
47420
Distance variable is not defined yet.
10935
67583
Distance variable is not defined yet.
10936
77442
Distance
24124.96759484211
10937
48737
Distance variable is not defined yet.
10938
64755
Distance variable is not defined yet.
10939
75163
Distance variable is not defined yet.
10940
17821
Distance variable is not defined yet.
10941
75759
Distance variable is not defined yet.
10942
94597
Distance
26239.984111346195
10943
33001
Distance variable is not defined yet.
10944
36509
Distance variable is not defined yet.
10945
05068
Distance variable is not defined yet.
10946
28537
Distance variable is not defined yet.
10947
25902
Distance variable is not defined yet.
10948
28448
Distance variable is not defined yet.
10949
38668
Distance variable is not defined yet.
10950
27016
Distance variable is not defined yet.
10951
54871
Distance variable is not defined yet.
10952
95466
Distance variable is not defined yet.
10953
96033
Distance variable is not defined yet.
10954
54498
Distance variable is not defined yet.
10955
10925
Distance variable is not defined yet.
10956
23827
Distance variable is not defined yet.
10957
35147
Distance variable is not defined yet.
10958
86040
Distance variable is not defined yet.
10959
47361
Distance
22234.002403630966
10960
50001
Distance variable is not defined yet.
10961
81123
Distance variable is not defined yet.
10962
62278
Distance variable is not defined yet.
10963
01301
Distance variable is not defined yet.
10964
54513
Distance
26504.683472807923
10965
67061
Distance variable is not defined yet.
10966
43321
Distance variable is not defined yet.
10967
24352
Distance variable is not defined yet.
10968
37016
Distance
26502.969577883996
10969
49638
Distance variable is not defined yet.
10970
63936
Distance
17215.032662998165
10971
63546
Distance variable is not defined yet.
10972
29449
Distance variable is not defined yet.
10973
21890
Distance
26497.589080043963
10974
13754
Distance variable is not defined yet.
10975
76263
Distance
26491.750515625
10976
62459
Distance variable is not defined yet.
10977
74083
Distance variable is not defined yet.
10978
49747
Distance variable is not defined yet.
10979
85087
Distance variable is not defined yet.
10980
19962
Distance
18755.888814039274
10981
64020
Distance variable is not defined yet.
10982
61850
Distance variable is not defined yet.
10983
45764
Distance variable is not defined yet.
10984
68446
Distance variable is not defined yet.
10985
03044
Distance
26472.943262090765
10986
15784
Distance variable is not defined yet.
10987
04348
Distance variable is not defined yet.
10988
35575
Distance variable is not defined yet.
10989
44687
Distance variable is not defined yet.
10990
83436
Distance variable is not defined yet.
10991
86331
Distance variable is not defined yet.
10992
49428
Distance variable is not defined yet.
10993
15864
Distance variable is not defined yet.
10994
47031
Distance variable is not defined yet.
10995
99656
Distance variable is not defined yet.
10996
66427
Distance variable is not defined yet.
10997
01039
Distance variable is not defined yet.
10998
42638
Distance variable is not defined yet.
10999
74852
Distance
26452.89681374706
11000
56353
Distance
26452.15396067191
11001
47177
Distance variable is not defined yet.
11002
76228
Distance variable is not defined yet.
11003
38225
Distance variable is not defined yet.
11004
28762
Distance variable is not defined yet.
11005
70578
Distance variable is not defined yet.
11006
82901
Distance variable is not defined yet.
11007
39083
Distance variable is not defined yet.
11008
01550
Distance variable is not defined yet.
11009
26884
Distance variable is not defined yet.
11010
03604
Distance variable is not defined yet.
11011
81084
Distance variable is not defined yet.
11012
50433
Distance variable is not defined yet.
11013
93432
Distance variable is not defined yet.
11014
48096
Distance
18756.472090547148
11015
64466
Distance variable is not defined yet.
11016
51550
Distance variable is not defined yet.
11017
17925
Distance variable is not defined yet.
11018
56680
Distance variable is not defined yet.
11019
91301
Distance variable is not defined yet.
11020
16734
Distance variable is not defined yet.
11021
73726
Distance variable is not defined yet.
11022
04020
Distance variable is not defined yet.
11023
74560
Distance variable is not defined yet.
11024
43338
Distance variable is not defined yet.
11025
44640
Distance variable is not defined yet.
11026
83624
Distance variable is not defined yet.
11027
12209
Distance variable is not defined yet.
11028
75446
Distance variable is not defined yet.
11029
44235
Distance variable is not defined yet.
11030
25142
Distance variable is not defined yet.
11031
79549
Distance variable is not defined yet.
11032
16699
Distance variable is not defined yet.
11033
71935
Distance variable is not defined yet.
11034
62836
Distance variable is not defined yet.
11035
95962
Distance variable is not defined yet.
11036
94806
Distance
25063.380259294
11037
56458
Distance variable is not defined yet.
11038
02650
Distance
4082.492888515243
11039
41559
Distance
16914.32341004321
11040
15333
Distance variable is not defined yet.
11041
74935
Distance variable is not defined yet.
11042
29567
Distance variable is not defined yet.
11043
16331
Distance variable is not defined yet.
11044
25411
Distance variable is not defined yet.
11045
01772
Distance
26378.20434465669
11046
72959
Distance variable is not defined yet.
11047
42647
Distance variable is not defined yet.
11048
87501
Distance variable is not defined yet.
11049
57532
Distance variable is not defined yet.
11050
60442
Distance
26372.885445647647
11051
38563
Distance variable is not defined yet.
11052
64475
Distance variable is not defined yet.
11053
08019
Distance
26371.55152748665
11054
41822
Distance variable is not defined yet.
11055
16333
Distance variable is not defined yet.
11056
72427
Distance variable is not defined yet.
11057
52637
Distance variable is not defined yet.
11058
48897
Distance variable is not defined yet.
11059
24250
Distance variable is not defined yet.
11060
77033
Distance
7641.40837801199
11061
53125
Distance variable is not defined yet.
11062
45630
Distance variable is not defined yet.
11063
39325
Distance variable is not defined yet.
11064
19967
Distance
23095.361229468646
11065
16829
Distance variable is not defined yet.
11066
44856
Distance variable is not defined yet.
11067
80650
Distance variable is not defined yet.
11068
99003
Distance
11610.813881850238
11069
94805
Distance
24376.07028431653
11070
98542
Distance
8544.342133754226
11071
12207
Distance variable is not defined yet.
11072
16942
Distance variable is not defined yet.
11073
63955
Distance
22385.04050186592
11074
01757
Distance variable is not defined yet.
11075
51048
Distance variable is not defined yet.
11076
30164
Distance variable is not defined yet.
11077
72410
Distance variable is not defined yet.
11078
55709
Distance variable is not defined yet.
11079
94924
Distance variable is not defined yet.
11080
37066
Distance
21679.41516203669
11081
68062
Distance variable is not defined yet.
11082
08312
Distance variable is not defined yet.
11083
88011
Distance
16831.001503683812
11084
84719
Distance variable is not defined yet.
11085
18631
Distance variable is not defined yet.
11086
54654
Distance variable is not defined yet.
11087
56667
Distance variable is not defined yet.
11088
77663
Distance variable is not defined yet.
11089
78932
Distance variable is not defined yet.
11090
41183
Distance
235.36304994534078
11091
16683
Distance variable is not defined yet.
11092
03225
Distance
26307.331580104088
11093
62225
Distance
678.964822400647
11094
25061
Distance variable is not defined yet.
11095
05034
Distance variable is not defined yet.
11096
66541
Distance variable is not defined yet.
11097
20878
Distance
9755.887520355443
11098
50480
Distance variable is not defined yet.
11099
34449
Distance
26292.93164007168
11100
17086
Distance variable is not defined yet.
11101
13495
Distance
9624.805108043476
11102
14889
Distance variable is not defined yet.
11103
39423
Distance variable is not defined yet.
11104
75428
Distance variable is not defined yet.
11105
36748
Distance variable is not defined yet.
11106
21861
Distance variable is not defined yet.
11107
48735
Distance variable is not defined yet.
11108
59248
Distance variable is not defined yet.
11109
59759
Distance variable is not defined yet.
11110
17952
Distance
25721.90379927848
11111
48050
Distance
20229.93224232099
11112
39662
Distance variable is not defined yet.
11113
81151
Distance variable is not defined yet.
11114
38313
Distance
26270.30284828407
11115
80836
Distance variable is not defined yet.
11116
88417
Distance variable is not defined yet.
11117
91354
Distance
26268.39633470765
11118
31816
Distance variable is not defined yet.
11119
01245
Distance variable is not defined yet.
11120
63645
Distance variable is not defined yet.
11121
50458
Distance variable is not defined yet.
11122

Warning: Cannot load hourly/2021/ULJ8M.csv.gz from https://bulk.meteostat.net/v2/

Distance
19326.992590034868
11412
30711
Distance variable is not defined yet.
11413
36752
Distance
18492.861325524445
11414
57028
Distance variable is not defined yet.
11415
44613
Distance variable is not defined yet.
11416
68717
Distance variable is not defined yet.
11417
72945
Distance
16112.155791183937
11418
75450
Distance variable is not defined yet.
11419
92392
Distance
22919.907122594155
11420
44429
Distance variable is not defined yet.
11421
12996
Distance variable is not defined yet.
11422
16922
Distance variable is not defined yet.
11423
31318
Distance variable is not defined yet.
11424
56176
Distance
25855.31259559607
11425
70652
Distance variable is not defined yet.
11426
59101
Distance variable is not defined yet.
11427
63436
Distance variable is not defined yet.
11428
44411
Distance variable is not defined yet.
11429
14804
Distance variable is not defined yet.
11430
26074
Distance
4507.59433611841
11431
78125
Distance
24595.808945595578
11432
80830
Distance
17843.630301191137
11433
79928
Distance variable is not defined yet.
11434
55334
Distance variable is not defined yet.
11435
10954
Distance variable is not defined yet.
11436
87421
Distance variable is not defined yet.
11437
10927
Distance variable is not defined yet.
11438
70757
Distance variable is not defined yet.
11439
29448
Distance variable is not defined yet.
11440
27214
Distance variable is not defined yet.
11441
58071
Distance variable is not defined yet.
11442
78349
Distance variable is not defined yet.
11443
55977
Distance variable is not defined yet.
11444
15760
Distance variable is not defined yet.
11445
74435
Distance variable is not defined yet.
11446
53534
Distance variable is not defined yet.
11447
58243
Distance variable is not defined yet.
11448
64422
Distance variable is not defined yet.
11449
17976
Distance variable is not defined yet.
11450
32776
Distance variable is not defined yet.
11451
77041
Distance
10020.849144493937
11452
25984
Distance variable is not defined yet.
11453
97021
Distance variable is not defined yet.
11454
60423
Distance variable is not defined yet.
11455
78369
Distance variable is not defined yet.
11456
60969
Distance variable is not defined yet.
11457
08902
Distance variable is not defined yet.
11458
38964
Distance variable is not defined yet.
11459
54446
Distance variable is not defined yet.
11460
06013
Distance
25806.542074729263
11461
25008
Distance variable is not defined yet.
11462
67753
Distance variable is not defined yet.
11463
98853
Distance variable is not defined yet.
11464
45742
Distance variable is not defined yet.
11465
37770
Distance variable is not defined yet.
11466
43569
Distance variable is not defined yet.
11467
29585
Distance
25799.80438324317
11468
18443
Distance variable is not defined yet.
11469
15695
Distance variable is not defined yet.
11470
31565
Distance variable is not defined yet.
11471
50863
Distance variable is not defined yet.
11472
62515
Distance variable is not defined yet.
11473
15014
Distance variable is not defined yet.
11474
03070
Distance
25792.995799088632
11475
97322
Distance variable is not defined yet.
11476
35580
Distance variable is not defined yet.
11477
37342
Distance
12534.285430410197
11478
62871
Distance variable is not defined yet.
11479
85331
Distance variable is not defined yet.
11480
14564
Distance
11514.042393945441
11481
61346
Distance variable is not defined yet.
11482
40489
Distance variable is not defined yet.
11483
62001
Distance variable is not defined yet.
11484
38311
Distance variable is not defined yet.
11485
06778
Distance variable is not defined yet.
11486
28444
Distance variable is not defined yet.
11487
14877
Distance variable is not defined yet.
11488
64831
Distance variable is not defined yet.
11489
24894
Distance variable is not defined yet.
11490
87567
Distance variable is not defined yet.
11491
65655
Distance variable is not defined yet.
11492
06351
Distance variable is not defined yet.
11493
50653
Distance variable is not defined yet.
11494
80610
Distance variable is not defined yet.
11495
37075
Distance
25760.440871984996
11496
61450
Distance variable is not defined yet.
11497
38870
Distance variable is not defined yet.
11498
45879
Distance variable is not defined yet.
11499
54460
Distance variable is not defined yet.
11500
74831
Distance variable is not defined yet.
11501
01952
Distance variable is not defined yet.
11502
94596
Distance
11481.301149628096
11503
14006
Distance variable is not defined yet.
11504
99676
Distance variable is not defined yet.
11505
40052
Distance
24512.68211476961
11506
49544
Distance variable is not defined yet.
11507
77020
Distance
15372.451630038091
11508
98010
Distance variable is not defined yet.
11509
62984
Distance variable is not defined yet.
11510
76567
Distance variable is not defined yet.
11511
78121
Distance
25743.751891168366
11512
65620
Distance variable is not defined yet.
11513
84039
Distance
25396.330246682468
11514
28383
Distance
19272.89468567198
11515
17317
Distance variable is not defined yet.
11516
22539
Distance variable is not defined yet.
11517
48436
Distance variable is not defined yet.
11518
05354
Distance variable is not defined yet.
11519
74959
Distance variable is not defined yet.
11520
15776
Distance variable is not defined yet.
11521
60948
Distance variable is not defined yet.
11522
02827
Distance variable is not defined yet.
11523
43832
Distance variable is not defined yet.
11524
61856
Distance variable is not defined yet.
11525
43406
Distance variable is not defined yet.
11526
07456
Distance variable is not defined yet.
11527
94021
Distance variable is not defined yet.
11528
44624
Distance variable is not defined yet.
11529
04471
Distance variable is not defined yet.
11530
29809
Distance variable is not defined yet.
11531
61241
Distance variable is not defined yet.
11532
38737
Distance variable is not defined yet.
11533
98538
Distance variable is not defined yet.
11534
28097
Distance variable is not defined yet.
11535
12837
Distance variable is not defined yet.
11536
99330
Distance variable is not defined yet.
11537
82009
Distance variable is not defined yet.
11538
62665
Distance variable is not defined yet.
11539
54537
Distance variable is not defined yet.
11540
07718
Distance variable is not defined yet.
11541
50058
Distance
22896.483021532345
11542
54630
Distance variable is not defined yet.
11543
15433
Distance variable is not defined yet.
11544
64671
Distance variable is not defined yet.
11545
74966
Distance variable is not defined yet.
11546
29479
Distance
25684.95378284309
11547
02633
Distance
2514.471536781684
11548
96705
Distance variable is not defined yet.
11549
30710
Distance variable is not defined yet.
11550
58346
Distance variable is not defined yet.
11551
23307
Distance variable is not defined yet.
11552
15078
Distance variable is not defined yet.
11553
37888
Distance variable is not defined yet.
11554
47841
Distance variable is not defined yet.
11555
79561
Distance variable is not defined yet.
11556
56523
Distance variable is not defined yet.
11557
14585
Distance
18585.570467905723
11558
75750
Distance variable is not defined yet.
11559
38021
Distance variable is not defined yet.
11560
46913
Distance variable is not defined yet.
11561
40771
Distance
16403.536280984667
11562
48023
Distance
17948.296226073413
11563
08852
Distance variable is not defined yet.
11564
96141
Distance
25660.513249541582
11565
28367
Distance
25659.730727610397
11566
54106
Distance variable is not defined yet.
11567
41527
Distance variable is not defined yet.
11568
56090
Distance variable is not defined yet.
11569
71004
Distance variable is not defined yet.
11570
35766
Distance variable is not defined yet.
11571
05737
Distance variable is not defined yet.
11572
06091
Distance variable is not defined yet.
11573
95954
Distance variable is not defined yet.
11574
57334
Distance variable is not defined yet.
11575
30185
Distance variable is not defined yet.
11576
13694
Distance variable is not defined yet.
11577
95248
Distance variable is not defined yet.
11578
49892
Distance variable is not defined yet.
11579
60020
Distance variable is not defined yet.
11580
57018
Distance variable is not defined yet.
11581
59252
Distance variable is not defined yet.
11582
36871
Distance variable is not defined yet.
11583
34286
Distance variable is not defined yet.
11584
27012
Distance
19770.74093122347
11585
50558
Distance variable is not defined yet.
11586
18331
Distance variable is not defined yet.
11587
05262
Distance
21809.426181870094
11588
25162
Distance variable is not defined yet.
11589
08343
Distance variable is not defined yet.
11590
26525
Distance
25248.826661654948
11591
77430
Distance variable is not defined yet.
11592
08867
Distance variable is not defined yet.
11593
30521
Distance
15146.201003078422
11594
93272
Distance variable is not defined yet.
11595
14466
Distance
25533.72529007201
11596
30441
Distance
24013.12267786455
11597
01518
Distance variable is not defined yet.
11598
91377
Distance variable is not defined yet.
11599
22476
Distance variable is not defined yet.
11600
14454
Distance variable is not defined yet.
11601
72768
Distance variable is not defined yet.
11602
54762
Distance variable is not defined yet.
11603
38858
Distance variable is not defined yet.
11604
36874
Distance
22065.09085748135
11605
71334
Distance
11782.935170328547
11606
81332
Distance variable is not defined yet.
11607
76569
Distance variable is not defined yet.
11608
99757
Distance
25598.363913686248
11609
32703
Distance variable is not defined yet.
11610
38456
Distance
11274.782616129893
11611
37166
Distance variable is not defined yet.
11612
10979
Distance variable is not defined yet.
11613
19559
Distance variable is not defined yet.
11614
23842
Distance variable is not defined yet.
11615
36071
Distance variable is not defined yet.
11616
46124
Distance
12679.264112957759
11617
31007
Distance variable is not defined yet.
11618
38833
Distance variable is not defined yet.
11619
47869
Distance variable is not defined yet.
11620
15043
Distance variable is not defined yet.
11621
29014
Distance
25583.498826473642
11622
47616
Distance variable is not defined yet.
11623
47918
Distance variable is not defined yet.
11624
61546
Distance variable is not defined yet.
11625
92230
Distance variable is not defined yet.
11626
71223
Distance variable is not defined yet.
11627
54488
Distance variable is not defined yet.
11628
48411
Distance variable is not defined yet.
11629
14479
Distance variable is not defined yet.
11630
29135
Distance
25563.378821648283
11631
71238
Distance variable is not defined yet.
11632
04072
Distance variable is not defined yet.
11633
30041
Distance
25560.843701545087
11634
29432
Distance variable is not defined yet.
11635
41535
Distance
24386.835072948368
11636
50449
Distance variable is not defined yet.
11637
43413
Distance variable is not defined yet.
11638
24593
Distance
22701.610276903917
11639
92602
Distance
9281.4811821812
11640
31543
Distance variable is not defined yet.
11641
56734
Distance variable is not defined yet.
11642
22436
Distance variable is not defined yet.
11643
12210
Distance variable is not defined yet.
11644
21636
Distance
8019.391968881486
11645
65807
Distance variable is not defined yet.
11646
62897
Distance variable is not defined yet.
11647
16435
Distance variable is not defined yet.
11648
13042
Distance variable is not defined yet.
11649
49404
Distance variable is not defined yet.
11650
47356
Distance
12375.497562105238
11651
70514
Distance variable is not defined yet.
11652
98345
Distance variable is not defined yet.
11653
54968
Distance variable is not defined yet.
11654
24571
Distance variable is not defined yet.
11655
76511
Distance variable is not defined yet.
11656
60936
Distance variable is not defined yet.
11657
76660
Distance variable is not defined yet.
11658
08816
Distance variable is not defined yet.
11659
69161
Distance variable is not defined yet.
11660
62920
Distance variable is not defined yet.
11661
81007
Distance variable is not defined yet.
11662
37050
Distance variable is not defined yet.
11663
58225
Distance variable is not defined yet.
11664
85737
Distance variable is not defined yet.
11665
65772
Distance variable is not defined yet.
11666
01745
Distance variable is not defined yet.
11667
83661
Distance variable is not defined yet.
11668
05732
Distance variable is not defined yet.
11669
34639
Distance variable is not defined yet.
11670
20850
Distance
8807.75894824116
11671
65282
Distance variable is not defined yet.
11672
60407
Distance variable is not defined yet.
11673
29080
Distance variable is not defined yet.
11674
52640
Distance variable is not defined yet.
11675
27356
Distance
25493.206400445204
11676
32615
Distance variable is not defined yet.
11677
50636
Distance variable is not defined yet.
11678
31562
Distance variable is not defined yet.
11679
15030
Distance variable is not defined yet.
11680
35087
Distance variable is not defined yet.
11681
66528
Distance variable is not defined yet.
11682
93451
Distance variable is not defined yet.
11683
24219
Distance variable is not defined yet.
11684
72136
Distance variable is not defined yet.
11685
30739
Distance
14597.077061851725
11686
05346
Distance variable is not defined yet.
11687
12785
Distance variable is not defined yet.
11688
08081
Distance variable is not defined yet.
11689
26234
Distance variable is not defined yet.
11690
01721
Distance
25460.846049378564
11691
04666
Distance
19137.18218197583
11692
87540
Distance variable is not defined yet.
11693
91362
Distance variable is not defined yet.
11694
75488
Distance variable is not defined yet.
11695
03238
Distance variable is not defined yet.
11696
58725
Distance variable is not defined yet.
11697
30553
Distance
12156.740165450317
11698
69026
Distance variable is not defined yet.
11699
04406
Distance variable is not defined yet.
11700
76086
Distance variable is not defined yet.
11701
08323
Distance variable is not defined yet.
11702
44659
Distance variable is not defined yet.
11703
62476
Distance variable is not defined yet.
11704
62355
Distance variable is not defined yet.
11705
58356
Distance variable is not defined yet.
11706
54201
Distance variable is not defined yet.
11707
99650
Distance
25420.686334192553
11708
27509
Distance variable is not defined yet.
11709
78162
Distance variable is not defined yet.
11710
24712
Distance variable is not defined yet.
11711
41810
Distance variable is not defined yet.
11712
97341
Distance variable is not defined yet.
11713
35620
Distance variable is not defined yet.
11714
97423
Distance variable is not defined yet.
11715
39145
Distance variable is not defined yet.
11716
37174
Distance variable is not defined yet.
11717
45786
Distance variable is not defined yet.
11718
04605
Distance variable is not defined yet.
11719
75471
Distance variable is not defined yet.
11720
36922
Distance variable is not defined yet.
11721
37322
Distance
10633.713552073777
11722
72544
Distance variable is not defined yet.
11723
05442
Distance variable is not defined yet.
11724
56536
Distance variable is not defined yet.
11725
36343
Distance
23439.49258752451
11726
56571
Distance variable is not defined yet.
11727
16038
Distance variable is not defined yet.
11728
51355
Distance
24709.783775623873
11729
47224
Distance variable is not defined yet.
11730
41004
Distance variable is not defined yet.
11731
43140

Warning: Cannot load hourly/2021/5WIOQ.csv.gz from https://bulk.meteostat.net/v2/

Distance
25381.09906200974
11732
63456
Distance variable is not defined yet.
11733
27243
Distance variable is not defined yet.
11734
75851
Distance variable is not defined yet.
11735
76087
Distance variable is not defined yet.
11736
12115
Distance variable is not defined yet.
11737
65669
Distance variable is not defined yet.
11738
79423
Distance
24839.47334330568
11739
70523
Distance variable is not defined yet.
11740
52554
Distance variable is not defined yet.
11741
81427
Distance variable is not defined yet.
11742
78636
Distance
25356.21978401755
11743
70782
Distance variable is not defined yet.
11744
55041
Distance variable is not defined yet.
11745
71060
Distance variable is not defined yet.
11746
83660
Distance variable is not defined yet.
11747
41602
Distance
10063.881622619263
11748
68927
Distance variable is not defined yet.
11749
03855
Distance variable is not defined yet.
11750
31087
Distance variable is not defined yet.
11751
99510
Distance
25347.91505823051
11752
37328
Distance
18324.918402838237
11753
75169
Distance variable is not defined yet.
11754
07737
Distance variable is not defined yet.
11755
28392
Distance variable is not defined yet.
11756
62538
Distance variable is not defined yet.
11757
13084
Distance variable is not defined yet.
11758
01011
Distance variable is not defined yet.
11759
64492
Distance variable is not defined yet.
11760
56469
Distance variable is not defined yet.
11761
99830
Distance variable is not defined yet.
11762
84319
Distance variable is not defined yet.
11763
98624
Distance variable is not defined yet.
11764
95631
Distance variable is not defined yet.
11765
12580
Distance
19760.035788006873
11766
38843
Distance variable is not defined yet.
11767
15927
Distance variable is not defined yet.
11768
51239
Distance
24411.009200794724
11769
54013
Distance variable is not defined yet.
11770
77971
Distance variable is not defined yet.
11771
48845
Distance variable is not defined yet.
11772
14486
Distance variable is not defined yet.
11773
59275
Distance variable is not defined yet.
11774
49263
Distance variable is not defined yet.
11775
68307
Distance variable is not defined yet.
11776
30528
Distance variable is not defined yet.
11777
47854
Distance variable is not defined yet.
11778
40442
Distance variable is not defined yet.
11779
21130
Distance variable is not defined yet.
11780
75975
Distance variable is not defined yet.
11781
24869
Distance variable is not defined yet.
11782
15681
Distance variable is not defined yet.
11783
29803
Distance variable is not defined yet.
11784
81155
Distance variable is not defined yet.
11785
98024
Distance variable is not defined yet.
11786
45382
Distance variable is not defined yet.
11787
94940
Distance variable is not defined yet.
11788
62373
Distance variable is not defined yet.
11789
26181
Distance variable is not defined yet.
11790
48178
Distance
25298.76520288409
11791
48032
Distance variable is not defined yet.
11792
66959
Distance variable is not defined yet.
11793
69146
Distance variable is not defined yet.
11794
38941
Distance variable is not defined yet.
11795
29639
Distance variable is not defined yet.
11796
82633
Distance variable is not defined yet.
11797
01966
Distance
25285.209683207897
11798
65633
Distance variable is not defined yet.
11799
04226
Distance variable is not defined yet.
11800
55330
Distance variable is not defined yet.
11801
33585
Distance
24674.690850265804
11802
97539
Distance variable is not defined yet.
11803
39439
Distance variable is not defined yet.
11804
16928
Distance variable is not defined yet.
11805
49866
Distance
2569.687144275373
11806
75860
Distance variable is not defined yet.
11807
41607
Distance
22830.539117349632
11808
49080
Distance variable is not defined yet.
11809
50020
Distance variable is not defined yet.
11810
63953
Distance
19832.965224294025
11811
22485
Distance variable is not defined yet.
11812
13650
Distance variable is not defined yet.
11813
87714
Distance variable is not defined yet.
11814
04468
Distance variable is not defined yet.
11815
27849
Distance variable is not defined yet.
11816
57522
Distance variable is not defined yet.
11817
97876
Distance variable is not defined yet.
11818
64439
Distance
22091.11942016435
11819
63739
Distance variable is not defined yet.
11820
38343
Distance variable is not defined yet.
11821
41650
Distance
20533.036154557845
11822
84004
Distance
25253.691480668607
11823
44451
Distance variable is not defined yet.
11824
60071
Distance variable is not defined yet.
11825
14169
Distance variable is not defined yet.
11826
88232
Distance variable is not defined yet.
11827
16443
Distance variable is not defined yet.
11828
12186
Distance variable is not defined yet.
11829
92086
Distance
25248.423223393584
11830
26587
Distance variable is not defined yet.
11831
05257
Distance
7310.422379537998
11832
50517
Distance variable is not defined yet.
11833
78934
Distance
7252.682874861036
11834
28621
Distance variable is not defined yet.
11835
41666
Distance variable is not defined yet.
11836
50206
Distance variable is not defined yet.
11837
24069
Distance variable is not defined yet.
11838
22460
Distance variable is not defined yet.
11839
77023
Distance
9979.049573646218
11840
12545
Distance
10663.658359632991
11841
49458
Distance variable is not defined yet.
11842
05827
Distance variable is not defined yet.
11843
72926
Distance variable is not defined yet.
11844
72645
Distance variable is not defined yet.
11845
43149
Distance variable is not defined yet.
11846
67146
Distance variable is not defined yet.
11847
44470
Distance variable is not defined yet.
11848
27842

Warning: Cannot load hourly/2021/KRZZ0.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/KRZZ0.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/KRZZ0.csv.gz from https://bulk.meteostat.net/v2/

Distance
16374.691303413945
11849
47850
Distance variable is not defined yet.
11850
21711
Distance variable is not defined yet.
11851
44887
Distance variable is not defined yet.
11852
44067
Distance
25220.993122537093
11853
24340
Distance variable is not defined yet.
11854
44608
Distance variable is not defined yet.
11855
72045
Distance variable is not defined yet.
11856
61529
Distance variable is not defined yet.
11857
77451
Distance variable is not defined yet.
11858
83856
Distance variable is not defined yet.
11859
62519
Distance variable is not defined yet.
11860
59276
Distance variable is not defined yet.
11861
51055
Distance variable is not defined yet.
11862
43345
Distance variable is not defined yet.
11863
54612
Distance variable is not defined yet.
11864
41777
Distance variable is not defined yet.
11865
55387
Distance
25210.153743694667
11866
39482
Distance
23782.286605109603
11867
62374
Distance variable is not defined yet.
11868
45154
Distance variable is not defined yet.
11869
75931
Distance variable is not defined yet.
11870
71837
Distance variable is not defined yet.
11871
24634
Distance variable is not defined yet.
11872
52223
Distance variable is not defined yet.
11873
51440
Distance
15392.131278395482
11874
44286
Distance variable is not defined yet.
11875
68003
Distance variable is not defined yet.
11876
27539
Distance variable is not defined yet.
11877
35553
Distance variable is not defined yet.
11878
04733
Distance variable is not defined yet.
11879
18706
Distance variable is not defined yet.
11880
79748
Distance variable is not defined yet.
11881
31796
Distance variable is not defined yet.
11882
12153
Distance variable is not defined yet.
11883
39756
Distance variable is not defined yet.
11884
57754
Distance variable is not defined yet.
11885
14721
Distance variable is not defined yet.
11886
37035
Distance variable is not defined yet.
11887
54628
Distance
25178.91657776087
11888
29045
Distance variable is not defined yet.
11889
30581
Distance variable is not defined yet.
11890
14414
Distance variable is not defined yet.
11891
14825
Distance variable is not defined yet.
11892
13138
Distance variable is not defined yet.
11893
55726
Distance variable is not defined yet.
11894
77055
Distance
17599.932018122756
11895
24124
Distance variable is not defined yet.
11896
99034
Distance variable is not defined yet.
11897
78416
Distance
15768.977330069172
11898
84305
Distance variable is not defined yet.
11899
46036
Distance variable is not defined yet.
11900
59044
Distance
7781.284078331221
11901
65262
Distance variable is not defined yet.
11902
35112
Distance variable is not defined yet.
11903
04349
Distance variable is not defined yet.
11904
36474
Distance variable is not defined yet.
11905
13131
Distance variable is not defined yet.
11906
75452
Distance variable is not defined yet.
11907
01066
Distance variable is not defined yet.
11908
56343
Distance variable is not defined yet.
11909
17836
Distance variable is not defined yet.
11910
38579
Distance variable is not defined yet.
11911
30236
Distance
25154.028292522657
11912
24851
Distance variable is not defined yet.
11913
58735
Distance variable is not defined yet.
11914
13624
Distance variable is not defined yet.
11915
07716
Distance variable is not defined yet.
11916
63345
Distance variable is not defined yet.
11917
93648
Distance variable is not defined yet.
11918
27928
Distance variable is not defined yet.
11919
66782
Distance variable is not defined yet.
11920
31068
Distance variable is not defined yet.
11921
73040
Distance variable is not defined yet.
11922
20855
Distance
4604.635827020316
11923
62808
Distance variable is not defined yet.
11924
15440
Distance variable is not defined yet.
11925
27816
Distance variable is not defined yet.
11926
62019
Distance
24655.88434972079
11927
67566
Distance variable is not defined yet.
11928
35456
Distance
23918.896237973586
11929
51549
Distance variable is not defined yet.
11930
66094
Distance variable is not defined yet.
11931
36749
Distance variable is not defined yet.
11932
83112
Distance variable is not defined yet.
11933
39069
Distance variable is not defined yet.
11934
08850
Distance variable is not defined yet.
11935
06263
Distance variable is not defined yet.
11936
12037
Distance variable is not defined yet.
11937
56579
Distance variable is not defined yet.
11938
60420
Distance variable is not defined yet.
11939
69331
Distance variable is not defined yet.
11940
43526
Distance variable is not defined yet.
11941
13417
Distance
9082.608254272838
11942
14772
Distance variable is not defined yet.
11943
04743
Distance variable is not defined yet.
11944
48617
Distance variable is not defined yet.
11945
62231
Distance variable is not defined yet.
11946
27891
Distance variable is not defined yet.
11947
50479
Distance variable is not defined yet.
11948
85923
Distance variable is not defined yet.
11949
82604
Distance variable is not defined yet.
11950
22831
Distance variable is not defined yet.
11951
28464
Distance variable is not defined yet.
11952
99555
Distance
25096.58009780197
11953
15144
Distance
24565.578600945493
11954
60408
Distance variable is not defined yet.
11955
46158
Distance variable is not defined yet.
11956
58273
Distance variable is not defined yet.
11957
56211
Distance variable is not defined yet.
11958
59419
Distance variable is not defined yet.
11959
62822
Distance variable is not defined yet.
11960
49073
Distance
25086.538286607996
11961
49321
Distance variable is not defined yet.
11962
17565
Distance variable is not defined yet.
11963
21521
Distance variable is not defined yet.
11964
29015
Distance variable is not defined yet.
11965
61482
Distance variable is not defined yet.
11966
84312
Distance variable is not defined yet.
11967
35961
Distance variable is not defined yet.
11968
71962
Distance variable is not defined yet.
11969
40010
Distance variable is not defined yet.
11970
48045
Distance
25073.420383872926
11971
62675
Distance variable is not defined yet.
11972
65026
Distance variable is not defined yet.
11973
49461
Distance variable is not defined yet.
11974
78886
Distance variable is not defined yet.
11975
54724
Distance
25069.694828638025
11976
90265
Distance
25068.194253193586
11977
56289
Distance
25064.829879313882
11978
33547
Distance
25064.677449867308
11979
55082
Distance
8151.7667254524895
11980
05473
Distance variable is not defined yet.
11981
36477
Distance variable is not defined yet.
11982
56013
Distance variable is not defined yet.
11983
73455
Distance variable is not defined yet.
11984
52309
Distance variable is not defined yet.
11985
56160
Distance variable is not defined yet.
11986
74871
Distance variable is not defined yet.
11987
63961
Distance
22688.08207369147
11988
64076
Distance variable is not defined yet.
11989
65470
Distance variable is not defined yet.
11990
35083
Distance variable is not defined yet.
11991
13783
Distance variable is not defined yet.
11992
56057
Distance variable is not defined yet.
11993
28681
Distance
25052.698769696646
11994
15148
Distance
11503.254886964694
11995
46760
Distance variable is not defined yet.
11996
97109
Distance variable is not defined yet.
11997
46147
Distance variable is not defined yet.
11998
77650
Distance variable is not defined yet.
11999
08089
Distance variable is not defined yet.
12000
96755
Distance
11617.995886072411
12001
51553
Distance variable is not defined yet.
12002
23045
Distance variable is not defined yet.
12003
77080
Distance
16836.130100652128
12004
57030
Distance variable is not defined yet.
12005
74042
Distance variable is not defined yet.
12006
61471
Distance variable is not defined yet.
12007
56153
Distance variable is not defined yet.
12008
52720
Distance variable is not defined yet.
12009
04676
Distance variable is not defined yet.
12010
96051
Distance variable is not defined yet.
12011
21756
Distance variable is not defined yet.
12012
97343
Distance variable is not defined yet.
12013
67235
Distance variable is not defined yet.
12014
12822
Distance variable is not defined yet.
12015
03768
Distance variable is not defined yet.
12016
75847
Distance variable is not defined yet.
12017
99607
Distance
25025.12772415555
12018
05676
Distance variable is not defined yet.
12019
44833
Distance variable is not defined yet.
12020
40402
Distance variable is not defined yet.
12021
61732
Distance variable is not defined yet.
12022
99031
Distance variable is not defined yet.
12023
27967
Distance variable is not defined yet.
12024
15829
Distance variable is not defined yet.
12025
21665
Distance
22855.66413170536
12026
27242
Distance variable is not defined yet.
12027
70744
Distance variable is not defined yet.
12028
62551
Distance variable is not defined yet.
12029
30234
Distance variable is not defined yet.
12030
88337
Distance
19831.92505111005
12031
58017
Distance
23456.229689743588
12032
73005
Distance variable is not defined yet.
12033
42350
Distance
21220.44727649035
12034
85262
Distance variable is not defined yet.
12035
68828
Distance variable is not defined yet.
12036
86409
Distance variable is not defined yet.
12037
29010
Distance variable is not defined yet.
12038
28642
Distance variable is not defined yet.
12039
43316
Distance variable is not defined yet.
12040
78407
Distance
19617.795326294196
12041
04237
Distance variable is not defined yet.
12042
58422
Distance variable is not defined yet.
12043
56367
Distance variable is not defined yet.
12044
50652
Distance variable is not defined yet.
12045
82430
Distance
20034.40853144214
12046
41567
Distance
22970.568990570293
12047
25051
Distance variable is not defined yet.
12048
39885
Distance variable is not defined yet.
12049
15026
Distance variable is not defined yet.
12050
72923
Distance
19274.781442267235
12051
62349
Distance variable is not defined yet.
12052
03817
Distance variable is not defined yet.
12053
58056
Distance variable is not defined yet.
12054
74477
Distance variable is not defined yet.
12055
22579
Distance variable is not defined yet.
12056
76082
Distance variable is not defined yet.
12057
05031
Distance variable is not defined yet.
12058
15781
Distance variable is not defined yet.
12059
62819
Distance variable is not defined yet.
12060
71331
Distance variable is not defined yet.
12061
81081
Distance variable is not defined yet.
12062
62543
Distance variable is not defined yet.
12063
26161
Distance variable is not defined yet.
12064
10598
Distance variable is not defined yet.
12065
01566
Distance variable is not defined yet.
12066
70706
Distance variable is not defined yet.
12067
45880
Distance variable is not defined yet.
12068
76650
Distance variable is not defined yet.
12069
56037
Distance variable is not defined yet.
12070
68047
Distance variable is not defined yet.
12071
29565
Distance variable is not defined yet.
12072
15767
Distance variable is not defined yet.
12073
61568
Distance variable is not defined yet.
12074
05046
Distance variable is not defined yet.
12075
85640
Distance variable is not defined yet.
12076
32407
Distance
10502.854354282414
12077
25504
Distance variable is not defined yet.
12078
25134
Distance variable is not defined yet.
12079
04354
Distance variable is not defined yet.
12080
14475
Distance
14464.164404233765
12081
39661
Distance variable is not defined yet.
12082
28683
Distance variable is not defined yet.
12083
35772
Distance variable is not defined yet.
12084
15632
Distance variable is not defined yet.
12085
48725
Distance variable is not defined yet.
12086
74865
Distance variable is not defined yet.
12087
21053
Distance variable is not defined yet.
12088
97383
Distance variable is not defined yet.
12089
27947
Distance
24924.574011936522
12090
08038
Distance variable is not defined yet.
12091
85646
Distance variable is not defined yet.
12092
01339
Distance variable is not defined yet.
12093
24237
Distance variable is not defined yet.
12094
61774
Distance variable is not defined yet.
12095
38332
Distance variable is not defined yet.
12096
45855
Distance variable is not defined yet.
12097
31647
Distance variable is not defined yet.
12098
95361
Distance variable is not defined yet.
12099
46060
Distance
17476.63742062576
12100
32759
Distance
24905.013544421192
12101
38457
Distance
22915.930642734136
12102
72414
Distance variable is not defined yet.
12103
63755
Distance variable is not defined yet.
12104
27853
Distance variable is not defined yet.
12105
45352
Distance variable is not defined yet.
12106
03887
Distance variable is not defined yet.
12107
72421
Distance variable is not defined yet.
12108
50254
Distance variable is not defined yet.
12109
57223
Distance variable is not defined yet.
12110
32011
Distance variable is not defined yet.
12111
52729
Distance variable is not defined yet.
12112
82609
Distance variable is not defined yet.
12113
96021
Distance variable is not defined yet.
12114
61846
Distance variable is not defined yet.
12115
16312
Distance variable is not defined yet.
12116
84121
Distance variable is not defined yet.
12117
52334
Distance variable is not defined yet.
12118
35016
Distance variable is not defined yet.
12119
94509
Distance
20978.287748945182
12120
51358
Distance
20682.41076000078
12121
27873
Distance variable is not defined yet.
12122
99548
Distance variable is not defined yet.
12123
39167
Distance variable is not defined yet.
12124
55612
Distance variable is not defined yet.
12125
30113
Distance variable is not defined yet.
12126
33897
Distance variable is not defined yet.
12127
08006
Distance
1546.0316115965684
12128
68752
Distance variable is not defined yet.
12129
08050
Distance
14346.364390499195
12130
43334
Distance variable is not defined yet.
12131
21105
Distance variable is not defined yet.
12132
50606
Distance variable is not defined yet.
12133
88210
Distance variable is not defined yet.
12134
04616
Distance variable is not defined yet.
12135
37819
Distance variable is not defined yet.
12136
02825
Distance variable is not defined yet.
12137
61722
Distance variable is not defined yet.
12138
25630
Distance
20972.60295076264
12139
77046
Distance
18084.80106275159
12140
23192
Distance
17095.888964190617
12141
25978
Distance variable is not defined yet.
12142
22427
Distance variable is not defined yet.
12143
22811
Distance variable is not defined yet.
12144
51448
Distance variable is not defined yet.
12145
41749
Distance
24854.009146277065
12146
58059
Distance variable is not defined yet.
12147
49623
Distance variable is not defined yet.
12148
55961
Distance variable is not defined yet.
12149
14869
Distance variable is not defined yet.
12150
25650
Distance
21786.37884890429
12151
15698
Distance variable is not defined yet.
12152
62865
Distance variable is not defined yet.
12153
13364
Distance variable is not defined yet.
12154
16025
Distance variable is not defined yet.
12155
16114
Distance variable is not defined yet.
12156
47955
Distance variable is not defined yet.
12157
47640
Distance variable is not defined yet.
12158
26571
Distance variable is not defined yet.
12159
50155
Distance variable is not defined yet.
12160
52140
Distance variable is not defined yet.
12161
72051
Distance variable is not defined yet.
12162
43358
Distance variable is not defined yet.
12163
14108
Distance variable is not defined yet.
12164
53195
Distance variable is not defined yet.
12165
72524
Distance variable is not defined yet.
12166
04064
Distance variable is not defined yet.
12167
76041
Distance variable is not defined yet.
12168
99350
Distance variable is not defined yet.
12169
63036
Distance variable is not defined yet.
12170
92082
Distance variable is not defined yet.
12171
85629
Distance variable is not defined yet.
12172
83444
Distance variable is not defined yet.
12173
12182
Distance variable is not defined yet.
12174
23009
Distance variable is not defined yet.
12175
37881
Distance variable is not defined yet.
12176
74365
Distance variable is not defined yet.
12177
21838
Distance variable is not defined yet.
12178
95240
Distance variable is not defined yet.
12179
46974
Distance variable is not defined yet.
12180
64498
Distance variable is not defined yet.
12181
84043
Distance variable is not defined yet.
12182
04634
Distance variable is not defined yet.
12183
37880
Distance variable is not defined yet.
12184
41543
Distance
21618.009734203537
12185
29655
Distance variable is not defined yet.
12186
08512
Distance variable is not defined yet.
12187
61341
Distance variable is not defined yet.
12188
70644
Distance variable is not defined yet.
12189
32948
Distance
24804.33313550294
12190
61240
Distance variable is not defined yet.
12191
19507
Distance variable is not defined yet.
12192
72454
Distance variable is not defined yet.
12193
59436
Distance
17198.674600165203
12194
50439
Distance variable is not defined yet.
12195
92673
Distance
24240.959756025437
12196
21655
Distance
14036.409817813794
12197
27021
Distance
22979.671451437618
12198
75457
Distance variable is not defined yet.
12199
25165
Distance variable is not defined yet.
12200
08535
Distance
24794.693206715594
12201
52320
Distance variable is not defined yet.
12202
62006
Distance variable is not defined yet.
12203
49955
Distance variable is not defined yet.
12204
84638
Distance variable is not defined yet.
12205
95762
Distance variable is not defined yet.
12206
78393
Distance variable is not defined yet.
12207
34431
Distance variable is not defined yet.
12208
65276
Distance variable is not defined yet.
12209
52312
Distance variable is not defined yet.
12210
62905
Distance variable is not defined yet.
12211
14748
Distance variable is not defined yet.
12212
29338
Distance variable is not defined yet.
12213
10501
Distance variable is not defined yet.
12214
24105
Distance variable is not defined yet.
12215
84737
Distance variable is not defined yet.
12216
14858
Distance variable is not defined yet.
12217
97125
Distance variable is not defined yet.
12218
93662
Distance variable is not defined yet.
12219
44813
Distance variable is not defined yet.
12220
54413
Distance
24779.692999381434
12221
64061
Distance variable is not defined yet.
12222
54966
Distance variable is not defined yet.
12223
21132
Distance variable is not defined yet.
12224
80497
Distance
24427.563739569552
12225
83011
Distance variable is not defined yet.
12226
65401
Distance variable is not defined yet.
12227
78405
Distance
17141.634054623242
12228
04555
Distance variable is not defined yet.
12229
45381
Distance
24771.1377810814
12230
04734
Distance variable is not defined yet.
12231
74748
Distance variable is not defined yet.
12232
49349
Distance variable is not defined yet.
12233
79087
Distance variable is not defined yet.
12234
28689
Distance variable is not defined yet.
12235
95066
Distance variable is not defined yet.
12236
57026
Distance variable is not defined yet.
12237
15137
Distance
9857.31998453663
12238
24597
Distance variable is not defined yet.
12239
39750
Distance variable is not defined yet.
12240
61046
Distance
24756.203861371006
12241
83001
Distance variable is not defined yet.
12242
13618
Distance variable is not defined yet.
12243
53079
Distance variable is not defined yet.
12244
15132
Distance
6847.7274202079525
12245
47104
Distance variable is not defined yet.
12246
37645
Distance variable is not defined yet.
12247
23947
Distance
24743.430073143158
12248
08824
Distance variable is not defined yet.
12249
21154
Distance variable is not defined yet.
12250
05471
Distance
24738.13324129768
12251
67431
Distance variable is not defined yet.
12252
94925
Distance
23245.718318667838
12253
72024
Distance variable is not defined yet.
12254
29037
Distance variable is not defined yet.
12255
18030
Distance
8242.610376525641
12256
22529
Distance variable is not defined yet.
12257
72086
Distance variable is not defined yet.
12258
77622
Distance variable is not defined yet.
12259
03235
Distance variable is not defined yet.
12260
19730
Distance variable is not defined yet.
12261
01375
Distance variable is not defined yet.
12262
54207

Warning: Cannot load hourly/2021/74780.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/74780.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/74780.csv.gz from https://bulk.meteostat.net/v2/

Distance
22231.575284348255
12836
18354
Distance variable is not defined yet.
12837
66411
Distance variable is not defined yet.
12838
43101
Distance variable is not defined yet.
12839
45304
Distance variable is not defined yet.
12840
45112
Distance variable is not defined yet.
12841
03218
Distance variable is not defined yet.
12842
49713
Distance
23968.28926317714
12843
51446
Distance variable is not defined yet.
12844
48433
Distance variable is not defined yet.
12845
93256
Distance variable is not defined yet.
12846
51559
Distance
23960.71828939117
12847
72165
Distance variable is not defined yet.
12848
56248
Distance variable is not defined yet.
12849
58001
Distance variable is not defined yet.
12850
50471
Distance variable is not defined yet.
12851
24090
Distance variable is not defined yet.
12852
87712
Distance variable is not defined yet.
12853
67330
Distance variable is not defined yet.
12854
23897
Distance variable is not defined yet.
12855
25086
Distance variable is not defined yet.
12856
53530
Distance variable is not defined yet.
12857
62863
Distance variable is not defined yet.
12858
66064
Distance variable is not defined yet.
12859
44864
Distance variable is not defined yet.
12860
60103
Distance
8758.753064627545
12861
47452
Distance variable is not defined yet.
12862
98284
Distance variable is not defined yet.
12863
17967
Distance variable is not defined yet.
12864
57224
Distance variable is not defined yet.
12865
56369
Distance variable is not defined yet.
12866
28779
Distance
4387.96103606838
12867
45162
Distance variable is not defined yet.
12868
53114
Distance variable is not defined yet.
12869
15692
Distance
20722.152579957972
12870
18322
Distance variable is not defined yet.
12871
56593
Distance variable is not defined yet.
12872
88240
Distance variable is not defined yet.
12873
56375
Distance variable is not defined yet.
12874
34691
Distance variable is not defined yet.
12875
35091
Distance variable is not defined yet.
12876
24631
Distance variable is not defined yet.
12877
76459
Distance variable is not defined yet.
12878
55772
Distance
23919.27215018235
12879
76853
Distance variable is not defined yet.
12880
16661
Distance variable is not defined yet.
12881
68466
Distance variable is not defined yet.
12882
15447
Distance variable is not defined yet.
12883
01094
Distance variable is not defined yet.
12884
15313
Distance variable is not defined yet.
12885
62536
Distance variable is not defined yet.
12886
07758
Distance variable is not defined yet.
12887
61054
Distance variable is not defined yet.
12888
48438
Distance variable is not defined yet.
12889
78069
Distance variable is not defined yet.
12890
27517
Distance variable is not defined yet.
12891
45831
Distance variable is not defined yet.
12892
98077
Distance variable is not defined yet.
12893
62051
Distance variable is not defined yet.
12894
36738
Distance variable is not defined yet.
12895
38370
Distance variable is not defined yet.
12896
68937
Distance variable is not defined yet.
12897
48039
Distance variable is not defined yet.
12898
54171
Distance variable is not defined yet.
12899
23146
Distance variable is not defined yet.
12900
24845
Distance variable is not defined yet.
12901
53963
Distance variable is not defined yet.
12902
18252
Distance
18533.852307073314
12903
12074
Distance variable is not defined yet.
12904
27278
Distance variable is not defined yet.
12905
02669
Distance
2221.2372837124512
12906
22508
Distance variable is not defined yet.
12907
56326
Distance variable is not defined yet.
12908
30135
Distance
23886.260529694468
12909
51467
Distance variable is not defined yet.
12910
81137
Distance variable is not defined yet.
12911
64458
Distance variable is not defined yet.
12912
10965
Distance variable is not defined yet.
12913
76556
Distance
23880.950348710463
12914
14731
Distance variable is not defined yet.
12915
27705
Distance variable is not defined yet.
12916
83616
Distance variable is not defined yet.
12917
37018
Distance variable is not defined yet.
12918
15714
Distance variable is not defined yet.
12919
15025
Distance
6237.07327512829
12920
31763
Distance variable is not defined yet.
12921
16911
Distance variable is not defined yet.
12922
10963
Distance variable is not defined yet.
12923
68666
Distance variable is not defined yet.
12924
12832
Distance variable is not defined yet.
12925
97627
Distance variable is not defined yet.
12926
93422
Distance variable is not defined yet.
12927
07480
Distance variable is not defined yet.
12928
06063
Distance variable is not defined yet.
12929
13313
Distance variable is not defined yet.
12930
62282
Distance variable is not defined yet.
12931
35643
Distance variable is not defined yet.
12932
94507
Distance
23063.593199449933
12933
19526
Distance variable is not defined yet.
12934
54819
Distance variable is not defined yet.
12935
62233
Distance
10817.685333522766
12936
68876
Distance variable is not defined yet.
12937
56253
Distance variable is not defined yet.
12938
27818
Distance variable is not defined yet.
12939
21779
Distance variable is not defined yet.
12940
54001
Distance variable is not defined yet.
12941
18603
Distance variable is not defined yet.
12942
98364
Distance variable is not defined yet.
12943
22974
Distance
23834.0784679403
12944
47141
Distance variable is not defined yet.
12945
41062
Distance variable is not defined yet.
12946
71129
Distance variable is not defined yet.
12947
39363
Distance variable is not defined yet.
12948
60479
Distance variable is not defined yet.
12949
39071
Distance variable is not defined yet.
12950
20736
Distance variable is not defined yet.
12951
36574
Distance variable is not defined yet.
12952
14168
Distance variable is not defined yet.
12953
79041
Distance variable is not defined yet.
12954
54763
Distance variable is not defined yet.
12955
31624
Distance
23819.60641992012
12956
74437
Distance variable is not defined yet.
12957
42240
Distance variable is not defined yet.
12958
25132
Distance variable is not defined yet.
12959
04763
Distance variable is not defined yet.
12960
49816
Distance variable is not defined yet.
12961
49884
Distance variable is not defined yet.
12962
68462
Distance variable is not defined yet.
12963
93306
Distance variable is not defined yet.
12964
75424
Distance variable is not defined yet.
12965
47620
Distance variable is not defined yet.
12966
15691
Distance
21023.259816905822
12967
14873
Distance variable is not defined yet.
12968
03464
Distance variable is not defined yet.
12969
91702
Distance
20879.266011459593
12970
01534
Distance variable is not defined yet.
12971
61251
Distance variable is not defined yet.
12972
25035
Distance variable is not defined yet.
12973
15019
Distance variable is not defined yet.
12974
57227
Distance variable is not defined yet.
12975
15466
Distance variable is not defined yet.
12976
53804
Distance variable is not defined yet.
12977
48654
Distance variable is not defined yet.
12978
21015
Distance variable is not defined yet.
12979
73532
Distance variable is not defined yet.
12980
05658
Distance variable is not defined yet.
12981
38949
Distance variable is not defined yet.
12982
42649
Distance variable is not defined yet.
12983
56330
Distance variable is not defined yet.
12984
45389
Distance
23778.458108997005
12985
22713
Distance variable is not defined yet.
12986
62688
Distance variable is not defined yet.
12987
03261
Distance variable is not defined yet.
12988
61914
Distance variable is not defined yet.
12989
62907
Distance variable is not defined yet.
12990
27857
Distance variable is not defined yet.
12991
24554
Distance
4206.001243783591
12992
61956
Distance variable is not defined yet.
12993
36907
Distance variable is not defined yet.
12994
46374
Distance variable is not defined yet.
12995
14767
Distance variable is not defined yet.
12996
66434
Distance variable is not defined yet.
12997
61275
Distance variable is not defined yet.
12998
56209
Distance
23758.488930849482
12999
72644
Distance variable is not defined yet.
13000
88341
Distance variable is not defined yet.
13001
95323
Distance variable is not defined yet.
13002
03741
Distance variable is not defined yet.
13003
53572
Distance variable is not defined yet.
13004
29936
Distance variable is not defined yet.
13005
72342
Distance variable is not defined yet.
13006
27326
Distance variable is not defined yet.
13007
47648
Distance variable is not defined yet.
13008
12429
Distance variable is not defined yet.
13009
38769
Distance variable is not defined yet.
13010
01525
Distance variable is not defined yet.
13011
73553
Distance variable is not defined yet.
13012
20841
Distance
13797.945181431318
13013
68058
Distance
23736.394467557668
13014
65202
Distance variable is not defined yet.
13015
97844
Distance variable is not defined yet.
13016
33920
Distance
23734.06692427864
13017
23829
Distance variable is not defined yet.
13018
28376
Distance variable is not defined yet.
13019
01585
Distance variable is not defined yet.
13020
23021
Distance variable is not defined yet.
13021
31821
Distance variable is not defined yet.
13022
57756
Distance variable is not defined yet.
13023
72455
Distance variable is not defined yet.
13024
46039
Distance
23727.318957521682
13025
64496
Distance variable is not defined yet.
13026
15050
Distance variable is not defined yet.
13027
79083
Distance variable is not defined yet.
13028
91917
Distance variable is not defined yet.
13029
14138
Distance variable is not defined yet.
13030
35475
Distance variable is not defined yet.
13031
84109
Distance variable is not defined yet.
13032
56022
Distance variable is not defined yet.
13033
61756
Distance variable is not defined yet.
13034
66835
Distance variable is not defined yet.
13035
13630
Distance variable is not defined yet.
13036
57433
Distance variable is not defined yet.
13037
30757
Distance variable is not defined yet.
13038
56270
Distance
7366.380339495927
13039
74881
Distance variable is not defined yet.
13040
55375
Distance variable is not defined yet.
13041
51009
Distance variable is not defined yet.
13042
11050
Distance
23697.392472354277
13043
29685
Distance variable is not defined yet.
13044
54232
Distance variable is not defined yet.
13045
14590
Distance variable is not defined yet.
13046
75839
Distance variable is not defined yet.
13047
33953
Distance variable is not defined yet.
13048
17841
Distance variable is not defined yet.
13049
44627
Distance variable is not defined yet.
13050
35143
Distance
21773.543630460023
13051
44056
Distance variable is not defined yet.
13052
53968
Distance
23000.009466225147
13053
53013
Distance variable is not defined yet.
13054
77474
Distance variable is not defined yet.
13055
30147
Distance variable is not defined yet.
13056
72936
Distance
3448.6564796576345
13057
26270
Distance variable is not defined yet.
13058
87525
Distance variable is not defined yet.
13059
47859
Distance variable is not defined yet.
13060
45369
Distance
12339.90906147796
13061
80808
Distance
23664.382296442433
13062
30253
Distance
15190.005908295372
13063
41175
Distance
23030.985840066813
13064
95236
Distance variable is not defined yet.
13065
53558
Distance variable is not defined yet.
13066
72434
Distance variable is not defined yet.
13067
43359
Distance variable is not defined yet.
13068
42328
Distance variable is not defined yet.
13069
56637
Distance variable is not defined yet.
13070
67112
Distance variable is not defined yet.
13071
80621
Distance
23649.727995722493
13072
55335
Distance variable is not defined yet.
13073
28722
Distance variable is not defined yet.
13074
44820
Distance variable is not defined yet.
13075
37026
Distance variable is not defined yet.
13076
68417
Distance variable is not defined yet.
13077
80401
Distance variable is not defined yet.
13078
36030
Distance variable is not defined yet.
13079
27850
Distance
16203.441737491732
13080
35760
Distance
23639.493228522286
13081
31743
Distance variable is not defined yet.
13082
32460
Distance variable is not defined yet.
13083
04693
Distance variable is not defined yet.
13084
18463
Distance variable is not defined yet.
13085
48755
Distance variable is not defined yet.
13086
75779
Distance variable is not defined yet.
13087
06758
Distance variable is not defined yet.
13088
24282
Distance variable is not defined yet.
13089
67650
Distance variable is not defined yet.
13090
52346
Distance variable is not defined yet.
13091
12159
Distance variable is not defined yet.
13092
61548
Distance variable is not defined yet.
13093
64763
Distance variable is not defined yet.
13094
16724
Distance variable is not defined yet.
13095
50230
Distance variable is not defined yet.
13096
29162
Distance variable is not defined yet.
13097
50123
Distance variable is not defined yet.
13098
24966
Distance variable is not defined yet.
13099
81239
Distance variable is not defined yet.
13100
79525
Distance variable is not defined yet.
13101
25239
Distance variable is not defined yet.
13102
70447
Distance variable is not defined yet.
13103
76377
Distance variable is not defined yet.
13104
04488
Distance variable is not defined yet.
13105
19511
Distance variable is not defined yet.
13106
62621
Distance variable is not defined yet.
13107
47666
Distance variable is not defined yet.
13108
14456
Distance variable is not defined yet.
13109
49777
Distance variable is not defined yet.
13110
01588
Distance variable is not defined yet.
13111
30250
Distance
5423.200928349919
13112
64433
Distance variable is not defined yet.
13113
52144
Distance variable is not defined yet.
13114
50864
Distance variable is not defined yet.
13115
30624
Distance
18699.557826765256
13116
15762
Distance variable is not defined yet.
13117
06282
Distance variable is not defined yet.
13118
39183
Distance variable is not defined yet.
13119
60912
Distance variable is not defined yet.
13120
95634
Distance variable is not defined yet.
13121
42123
Distance variable is not defined yet.
13122
45876
Distance variable is not defined yet.
13123
52774
Distance variable is not defined yet.
13124
63013
Distance variable is not defined yet.
13125
72727
Distance variable is not defined yet.
13126
33956
Distance variable is not defined yet.
13127
03290
Distance variable is not defined yet.
13128
03227
Distance variable is not defined yet.
13129
46818
Distance
23564.987035567752
13130
72638
Distance variable is not defined yet.
13131
46984
Distance variable is not defined yet.
13132
71937
Distance variable is not defined yet.
13133
50239
Distance variable is not defined yet.
13134
20603
Distance
20373.87026090105
13135
29030
Distance variable is not defined yet.
13136
58630
Distance variable is not defined yet.
13137
27306
Distance variable is not defined yet.
13138
12769
Distance variable is not defined yet.
13139
05161
Distance variable is not defined yet.
13140
48044
Distance
9211.741892132282
13141
47124
Distance variable is not defined yet.
13142
51027
Distance
21729.053272444147
13143
06855
Distance
23551.490140713384
13144
72025
Distance variable is not defined yet.
13145
72014
Distance variable is not defined yet.
13146
49410
Distance variable is not defined yet.
13147
45651
Distance variable is not defined yet.
13148
45360
Distance variable is not defined yet.
13149
54463
Distance variable is not defined yet.
13150
57238
Distance variable is not defined yet.
13151
47433
Distance variable is not defined yet.
13152
21853
Distance variable is not defined yet.
13153
49106
Distance variable is not defined yet.
13154
75448
Distance variable is not defined yet.
13155
50530
Distance variable is not defined yet.
13156
32461
Distance variable is not defined yet.
13157
59212
Distance variable is not defined yet.
13158
59937
Distance variable is not defined yet.
13159
05075
Distance variable is not defined yet.
13160
54857
Distance variable is not defined yet.
13161
01082
Distance variable is not defined yet.
13162
61274
Distance variable is not defined yet.
13163
04286
Distance variable is not defined yet.
13164
95935
Distance variable is not defined yet.
13165
68442
Distance variable is not defined yet.
13166
50576
Distance variable is not defined yet.
13167
28338
Distance
23515.545444912615
13168
06854
Distance variable is not defined yet.
13169
73030
Distance variable is not defined yet.
13170
15725
Distance variable is not defined yet.
13171
41517
Distance variable is not defined yet.
13172
15049
Distance variable is not defined yet.
13173
28021
Distance variable is not defined yet.
13174
74555
Distance variable is not defined yet.
13175
71268
Distance variable is not defined yet.
13176
70438
Distance variable is not defined yet.
13177
55803
Distance variable is not defined yet.
13178
34289
Distance variable is not defined yet.
13179
30427
Distance
23499.6086452873
13180
61853
Distance variable is not defined yet.
13181
25024
Distance variable is not defined yet.
13182
13033
Distance variable is not defined yet.
13183
73650
Distance variable is not defined yet.
13184
81432
Distance variable is not defined yet.
13185
15636
Distance
22427.56722606179
13186
61311
Distance variable is not defined yet.
13187
29819
Distance variable is not defined yet.
13188
04625
Distance variable is not defined yet.
13189
67336
Distance variable is not defined yet.
13190
94530
Distance
22980.57023281682
13191
79124
Distance variable is not defined yet.
13192
03819
Distance variable is not defined yet.
13193
56098
Distance variable is not defined yet.
13194
15679
Distance variable is not defined yet.
13195
44444
Distance variable is not defined yet.
13196
39739
Distance variable is not defined yet.
13197
56222
Distance variable is not defined yet.
13198
29048
Distance variable is not defined yet.
13199
62987
Distance variable is not defined yet.
13200
50659
Distance variable is not defined yet.
13201
17030
Distance variable is not defined yet.
13202
68816
Distance variable is not defined yet.
13203
59405
Distance
19301.664650675437
13204
15446
Distance variable is not defined yet.
13205
77470
Distance
12596.662957485498
13206
70462
Distance variable is not defined yet.
13207
70777
Distance variable is not defined yet.
13208
12946
Distance variable is not defined yet.
13209
40826
Distance variable is not defined yet.
13210
45142
Distance variable is not defined yet.
13211
78255
Distance
8233.58497973959
13212
73057
Distance variable is not defined yet.
13213
49332
Distance variable is not defined yet.
13214
61418
Distance variable is not defined yet.
13215
56115
Distance variable is not defined yet.
13216
54658
Distance
16023.201582716312
13217
73028
Distance variable is not defined yet.
13218
49233
Distance variable is not defined yet.
13219
35005
Distance variable is not defined yet.
13220
92561
Distance variable is not defined yet.
13221
30213
Distance variable is not defined yet.
13222
53919
Distance variable is not defined yet.
13223
07870
Distance variable is not defined yet.
13224
01037
Distance variable is not defined yet.
13225
36525
Distance
19086.974486941803
13226
56544
Distance variable is not defined yet.
13227
07446
Distance variable is not defined yet.
13228
75490
Distance variable is not defined yet.
13229
30643
Distance
20529.035020046424
13230
25831
Distance variable is not defined yet.
13231
25180
Distance variable is not defined yet.
13232
69210
Distance variable is not defined yet.
13233
50484
Distance variable is not defined yet.
13234
64469
Distance variable is not defined yet.
13235
08328
Distance variable is not defined yet.
13236
61334
Distance variable is not defined yet.
13237
66531
Distance variable is not defined yet.
13238
84032
Distance variable is not defined yet.
13239
08344
Distance variable is not defined yet.
13240
47437
Distance variable is not defined yet.
13241
48043
Distance
3913.0513030035872
13242
35073
Distance variable is not defined yet.
13243
73562
Distance variable is not defined yet.
13244
24059
Distance variable is not defined yet.
13245
06786
Distance variable is not defined yet.
13246
37308
Distance

Warning: Cannot load hourly/2021/72280.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/72280.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/72280.csv.gz from https://bulk.meteostat.net/v2/

Distance
22396.96766266269
14109
62281
Distance
18163.752444007772
14110
97810
Distance variable is not defined yet.
14111
30009
Distance variable is not defined yet.
14112
38061
Distance variable is not defined yet.
14113
55389
Distance variable is not defined yet.
14114
76673
Distance variable is not defined yet.
14115
37730
Distance variable is not defined yet.
14116
15924
Distance
21737.561709223974
14117
77435
Distance variable is not defined yet.
14118
82701
Distance variable is not defined yet.
14119
49452
Distance variable is not defined yet.
14120
32564
Distance
22387.21199696686
14121
14537
Distance
19300.346996188753
14122
56026
Distance variable is not defined yet.
14123
40939
Distance variable is not defined yet.
14124
74431
Distance variable is not defined yet.
14125
61870
Distance variable is not defined yet.
14126
06387
Distance variable is not defined yet.
14127
31551
Distance
22376.399290001777
14128
63939
Distance variable is not defined yet.
14129
23025
Distance variable is not defined yet.
14130
79005
Distance variable is not defined yet.
14131
73089
Distance
22372.205247532584
14132
08826
Distance variable is not defined yet.
14133
74553
Distance variable is not defined yet.
14134
95682
Distance variable is not defined yet.
14135
31642
Distance variable is not defined yet.
14136
74837
Distance variable is not defined yet.
14137
38623
Distance variable is not defined yet.
14138
77951
Distance variable is not defined yet.
14139
62031
Distance variable is not defined yet.
14140
42409
Distance variable is not defined yet.
14141
95982
Distance variable is not defined yet.
14142
28611
Distance variable is not defined yet.
14143
21921
Distance variable is not defined yet.
14144
42088
Distance variable is not defined yet.
14145
60401
Distance variable is not defined yet.
14146
23881
Distance variable is not defined yet.
14147
53816
Distance variable is not defined yet.
14148
43107
Distance variable is not defined yet.
14149
32218
Distance variable is not defined yet.
14150
08901
Distance variable is not defined yet.
14151
31070
Distance variable is not defined yet.
14152
94511
Distance variable is not defined yet.
14153
49426
Distance variable is not defined yet.
14154
73507
Distance variable is not defined yet.
14155
66226
Distance variable is not defined yet.
14156
08823
Distance variable is not defined yet.
14157
46960
Distance variable is not defined yet.
14158
47122
Distance variable is not defined yet.
14159
16651
Distance variable is not defined yet.
14160
49745
Distance variable is not defined yet.
14161
71944
Distance variable is not defined yet.
14162
14726
Distance variable is not defined yet.
14163
72415
Distance variable is not defined yet.
14164
62242
Distance variable is not defined yet.
14165
29741
Distance variable is not defined yet.
14166
50483
Distance variable is not defined yet.
14167
84653
Distance
13207.061139799704
14168
53599
Distance variable is not defined yet.
14169
19564
Distance variable is not defined yet.
14170
60487
Distance variable is not defined yet.
14171
74523
Distance variable is not defined yet.
14172
76487
Distance variable is not defined yet.
14173
16950
Distance variable is not defined yet.
14174
46307
Distance variable is not defined yet.
14175
39574
Distance variable is not defined yet.
14176
30734
Distance
20255.121933741506
14177
32258
Distance
16239.98533441999
14178
95726
Distance variable is not defined yet.
14179
54016
Distance
12926.95698837603
14180
67056
Distance variable is not defined yet.
14181
28462
Distance variable is not defined yet.
14182
92677
Distance
15498.298405692323
14183
48872
Distance variable is not defined yet.
14184
47853
Distance variable is not defined yet.
14185
55705
Distance variable is not defined yet.
14186
40047
Distance variable is not defined yet.
14187
30755
Distance variable is not defined yet.
14188
48616
Distance variable is not defined yet.
14189
76621
Distance variable is not defined yet.
14190
99832
Distance
22329.626806301207
14191
49064
Distance variable is not defined yet.
14192
47865
Distance variable is not defined yet.
14193
01074
Distance variable is not defined yet.
14194
18302
Distance variable is not defined yet.
14195
16729
Distance variable is not defined yet.
14196
41721
Distance variable is not defined yet.
14197
78877

Warning: Cannot load hourly/2021/5K6VK.csv.gz from https://bulk.meteostat.net/v2/

Distance
12630.985791560644
14198
50248
Distance variable is not defined yet.
14199
19971
Distance variable is not defined yet.
14200
49759
Distance variable is not defined yet.
14201
49916
Distance variable is not defined yet.
14202
37188
Distance
22147.58585538779
14203
52653
Distance variable is not defined yet.
14204
12165
Distance variable is not defined yet.
14205
48659
Distance variable is not defined yet.
14206
37711
Distance variable is not defined yet.
14207
05673
Distance variable is not defined yet.
14208
43822
Distance variable is not defined yet.
14209
39170
Distance variable is not defined yet.
14210
68803
Distance variable is not defined yet.
14211
50450
Distance variable is not defined yet.
14212
61238
Distance variable is not defined yet.
14213
44081
Distance variable is not defined yet.
14214
70639
Distance variable is not defined yet.
14215
62468
Distance variable is not defined yet.
14216
73448
Distance variable is not defined yet.
14217
50271
Distance variable is not defined yet.
14218
20616
Distance
22299.719496236183
14219
20106
Distance variable is not defined yet.
14220
40346
Distance variable is not defined yet.
14221
44838
Distance variable is not defined yet.
14222
77043
Distance
21016.17160241632
14223
47882
Distance variable is not defined yet.
14224
50141
Distance variable is not defined yet.
14225
20180
Distance variable is not defined yet.
14226
14757
Distance variable is not defined yet.
14227
50171
Distance variable is not defined yet.
14228
67132
Distance variable is not defined yet.
14229
98921
Distance variable is not defined yet.
14230
65806
Distance variable is not defined yet.
14231
61424
Distance variable is not defined yet.
14232
05841
Distance variable is not defined yet.
14233
36271
Distance variable is not defined yet.
14234
16412
Distance variable is not defined yet.
14235
34771
Distance variable is not defined yet.
14236
64733
Distance variable is not defined yet.
14237
42204
Distance variable is not defined yet.
14238
66951
Distance variable is not defined yet.
14239
05774
Distance variable is not defined yet.
14240
68424
Distance variable is not defined yet.
14241
32767
Distance variable is not defined yet.
14242
63530
Distance variable is not defined yet.
14243
61778
Distance variable is not defined yet.
14244
76050
Distance variable is not defined yet.
14245
68461
Distance variable is not defined yet.
14246
02713
Distance
22280.93822429676
14247
61479
Distance variable is not defined yet.
14248
80235
Distance variable is not defined yet.
14249
30238
Distance
12524.995410290727
14250
73067
Distance variable is not defined yet.
14251
46186
Distance variable is not defined yet.
14252
97496
Distance variable is not defined yet.
14253
95377
Distance
5940.5629379769625
14254
66093
Distance variable is not defined yet.
14255
64444
Distance variable is not defined yet.
14256
59718
Distance variable is not defined yet.
14257
37345
Distance variable is not defined yet.
14258
04097
Distance
5533.177687597964
14259
24065
Distance variable is not defined yet.
14260
62892
Distance
21918.592889040556
14261
83676
Distance variable is not defined yet.
14262
31024
Distance variable is not defined yet.
14263
24868
Distance variable is not defined yet.
14264
29945
Distance variable is not defined yet.
14265
75848
Distance variable is not defined yet.
14266
70810
Distance variable is not defined yet.
14267
48036
Distance
5470.4081544372475
14268
72564
Distance variable is not defined yet.
14269
74640
Distance variable is not defined yet.
14270
05763
Distance variable is not defined yet.
14271
01270
Distance variable is not defined yet.
14272
51016
Distance variable is not defined yet.
14273
65054
Distance variable is not defined yet.
14274
21916
Distance variable is not defined yet.
14275
65320
Distance variable is not defined yet.
14276
23238
Distance variable is not defined yet.
14277
61323
Distance variable is not defined yet.
14278
97486
Distance variable is not defined yet.
14279
62366
Distance variable is not defined yet.
14280
50523
Distance variable is not defined yet.
14281
01951
Distance variable is not defined yet.
14282
78931
Distance variable is not defined yet.
14283
53578
Distance variable is not defined yet.
14284
17032
Distance variable is not defined yet.
14285
75859
Distance variable is not defined yet.
14286
28342
Distance variable is not defined yet.
14287
73017
Distance variable is not defined yet.
14288
63559
Distance variable is not defined yet.
14289
50033
Distance variable is not defined yet.
14290
10505
Distance variable is not defined yet.
14291
17772
Distance variable is not defined yet.
14292
15444
Distance variable is not defined yet.
14293
29493
Distance variable is not defined yet.
14294
54961
Distance variable is not defined yet.
14295
65630
Distance variable is not defined yet.
14296
56339
Distance variable is not defined yet.
14297
19956
Distance variable is not defined yet.
14298
62052
Distance variable is not defined yet.
14299
15461
Distance variable is not defined yet.
14300
31037
Distance
4813.127998268242
14301
40006
Distance variable is not defined yet.
14302
52142
Distance variable is not defined yet.
14303
32462
Distance variable is not defined yet.
14304
14129
Distance variable is not defined yet.
14305
25921
Distance variable is not defined yet.
14306
32336
Distance variable is not defined yet.
14307
01460

Warning: Cannot load hourly/2021/KAYE0.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/KAYE0.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/KAYE0.csv.gz from https://bulk.meteostat.net/v2/

Distance
9743.83570217194
14308
84311
Distance variable is not defined yet.
14309
93510
Distance variable is not defined yet.
14310
72672
Distance variable is not defined yet.
14311
54411
Distance variable is not defined yet.
14312
06334
Distance variable is not defined yet.
14313
92692
Distance
9533.877399042933
14314
19963
Distance variable is not defined yet.
14315
49052
Distance variable is not defined yet.
14316
31302
Distance variable is not defined yet.
14317
74937
Distance variable is not defined yet.
14318
41007
Distance variable is not defined yet.
14319
70353
Distance variable is not defined yet.
14320
08882
Distance variable is not defined yet.
14321
52728
Distance variable is not defined yet.
14322
72223
Distance variable is not defined yet.
14323
67731
Distance variable is not defined yet.
14324
65321
Distance variable is not defined yet.
14325
50514
Distance variable is not defined yet.
14326
78642
Distance variable is not defined yet.
14327
23875
Distance
22194.546643597554
14328
22824
Distance
21461.261827626957
14329
94950
Distance variable is not defined yet.
14330
15848
Distance variable is not defined yet.
14331
02382

Warning: Cannot load hourly/2021/KNZW0.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/KNZW0.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/KNZW0.csv.gz from https://bulk.meteostat.net/v2/

Distance
22192.74376927375
14332
56110
Distance variable is not defined yet.
14333
07730
Distance variable is not defined yet.
14334
97457
Distance variable is not defined yet.
14335
62572
Distance variable is not defined yet.
14336
76446
Distance variable is not defined yet.
14337
65756
Distance variable is not defined yet.
14338
44849
Distance variable is not defined yet.
14339
65023
Distance variable is not defined yet.
14340
13167
Distance variable is not defined yet.
14341
56255
Distance variable is not defined yet.
14342
84092
Distance variable is not defined yet.
14343
27880
Distance variable is not defined yet.
14344
64016
Distance variable is not defined yet.
14345
25431
Distance variable is not defined yet.
14346
95449
Distance variable is not defined yet.
14347
97761
Distance variable is not defined yet.
14348
18210
Distance variable is not defined yet.
14349
21679
Distance
19766.851757044376
14350
26060
Distance
10992.541729491793
14351
28636
Distance variable is not defined yet.
14352
47634
Distance variable is not defined yet.
14353
39773
Distance variable is not defined yet.
14354
75605
Distance variable is not defined yet.
14355
63122
Distance variable is not defined yet.
14356
77471
Distance variable is not defined yet.
14357
64088
Distance variable is not defined yet.
14358
40958
Distance variable is not defined yet.
14359
21659
Distance variable is not defined yet.
14360
50161
Distance variable is not defined yet.
14361
98110
Distance
22153.013332016817
14362
45833
Distance variable is not defined yet.
14363
04011
Distance
21948.517716533723
14364
39755
Distance variable is not defined yet.
14365
16154
Distance variable is not defined yet.
14366
27712
Distance variable is not defined yet.
14367
17067
Distance variable is not defined yet.
14368
14172
Distance variable is not defined yet.
14369
24815
Distance variable is not defined yet.
14370
18214
Distance variable is not defined yet.
14371
13838
Distance variable is not defined yet.
14372
43031
Distance variable is not defined yet.
14373
49710
Distance variable is not defined yet.
14374
38587
Distance variable is not defined yet.
14375
44264
Distance variable is not defined yet.
14376
27829
Distance variable is not defined yet.
14377
97461
Distance variable is not defined yet.
14378
18624
Distance variable is not defined yet.
14379
77970
Distance variable is not defined yet.
14380
54876
Distance variable is not defined yet.
14381
45744
Distance variable is not defined yet.
14382
56443
Distance
22125.92582647136
14383
60107
Distance
7415.391495738078
14384
52536
Distance variable is not defined yet.
14385
13156
Distance variable is not defined yet.
14386
54209
Distance
15269.559161381409
14387
38016
Distance variable is not defined yet.
14388
74948
Distance variable is not defined yet.
14389
24070
Distance variable is not defined yet.
14390
31075
Distance variable is not defined yet.
14391
49050
Distance variable is not defined yet.
14392
65085
Distance variable is not defined yet.
14393
37362
Distance variable is not defined yet.
14394
51536
Distance variable is not defined yet.
14395
33327
Distance
22111.489412525436
14396
45669
Distance variable is not defined yet.
14397
56535
Distance variable is not defined yet.
14398
29470
Distance
22106.51631872293
14399
23899
Distance
22106.047578542653
14400
03608
Distance variable is not defined yet.
14401
75442
Distance variable is not defined yet.
14402
28115
Distance variable is not defined yet.
14403
98274
Distance variable is not defined yet.
14404
08072
Distance variable is not defined yet.
14405
15479
Distance variable is not defined yet.
14406
33841
Distance variable is not defined yet.
14407
38368
Distance variable is not defined yet.
14408
61073
Distance variable is not defined yet.
14409
15938
Distance variable is not defined yet.
14410
29001
Distance variable is not defined yet.
14411
50044
Distance variable is not defined yet.
14412
48741
Distance variable is not defined yet.
14413
83867
Distance variable is not defined yet.
14414
77051
Distance
9663.119472307495
14415
23958
Distance variable is not defined yet.
14416
19709
Distance variable is not defined yet.
14417
80107
Distance variable is not defined yet.
14418
63774
Distance variable is not defined yet.
14419
28117
Distance variable is not defined yet.
14420
83406
Distance variable is not defined yet.
14421
57076
Distance variable is not defined yet.
14422
17872
Distance variable is not defined yet.
14423
32350
Distance variable is not defined yet.
14424
56441
Distance variable is not defined yet.
14425
16943
Distance variable is not defined yet.
14426
23002
Distance
22073.666070889463
14427
03293
Distance variable is not defined yet.
14428
62833
Distance variable is not defined yet.
14429
94922
Distance variable is not defined yet.
14430
94904
Distance variable is not defined yet.
14431
94020
Distance variable is not defined yet.
14432
13492
Distance
5550.688182828501
14433
18336
Distance variable is not defined yet.
14434
75571
Distance variable is not defined yet.
14435
27852
Distance variable is not defined yet.
14436
84526
Distance variable is not defined yet.
14437
26572
Distance variable is not defined yet.
14438
63785
Distance variable is not defined yet.
14439
98560
Distance variable is not defined yet.
14440
97449
Distance variable is not defined yet.
14441
75431
Distance variable is not defined yet.
14442
33860
Distance variable is not defined yet.
14443
01376
Distance variable is not defined yet.
14444
56442
Distance variable is not defined yet.
14445
28725
Distance
7948.176352672182
14446
55910
Distance variable is not defined yet.
14447
35774
Distance variable is not defined yet.
14448
15377
Distance variable is not defined yet.
14449
29691
Distance variable is not defined yet.
14450
52738
Distance variable is not defined yet.
14451
15110
Distance
6361.825331339542
14452
49725
Distance variable is not defined yet.
14453
50577
Distance variable is not defined yet.
14454
25865
Distance variable is not defined yet.
14455
05042
Distance variable is not defined yet.
14456
95369
Distance variable is not defined yet.
14457
61443
Distance variable is not defined yet.
14458
31547
Distance variable is not defined yet.
14459
53118
Distance
22038.833230972443
14460
77047
Distance
11765.43280123551
14461
73061
Distance variable is not defined yet.
14462
72579
Distance variable is not defined yet.
14463
87041
Distance variable is not defined yet.
14464
79045
Distance variable is not defined yet.
14465
22973
Distance variable is not defined yet.
14466
72668
Distance variable is not defined yet.
14467
49128
Distance variable is not defined yet.
14468
42039
Distance variable is not defined yet.
14469
22637
Distance variable is not defined yet.
14470
93280
Distance variable is not defined yet.
14471
79942
Distance variable is not defined yet.
14472
33982
Distance variable is not defined yet.
14473
78122
Distance variable is not defined yet.
14474
74856
Distance variable is not defined yet.
14475
61091
Distance variable is not defined yet.
14476
51350
Distance variable is not defined yet.
14477
73458
Distance variable is not defined yet.
14478
53586
Distance variable is not defined yet.
14479
15477
Distance variable is not defined yet.
14480
60010
Distance
18840.149288604563
14481
38028
Distance variable is not defined yet.
14482
55090
Distance
9998.876618433549
14483
01749
Distance
20275.87839299549
14484
76527
Distance variable is not defined yet.
14485
55716
Distance variable is not defined yet.
14486
52362
Distance variable is not defined yet.
14487
10950
Distance
21814.335077315907
14488
14470
Distance variable is not defined yet.
14489
46940
Distance variable is not defined yet.
14490
94850
Distance
13249.115942699345
14491
74333
Distance variable is not defined yet.
14492
53964
Distance variable is not defined yet.
14493
37682
Distance
13105.903845814417
14494
16669
Distance variable is not defined yet.
14495
51461
Distance variable is not defined yet.
14496
37892
Distance variable is not defined yet.
14497
50130
Distance variable is not defined yet.
14498
38844
Distance variable is not defined yet.
14499
25159
Distance variable is not defined yet.
14500
38749
Distance variable is not defined yet.
14501
24646
Distance variable is not defined yet.
14502
95938
Distance
18617.5747786361
14503
73016
Distance variable is not defined yet.
14504
46920
Distance variable is not defined yet.
14505
55395
Distance variable is not defined yet.
14506
54154
Distance variable is not defined yet.
14507
28572
Distance variable is not defined yet.
14508
26576
Distance variable is not defined yet.
14509
26343
Distance variable is not defined yet.
14510
43524
Distance variable is not defined yet.
14511
07458
Distance variable is not defined yet.
14512
52352
Distance variable is not defined yet.
14513
54619
Distance variable is not defined yet.
14514
14052
Distance variable is not defined yet.
14515
78419
Distance
2203.088056403206
14516
72010
Distance variable is not defined yet.
14517
49451
Distance variable is not defined yet.
14518
61324
Distance variable is not defined yet.
14519
35748
Distance variable is not defined yet.
14520
71466
Distance variable is not defined yet.
14521
74422
Distance variable is not defined yet.
14522
27317
Distance variable is not defined yet.
14523
17344
Distance
17528.596485937695
14524
29161
Distance variable is not defined yet.
14525
43779
Distance variable is not defined yet.
14526
60477
Distance variable is not defined yet.
14527
78012
Distance variable is not defined yet.
14528
63134
Distance variable is not defined yet.
14529
41539
Distance
16927.62601782193
14530
15129
Distance
9356.958964020583
14531
35552
Distance variable is not defined yet.
14532
44428
Distance variable is not defined yet.
14533
34661
Distance variable is not defined yet.
14534
95228
Distance variable is not defined yet.
14535
48635
Distance variable is not defined yet.
14536
24549
Distance variable is not defined yet.
14537
77486
Distance variable is not defined yet.
14538
92399
Distance variable is not defined yet.
14539
39834
Distance variable is not defined yet.
14540
32565
Distance variable is not defined yet.
14541
94129
Distance
13285.996701945809
14542
18040
Distance variable is not defined yet.
14543
01950
Distance variable is not defined yet.
14544
08319
Distance variable is not defined yet.
14545
67632
Distance variable is not defined yet.
14546
76885
Distance variable is not defined yet.
14547
27862
Distance variable is not defined yet.
14548
84308
Distance variable is not defined yet.
14549
99026
Distance variable is not defined yet.
14550
78933
Distance variable is not defined yet.
14551
61008
Distance variable is not defined yet.
14552
32949
Distance
13389.427130026492
14553
66092
Distance variable is not defined yet.
14554
56185
Distance variable is not defined yet.
14555
94571
Distance variable is not defined yet.
14556
13756
Distance variable is not defined yet.
14557
75949
Distance variable is not defined yet.
14558
75707
Distance variable is not defined yet.
14559
71943
Distance variable is not defined yet.
14560
10520
Distance variable is not defined yet.
14561
21718
Distance variable is not defined yet.
14562
48371
Distance variable is not defined yet.
14563
55710
Distance variable is not defined yet.
14564
61910
Distance variable is not defined yet.
14565
18250
Distance
7342.607824937042
14566
48652
Distance variable is not defined yet.
14567
48380
Distance variable is not defined yet.
14568
13753
Distance variable is not defined yet.
14569
15733
Distance variable is not defined yet.
14570
37049
Distance
18249.760350207885
14571
36279
Distance variable is not defined yet.
14572
12737
Distance variable is not defined yet.
14573
48746
Distance variable is not defined yet.
14574
65803
Distance variable is not defined yet.
14575
67053
Distance variable is not defined yet.
14576
52769
Distance variable is not defined yet.
14577
35160
Distance
21893.792275101558
14578
77433
Distance
15910.937506332726
14579
49460
Distance variable is not defined yet.
14580
40856
Distance variable is not defined yet.
14581
81025
Distance variable is not defined yet.
14582
54112
Distance variable is not defined yet.
14583
68050
Distance variable is not defined yet.
14584
35903
Distance variable is not defined yet.
14585
34759
Distance variable is not defined yet.
14586
32514
Distance
6855.900522111368
14587
48456
Distance variable is not defined yet.
14588
36039
Distance variable is not defined yet.
14589
47840
Distance variable is not defined yet.
14590
20751
Distance
21881.382372603322
14591
15145
Distance
10607.406064081528
14592
44837
Distance variable is not defined yet.
14593
36575
Distance variable is not defined yet.
14594
47858
Distance variable is not defined yet.
14595
72555
Distance variable is not defined yet.
14596
74452
Distance variable is not defined yet.
14597
84521
Distance variable is not defined yet.
14598
73950
Distance variable is not defined yet.
14599
42156
Distance variable is not defined yet.
14600
49766
Distance variable is not defined yet.
14601
76872
Distance variable is not defined yet.
14602
22715
Distance variable is not defined yet.
14603
66733
Distance variable is not defined yet.
14604
54436
Distance variable is not defined yet.
14605
56578
Distance variable is not defined yet.
14606
88415
Distance variable is not defined yet.
14607
76444
Distance variable is not defined yet.
14608
50570
Distance variable is not defined yet.
14609
80232
Distance variable is not defined yet.
14610
24520
Distance variable is not defined yet.
14611
35953
Distance variable is not defined yet.
14612
05650
Distance variable is not defined yet.
14613
84721
Distance variable is not defined yet.
14614
54895
Distance variable is not defined yet.
14615
08353
Distance variable is not defined yet.
14616
48154
Distance variable is not defined yet.
14617
07421
Distance variable is not defined yet.
14618
45784
Distance variable is not defined yet.
14619
12770
Distance variable is not defined yet.
14620
62346
Distance variable is not defined yet.
14621
63068
Distance variable is not defined yet.
14622
61239
Distance variable is not defined yet.
14623
27832
Distance
8197.252604401028
14624
38044
Distance variable is not defined yet.
14625
83801
Distance variable is not defined yet.
14626
76452
Distance variable is not defined yet.
14627
25817
Distance variable is not defined yet.
14628
63465
Distance variable is not defined yet.
14629
44402
Distance variable is not defined yet.
14630
23398
Distance variable is not defined yet.
14631
13071
Distance variable is not defined yet.
14632
16350
Distance variable is not defined yet.
14633
64084
Distance variable is not defined yet.
14634
54670
Distance variable is not defined yet.
14635
27006
Distance variable is not defined yet.
14636
55711
Distance variable is not defined yet.
14637
84736
Distance variable is not defined yet.
14638
53820
Distance variable is not defined yet.
14639
76823
Distance variable is not defined yet.
14640
51653
Distance variable is not defined yet.
14641
17519
Distance variable is not defined yet.
14642
91381
Distance
4042.76626291285
14643
16647
Distance variable is not defined yet.
14644
02025
Distance
13422.096483206324
14645
19567
Distance variable is not defined yet.
14646
48353
Distance variable is not defined yet.
14647
22850
Distance
21562.24063428777
14648
14769
Distance variable is not defined yet.
14649
16622
Distance variable is not defined yet.
14650
14450
Distance
21650.39002420931
14651
34667
Distance variable is not defined yet.
14652
53004
Distance variable is not defined yet.
14653
48167
Distance variable is not defined yet.
14654
84071
Distance variable is not defined yet.
14655
56069
Distance
21791.83021255669
14656
03101
Distance
7041.309190578851
14657
27379
Distance variable is not defined yet.
14658
36853
Distance variable is not defined yet.
14659
04030
Distance variable is not defined yet.
14660
53042
Distance variable is not defined yet.
14661
98841
Distance
20516.483045398014
14662
14525
Distance variable is not defined yet.
14663
77029
Distance
14064.730612270214
14664
53933
Distance variable is not defined yet.
14665
65243
Distance variable is not defined yet.
14666
27022
Distance variable is not defined yet.
14667
38220
Distance variable is not defined yet.
14668
16727
Distance variable is not defined yet.
14669
36608
Distance variable is not defined yet.
14670
21676
Distance variable is not defined yet.
14671
79085
Distance variable is not defined yet.
14672
37771
Distance
21773.953146847503
14673
14468
Distance variable is not defined yet.
14674
55936
Distance variable is not defined yet.
14675
54530
Distance variable is not defined yet.
14676
61726
Distance variable is not defined yet.
14677
01053
Distance variable is not defined yet.
14678
15834
Distance variable is not defined yet.
14679
25187
Distance variable is not defined yet.
14680
67564
Distance variable is not defined yet.
14681
61236
Distance variable is not defined yet.
14682
77420
Distance variable is not defined yet.
14683
62336
Distance variable is not defined yet.
14684
49066
Distance
21764.491855694883
14685
81637
Distance variable is not defined yet.
14686
24881
Distance variable is not defined yet.
14687
59213
Distance variable is not defined yet.
14688
23427
Distance variable is not defined yet.
14689
72458
Distance variable is not defined yet.
14690
83202
Distance variable is not defined yet.
14691
47963
Distance variable is not defined yet.
14692
62887
Distance variable is not defined yet.
14693
17886
Distance variable is not defined yet.
14694
38049
Distance variable is not defined yet.
14695
30756
Distance variable is not defined yet.
14696
44215
Distance variable is not defined yet.
14697
05830
Distance
17708.64081290023
14698
25009
Distance variable is not defined yet.
14699
53033
Distance variable is not defined yet.
14700
48834
Distance variable is not defined yet.
14701
93021
Distance variable is not defined yet.
14702
50276
Distance
19959.093595382583
14703
31765
Distance variable is not defined yet.
14704
30814
Distance variable is not defined yet.
14705
13633
Distance
19383.521617764207
14706
49247
Distance variable is not defined yet.
14707
10920
Distance variable is not defined yet.
14708
32640
Distance variable is not defined yet.
14709
91916
Distance variable is not defined yet.
14710
77367
Distance variable is not defined yet.
14711
68733
Distance variable is not defined yet.
14712
14039
Distance variable is not defined yet.
14713
49238
Distance
21729.323103716368
14714
55315
Distance variable is not defined yet.
14715
14101
Distance variable is not defined yet.
14716
15410
Distance variable is not defined yet.
14717
68740
Distance variable is not defined yet.
14718
97385
Distance variable is not defined yet.
14719
55308
Distance variable is not defined yet.
14720
56274
Distance variable is not defined yet.
14721
12024
Distance variable is not defined yet.
14722
55352
Distance variable is not defined yet.
14723
54622
Distance variable is not defined yet.
14724
76481
Distance variable is not defined yet.
14725
41519
Distance
20528.800972763453
14726
77328
Distance
18341.462685403814
14727
01264
Distance variable is not defined yet.
14728
30180
Distance variable is not defined yet.
14729
65248
Distance variable is not defined yet.
14730
49220
Distance variable is not defined yet.
14731
71468
Distance
15718.767293927614
14732
30828
Distance variable is not defined yet.
14733
87942
Distance variable is not defined yet.
14734
59427
Distance variable is not defined yet.
14735
23487
Distance variable is not defined yet.
14736
22641
Distance variable is not defined yet.
14737
48441
Distance variable is not defined yet.
14738
52236
Distance variable is not defined yet.
14739
35453
Distance variable is not defined yet.
14740
67101
Distance variable is not defined yet.
14741
52219
Distance variable is not defined yet.
14742
84062

Warning: Cannot load hourly/2021/KCGX0.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/KCGX0.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/KCGX0.csv.gz from https://bulk.meteostat.net/v2/

Distance
12870.07956442664
15367
21713
Distance variable is not defined yet.
15368
21530
Distance variable is not defined yet.
15369
54408
Distance variable is not defined yet.
15370
66711
Distance variable is not defined yet.
15371
77028
Distance
20815.34534454274
15372
72738
Distance variable is not defined yet.
15373
59002
Distance variable is not defined yet.
15374
35074
Distance variable is not defined yet.
15375
76020
Distance variable is not defined yet.
15376
90272
Distance
10990.32623159942
15377
15034
Distance
2649.78978526708
15378
05847
Distance variable is not defined yet.
15379
32618
Distance variable is not defined yet.
15380
15001
Distance variable is not defined yet.
15381
82942
Distance variable is not defined yet.
15382
37763
Distance variable is not defined yet.
15383
28168
Distance variable is not defined yet.
15384
43021
Distance variable is not defined yet.
15385
05735
Distance variable is not defined yet.
15386
76227
Distance variable is not defined yet.
15387
51051
Distance variable is not defined yet.
15388
55056
Distance variable is not defined yet.
15389
23061
Distance variable is not defined yet.
15390
70129
Distance
20941.859814764663
15391
84007
Distance
18673.221945761303
15392
29544
Distance variable is not defined yet.
15393
17582
Distance variable is not defined yet.
15394
29697
Distance variable is not defined yet.
15395
27252
Distance variable is not defined yet.
15396
26447
Distance variable is not defined yet.
15397
76484
Distance variable is not defined yet.
15398
43336
Distance variable is not defined yet.
15399
68325
Distance variable is not defined yet.
15400
89820
Distance variable is not defined yet.
15401
04350
Distance variable is not defined yet.
15402
85748
Distance variable is not defined yet.
15403
74849
Distance variable is not defined yet.
15404
92336

Warning: Cannot load hourly/2021/8RXA6.csv.gz from https://bulk.meteostat.net/v2/

Distance
14682.363677488951
15405
93517
Distance variable is not defined yet.
15406
76679
Distance variable is not defined yet.
15407
61072
Distance variable is not defined yet.
15408
45353
Distance variable is not defined yet.
15409
11576
Distance variable is not defined yet.
15410
49116
Distance variable is not defined yet.
15411
65251
Distance variable is not defined yet.
15412
60444
Distance variable is not defined yet.
15413
77401
Distance
18849.688427916106
15414
42041
Distance variable is not defined yet.
15415
99021
Distance variable is not defined yet.
15416
27616
Distance variable is not defined yet.
15417
33843
Distance variable is not defined yet.
15418
03279
Distance variable is not defined yet.
15419
99160
Distance variable is not defined yet.
15420
24290
Distance variable is not defined yet.
15421
93060
Distance variable is not defined yet.
15422
78101
Distance variable is not defined yet.
15423
68322
Distance variable is not defined yet.
15424
58067
Distance variable is not defined yet.
15425
38726
Distance variable is not defined yet.
15426
50469
Distance variable is not defined yet.
15427
61753
Distance variable is not defined yet.
15428
15057
Distance variable is not defined yet.
15429
78852
Distance variable is not defined yet.
15430
84763
Distance variable is not defined yet.
15431
61929
Distance variable is not defined yet.
15432
04416
Distance variable is not defined yet.
15433
65648
Distance variable is not defined yet.
15434
54639
Distance variable is not defined yet.
15435
47847
Distance variable is not defined yet.
15436
06782
Distance variable is not defined yet.
15437
45674
Distance variable is not defined yet.
15438
77040
Distance
15293.689939857819
15439
85143
Distance variable is not defined yet.
15440
54550
Distance variable is not defined yet.
15441
77345
Distance variable is not defined yet.
15442
37715
Distance variable is not defined yet.
15443
16034
Distance variable is not defined yet.
15444
40515
Distance variable is not defined yet.
15445
05826
Distance variable is not defined yet.
15446
92532
Distance variable is not defined yet.
15447
59230
Distance variable is not defined yet.
15448
44445
Distance variable is not defined yet.
15449
97481
Distance variable is not defined yet.
15450
63124
Distance variable is not defined yet.
15451
30821
Distance variable is not defined yet.
15452
54130
Distance variable is not defined yet.
15453
64840
Distance variable is not defined yet.
15454
54556
Distance variable is not defined yet.
15455
25843
Distance variable is not defined yet.
15456
35973
Distance variable is not defined yet.
15457
76077
Distance variable is not defined yet.
15458
03291
Distance variable is not defined yet.
15459
55033
Distance variable is not defined yet.
15460
88352
Distance variable is not defined yet.
15461
77432
Distance variable is not defined yet.
15462
62323
Distance variable is not defined yet.
15463
18324
Distance variable is not defined yet.
15464
31783
Distance variable is not defined yet.
15465
48464
Distance variable is not defined yet.
15466
29666
Distance variable is not defined yet.
15467
05653
Distance variable is not defined yet.
15468
27291
Distance variable is not defined yet.
15469
78652
Distance variable is not defined yet.
15470
78016
Distance variable is not defined yet.
15471
56452
Distance variable is not defined yet.
15472
21777
Distance variable is not defined yet.
15473
61278
Distance variable is not defined yet.
15474
64070
Distance variable is not defined yet.
15475
72325
Distance variable is not defined yet.
15476
57243
Distance variable is not defined yet.
15477
78612
Distance variable is not defined yet.
15478
67060
Distance variable is not defined yet.
15479
81154
Distance variable is not defined yet.
15480
55364
Distance variable is not defined yet.
15481
24831
Distance variable is not defined yet.
15482
14827
Distance variable is not defined yet.
15483
77539
Distance variable is not defined yet.
15484
30288
Distance variable is not defined yet.
15485
86436
Distance variable is not defined yet.
15486
94708
Distance
14115.080403905993
15487
15623
Distance variable is not defined yet.
15488
97027
Distance variable is not defined yet.
15489
27861
Distance variable is not defined yet.
15490
29821
Distance variable is not defined yet.
15491
50447
Distance variable is not defined yet.
15492
15235
Distance
14335.68954404075
15493
68328
Distance variable is not defined yet.
15494
25702
Distance variable is not defined yet.
15495
83462
Distance variable is not defined yet.
15496
80226
Distance variable is not defined yet.
15497
62997
Distance variable is not defined yet.
15498
26586
Distance variable is not defined yet.
15499
73027
Distance variable is not defined yet.
15500
31552
Distance variable is not defined yet.
15501
54766
Distance variable is not defined yet.
15502
54861
Distance variable is not defined yet.
15503
77483
Distance variable is not defined yet.
15504
56223
Distance variable is not defined yet.
15505
55349
Distance variable is not defined yet.
15506
17315
Distance
11591.149967966072
15507
43319
Distance variable is not defined yet.
15508
95493
Distance variable is not defined yet.
15509
72847
Distance variable is not defined yet.
15510
50038
Distance variable is not defined yet.
15511
27604
Distance variable is not defined yet.
15512
15960
Distance variable is not defined yet.
15513
15469
Distance variable is not defined yet.
15514
30248
Distance variable is not defined yet.
15515
78391
Distance variable is not defined yet.
15516
78402
Distance
17805.209952998805
15517
32766
Distance variable is not defined yet.
15518
97045
Distance variable is not defined yet.
15519
13849
Distance variable is not defined yet.
15520
59231
Distance variable is not defined yet.
15521
56327
Distance variable is not defined yet.
15522
23850
Distance variable is not defined yet.
15523
57384
Distance variable is not defined yet.
15524
20860
Distance
12049.534969466693
15525
37187
Distance variable is not defined yet.
15526
10913
Distance variable is not defined yet.
15527
38581
Distance variable is not defined yet.
15528
57068
Distance variable is not defined yet.
15529
21136
Distance variable is not defined yet.
15530
74054
Distance
17858.91970122979
15531
70668
Distance variable is not defined yet.
15532
67640
Distance variable is not defined yet.
15533
44695
Distance variable is not defined yet.
15534
54653
Distance variable is not defined yet.
15535
32617
Distance variable is not defined yet.
15536
75451
Distance variable is not defined yet.
15537
48754
Distance variable is not defined yet.
15538
35178
Distance variable is not defined yet.
15539
66938
Distance variable is not defined yet.
15540
22644
Distance variable is not defined yet.
15541
14867
Distance variable is not defined yet.
15542
17018
Distance variable is not defined yet.
15543
13605
Distance variable is not defined yet.
15544
84045
Distance variable is not defined yet.
15545
55374
Distance variable is not defined yet.
15546
07704
Distance variable is not defined yet.
15547
17579
Distance variable is not defined yet.
15548
23915
Distance variable is not defined yet.
15549
14808
Distance
20472.41875988086
15550
68017
Distance variable is not defined yet.
15551
49418
Distance variable is not defined yet.
15552
68941
Distance variable is not defined yet.
15553
26588
Distance variable is not defined yet.
15554
14094
Distance variable is not defined yet.
15555
91361
Distance variable is not defined yet.
15556
25425
Distance variable is not defined yet.
15557
35640
Distance variable is not defined yet.
15558
29058
Distance
20749.333832969067
15559
12781
Distance variable is not defined yet.
15560
77629
Distance variable is not defined yet.
15561
93063
Distance
12777.850107104916
15562
59353
Distance variable is not defined yet.
15563
93535
Distance variable is not defined yet.
15564
51562
Distance variable is not defined yet.
15565
41174
Distance variable is not defined yet.
15566
47948
Distance variable is not defined yet.
15567
27248
Distance variable is not defined yet.
15568
64461
Distance variable is not defined yet.
15569
17083
Distance variable is not defined yet.
15570
61817
Distance variable is not defined yet.
15571
05463
Distance variable is not defined yet.
15572
60660
Distance
14873.765651781623
15573
35019
Distance variable is not defined yet.
15574
48315
Distance
15203.302531515988
15575
47959
Distance variable is not defined yet.
15576
50467
Distance variable is not defined yet.
15577
37774
Distance variable is not defined yet.
15578
98125
Distance variable is not defined yet.
15579
78621
Distance
20728.195910831302
15580
48152
Distance variable is not defined yet.
15581
26731
Distance variable is not defined yet.
15582
39819
Distance variable is not defined yet.
15583
17080
Distance variable is not defined yet.
15584
72412
Distance variable is not defined yet.
15585
41725
Distance variable is not defined yet.
15586
85132
Distance variable is not defined yet.
15587
56360
Distance
19945.54899645449
15588
76064
Distance variable is not defined yet.
15589
44417
Distance variable is not defined yet.
15590
63771
Distance variable is not defined yet.
15591
22627
Distance variable is not defined yet.
15592
45334
Distance variable is not defined yet.
15593
65486
Distance variable is not defined yet.
15594
13104
Distance variable is not defined yet.
15595
23830
Distance variable is not defined yet.
15596
60060
Distance variable is not defined yet.
15597
04352
Distance variable is not defined yet.
15598
78561
Distance variable is not defined yet.
15599
44681
Distance variable is not defined yet.
15600
48811
Distance variable is not defined yet.
15601
65016
Distance variable is not defined yet.
15602
25003
Distance variable is not defined yet.
15603
95736
Distance
13218.110123434493
15604
50423
Distance variable is not defined yet.
15605
03812
Distance variable is not defined yet.
15606
05853
Distance
18877.862340671585
15607
15463
Distance variable is not defined yet.
15608
34679
Distance variable is not defined yet.
15609
33579
Distance
15423.56057136134
15610
78375
Distance
20698.08516349608
15611
29330
Distance variable is not defined yet.
15612
37688
Distance variable is not defined yet.
15613
16410
Distance variable is not defined yet.
15614
31324
Distance variable is not defined yet.
15615
67065
Distance variable is not defined yet.
15616
66734
Distance variable is not defined yet.
15617
56522
Distance variable is not defined yet.
15618
62361
Distance variable is not defined yet.
15619
74047
Distance variable is not defined yet.
15620
62563
Distance variable is not defined yet.
15621
38233
Distance variable is not defined yet.
15622
43717
Distance variable is not defined yet.
15623
53063
Distance variable is not defined yet.
15624
49657
Distance variable is not defined yet.
15625
33332
Distance variable is not defined yet.
15626
15448
Distance variable is not defined yet.
15627
58497
Distance variable is not defined yet.
15628
47037
Distance variable is not defined yet.
15629
56382
Distance
20343.49032415814
15630
58566
Distance variable is not defined yet.
15631
12525
Distance variable is not defined yet.
15632
47136
Distance variable is not defined yet.
15633
54659
Distance variable is not defined yet.
15634
38847
Distance variable is not defined yet.
15635
74641
Distance variable is not defined yet.
15636
65237
Distance variable is not defined yet.
15637
44090
Distance variable is not defined yet.
15638
17581
Distance variable is not defined yet.
15639
23106
Distance variable is not defined yet.
15640
04216
Distance variable is not defined yet.
15641
68042
Distance variable is not defined yet.
15642
61473
Distance variable is not defined yet.
15643
78610
Distance variable is not defined yet.
15644
52576
Distance variable is not defined yet.
15645
03042
Distance variable is not defined yet.
15646
74832
Distance variable is not defined yet.
15647
15783
Distance variable is not defined yet.
15648
73560
Distance variable is not defined yet.
15649
72464
Distance variable is not defined yet.
15650
13859
Distance variable is not defined yet.
15651
15675
Distance variable is not defined yet.
15652
16301
Distance variable is not defined yet.
15653
10983
Distance variable is not defined yet.
15654
33544
Distance variable is not defined yet.
15655
24325
Distance variable is not defined yet.
15656
47581
Distance variable is not defined yet.
15657
49103
Distance variable is not defined yet.
15658
07656
Distance variable is not defined yet.
15659
61063
Distance variable is not defined yet.
15660
60613
Distance
20650.507899977012
15661
36043
Distance variable is not defined yet.
15662
47227
Distance variable is not defined yet.
15663
52172
Distance variable is not defined yet.
15664
77054
Distance
12776.508550979215
15665
74867
Distance variable is not defined yet.
15666
64431
Distance variable is not defined yet.
15667
14784
Distance variable is not defined yet.
15668
75642
Distance variable is not defined yet.
15669
03037
Distance variable is not defined yet.
15670
31635
Distance variable is not defined yet.
15671
47126
Distance variable is not defined yet.
15672
62541
Distance variable is not defined yet.
15673
27837
Distance
15643.446121392175
15674
61031
Distance variable is not defined yet.
15675
74842
Distance variable is not defined yet.
15676
14511
Distance variable is not defined yet.
15677
54564
Distance variable is not defined yet.
15678
49645
Distance variable is not defined yet.
15679
42056
Distance variable is not defined yet.
15680
44874
Distance variable is not defined yet.
15681
13323
Distance
12042.7692171511
15682
50605
Distance variable is not defined yet.
15683
93563
Distance variable is not defined yet.
15684
29643
Distance variable is not defined yet.
15685
98845
Distance variable is not defined yet.
15686
62691
Distance variable is not defined yet.
15687
08536
Distance variable is not defined yet.
15688
78574
Distance variable is not defined yet.
15689
23056
Distance variable is not defined yet.
15690
24816
Distance variable is not defined yet.
15691
12821
Distance variable is not defined yet.
15692
60626
Distance
16841.47837866872
15693
62862
Distance variable is not defined yet.
15694
50120
Distance variable is not defined yet.
15695
46733
Distance variable is not defined yet.
15696
92282
Distance variable is not defined yet.
15697
38366
Distance variable is not defined yet.
15698
35971
Distance variable is not defined yet.
15699
73540
Distance variable is not defined yet.
15700
93440
Distance variable is not defined yet.
15701
50034
Distance variable is not defined yet.
15702
56651
Distance variable is not defined yet.
15703
76126
Distance
20602.29395573798
15704
74021
Distance variable is not defined yet.
15705
13120
Distance variable is not defined yet.
15706
61335
Distance variable is not defined yet.
15707
94707
Distance
13208.277279647169
15708
54245
Distance variable is not defined yet.
15709
42327
Distance variable is not defined yet.
15710
22902
Distance variable is not defined yet.
15711
45652
Distance variable is not defined yet.
15712
68730
Distance variable is not defined yet.
15713
31532
Distance variable is not defined yet.
15714
71292
Distance variable is not defined yet.
15715
50682
Distance variable is not defined yet.
15716
13621
Distance variable is not defined yet.
15717
28086
Distance variable is not defined yet.
15718
53023
Distance variable is not defined yet.
15719
56633
Distance variable is not defined yet.
15720
14717
Distance variable is not defined yet.
15721
12957
Distance variable is not defined yet.
15722
72012
Distance variable is not defined yet.
15723
31806
Distance variable is not defined yet.
15724
50859
Distance variable is not defined yet.
15725
50165
Distance variable is not defined yet.
15726
73527
Distance variable is not defined yet.
15727
27013
Distance
20576.860135535804
15728
76245
Distance variable is not defined yet.
15729
72426
Distance variable is not defined yet.
15730
41653
Distance
14987.088714308715
15731
04005
Distance variable is not defined yet.
15732
73086
Distance variable is not defined yet.
15733
53049
Distance variable is not defined yet.
15734
05836
Distance variable is not defined yet.
15735
81403
Distance variable is not defined yet.
15736
13752
Distance variable is not defined yet.
15737
50635
Distance variable is not defined yet.
15738
71720
Distance variable is not defined yet.
15739
15626
Distance variable is not defined yet.
15740
70442
Distance variable is not defined yet.
15741
84718
Distance variable is not defined yet.
15742
51035
Distance variable is not defined yet.
15743
48038
Distance
8698.868587976594
15744
30176
Distance variable is not defined yet.
15745
27587
Distance variable is not defined yet.
15746
06231
Distance variable is not defined yet.
15747
67215
Distance variable is not defined yet.
15748
21830
Distance variable is not defined yet.
15749
80540
Distance variable is not defined yet.
15750
20777
Distance
17043.935227667567
15751
29581
Distance variable is not defined yet.
15752
46573
Distance variable is not defined yet.
15753
15321
Distance variable is not defined yet.
15754
46743
Distance variable is not defined yet.
15755
56381
Distance variable is not defined yet.
15756
28763
Distance variable is not defined yet.
15757
10958
Distance variable is not defined yet.
15758
38241
Distance variable is not defined yet.
15759
84310
Distance variable is not defined yet.
15760
08528
Distance variable is not defined yet.
15761
56553
Distance variable is not defined yet.
15762
15084
Distance variable is not defined yet.
15763
56587
Distance variable is not defined yet.
15764
01506
Distance variable is not defined yet.
15765
48239
Distance variable is not defined yet.
15766
76890
Distance variable is not defined yet.
15767
61752
Distance variable is not defined yet.
15768
62344
Distance variable is not defined yet.
15769
38582
Distance variable is not defined yet.
15770
42451
Distance variable is not defined yet.
15771
68973
Distance variable is not defined yet.
15772
24149
Distance variable is not defined yet.
15773
48893
Distance variable is not defined yet.
15774
03276
Distance variable is not defined yet.
15775
10536
Distance variable is not defined yet.
15776
44139
Distance variable is not defined yet.
15777
58420
Distance variable is not defined yet.
15778
71280
Distance variable is not defined yet.
15779
14521
Distance variable is not defined yet.
15780
53059
Distance
20515.883372062646
15781
30747
Distance variable is not defined yet.
15782
04076
Distance variable is not defined yet.
15783
15677
Distance variable is not defined yet.
15784
64490
Distance variable is not defined yet.
15785
75034
Distance
20509.49972125848
15786
49450
Distance variable is not defined yet.
15787
55973
Distance variable is not defined yet.
15788
57017
Distance variable is not defined yet.
15789
87532
Distance variable is not defined yet.
15790
50601
Distance variable is not defined yet.
15791
62421
Distance variable is not defined yet.
15792
12724
Distance variable is not defined yet.
15793
16113
Distance variable is not defined yet.
15794
92320
Distance variable is not defined yet.
15795
28682
Distance variable is not defined yet.
15796
37015
Distance variable is not defined yet.
15797
80642
Distance variable is not defined yet.
15798
31629
Distance variable is not defined yet.
15799
32951
Distance
16374.641829538034
15800
48442
Distance variable is not defined yet.
15801
40150
Distance variable is not defined yet.
15802
76429
Distance variable is not defined yet.
15803
27017
Distance variable is not defined yet.
15804
74463
Distance variable is not defined yet.
15805
23314
Distance
20483.9196550471
15806
82833
Distance variable is not defined yet.
15807
04015
Distance variable is not defined yet.
15808
13027
Distance variable is not defined yet.
15809
46941
Distance variable is not defined yet.
15810
52625
Distance
20475.15512630617
15811
59926

Warning: Cannot load hourly/2021/CDCYH.csv.gz from https://bulk.meteostat.net/v2/

Distance
19765.691052463237
16429
83847
Distance variable is not defined yet.
16430
87122
Distance
6501.661009218732
16431
32140
Distance variable is not defined yet.
16432
98933
Distance variable is not defined yet.
16433
67738
Distance variable is not defined yet.
16434
52078
Distance variable is not defined yet.
16435
58531
Distance variable is not defined yet.
16436
27851
Distance variable is not defined yet.
16437
54562
Distance variable is not defined yet.
16438
46574
Distance variable is not defined yet.
16439
24534
Distance variable is not defined yet.
16440
97633
Distance variable is not defined yet.
16441
31328
Distance variable is not defined yet.
16442
83431
Distance variable is not defined yet.
16443
62478
Distance variable is not defined yet.
16444
77078
Distance variable is not defined yet.
16445
49252
Distance variable is not defined yet.
16446
36344
Distance variable is not defined yet.
16447
38063
Distance variable is not defined yet.
16448
21865
Distance variable is not defined yet.
16449
50111
Distance variable is not defined yet.
16450
45788
Distance variable is not defined yet.
16451
24360
Distance variable is not defined yet.
16452
24716
Distance variable is not defined yet.
16453
13755
Distance variable is not defined yet.
16454
16148
Distance variable is not defined yet.
16455
02048
Distance variable is not defined yet.
16456
72081
Distance variable is not defined yet.
16457
07880
Distance variable is not defined yet.
16458
05036
Distance variable is not defined yet.
16459
53074
Distance variable is not defined yet.
16460
66755
Distance variable is not defined yet.
16461
83424
Distance variable is not defined yet.
16462
46742
Distance variable is not defined yet.
16463
63121
Distance variable is not defined yet.
16464
12788
Distance variable is not defined yet.
16465
98606
Distance variable is not defined yet.
16466
13682
Distance variable is not defined yet.
16467
96062
Distance variable is not defined yet.
16468
47147
Distance variable is not defined yet.
16469
33194
Distance
19723.832216299954
16470
72416
Distance variable is not defined yet.
16471
18218
Distance
13060.06762288949
16472
95376
Distance
5418.421163541873
16473
56688
Distance variable is not defined yet.
16474
28457
Distance variable is not defined yet.
16475
74944
Distance variable is not defined yet.
16476
67209
Distance variable is not defined yet.
16477
14824
Distance variable is not defined yet.
16478
33573
Distance
4785.295584557694
16479
82240
Distance variable is not defined yet.
16480
30573
Distance variable is not defined yet.
16481
13341
Distance
12713.72131045098
16482
01701
Distance variable is not defined yet.
16483
95327
Distance variable is not defined yet.
16484
01008
Distance variable is not defined yet.
16485
62846
Distance variable is not defined yet.
16486
62820
Distance variable is not defined yet.
16487
96725
Distance variable is not defined yet.
16488
04086
Distance variable is not defined yet.
16489
08735
Distance variable is not defined yet.
16490
04554
Distance variable is not defined yet.
16491
61871
Distance variable is not defined yet.
16492
45872
Distance variable is not defined yet.
16493
04259
Distance variable is not defined yet.
16494
37101
Distance variable is not defined yet.
16495
38075
Distance variable is not defined yet.
16496
58281
Distance variable is not defined yet.
16497
24878
Distance variable is not defined yet.
16498
49677
Distance variable is not defined yet.
16499
12764
Distance variable is not defined yet.
16500
24277
Distance variable is not defined yet.
16501
99644
Distance variable is not defined yet.
16502
49649
Distance variable is not defined yet.
16503
03263
Distance variable is not defined yet.
16504
37051
Distance variable is not defined yet.
16505
45810
Distance variable is not defined yet.
16506
49667
Distance variable is not defined yet.
16507
92407
Distance variable is not defined yet.
16508
98072
Distance variable is not defined yet.
16509
97857
Distance variable is not defined yet.
16510
94104
Distance
7556.666007713671
16511
25928
Distance variable is not defined yet.
16512
15710
Distance variable is not defined yet.
16513
23917
Distance
19677.91747835814
16514
23840
Distance variable is not defined yet.
16515
43070
Distance variable is not defined yet.
16516
14489
Distance variable is not defined yet.
16517
86335
Distance variable is not defined yet.
16518
51237
Distance variable is not defined yet.
16519
36105
Distance variable is not defined yet.
16520
80128
Distance variable is not defined yet.
16521
21133
Distance variable is not defined yet.
16522
50851
Distance variable is not defined yet.
16523
93505
Distance variable is not defined yet.
16524
04238
Distance variable is not defined yet.
16525
46050
Distance variable is not defined yet.
16526
60421
Distance
11659.425173871086
16527
54614
Distance variable is not defined yet.
16528
97739
Distance variable is not defined yet.
16529
36353
Distance
14148.64646056505
16530
61749
Distance variable is not defined yet.
16531
15716
Distance variable is not defined yet.
16532
77081
Distance
8325.70694922653
16533
58278
Distance variable is not defined yet.
16534
43739
Distance variable is not defined yet.
16535
15711
Distance variable is not defined yet.
16536
62537
Distance variable is not defined yet.
16537
63136
Distance variable is not defined yet.
16538
58765
Distance variable is not defined yet.
16539
41168
Distance variable is not defined yet.
16540
54227
Distance variable is not defined yet.
16541
13660
Distance variable is not defined yet.
16542
37604
Distance variable is not defined yet.
16543
02882
Distance
19644.08729462595
16544
71024
Distance variable is not defined yet.
16545
44003
Distance variable is not defined yet.
16546
64761
Distance variable is not defined yet.
16547
12766
Distance variable is not defined yet.
16548
17072
Distance variable is not defined yet.
16549
47562
Distance variable is not defined yet.
16550
53057
Distance variable is not defined yet.
16551
95452
Distance variable is not defined yet.
16552
34637
Distance variable is not defined yet.
16553
77095
Distance
10180.539981686483
16554
45156
Distance variable is not defined yet.
16555
64077
Distance variable is not defined yet.
16556
65247
Distance variable is not defined yet.
16557
65729
Distance variable is not defined yet.
16558
97446
Distance variable is not defined yet.
16559
96145
Distance variable is not defined yet.
16560
44333
Distance variable is not defined yet.
16561
24347
Distance variable is not defined yet.
16562
08510
Distance variable is not defined yet.
16563
56288
Distance variable is not defined yet.
16564
37721
Distance variable is not defined yet.
16565
94938
Distance variable is not defined yet.
16566
82716
Distance variable is not defined yet.
16567
52133
Distance variable is not defined yet.
16568
42130
Distance variable is not defined yet.
16569
85935
Distance variable is not defined yet.
16570
12089
Distance
5903.4205839177785
16571
36859
Distance variable is not defined yet.
16572
46368
Distance
19605.001115995525
16573
50519
Distance variable is not defined yet.
16574
80125
Distance variable is not defined yet.
16575
22736
Distance variable is not defined yet.
16576
96055
Distance variable is not defined yet.
16577
59715
Distance variable is not defined yet.
16578
73570
Distance variable is not defined yet.
16579
03845
Distance variable is not defined yet.
16580
92274
Distance variable is not defined yet.
16581
07465
Distance variable is not defined yet.
16582
55779
Distance variable is not defined yet.
16583
11024
Distance
19595.44789699506
16584
24601
Distance variable is not defined yet.
16585
37614
Distance
19368.117514405378
16586
21829
Distance variable is not defined yet.
16587
29909
Distance
19590.76345832277
16588
27544
Distance variable is not defined yet.
16589
62319
Distance variable is not defined yet.
16590
37725
Distance variable is not defined yet.
16591
50627
Distance variable is not defined yet.
16592
16153
Distance variable is not defined yet.
16593
68371
Distance variable is not defined yet.
16594
92322
Distance variable is not defined yet.
16595
74644
Distance variable is not defined yet.
16596
74726
Distance variable is not defined yet.
16597
13803
Distance variable is not defined yet.
16598
62671
Distance variable is not defined yet.
16599
21821
Distance variable is not defined yet.
16600
54660
Distance variable is not defined yet.
16601
71941
Distance variable is not defined yet.
16602
56291
Distance variable is not defined yet.
16603
61917
Distance variable is not defined yet.
16604
15443
Distance variable is not defined yet.
16605
11958
Distance variable is not defined yet.
16606
62910
Distance variable is not defined yet.
16607
33867
Distance variable is not defined yet.
16608
53150
Distance variable is not defined yet.
16609
62330
Distance variable is not defined yet.
16610
15628
Distance variable is not defined yet.
16611
35173
Distance variable is not defined yet.
16612
28460
Distance variable is not defined yet.
16613
97267
Distance
19558.023932124022
16614
92341
Distance variable is not defined yet.
16615
79527
Distance variable is not defined yet.
16616
79366
Distance variable is not defined yet.
16617
53937
Distance variable is not defined yet.
16618
46958
Distance variable is not defined yet.
16619
42366
Distance variable is not defined yet.
16620
02038
Distance variable is not defined yet.
16621
42369
Distance variable is not defined yet.
16622
62890
Distance variable is not defined yet.
16623
43143
Distance variable is not defined yet.
16624
44507
Distance variable is not defined yet.
16625
47863
Distance variable is not defined yet.
16626
61282
Distance variable is not defined yet.
16627
55909
Distance variable is not defined yet.
16628
08854
Distance variable is not defined yet.
16629
70715
Distance variable is not defined yet.
16630
54173
Distance variable is not defined yet.
16631
40444
Distance variable is not defined yet.
16632
61928
Distance variable is not defined yet.
16633
17016
Distance variable is not defined yet.
16634
40110
Distance variable is not defined yet.
16635
37184
Distance variable is not defined yet.
16636
41647
Distance
18742.684896637624
16637
06234
Distance variable is not defined yet.
16638
60452
Distance variable is not defined yet.
16639
01354
Distance variable is not defined yet.
16640
77880
Distance variable is not defined yet.
16641
79562
Distance variable is not defined yet.
16642
65053
Distance variable is not defined yet.
16643
68723
Distance variable is not defined yet.
16644
18371
Distance variable is not defined yet.
16645
77518
Distance variable is not defined yet.
16646
01863
Distance
18634.888833523073
16647
05764
Distance variable is not defined yet.
16648
45769
Distance variable is not defined yet.
16649
55792
Distance variable is not defined yet.
16650
78142
Distance variable is not defined yet.
16651
56467
Distance variable is not defined yet.
16652
38134
Distance variable is not defined yet.
16653
02631
Distance
12333.743166920594
16654
58481
Distance variable is not defined yet.
16655
04353
Distance variable is not defined yet.
16656
38006
Distance variable is not defined yet.
16657
45337
Distance variable is not defined yet.
16658
29105
Distance variable is not defined yet.
16659
48130
Distance variable is not defined yet.
16660
47041
Distance variable is not defined yet.
16661
50263
Distance variable is not defined yet.
16662
91360
Distance variable is not defined yet.
16663
38229
Distance variable is not defined yet.
16664
04021
Distance
11463.674784295936
16665
75051

Warning: Cannot load hourly/2021/KNBE0.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/KNBE0.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/KNBE0.csv.gz from https://bulk.meteostat.net/v2/

Distance
5864.680040227287
16666
62666
Distance variable is not defined yet.
16667
78736
Distance variable is not defined yet.
16668
01054
Distance variable is not defined yet.
16669
61552
Distance variable is not defined yet.
16670
34983
Distance variable is not defined yet.
16671
48861
Distance variable is not defined yet.
16672
03102
Distance
9822.96710761183
16673
14526
Distance variable is not defined yet.
16674
22903
Distance variable is not defined yet.
16675
83615
Distance variable is not defined yet.
16676
25414
Distance variable is not defined yet.
16677
26378
Distance variable is not defined yet.
16678
47336
Distance variable is not defined yet.
16679
73764
Distance variable is not defined yet.
16680
62255
Distance variable is not defined yet.
16681
56166
Distance variable is not defined yet.
16682
62548
Distance variable is not defined yet.
16683
04280
Distance variable is not defined yet.
16684
65754
Distance variable is not defined yet.
16685
71842
Distance variable is not defined yet.
16686
01569
Distance variable is not defined yet.
16687
67212
Distance variable is not defined yet.
16688
16635
Distance variable is not defined yet.
16689
72935
Distance variable is not defined yet.
16690
28463
Distance variable is not defined yet.
16691
19562
Distance variable is not defined yet.
16692
28031
Distance variable is not defined yet.
16693
56137
Distance variable is not defined yet.
16694
98177
Distance variable is not defined yet.
16695
95409
Distance variable is not defined yet.
16696
47163
Distance variable is not defined yet.
16697
80123
Distance variable is not defined yet.
16698
15324
Distance variable is not defined yet.
16699
95689
Distance variable is not defined yet.
16700
60202
Distance variable is not defined yet.
16701
16110
Distance variable is not defined yet.
16702
63841
Distance variable is not defined yet.
16703
15957
Distance variable is not defined yet.
16704
36572
Distance variable is not defined yet.
16705
97826
Distance variable is not defined yet.
16706
63126
Distance variable is not defined yet.
16707
99603
Distance variable is not defined yet.
16708
38483
Distance variable is not defined yet.
16709
10953
Distance
10725.01223984123
16710
49801
Distance variable is not defined yet.
16711
25904
Distance variable is not defined yet.
16712
54623
Distance
17213.575097687833
16713
25419
Distance variable is not defined yet.
16714
34287
Distance variable is not defined yet.
16715
14061
Distance variable is not defined yet.
16716
62854
Distance variable is not defined yet.
16717
15353
Distance variable is not defined yet.
16718
48418
Distance variable is not defined yet.
16719
07677
Distance variable is not defined yet.
16720
08829
Distance variable is not defined yet.
16721
32531
Distance variable is not defined yet.
16722
93247
Distance variable is not defined yet.
16723
03466
Distance variable is not defined yet.
16724
28428
Distance variable is not defined yet.
16725
17053
Distance variable is not defined yet.
16726
18330
Distance variable is not defined yet.
16727
06424
Distance variable is not defined yet.
16728
19506
Distance variable is not defined yet.
16729
84783
Distance variable is not defined yet.
16730
57257
Distance variable is not defined yet.
16731
77591
Distance variable is not defined yet.
16732
27370
Distance variable is not defined yet.
16733
13460
Distance
14578.073177459219
16734
99148
Distance variable is not defined yet.
16735
21632
Distance variable is not defined yet.
16736
49253
Distance variable is not defined yet.
16737
06029
Distance variable is not defined yet.
16738
45817
Distance variable is not defined yet.
16739
16875
Distance variable is not defined yet.
16740
53075
Distance variable is not defined yet.
16741
61769
Distance variable is not defined yet.
16742
30621
Distance variable is not defined yet.
16743
39567
Distance variable is not defined yet.
16744
28902
Distance variable is not defined yet.
16745
38236
Distance variable is not defined yet.
16746
61564
Distance variable is not defined yet.
16747
23874
Distance variable is not defined yet.
16748
18232
Distance
10699.597688184105
16749
27504
Distance variable is not defined yet.
16750
93953
Distance
8531.540876065175
16751
07881
Distance variable is not defined yet.
16752
74630
Distance variable is not defined yet.
16753
56169
Distance variable is not defined yet.
16754
29702
Distance variable is not defined yet.
16755
66717
Distance variable is not defined yet.
16756
62612
Distance variable is not defined yet.
16757
98383
Distance variable is not defined yet.
16758
45773
Distance variable is not defined yet.
16759
51447
Distance variable is not defined yet.
16760
48460
Distance variable is not defined yet.
16761
16650
Distance variable is not defined yet.
16762
56091
Distance variable is not defined yet.
16763
04543
Distance variable is not defined yet.
16764
04087
Distance variable is not defined yet.
16765
36277
Distance variable is not defined yet.
16766
66866
Distance variable is not defined yet.
16767
83805
Distance variable is not defined yet.
16768
41772
Distance variable is not defined yet.
16769
20693
Distance variable is not defined yet.
16770
43837
Distance variable is not defined yet.
16771
43446
Distance variable is not defined yet.
16772
67342
Distance variable is not defined yet.
16773
56174
Distance variable is not defined yet.
16774
05839
Distance variable is not defined yet.
16775
17365
Distance
16010.55781044996
16776
62379
Distance variable is not defined yet.
16777
15104
Distance
7347.489205340284
16778
24138
Distance variable is not defined yet.
16779
12771
Distance variable is not defined yet.
16780
97537
Distance variable is not defined yet.
16781
94105
Distance
6819.658110903842
16782
55923
Distance variable is not defined yet.
16783
34945
Distance variable is not defined yet.
16784
48150
Distance variable is not defined yet.
16785
94501
Distance
3792.0276957838664
16786
75756
Distance variable is not defined yet.
16787
75708
Distance variable is not defined yet.
16788
76009
Distance variable is not defined yet.
16789
28071
Distance variable is not defined yet.
16790
02351
Distance
17026.76507024794
16791
65769
Distance
10054.636168432013
16792
38066
Distance variable is not defined yet.
16793
93610
Distance variable is not defined yet.
16794
25320
Distance variable is not defined yet.
16795
53170
Distance variable is not defined yet.
16796
28455
Distance variable is not defined yet.
16797
57061
Distance variable is not defined yet.
16798
98074
Distance variable is not defined yet.
16799
61089
Distance variable is not defined yet.
16800
40037
Distance
15103.587075072342
16801
75853
Distance variable is not defined yet.
16802
30740
Distance variable is not defined yet.
16803
27405
Distance variable is not defined yet.
16804
24076
Distance variable is not defined yet.
16805
45249
Distance
19358.67717476108
16806
51630
Distance variable is not defined yet.
16807
66076
Distance variable is not defined yet.
16808
22504
Distance variable is not defined yet.
16809
47012
Distance
19353.76121030197
16810
29828
Distance variable is not defined yet.
16811
40334
Distance variable is not defined yet.
16812
14893
Distance variable is not defined yet.
16813
12188
Distance variable is not defined yet.
16814
44230
Distance variable is not defined yet.
16815
52047
Distance variable is not defined yet.
16816
38455
Distance variable is not defined yet.
16817
95209
Distance variable is not defined yet.
16818
66757
Distance variable is not defined yet.
16819
15122
Distance
1487.0593703624793
16820
56052
Distance variable is not defined yet.
16821
15672
Distance variable is not defined yet.
16822
93606
Distance variable is not defined yet.
16823
83442
Distance variable is not defined yet.
16824
68331
Distance variable is not defined yet.
16825
45340
Distance variable is not defined yet.
16826
74468
Distance variable is not defined yet.
16827
15925
Distance variable is not defined yet.
16828
46550
Distance variable is not defined yet.
16829
12775
Distance variable is not defined yet.
16830
60192
Distance
11528.632258933007
16831
33856
Distance variable is not defined yet.
16832
78739
Distance variable is not defined yet.
16833
21661
Distance variable is not defined yet.
16834
54841
Distance variable is not defined yet.
16835
16440
Distance variable is not defined yet.
16836
27856
Distance variable is not defined yet.
16837
28133
Distance variable is not defined yet.
16838
14013
Distance variable is not defined yet.
16839
76565
Distance variable is not defined yet.
16840
63855
Distance variable is not defined yet.
16841
17318
Distance
17392.74848839623
16842
55766
Distance variable is not defined yet.
16843
18083
Distance variable is not defined yet.
16844
54849
Distance variable is not defined yet.
16845
18085
Distance variable is not defined yet.
16846
29644
Distance
19308.01371653466
16847
83655
Distance variable is not defined yet.
16848
42464
Distance variable is not defined yet.
16849
50139
Distance variable is not defined yet.
16850
28169
Distance variable is not defined yet.
16851
87068
Distance variable is not defined yet.
16852
96024
Distance variable is not defined yet.
16853
62867
Distance variable is not defined yet.
16854
42170
Distance variable is not defined yet.
16855
30258
Distance variable is not defined yet.
16856
78717
Distance variable is not defined yet.
16857
38487
Distance variable is not defined yet.
16858
84320
Distance variable is not defined yet.
16859
22060
Distance
2649.928063319907
16860
61369
Distance variable is not defined yet.
16861
38255
Distance variable is not defined yet.
16862
63025
Distance variable is not defined yet.
16863
39330
Distance variable is not defined yet.
16864
65771
Distance variable is not defined yet.
16865
86022
Distance variable is not defined yet.
16866
24882
Distance variable is not defined yet.
16867
04429
Distance variable is not defined yet.
16868
70607
Distance variable is not defined yet.
16869
50246
Distance variable is not defined yet.
16870
66714
Distance variable is not defined yet.
16871
48815
Distance variable is not defined yet.
16872
04236
Distance variable is not defined yet.
16873
76571
Distance
19283.80441812031
16874
94561
Distance variable is not defined yet.
16875
84108
Distance variable is not defined yet.
16876
33548
Distance
19282.16366393708
16877
22102
Distance variable is not defined yet.
16878
86303
Distance variable is not defined yet.
16879
46511
Distance variable is not defined yet.
16880
12738
Distance variable is not defined yet.
16881
73433
Distance variable is not defined yet.
16882
40108
Distance variable is not defined yet.
16883
99589
Distance
19276.540852467188
16884
20754
Distance variable is not defined yet.
16885
23936
Distance variable is not defined yet.
16886
06752
Distance variable is not defined yet.
16887
29851
Distance variable is not defined yet.
16888
01560
Distance variable is not defined yet.
16889
35634
Distance variable is not defined yet.
16890
56521
Distance variable is not defined yet.
16891
58486
Distance variable is not defined yet.
16892
66007
Distance variable is not defined yet.
16893
59047
Distance variable is not defined yet.
16894
63129
Distance variable is not defined yet.
16895
35673
Distance variable is not defined yet.
16896
44287
Distance variable is not defined yet.
16897
34434
Distance variable is not defined yet.
16898
28334
Distance variable is not defined yet.
16899
02769
Distance
19264.243469362442
16900
95531
Distance variable is not defined yet.
16901
71759
Distance variable is not defined yet.
16902
39629
Distance variable is not defined yet.
16903
87728
Distance variable is not defined yet.
16904
40828
Distance variable is not defined yet.
16905
17039
Distance variable is not defined yet.
16906
20817
Distance
19120.29027452724
16907
01050
Distance variable is not defined yet.
16908
54642
Distance variable is not defined yet.
16909
31321
Distance
19252.80646313773
16910
24258
Distance variable is not defined yet.
16911
07851
Distance variable is not defined yet.
16912
97034
Distance variable is not defined yet.
16913
24726
Distance variable is not defined yet.
16914
40026
Distance variable is not defined yet.
16915
75856
Distance variable is not defined yet.
16916
43920
Distance variable is not defined yet.
16917
53178
Distance variable is not defined yet.
16918
15866
Distance variable is not defined yet.
16919
51052
Distance variable is not defined yet.
16920
53002
Distance variable is not defined yet.
16921
67416
Distance variable is not defined yet.
16922
66050
Distance variable is not defined yet.
16923
32081
Distance variable is not defined yet.
16924
84340
Distance variable is not defined yet.
16925
13617
Distance variable is not defined yet.
16926
44707
Distance variable is not defined yet.
16927
99346
Distance variable is not defined yet.
16928
62012
Distance variable is not defined yet.
16929
64147
Distance
1547.545658177805
16930
95675
Distance variable is not defined yet.
16931
74030
Distance variable is not defined yet.
16932
19311
Distance variable is not defined yet.
16933
30075
Distance
19236.805277394607
16934
16424
Distance variable is not defined yet.
16935
15349
Distance variable is not defined yet.
16936
17562
Distance variable is not defined yet.
16937
71968
Distance variable is not defined yet.
16938
61370
Distance variable is not defined yet.
16939
28904
Distance variable is not defined yet.
16940
17861
Distance variable is not defined yet.
16941
55941
Distance
16612.8395180943
16942
02725
Distance
19222.369414537705
16943
78344
Distance variable is not defined yet.
16944
33872
Distance variable is not defined yet.
16945
62269
Distance
8257.608287889429
16946
10803
Distance variable is not defined yet.
16947
92241
Distance variable is not defined yet.
16948
64146
Distance
4970.235857158855
16949
92321
Distance variable is not defined yet.
16950
27569
Distance variable is not defined yet.
16951
49104
Distance variable is not defined yet.
16952
19539
Distance variable is not defined yet.
16953
47240
Distance variable is not defined yet.
16954
59484
Distance variable is not defined yet.
16955
97442
Distance variable is not defined yet.
16956
38059
Distance variable is not defined yet.
16957
17860
Distance variable is not defined yet.
16958
24317
Distance variable is not defined yet.
16959
68742
Distance variable is not defined yet.
16960
40310
Distance variable is not defined yet.
16961
14506
Distance
18042.72579009243
16962
76474
Distance variable is not defined yet.
16963
15437
Distance variable is not defined yet.
16964
34288
Distance variable is not defined yet.
16965
61360
Distance variable is not defined yet.
16966
62520
Distance variable is not defined yet.
16967
53569
Distance variable is not defined yet.
16968
48618
Distance variable is not defined yet.
16969
05648
Distance variable is not defined yet.
16970
15464
Distance variable is not defined yet.
16971
54443
Distance variable is not defined yet.
16972
48866
Distance variable is not defined yet.
16973
48316
Distance variable is not defined yet.
16974
49893
Distance variable is not defined yet.
16975
23024
Distance
5359.798835260817
16976
02815
Distance variable is not defined yet.
16977
75164
Distance
19182.763848656934
16978
06066
Distance variable is not defined yet.
16979
21872
Distance variable is not defined yet.
16980
49408
Distance variable is not defined yet.
16981
29742
Distance variable is not defined yet.
16982
45321
Distance variable is not defined yet.
16983
34689
Distance variable is not defined yet.
16984
39572

Warning: Cannot load hourly/2021/69535.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/69535.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/69535.csv.gz from https://bulk.meteostat.net/v2/

Distance
19175.57697138373
16985
62803
Distance variable is not defined yet.
16986
10576
Distance variable is not defined yet.
16987
38658
Distance variable is not defined yet.
16988
29373
Distance variable is not defined yet.
16989
20852
Distance
13598.434491612235
16990
38501
Distance variable is not defined yet.
16991
08738
Distance variable is not defined yet.
16992
96111
Distance variable is not defined yet.
16993
45032
Distance variable is not defined yet.
16994
95315
Distance variable is not defined yet.
16995
44443
Distance variable is not defined yet.
16996
13424
Distance
1487.1846635524014
16997
98133
Distance variable is not defined yet.
16998
72134
Distance variable is not defined yet.
16999
54638
Distance variable is not defined yet.
17000
46764
Distance variable is not defined yet.
17001
15688
Distance variable is not defined yet.
17002
13428
Distance variable is not defined yet.
17003
56096
Distance variable is not defined yet.
17004
69367
Distance variable is not defined yet.
17005
16510
Distance variable is not defined yet.
17006
70729
Distance variable is not defined yet.
17007
55604
Distance variable is not defined yet.
17008
60548
Distance variable is not defined yet.
17009
62829
Distance variable is not defined yet.
17010
97833
Distance variable is not defined yet.
17011
60657
Distance
9279.447110184723
17012
95415
Distance variable is not defined yet.
17013
24370
Distance variable is not defined yet.
17014
18438
Distance variable is not defined yet.
17015
62975
Distance variable is not defined yet.
17016
56312
Distance variable is not defined yet.
17017
48649
Distance variable is not defined yet.
17018
70645
Distance variable is not defined yet.
17019
44904
Distance variable is not defined yet.
17020
13141
Distance variable is not defined yet.
17021
30471
Distance variable is not defined yet.
17022
29658
Distance variable is not defined yet.
17023
45780
Distance variable is not defined yet.
17024
37860
Distance variable is not defined yet.
17025
17837
Distance variable is not defined yet.
17026
43432
Distance variable is not defined yet.
17027
93619
Distance variable is not defined yet.
17028
06370
Distance variable is not defined yet.
17029
28479
Distance variable is not defined yet.
17030
15644
Distance variable is not defined yet.
17031
51541
Distance variable is not defined yet.
17032
21920
Distance variable is not defined yet.
17033
70820
Distance variable is not defined yet.
17034
77705
Distance variable is not defined yet.
17035
17041
Distance variable is not defined yet.
17036
61115
Distance variable is not defined yet.
17037
67363
Distance variable is not defined yet.
17038
50227
Distance variable is not defined yet.
17039
49806
Distance variable is not defined yet.
17040
65747
Distance variable is not defined yet.
17041
05859
Distance variable is not defined yet.
17042
61283
Distance variable is not defined yet.
17043
01351
Distance variable is not defined yet.
17044
15727
Distance variable is not defined yet.
17045
27828
Distance variable is not defined yet.
17046
96741
Distance variable is not defined yet.
17047
50160
Distance variable is not defined yet.
17048
73661
Distance variable is not defined yet.
17049
41003
Distance variable is not defined yet.
17050
32448
Distance variable is not defined yet.
17051
40049
Distance
13878.370411319256
17052
56263
Distance variable is not defined yet.
17053
24887
Distance variable is not defined yet.
17054
03086
Distance variable is not defined yet.
17055
21009
Distance variable is not defined yet.
17056
50529
Distance variable is not defined yet.
17057
91302
Distance variable is not defined yet.
17058
01223
Distance variable is not defined yet.
17059
01930
Distance variable is not defined yet.
17060
79733
Distance variable is not defined yet.
17061
60963
Distance variable is not defined yet.
17062
67511
Distance variable is not defined yet.
17063
87557
Distance variable is not defined yet.
17064
47611
Distance variable is not defined yet.
17065
33141

Warning: Cannot load hourly/2021/JY84X.csv.gz from https://bulk.meteostat.net/v2/

Distance
19098.739361717548
17066
71067
Distance variable is not defined yet.
17067
12009
Distance variable is not defined yet.
17068
60416
Distance variable is not defined yet.
17069
19543
Distance variable is not defined yet.
17070
98844
Distance variable is not defined yet.
17071
32444
Distance
4234.795796005137
17072
78594
Distance variable is not defined yet.
17073
72065
Distance variable is not defined yet.
17074
75413
Distance variable is not defined yet.
17075
49040
Distance
19088.998179877995
17076
14706
Distance variable is not defined yet.
17077
46950
Distance variable is not defined yet.
17078
24843
Distance variable is not defined yet.
17079
29525
Distance variable is not defined yet.
17080
97106
Distance variable is not defined yet.
17081
50707
Distance variable is not defined yet.
17082
04679
Distance variable is not defined yet.
17083
58222
Distance variable is not defined yet.
17084
54661
Distance variable is not defined yet.
17085
13328
Distance
18711.345571531565
17086
45106
Distance variable is not defined yet.
17087
21863
Distance variable is not defined yet.
17088
50127
Distance variable is not defined yet.
17089
61327
Distance variable is not defined yet.
17090
77448
Distance variable is not defined yet.
17091
65339
Distance variable is not defined yet.
17092
15338
Distance variable is not defined yet.
17093
76693
Distance variable is not defined yet.
17094
64080
Distance variable is not defined yet.
17095
17948
Distance variable is not defined yet.
17096
31025
Distance variable is not defined yet.
17097
26250
Distance variable is not defined yet.
17098
01367
Distance variable is not defined yet.
17099
52333
Distance variable is not defined yet.
17100
40299
Distance variable is not defined yet.
17101
18042
Distance variable is not defined yet.
17102
68870
Distance variable is not defined yet.
17103
62558
Distance variable is not defined yet.
17104
64836
Distance variable is not defined yet.
17105
38725
Distance variable is not defined yet.
17106
02836
Distance variable is not defined yet.
17107
22152
Distance
7789.326387067341
17108
78605
Distance variable is not defined yet.
17109
08084
Distance variable is not defined yet.
17110
23857
Distance variable is not defined yet.
17111
51454
Distance variable is not defined yet.
17112
49113
Distance variable is not defined yet.
17113
98836
Distance variable is not defined yet.
17114
02892
Distance variable is not defined yet.
17115
13076
Distance variable is not defined yet.
17116
53520
Distance variable is not defined yet.
17117
93543
Distance variable is not defined yet.
17118
47880
Distance variable is not defined yet.
17119
03057
Distance variable is not defined yet.
17120
49504
Distance variable is not defined yet.
17121
28450
Distance variable is not defined yet.
17122
34986
Distance variable is not defined yet.
17123
47373
Distance variable is not defined yet.
17124
70373
Distance variable is not defined yet.
17125
07840
Distance variable is not defined yet.
17126
80809
Distance variable is not defined yet.
17127
54749
Distance variable is not defined yet.
17128
96761

Warning: Cannot load hourly/2021/91189.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/91189.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/91189.csv.gz from https://bulk.meteostat.net/v2/

Distance
8651.877866382747
17129
33469
Distance variable is not defined yet.
17130
03841
Distance variable is not defined yet.
17131
72523
Distance variable is not defined yet.
17132
16150
Distance variable is not defined yet.
17133
04066
Distance variable is not defined yet.
17134
35043
Distance variable is not defined yet.
17135
03045
Distance
14852.487386130195
17136
68318
Distance variable is not defined yet.
17137
15920
Distance variable is not defined yet.
17138
77422
Distance variable is not defined yet.
17139
48470
Distance variable is not defined yet.
17140
13321
Distance
6946.516138141683
17141
48393
Distance variable is not defined yet.
17142
15051
Distance variable is not defined yet.
17143
41649
Distance variable is not defined yet.
17144
38357
Distance variable is not defined yet.
17145
61315
Distance variable is not defined yet.
17146
47546
Distance variable is not defined yet.
17147
30052
Distance variable is not defined yet.
17148
68924
Distance variable is not defined yet.
17149
05820
Distance variable is not defined yet.
17150
10553
Distance variable is not defined yet.
17151
14777
Distance variable is not defined yet.
17152
59354
Distance variable is not defined yet.
17153
14081
Distance variable is not defined yet.
17154
37801
Distance variable is not defined yet.
17155
97042
Distance variable is not defined yet.
17156
73655
Distance variable is not defined yet.
17157
15849
Distance variable is not defined yet.
17158
14507
Distance variable is not defined yet.
17159
48634
Distance variable is not defined yet.
17160
31784
Distance variable is not defined yet.
17161
45310
Distance variable is not defined yet.
17162
40913
Distance variable is not defined yet.
17163
17867
Distance variable is not defined yet.
17164
14886
Distance variable is not defined yet.
17165
54631
Distance variable is not defined yet.
17166
47537
Distance variable is not defined yet.
17167
70770
Distance variable is not defined yet.
17168
53179
Distance
18997.98845845676
17169
52647
Distance variable is not defined yet.
17170
14760
Distance variable is not defined yet.
17171
27807
Distance variable is not defined yet.
17172
03449
Distance variable is not defined yet.
17173
46767
Distance variable is not defined yet.
17174
61021
Distance variable is not defined yet.
17175
01440
Distance variable is not defined yet.
17176
32784
Distance variable is not defined yet.
17177
65345
Distance variable is not defined yet.
17178
62238
Distance variable is not defined yet.
17179
17557
Distance variable is not defined yet.
17180
77656
Distance variable is not defined yet.
17181
03441
Distance variable is not defined yet.
17182
51523
Distance variable is not defined yet.
17183
45853
Distance variable is not defined yet.
17184
80750
Distance variable is not defined yet.
17185
31201
Distance variable is not defined yet.
17186
80403
Distance variable is not defined yet.
17187
49795
Distance variable is not defined yet.
17188
03224
Distance variable is not defined yet.
17189
15350
Distance variable is not defined yet.
17190
11030
Distance variable is not defined yet.
17191
61949
Distance variable is not defined yet.
17192
95462
Distance variable is not defined yet.
17193
55017
Distance variable is not defined yet.
17194
22849
Distance
16217.252957790608
17195
06820
Distance variable is not defined yet.
17196
74857
Distance variable is not defined yet.
17197
64083
Distance
10969.930592520204
17198
37419
Distance variable is not defined yet.
17199
97371
Distance variable is not defined yet.
17200
99019
Distance variable is not defined yet.
17201
49071
Distance variable is not defined yet.
17202
84752
Distance variable is not defined yet.
17203
62943
Distance variable is not defined yet.
17204
50634
Distance variable is not defined yet.
17205
70775
Distance variable is not defined yet.
17206
72085
Distance variable is not defined yet.
17207
05494
Distance variable is not defined yet.
17208
24740
Distance variable is not defined yet.
17209
55719
Distance variable is not defined yet.
17210
27866
Distance variable is not defined yet.
17211
07463
Distance variable is not defined yet.
17212
38558
Distance variable is not defined yet.
17213
95650
Distance
17454.20768033947
17214
07825
Distance variable is not defined yet.
17215
77354
Distance variable is not defined yet.
17216
50122
Distance variable is not defined yet.
17217
63084
Distance variable is not defined yet.
17218
26267
Distance variable is not defined yet.
17219
41097
Distance variable is not defined yet.
17220
75978
Distance variable is not defined yet.
17221
42452
Distance variable is not defined yet.
17222
84328
Distance variable is not defined yet.
17223
44280
Distance variable is not defined yet.
17224
56120
Distance variable is not defined yet.
17225
40763
Distance variable is not defined yet.
17226
27518
Distance variable is not defined yet.
17227
89410
Distance variable is not defined yet.
17228
74547
Distance variable is not defined yet.
17229
45845
Distance variable is not defined yet.
17230
68526
Distance variable is not defined yet.
17231
61018
Distance variable is not defined yet.
17232
27231
Distance variable is not defined yet.
17233
08752
Distance
8977.93786098717
17234
94122
Distance
15052.376008849174
17235
38702
Distance variable is not defined yet.
17236
99301
Distance variable is not defined yet.
17237
52168
Distance variable is not defined yet.
17238
05751
Distance variable is not defined yet.
17239
35978
Distance variable is not defined yet.
17240
76230
Distance variable is not defined yet.
17241
15961
Distance variable is not defined yet.
17242
12777
Distance variable is not defined yet.
17243
67546
Distance variable is not defined yet.
17244
12548
Distance
17787.58803576655
17245
15334
Distance variable is not defined yet.
17246
43062
Distance variable is not defined yet.
17247
49421
Distance variable is not defined yet.
17248
93218
Distance variable is not defined yet.
17249
55804
Distance variable is not defined yet.
17250
04071
Distance
16391.44042749109
17251
62014
Distance variable is not defined yet.
17252
02189
Distance
15269.844294698401
17253
19703
Distance variable is not defined yet.
17254
17529
Distance variable is not defined yet.
17255
75778
Distance variable is not defined yet.
17256
70584
Distance variable is not defined yet.
17257
02812
Distance variable is not defined yet.
17258
82334
Distance variable is not defined yet.
17259
64656
Distance variable is not defined yet.
17260
75661
Distance variable is not defined yet.
17261
16250
Distance variable is not defined yet.
17262
60462
Distance variable is not defined yet.
17263
02333
Distance
12792.841065666853
17264
05681
Distance variable is not defined yet.
17265
89439
Distance variable is not defined yet.
17266
03303
Distance variable is not defined yet.
17267
34473
Distance variable is not defined yet.
17268
54407
Distance variable is not defined yet.
17269
45771
Distance variable is not defined yet.
17270
24986
Distance variable is not defined yet.
17271
21014
Distance variable is not defined yet.
17272
24361
Distance variable is not defined yet.
17273
15863
Distance variable is not defined yet.
17274
76433
Distance variable is not defined yet.
17275
62843
Distance variable is not defined yet.
17276
24808
Distance variable is not defined yet.
17277
70552
Distance variable is not defined yet.
17278
11548
Distance variable is not defined yet.
17279
16246
Distance variable is not defined yet.
17280
28524
Distance
18876.15163758898
17281
68303
Distance variable is not defined yet.
17282
23180
Distance variable is not defined yet.
17283
24112
Distance variable is not defined yet.
17284
05837
Distance variable is not defined yet.
17285
21771
Distance variable is not defined yet.
17286
73025
Distance variable is not defined yet.
17287
74546
Distance variable is not defined yet.
17288
84073
Distance variable is not defined yet.
17289
64423
Distance variable is not defined yet.
17290
67853
Distance variable is not defined yet.
17291
77022
Distance
13078.287494005528
17292
23086
Distance variable is not defined yet.
17293
37036
Distance variable is not defined yet.
17294
15774
Distance variable is not defined yet.
17295
14741
Distance variable is not defined yet.
17296
24827
Distance variable is not defined yet.
17297
74022
Distance variable is not defined yet.
17298
27957
Distance variable is not defined yet.
17299
53809
Distance variable is not defined yet.
17300
27357
Distance variable is not defined yet.
17301
23942
Distance variable is not defined yet.
17302
71866
Distance variable is not defined yet.
17303
83864
Distance variable is not defined yet.
17304
76373
Distance variable is not defined yet.
17305
87048
Distance
8457.674897366844
17306
58261
Distance variable is not defined yet.
17307
45107
Distance variable is not defined yet.
17308
47528
Distance variable is not defined yet.
17309
30627
Distance variable is not defined yet.
17310
42171
Distance variable is not defined yet.
17311
79849
Distance variable is not defined yet.
17312
06751
Distance variable is not defined yet.
17313
21757
Distance variable is not defined yet.
17314
56085
Distance variable is not defined yet.
17315
24556
Distance variable is not defined yet.
17316
68779
Distance variable is not defined yet.
17317
27845
Distance variable is not defined yet.
17318
57041
Distance variable is not defined yet.
17319
14838
Distance variable is not defined yet.
17320
55382
Distance variable is not defined yet.
17321
58558
Distance variable is not defined yet.
17322
71411
Distance variable is not defined yet.
17323
15845
Distance variable is not defined yet.
17324
39665
Distance variable is not defined yet.
17325
43565
Distance variable is not defined yet.
17326
28628
Distance variable is not defined yet.
17327
40940
Distance variable is not defined yet.
17328
10976
Distance variable is not defined yet.
17329
05874
Distance variable is not defined yet.
17330
72445
Distance variable is not defined yet.
17331
51465
Distance variable is not defined yet.
17332
62093
Distance variable is not defined yet.
17333
69130
Distance
4524.800358041663
17334
77624
Distance variable is not defined yet.
17335
46701
Distance variable is not defined yet.
17336
28227
Distance variable is not defined yet.
17337
50028
Distance variable is not defined yet.
17338
48873
Distance variable is not defined yet.
17339
75943
Distance variable is not defined yet.
17340
01236
Distance variable is not defined yet.
17341
54311
Distance variable is not defined yet.
17342
64640
Distance variable is not defined yet.
17343
54230
Distance variable is not defined yet.
17344
03826
Distance variable is not defined yet.
17345
31649
Distance variable is not defined yet.
17346
61277
Distance variable is not defined yet.
17347
38127
Distance variable is not defined yet.
17348
61244
Distance variable is not defined yet.
17349
01069
Distance variable is not defined yet.
17350
04927
Distance variable is not defined yet.
17351
74346
Distance variable is not defined yet.
17352
41094
Distance variable is not defined yet.
17353
36036
Distance variable is not defined yet.
17354
15475
Distance variable is not defined yet.
17355
19374
Distance variable is not defined yet.
17356
97035
Distance variable is not defined yet.
17357
66042
Distance variable is not defined yet.
17358
15545
Distance variable is not defined yet.
17359
13072
Distance variable is not defined yet.
17360
24566
Distance variable is not defined yet.
17361
15460
Distance variable is not defined yet.
17362
02832
Distance variable is not defined yet.
17363
25977
Distance variable is not defined yet.
17364
75558
Distance variable is not defined yet.
17365
47925
Distance variable is not defined yet.
17366
15478
Distance variable is not defined yet.
17367
24517
Distance variable is not defined yet.
17368
26385
Distance variable is not defined yet.
17369
55070
Distance variable is not defined yet.
17370
14036
Distance variable is not defined yet.
17371
38351
Distance variable is not defined yet.
17372
41039
Distance variable is not defined yet.
17373
46172
Distance variable is not defined yet.
17374
43019
Distance variable is not defined yet.
17375
63538
Distance variable is not defined yet.
17376
95486
Distance variable is not defined yet.
17377
94901
Distance variable is not defined yet.
17378
48141
Distance variable is not defined yet.
17379
95140
Distance
18780.55945823753
17380
24354
Distance variable is not defined yet.
17381
68982
Distance variable is not defined yet.
17382
95693
Distance variable is not defined yet.
17383
25570
Distance variable is not defined yet.
17384
70357
Distance variable is not defined yet.
17385
35224
Distance variable is not defined yet.
17386
24657
Distance variable is not defined yet.
17387
95960
Distance variable is not defined yet.
17388
40223
Distance variable is not defined yet.
17389
14822
Distance
18627.143825585987
17390
21120
Distance variable is not defined yet.
17391
43721
Distance variable is not defined yet.
17392
54949
Distance variable is not defined yet.
17393
40051
Distance variable is not defined yet.
17394
58317
Distance variable is not defined yet.
17395
53137
Distance variable is not defined yet.
17396
10703
Distance variable is not defined yet.
17397
13693
Distance variable is not defined yet.
17398
26591
Distance variable is not defined yet.
17399
19939
Distance variable is not defined yet.
17400
53598
Distance variable is not defined yet.
17401
12992
Distance
14275.091041794243
17402
83714
Distance variable is not defined yet.
17403
74747
Distance variable is not defined yet.
17404
76884
Distance variable is not defined yet.
17405
66952
Distance variable is not defined yet.
17406
60002
Distance variable is not defined yet.
17407
72060
Distance variable is not defined yet.
17408
71001
Distance variable is not defined yet.
17409
55112
Distance
7574.379357601584
17410
14861
Distance variable is not defined yet.
17411
25908
Distance variable is not defined yet.
17412
61560
Distance variable is not defined yet.
17413
29645
Distance variable is not defined yet.
17414
50042
Distance variable is not defined yet.
17415
50477
Distance variable is not defined yet.
17416
14085
Distance variable is not defined yet.
17417
58363
Distance variable is not defined yet.
17418
18077
Distance
18742.902186073436
17419
12926
Distance variable is not defined yet.
17420
81087
Distance variable is not defined yet.
17421
71972
Distance variable is not defined yet.
17422
56168
Distance variable is not defined yet.
17423
12585
Distance
3639.698839493182
17424
08872
Distance variable is not defined yet.
17425
04009
Distance variable is not defined yet.
17426
37938
Distance variable is not defined yet.
17427
25025
Distance variable is not defined yet.
17428
44612
Distance variable is not defined yet.
17429
17512
Distance variable is not defined yet.
17430
47512
Distance variable is not defined yet.
17431
96720
Distance variable is not defined yet.
17432
27014
Distance variable is not defined yet.
17433
46303
Distance variable is not defined yet.
17434
88022
Distance variable is not defined yet.
17435
63131
Distance variable is not defined yet.
17436
24853
Distance variable is not defined yet.
17437
01347
Distance variable is not defined yet.
17438
43003
Distance variable is not defined yet.
17439
48169
Distance variable is not defined yet.
17440
31795
Distance variable is not defined yet.
17441
08340
Distance variable is not defined yet.
17442
24572
Distance variable is not defined yet.
17443
41713
Distance variable is not defined yet.
17444
10552
Distance variable is not defined yet.
17445
57245
Distance variable is not defined yet.
17446
49676
Distance variable is not defined yet.
17447
63848
Distance variable is not defined yet.
17448
27301
Distance variable is not defined yet.
17449
60145
Distance variable is not defined yet.
17450
48415
Distance variable is not defined yet.
17451
74469
Distance variable is not defined yet.
17452
42749
Distance variable is not defined yet.
17453
51024
Distance variable is not defined yet.
17454
59547
Distance variable is not defined yet.
17455
62629
Distance variable is not defined yet.
17456
14004
Distance variable is not defined yet.
17457
38362
Distance variable is not defined yet.
17458
94102
Distance
9020.432407017795
17459
68832
Distance variable is not defined yet.
17460
78261
Distance variable is not defined yet.
17461
55005
Distance variable is not defined yet.
17462
75041
Distance
18700.99940040819
17463
95380
Distance variable is not defined yet.
17464
39320
Distance variable is not defined yet.
17465
47631
Distance variable is not defined yet.
17466
21654
Distance
13258.843056599804
17467
31206
Distance variable is not defined yet.
17468
38052
Distance variable is not defined yet.
17469
87718
Distance variable is not defined yet.
17470
31016
Distance variable is not defined yet.
17471
63624
Distance variable is not defined yet.
17472
43151
Distance variable is not defined yet.
17473
38334
Distance variable is not defined yet.
17474
22032
Distance
14787.564504946648
17475
49320
Distance variable is not defined yet.
17476
28581
Distance variable is not defined yet.
17477
17853
Distance variable is not defined yet.
17478
11721
Distance variable is not defined yet.
17479
21629
Distance
12392.15405577112
17480
62693
Distance variable is not defined yet.
17481
20117
Distance variable is not defined yet.
17482
51531
Distance variable is not defined yet.
17483
67573
Distance variable is not defined yet.
17484
72004
Distance variable is not defined yet.
17485
60559
Distance variable is not defined yet.
17486
13441
Distance
8731.708473690898
17487
48871
Distance variable is not defined yet.
17488
37806
Distance variable is not defined yet.
17489
17340
Distance variable is not defined yet.
17490
13031
Distance
18175.800150251256
17491
56036
Distance variable is not defined yet.
17492
76957
Distance variable is not defined yet.
17493
50548
Distance variable is not defined yet.
17494
33837
Distance variable is not defined yet.
17495
53024
Distance variable is not defined yet.
17496
83434
Distance variable is not defined yet.
17497
76435
Distance variable is not defined yet.
17498
62434
Distance variable is not defined yet.
17499
89004
Distance variable is not defined yet.
17500
16679
Distance variable is not defined yet.
17501
49067
Distance variable is not defined yet.
17502
45349
Distance
18663.63505623911
17503
54082
Distance
11396.28288347227
17504
04910
Distance variable is not defined yet.
17505
49968
Distance variable is not defined yet.
17506
53505
Distance variable is not defined yet.
17507
33936
Distance variable is not defined yet.
17508
45851
Distance variable is not defined yet.
17509
57032
Distance variable is not defined yet.
17510
80236
Distance variable is not defined yet.
17511
54643
Distance variable is not defined yet.
17512
13651
Distance variable is not defined yet.
17513
47380
Distance variable is not defined yet.
17514
98260
Distance variable is not defined yet.
17515
12789
Distance variable is not defined yet.
17516
50560
Distance variable is not defined yet.
17517
56592
Distance variable is not defined yet.
17518
43342
Distance variable is not defined yet.
17519
49963
Distance variable is not defined yet.
17520
11023
Distance variable is not defined yet.
17521
14472
Distance variable is not defined yet.
17522
78043
Distance variable is not defined yet.
17523
56041
Distance variable is not defined yet.
17524
66732
Distance variable is not defined yet.
17525
33972
Distance variable is not defined yet.
17526
02645
Distance
8859.632755933797
17527
99709
Distance
18642.449359160542
17528
32082
Distance variable is not defined yet.
17529
67862
Distance variable is not defined yet.
17530
54547
Distance variable is not defined yet.
17531
22433
Distance variable is not defined yet.
17532
20842
Distance variable is not defined yet.
17533
31807
Distance variable is not defined yet.
17534
52660
Distance variable is not defined yet.
17535
36901

Warning: Cannot load hourly/2021/KNXX0.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/KNXX0.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/KNXX0.csv.gz from https://bulk.meteostat.net/v2/

Distance
6956.58216505597
17957
04779
Distance variable is not defined yet.
17958
51342
Distance variable is not defined yet.
17959
78607
Distance variable is not defined yet.
17960
01851
Distance variable is not defined yet.
17961
68790
Distance variable is not defined yet.
17962
89451
Distance variable is not defined yet.
17963
75801
Distance variable is not defined yet.
17964
50632
Distance variable is not defined yet.
17965
12047
Distance variable is not defined yet.
17966
83277
Distance variable is not defined yet.
17967
75956
Distance variable is not defined yet.
17968
70739
Distance variable is not defined yet.
17969
35064
Distance variable is not defined yet.
17970
33809
Distance variable is not defined yet.
17971
80741
Distance
14380.41300930543
17972
05067
Distance variable is not defined yet.
17973
20169
Distance variable is not defined yet.
17974
81647
Distance variable is not defined yet.
17975
96825
Distance
18170.076417220727
17976
60618
Distance
12312.289259150684
17977
69133
Distance variable is not defined yet.
17978
01463
Distance
11632.877135074054
17979
81621
Distance variable is not defined yet.
17980
78257
Distance
12790.220396107923
17981
15752
Distance variable is not defined yet.
17982
66948
Distance variable is not defined yet.
17983
53017
Distance variable is not defined yet.
17984
24931
Distance variable is not defined yet.
17985
70517
Distance variable is not defined yet.
17986
24350
Distance variable is not defined yet.
17987
29707
Distance
18161.587474707576
17988
73058
Distance variable is not defined yet.
17989
15823
Distance variable is not defined yet.
17990
27314
Distance variable is not defined yet.
17991
15946
Distance variable is not defined yet.
17992
18080
Distance
13559.074487564703
17993
33140
Distance
17807.41199844138
17994
63045
Distance variable is not defined yet.
17995
27813
Distance variable is not defined yet.
17996
15312
Distance variable is not defined yet.
17997
23233
Distance variable is not defined yet.
17998
74855
Distance variable is not defined yet.
17999
58355
Distance variable is not defined yet.
18000
16156
Distance variable is not defined yet.
18001
63088
Distance variable is not defined yet.
18002
42082
Distance variable is not defined yet.
18003
56150
Distance variable is not defined yet.
18004
87375
Distance variable is not defined yet.
18005
43082
Distance variable is not defined yet.
18006
37146
Distance variable is not defined yet.
18007
49405
Distance variable is not defined yet.
18008
02875
Distance variable is not defined yet.
18009
56121
Distance variable is not defined yet.
18010
51652
Distance variable is not defined yet.
18011
50169
Distance variable is not defined yet.
18012
18435
Distance variable is not defined yet.
18013
51556
Distance variable is not defined yet.
18014
56273
Distance variable is not defined yet.
18015
92371
Distance variable is not defined yet.
18016
12086
Distance variable is not defined yet.
18017
60169
Distance
6912.063026390498
18018
27283
Distance variable is not defined yet.
18019
06880
Distance variable is not defined yet.
18020
05906
Distance variable is not defined yet.
18021
28434
Distance variable is not defined yet.
18022
77063
Distance
17229.883490578606
18023
99403
Distance variable is not defined yet.
18024
40995
Distance variable is not defined yet.
18025
58216
Distance variable is not defined yet.
18026
68655
Distance variable is not defined yet.
18027
74459
Distance variable is not defined yet.
18028
13464
Distance
15312.445524252049
18029
31735
Distance variable is not defined yet.
18030
60471
Distance variable is not defined yet.
18031
68037
Distance variable is not defined yet.
18032
10550
Distance variable is not defined yet.
18033
30354
Distance variable is not defined yet.
18034
63043
Distance variable is not defined yet.
18035
73453
Distance variable is not defined yet.
18036
25810
Distance variable is not defined yet.
18037
19538
Distance variable is not defined yet.
18038
45686
Distance variable is not defined yet.
18039
01468
Distance variable is not defined yet.
18040
17810
Distance variable is not defined yet.
18041
47561
Distance
18100.15602260696
18042
31733
Distance variable is not defined yet.
18043
14513
Distance variable is not defined yet.
18044
49107
Distance variable is not defined yet.
18045
21810
Distance variable is not defined yet.
18046
52233
Distance variable is not defined yet.
18047
43555
Distance variable is not defined yet.
18048
43164
Distance variable is not defined yet.
18049
40356
Distance variable is not defined yet.
18050
31712
Distance variable is not defined yet.
18051
54473
Distance variable is not defined yet.
18052
95383
Distance variable is not defined yet.
18053
38614
Distance variable is not defined yet.
18054
54977
Distance variable is not defined yet.
18055
16833
Distance variable is not defined yet.
18056
30518
Distance
18089.45151681622
18057
98011
Distance variable is not defined yet.
18058
51527
Distance variable is not defined yet.
18059
16730
Distance variable is not defined yet.
18060
66710
Distance variable is not defined yet.
18061
11507
Distance variable is not defined yet.
18062
70359
Distance variable is not defined yet.
18063
75965
Distance variable is not defined yet.
18064
29175
Distance variable is not defined yet.
18065
63653
Distance variable is not defined yet.
18066
56237
Distance variable is not defined yet.
18067
63847
Distance variable is not defined yet.
18068
67020
Distance variable is not defined yet.
18069
47866
Distance variable is not defined yet.
18070
01740
Distance
14527.64971851565
18071
48631
Distance variable is not defined yet.
18072
23229
Distance variable is not defined yet.
18073
64166
Distance variable is not defined yet.
18074
77096
Distance
9256.53988216419
18075
08554
Distance variable is not defined yet.
18076
97112
Distance variable is not defined yet.
18077
80214
Distance variable is not defined yet.
18078
69343
Distance variable is not defined yet.
18079
31650
Distance variable is not defined yet.
18080
08302
Distance variable is not defined yet.
18081
60124
Distance variable is not defined yet.
18082
15003
Distance variable is not defined yet.
18083
26520
Distance variable is not defined yet.
18084
30184
Distance variable is not defined yet.
18085
07746
Distance variable is not defined yet.
18086
04252
Distance variable is not defined yet.
18087
23308
Distance variable is not defined yet.
18088
13092
Distance variable is not defined yet.
18089
10918
Distance variable is not defined yet.
18090
04614
Distance variable is not defined yet.
18091
14728
Distance variable is not defined yet.
18092
05053
Distance variable is not defined yet.
18093
38007
Distance variable is not defined yet.
18094
63130
Distance variable is not defined yet.
18095
24602
Distance variable is not defined yet.
18096
10507
Distance variable is not defined yet.
18097
01590
Distance variable is not defined yet.
18098
56264
Distance variable is not defined yet.
18099
03816
Distance variable is not defined yet.
18100
60201
Distance variable is not defined yet.
18101
24330
Distance variable is not defined yet.
18102
95629
Distance variable is not defined yet.
18103
58621
Distance variable is not defined yet.
18104
11771
Distance variable is not defined yet.
18105
48228
Distance variable is not defined yet.
18106
81057
Distance variable is not defined yet.
18107
25446
Distance variable is not defined yet.
18108
03858
Distance variable is not defined yet.
18109
17777
Distance variable is not defined yet.
18110
16511
Distance variable is not defined yet.
18111
01719
Distance
11010.545073021412
18112
22548
Distance variable is not defined yet.
18113
64062
Distance variable is not defined yet.
18114
33326
Distance variable is not defined yet.
18115
18635
Distance variable is not defined yet.
18116
27217
Distance variable is not defined yet.
18117
48895
Distance variable is not defined yet.
18118
77961
Distance variable is not defined yet.
18119
95366
Distance variable is not defined yet.
18120
37705
Distance variable is not defined yet.
18121
77562
Distance variable is not defined yet.
18122
96760
Distance variable is not defined yet.
18123
08324
Distance variable is not defined yet.
18124
88135
Distance variable is not defined yet.
18125
83332
Distance variable is not defined yet.
18126
35905
Distance variable is not defined yet.
18127
75433
Distance variable is not defined yet.
18128
35117
Distance variable is not defined yet.
18129
54141
Distance variable is not defined yet.
18130
27244
Distance variable is not defined yet.
18131
96137
Distance variable is not defined yet.
18132
47834
Distance variable is not defined yet.
18133
63867
Distance variable is not defined yet.
18134
78065
Distance variable is not defined yet.
18135
97116
Distance variable is not defined yet.
18136
27707
Distance variable is not defined yet.
18137
16621
Distance variable is not defined yet.
18138
34607
Distance variable is not defined yet.
18139
06242
Distance variable is not defined yet.
18140
43213
Distance variable is not defined yet.
18141
38644
Distance variable is not defined yet.
18142
66111
Distance
18000.835963566657
18143
53128
Distance variable is not defined yet.
18144
44680
Distance variable is not defined yet.
18145
48331
Distance variable is not defined yet.
18146
47590
Distance variable is not defined yet.
18147
10704
Distance variable is not defined yet.
18148
37034
Distance variable is not defined yet.
18149
61272
Distance variable is not defined yet.
18150
28713
Distance variable is not defined yet.
18151
06001
Distance variable is not defined yet.
18152
78001
Distance variable is not defined yet.
18153
45870
Distance variable is not defined yet.
18154
75780
Distance variable is not defined yet.
18155
01036
Distance variable is not defined yet.
18156
36613
Distance variable is not defined yet.
18157
17957
Distance variable is not defined yet.
18158
31057
Distance variable is not defined yet.
18159
53811
Distance variable is not defined yet.
18160
08518
Distance variable is not defined yet.
18161
60484
Distance variable is not defined yet.
18162
59082
Distance variable is not defined yet.
18163
28673
Distance variable is not defined yet.
18164
43230
Distance variable is not defined yet.
18165
77642
Distance variable is not defined yet.
18166
42544
Distance variable is not defined yet.
18167
88348
Distance variable is not defined yet.
18168
80543
Distance variable is not defined yet.
18169
26451
Distance variable is not defined yet.
18170
60561
Distance variable is not defined yet.
18171
93616
Distance variable is not defined yet.
18172
35611
Distance variable is not defined yet.
18173
17098
Distance variable is not defined yet.
18174
55327
Distance variable is not defined yet.
18175
36571
Distance variable is not defined yet.
18176
51640
Distance variable is not defined yet.
18177
50144
Distance variable is not defined yet.
18178
37886
Distance variable is not defined yet.
18179
38388
Distance variable is not defined yet.
18180
81082
Distance variable is not defined yet.
18181
17570
Distance variable is not defined yet.
18182
60129
Distance variable is not defined yet.
18183
28604
Distance variable is not defined yet.
18184
24991
Distance variable is not defined yet.
18185
37037
Distance variable is not defined yet.
18186
35061
Distance variable is not defined yet.
18187
53147
Distance variable is not defined yet.
18188
44265
Distance variable is not defined yet.
18189
60625
Distance
14474.873218158784
18190
37618
Distance
10963.855327200086
18191
30022
Distance variable is not defined yet.
18192
66515
Distance variable is not defined yet.
18193
08751
Distance variable is not defined yet.
18194
54874
Distance variable is not defined yet.
18195
31090
Distance variable is not defined yet.
18196
92610
Distance
4982.739546253254
18197
98923
Distance variable is not defined yet.
18198
17555
Distance variable is not defined yet.
18199
23426
Distance variable is not defined yet.
18200
24374
Distance variable is not defined yet.
18201
51636
Distance variable is not defined yet.
18202
83274
Distance variable is not defined yet.
18203
54889
Distance variable is not defined yet.
18204
01760
Distance variable is not defined yet.
18205
84014
Distance variable is not defined yet.
18206
47106
Distance variable is not defined yet.
18207
93257
Distance variable is not defined yet.
18208
28016
Distance variable is not defined yet.
18209
21733
Distance variable is not defined yet.
18210
56171
Distance variable is not defined yet.
18211
16344
Distance variable is not defined yet.
18212
71969
Distance variable is not defined yet.
18213
19555
Distance variable is not defined yet.
18214
21824
Distance variable is not defined yet.
18215
28451
Distance variable is not defined yet.
18216
41043
Distance variable is not defined yet.
18217
92026
Distance
17905.43026975636
18218
91962
Distance variable is not defined yet.
18219
46771
Distance variable is not defined yet.
18220
68064

Warning: Cannot load hourly/2021/72558.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/72558.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/72558.csv.gz from https://bulk.meteostat.net/v2/

Distance
4069.7196075525103
18221
24064
Distance variable is not defined yet.
18222
17762
Distance variable is not defined yet.
18223
43037
Distance variable is not defined yet.
18224
75437
Distance variable is not defined yet.
18225
63367
Distance variable is not defined yet.
18226
85747
Distance variable is not defined yet.
18227
62288
Distance variable is not defined yet.
18228
78389
Distance variable is not defined yet.
18229
35036
Distance variable is not defined yet.
18230
64089
Distance variable is not defined yet.
18231
56032
Distance variable is not defined yet.
18232
48880
Distance variable is not defined yet.
18233
24272
Distance variable is not defined yet.
18234
13664
Distance
10347.746800113358
18235
41619
Distance variable is not defined yet.
18236
43347
Distance variable is not defined yet.
18237
65082
Distance variable is not defined yet.
18238
45325
Distance variable is not defined yet.
18239
10526
Distance variable is not defined yet.
18240
56260
Distance variable is not defined yet.
18241
34238
Distance variable is not defined yet.
18242
60927
Distance variable is not defined yet.
18243
48362
Distance variable is not defined yet.
18244
53714
Distance variable is not defined yet.
18245
32567
Distance variable is not defined yet.
18246
46825
Distance variable is not defined yet.
18247
26354
Distance variable is not defined yet.
18248
10968
Distance variable is not defined yet.
18249
92211
Distance variable is not defined yet.
18250
03110
Distance
7805.263785110458
18251
58269
Distance variable is not defined yet.
18252
06376
Distance variable is not defined yet.
18253
56221
Distance variable is not defined yet.
18254
19731
Distance variable is not defined yet.
18255
89011
Distance variable is not defined yet.
18256
07803
Distance variable is not defined yet.
18257
53502
Distance variable is not defined yet.
18258
61745
Distance variable is not defined yet.
18259
64156
Distance variable is not defined yet.
18260
63133
Distance variable is not defined yet.
18261
87022
Distance variable is not defined yet.
18262
87416
Distance variable is not defined yet.
18263
60504
Distance variable is not defined yet.
18264
54430
Distance variable is not defined yet.
18265
51571
Distance variable is not defined yet.
18266
54422
Distance variable is not defined yet.
18267
37826
Distance variable is not defined yet.
18268
46508
Distance variable is not defined yet.
18269
15221
Distance
10018.961499978108
18270
46150
Distance variable is not defined yet.
18271
08067
Distance variable is not defined yet.
18272
67674
Distance variable is not defined yet.
18273
19547
Distance variable is not defined yet.
18274
43738
Distance variable is not defined yet.
18275
73646
Distance variable is not defined yet.
18276
96155
Distance variable is not defined yet.
18277
37118
Distance variable is not defined yet.
18278
99036
Distance variable is not defined yet.
18279
56229
Distance variable is not defined yet.
18280
37601
Distance
14044.253343216425
18281
83841
Distance variable is not defined yet.
18282
54213
Distance variable is not defined yet.
18283
02188
Distance
13147.952997579443
18284
53069
Distance variable is not defined yet.
18285
53515
Distance variable is not defined yet.
18286
85624
Distance variable is not defined yet.
18287
46182
Distance variable is not defined yet.
18288
68072
Distance variable is not defined yet.
18289
93560
Distance variable is not defined yet.
18290
98047
Distance variable is not defined yet.
18291
50651
Distance variable is not defined yet.
18292
04496
Distance variable is not defined yet.
18293
08202
Distance variable is not defined yet.
18294
75148
Distance variable is not defined yet.
18295
58655
Distance variable is not defined yet.
18296
68401
Distance variable is not defined yet.
18297
75447
Distance variable is not defined yet.
18298
92254
Distance variable is not defined yet.
18299
35183
Distance variable is not defined yet.
18300
94103
Distance
8375.244205120049
18301
93625
Distance variable is not defined yet.
18302
77079
Distance
8047.7930202467605
18303
94710
Distance
9420.633449027031
18304
21161
Distance variable is not defined yet.
18305
19522
Distance variable is not defined yet.
18306
42022
Distance variable is not defined yet.
18307
24823
Distance variable is not defined yet.
18308
47920
Distance variable is not defined yet.
18309
47368
Distance variable is not defined yet.
18310
95683
Distance variable is not defined yet.
18311
68069
Distance
9231.203312188505
18312
43506
Distance variable is not defined yet.
18313
30097
Distance variable is not defined yet.
18314
01775
Distance
16860.974798382034
18315
38018
Distance variable is not defined yet.
18316
46565
Distance variable is not defined yet.
18317
08558
Distance variable is not defined yet.
18318
21555
Distance variable is not defined yet.
18319
47630
Distance variable is not defined yet.
18320
53103
Distance
15997.15524323485
18321
74460
Distance variable is not defined yet.
18322
55110
Distance
17212.471185967806
18323
29056
Distance variable is not defined yet.
18324
46052
Distance variable is not defined yet.
18325
98239
Distance
6728.473669828403
18326
32410
Distance variable is not defined yet.
18327
46168
Distance variable is not defined yet.
18328
31773
Distance variable is not defined yet.
18329
76078
Distance
17815.50615317224
18330
67425
Distance variable is not defined yet.
18331
23938
Distance variable is not defined yet.
18332
10801
Distance variable is not defined yet.
18333
31764
Distance variable is not defined yet.
18334
28658
Distance variable is not defined yet.
18335
62334
Distance variable is not defined yet.
18336
75094
Distance variable is not defined yet.
18337
78592
Distance
17806.425971199908
18338
76252
Distance variable is not defined yet.
18339
56309
Distance variable is not defined yet.
18340
94512
Distance variable is not defined yet.
18341
22192
Distance
12106.656503976446
18342
06333
Distance variable is not defined yet.
18343
03838
Distance variable is not defined yet.
18344
45239
Distance variable is not defined yet.
18345
83201
Distance variable is not defined yet.
18346
08074
Distance variable is not defined yet.
18347
47970
Distance variable is not defined yet.
18348
22709
Distance variable is not defined yet.
18349
47334
Distance
7157.8826689605
18350
61049
Distance variable is not defined yet.
18351
63533
Distance variable is not defined yet.
18352
67039
Distance variable is not defined yet.
18353
65285
Distance variable is not defined yet.
18354
47842
Distance variable is not defined yet.
18355
47367
Distance variable is not defined yet.
18356
31630
Distance variable is not defined yet.
18357
53003
Distance variable is not defined yet.
18358
99113
Distance variable is not defined yet.
18359
19523
Distance variable is not defined yet.
18360
76518
Distance variable is not defined yet.
18361
50054
Distance variable is not defined yet.
18362
80644
Distance variable is not defined yet.
18363
28578
Distance variable is not defined yet.
18364
47536
Distance variable is not defined yet.
18365
21155
Distance variable is not defined yet.
18366
06612
Distance variable is not defined yet.
18367
62326
Distance variable is not defined yet.
18368
05474
Distance variable is not defined yet.
18369
96728
Distance variable is not defined yet.
18370
63044
Distance variable is not defined yet.
18371
14102
Distance variable is not defined yet.
18372
37846
Distance variable is not defined yet.
18373
92807
Distance
17769.472015663723
18374
26268
Distance variable is not defined yet.
18375
84604
Distance variable is not defined yet.
18376
72007
Distance variable is not defined yet.
18377
60540
Distance variable is not defined yet.
18378
31047
Distance variable is not defined yet.
18379
96765
Distance variable is not defined yet.
18380
06043
Distance variable is not defined yet.
18381
78608
Distance variable is not defined yet.
18382
29431
Distance variable is not defined yet.
18383
98266
Distance
17475.358151827266
18384
15937
Distance variable is not defined yet.
18385
49060
Distance variable is not defined yet.
18386
61569
Distance variable is not defined yet.
18387
40076
Distance variable is not defined yet.
18388
19810
Distance variable is not defined yet.
18389
54558
Distance variable is not defined yet.
18390
37394
Distance variable is not defined yet.
18391
29332
Distance variable is not defined yet.
18392
19504
Distance variable is not defined yet.
18393
43084
Distance variable is not defined yet.
18394
18445
Distance variable is not defined yet.
18395
33569
Distance variable is not defined yet.
18396
54180
Distance variable is not defined yet.
18397
27054
Distance variable is not defined yet.
18398
56461
Distance variable is not defined yet.
18399
36360
Distance variable is not defined yet.
18400
79536
Distance variable is not defined yet.
18401
24736
Distance variable is not defined yet.
18402
77091
Distance
16155.127020104359
18403
19061
Distance variable is not defined yet.
18404
30039
Distance variable is not defined yet.
18405
05858
Distance variable is not defined yet.
18406
08012
Distance variable is not defined yet.
18407
67579
Distance variable is not defined yet.
18408
46304
Distance variable is not defined yet.
18409
44805
Distance variable is not defined yet.
18410
73013
Distance variable is not defined yet.
18411
65559
Distance variable is not defined yet.
18412
84664
Distance
9334.563902229174
18413
99552
Distance variable is not defined yet.
18414
15936
Distance
17224.088429693133
18415
20818
Distance variable is not defined yet.
18416
15420
Distance variable is not defined yet.
18417
45122
Distance variable is not defined yet.
18418
51647
Distance variable is not defined yet.
18419
30547
Distance variable is not defined yet.
18420
03884
Distance variable is not defined yet.
18421
06456
Distance variable is not defined yet.
18422
34432
Distance variable is not defined yet.
18423
50603
Distance variable is not defined yet.
18424
21755
Distance variable is not defined yet.
18425
21050
Distance variable is not defined yet.
18426
45826
Distance variable is not defined yet.
18427
85326
Distance variable is not defined yet.
18428
64442
Distance variable is not defined yet.
18429
74964
Distance variable is not defined yet.
18430
46175
Distance variable is not defined yet.
18431
54984
Distance variable is not defined yet.
18432
29829
Distance variable is not defined yet.
18433
44506
Distance variable is not defined yet.
18434
53827
Distance variable is not defined yet.
18435
41660
Distance
13222.32550229479
18436
12168
Distance variable is not defined yet.
18437
13164
Distance variable is not defined yet.
18438
20778
Distance variable is not defined yet.
18439
97224
Distance variable is not defined yet.
18440
62514
Distance variable is not defined yet.
18441
98321
Distance variable is not defined yet.
18442
64428
Distance variable is not defined yet.
18443
13480
Distance variable is not defined yet.
18444
40162
Distance
13312.47384265467
18445
67205
Distance variable is not defined yet.
18446
07801
Distance variable is not defined yet.
18447
01519
Distance variable is not defined yet.
18448
46131
Distance variable is not defined yet.
18449
46342
Distance variable is not defined yet.
18450
50672
Distance variable is not defined yet.
18451
29576
Distance variable is not defined yet.
18452
55738
Distance variable is not defined yet.
18453
20132
Distance variable is not defined yet.
18454
92587
Distance variable is not defined yet.
18455
96090
Distance variable is not defined yet.
18456
03833
Distance variable is not defined yet.
18457
08083
Distance variable is not defined yet.
18458
53070
Distance variable is not defined yet.
18459
15756
Distance variable is not defined yet.
18460
33857
Distance variable is not defined yet.
18461
43760
Distance variable is not defined yet.
18462
04046
Distance variable is not defined yet.
18463
07436
Distance variable is not defined yet.
18464
49611
Distance variable is not defined yet.
18465
47932
Distance variable is not defined yet.
18466
07842
Distance variable is not defined yet.
18467
31833
Distance variable is not defined yet.
18468
19348
Distance
17691.565838413546
18469
74945
Distance variable is not defined yet.
18470
56654
Distance variable is not defined yet.
18471
60503
Distance variable is not defined yet.
18472
94116
Distance
15508.178092619397
18473
45884
Distance variable is not defined yet.
18474
04674
Distance variable is not defined yet.
18475
29487
Distance variable is not defined yet.
18476
80645
Distance variable is not defined yet.
18477
01922
Distance variable is not defined yet.
18478
77035
Distance
10467.113164705346
18479
24801
Distance variable is not defined yet.
18480
61877
Distance variable is not defined yet.
18481
13123
Distance variable is not defined yet.
18482
37029
Distance variable is not defined yet.
18483
56216
Distance variable is not defined yet.
18484
73664
Distance variable is not defined yet.
18485
66027
Distance
311.152388743803
18486
49753
Distance variable is not defined yet.
18487
66216
Distance variable is not defined yet.
18488
64131
Distance
13130.362181855344
18489
95949
Distance
16900.897182071592
18490
16145
Distance variable is not defined yet.
18491
78828
Distance variable is not defined yet.
18492
10708
Distance variable is not defined yet.
18493
56046
Distance
17653.78784597275
18494
65215
Distance variable is not defined yet.
18495
37719
Distance variable is not defined yet.
18496
44606
Distance variable is not defined yet.
18497
23085
Distance variable is not defined yet.
18498
81422
Distance variable is not defined yet.
18499
11777
Distance
17644.367664196663
18500
56577
Distance variable is not defined yet.
18501
15634
Distance variable is not defined yet.
18502
22738
Distance variable is not defined yet.
18503
35071
Distance variable is not defined yet.
18504
70463
Distance variable is not defined yet.
18505
58311
Distance variable is not defined yet.
18506
15868
Distance variable is not defined yet.
18507
24729
Distance variable is not defined yet.
18508
15943
Distance variable is not defined yet.
18509
43356
Distance variable is not defined yet.
18510
55126
Distance
8994.819019793353
18511
72769
Distance variable is not defined yet.
18512
38947
Distance
17443.44112304611
18513
99023
Distance variable is not defined yet.
18514
63826
Distance variable is not defined yet.
18515
13614
Distance
7865.05158511748
18516
78104
Distance variable is not defined yet.
18517
12570
Distance
11208.306615439302
18518
29910
Distance variable is not defined yet.
18519
59851
Distance variable is not defined yet.
18520
13036
Distance variable is not defined yet.
18521
56047
Distance variable is not defined yet.
18522
93314
Distance variable is not defined yet.
18523
78614
Distance variable is not defined yet.
18524
74051
Distance variable is not defined yet.
18525
28467
Distance variable is not defined yet.
18526
28326
Distance
17619.33070750069
18527
94575
Distance
17430.10067720085
18528
24460
Distance variable is not defined yet.
18529
33109
Distance variable is not defined yet.
18530
65335
Distance variable is not defined yet.
18531
28651
Distance variable is not defined yet.
18532
95337
Distance variable is not defined yet.
18533
13078
Distance variable is not defined yet.
18534
46793
Distance variable is not defined yet.
18535
84306
Distance variable is not defined yet.
18536
53522
Distance variable is not defined yet.
18537
47923
Distance variable is not defined yet.
18538
38451
Distance variable is not defined yet.
18539
28395
Distance
17603.12853940169
18540
25932
Distance variable is not defined yet.
18541
68437
Distance variable is not defined yet.
18542
48860
Distance variable is not defined yet.
18543
49715
Distance variable is not defined yet.
18544
66781
Distance variable is not defined yet.
18545
93465
Distance variable is not defined yet.
18546
12918
Distance
12573.407187545716
18547
89883
Distance variable is not defined yet.
18548
49629
Distance variable is not defined yet.
18549
15750
Distance variable is not defined yet.
18550
94720
Distance
11454.666085695782
18551
60659
Distance
16295.064918728931
18552
12060
Distance variable is not defined yet.
18553
48101
Distance variable is not defined yet.
18554
95232
Distance variable is not defined yet.
18555
49083
Distance variable is not defined yet.
18556
63352
Distance variable is not defined yet.
18557
52623
Distance variable is not defined yet.
18558
73564
Distance variable is not defined yet.
18559
97118
Distance variable is not defined yet.
18560
14560
Distance variable is not defined yet.
18561
45838
Distance variable is not defined yet.
18562
01886
Distance
13276.743225884586
18563
70809
Distance variable is not defined yet.
18564
07420
Distance variable is not defined yet.
18565
50116
Distance variable is not defined yet.
18566
15729
Distance variable is not defined yet.
18567
45333
Distance variable is not defined yet.
18568
72823
Distance variable is not defined yet.
18569
33954
Distance variable is not defined yet.
18570
69201
Distance variable is not defined yet.
18571
37376
Distance variable is not defined yet.
18572
30273
Distance variable is not defined yet.
18573
36475
Distance variable is not defined yet.
18574
15081
Distance variable is not defined yet.
18575
71427
Distance variable is not defined yet.
18576
37142
Distance variable is not defined yet.
18577
49272
Distance variable is not defined yet.
18578
26254
Distance variable is not defined yet.
18579
21851
Distance variable is not defined yet.
18580
94963
Distance variable is not defined yet.
18581
01035
Distance variable is not defined yet.
18582
72568
Distance variable is not defined yet.
18583
83540
Distance variable is not defined yet.
18584
78622
Distance variable is not defined yet.
18585
21044
Distance variable is not defined yet.
18586
54450
Distance variable is not defined yet.
18587
55312
Distance variable is not defined yet.
18588
30188
Distance
17550.105941870937
18589
55449
Distance
3643.319687371473
18590
43147
Distance variable is not defined yet.
18591
53554
Distance variable is not defined yet.
18592
57359
Distance variable is not defined yet.
18593
15005
Distance variable is not defined yet.
18594
48223
Distance variable is not defined yet.
18595
07642
Distance variable is not defined yet.
18596
23937
Distance variable is not defined yet.
18597
61252
Distance variable is not defined yet.
18598
52064
Distance variable is not defined yet.
18599
40391
Distance variable is not defined yet.
18600
29834
Distance variable is not defined yet.
18601
03087
Distance
17526.440543429424
18602
11596
Distance variable is not defined yet.
18603
42202
Distance variable is not defined yet.
18604
49228
Distance variable is not defined yet.
18605
67734
Distance variable is not defined yet.
18606
23128
Distance variable is not defined yet.
18607
03844
Distance variable is not defined yet.
18608
37849
Distance variable is not defined yet.
18609
60614
Distance
7540.0702967797715
18610
43778
Distance variable is not defined yet.
18611
95317
Distance variable is not defined yet.
18612
65567
Distance variable is not defined yet.
18613
08620
Distance
17518.422241421034
18614
38305
Distance variable is not defined yet.
18615
76666
Distance variable is not defined yet.
18616
73014
Distance variable is not defined yet.
18617
18240
Distance
10766.295551911004
18618
80442
Distance variable is not defined yet.
18619
50703
Distance variable is not defined yet.
18620
38361
Distance variable is not defined yet.
18621
92066
Distance variable is not defined yet.
18622
73059
Distance variable is not defined yet.
18623
22039
Distance
12312.209546020988
18624
28040
Distance variable is not defined yet.
18625
15639
Distance variable is not defined yet.
18626
02019
Distance variable is not defined yet.
18627
21532
Distance variable is not defined yet.
18628
43113
Distance variable is not defined yet.
18629
73622
Distance variable is not defined yet.
18630
17010

Warning: Cannot load hourly/2021/KDNK0.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/KDNK0.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/KDNK0.csv.gz from https://bulk.meteostat.net/v2/

Distance
12012.944218647157
21676
33181
Distance
13282.231671568086
21677
21085
Distance variable is not defined yet.
21678
11778
Distance variable is not defined yet.
21679
05871
Distance variable is not defined yet.
21680
80926
Distance
12671.495403739398
21681
54814
Distance variable is not defined yet.
21682
54826
Distance variable is not defined yet.
21683
78573
Distance variable is not defined yet.
21684
61319
Distance variable is not defined yet.
21685
17554
Distance variable is not defined yet.
21686
01238
Distance variable is not defined yet.
21687
47905
Distance variable is not defined yet.
21688
34737
Distance variable is not defined yet.
21689
01237
Distance variable is not defined yet.
21690
96822

Warning: Cannot load hourly/2021/91180.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/91180.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/91180.csv.gz from https://bulk.meteostat.net/v2/

Distance
14493.0500901776
21691
66207
Distance
14394.646635263854
21692
82510
Distance variable is not defined yet.
21693
29745
Distance variable is not defined yet.
21694
71282
Distance variable is not defined yet.
21695
78659
Distance variable is not defined yet.
21696
05440
Distance variable is not defined yet.
21697
75682
Distance variable is not defined yet.
21698
18078
Distance variable is not defined yet.
21699
08880
Distance variable is not defined yet.
21700
11040
Distance variable is not defined yet.
21701
08035
Distance variable is not defined yet.
21702
50830
Distance variable is not defined yet.
21703
30438
Distance variable is not defined yet.
21704
28510
Distance
14474.149155287445
21705
12784
Distance variable is not defined yet.
21706
78935
Distance
9907.954806718366
21707
62085
Distance variable is not defined yet.
21708
61802
Distance variable is not defined yet.
21709
97008
Distance variable is not defined yet.
21710
56629
Distance variable is not defined yet.
21711
48628
Distance variable is not defined yet.
21712
98262
Distance variable is not defined yet.
21713
76686
Distance variable is not defined yet.
21714
66518
Distance variable is not defined yet.
21715
15227
Distance
4751.3636526802775
21716
23867
Distance variable is not defined yet.
21717
47369
Distance variable is not defined yet.
21718
23108
Distance variable is not defined yet.
21719
36316
Distance variable is not defined yet.
21720
23230
Distance variable is not defined yet.
21721
75104
Distance
14454.502698163953
21722
68022
Distance
10948.196619314887
21723
33909
Distance variable is not defined yet.
21724
10471
Distance variable is not defined yet.
21725
54557
Distance variable is not defined yet.
21726
49509
Distance variable is not defined yet.
21727
45863
Distance variable is not defined yet.
21728
64029
Distance variable is not defined yet.
21729
89122
Distance variable is not defined yet.
21730
01876
Distance variable is not defined yet.
21731
07422
Distance variable is not defined yet.
21732
88338
Distance variable is not defined yet.
21733
07764
Distance variable is not defined yet.
21734
22737
Distance variable is not defined yet.
21735
55341
Distance variable is not defined yet.
21736
75493
Distance variable is not defined yet.
21737
31808
Distance variable is not defined yet.
21738
07107
Distance variable is not defined yet.
21739
35187
Distance variable is not defined yet.
21740
78726
Distance variable is not defined yet.
21741
49733
Distance
12084.143603453833
21742
52359
Distance variable is not defined yet.
21743
19122
Distance variable is not defined yet.
21744
85742
Distance variable is not defined yet.
21745
78749
Distance variable is not defined yet.
21746
52773
Distance variable is not defined yet.
21747
96107
Distance variable is not defined yet.
21748
44702
Distance variable is not defined yet.
21749
55410
Distance variable is not defined yet.
21750
04450
Distance variable is not defined yet.
21751
08029
Distance variable is not defined yet.
21752
72005
Distance variable is not defined yet.
21753
37732
Distance variable is not defined yet.
21754
39743
Distance variable is not defined yet.
21755
50567
Distance variable is not defined yet.
21756
79912
Distance variable is not defined yet.
21757
72951
Distance variable is not defined yet.
21758
25882
Distance variable is not defined yet.
21759
77482
Distance variable is not defined yet.
21760
16029
Distance variable is not defined yet.
21761
92014
Distance variable is not defined yet.
21762
30815
Distance variable is not defined yet.
21763
59256
Distance variable is not defined yet.
21764
11005
Distance variable is not defined yet.
21765
41101
Distance
12155.868160096301
21766
75460
Distance variable is not defined yet.
21767
02338
Distance variable is not defined yet.
21768
75662
Distance variable is not defined yet.
21769
89705
Distance variable is not defined yet.
21770
55408
Distance variable is not defined yet.
21771
30646
Distance variable is not defined yet.
21772
60606
Distance
3523.9672833542268
21773
29712
Distance variable is not defined yet.
21774
48219
Distance variable is not defined yet.
21775
01262
Distance variable is not defined yet.
21776
53577
Distance variable is not defined yet.
21777
43206
Distance variable is not defined yet.
21778
07102
Distance
14394.878264273506
21779
84065
Distance variable is not defined yet.
21780
34479
Distance variable is not defined yet.
21781
02465
Distance variable is not defined yet.
21782
54136
Distance variable is not defined yet.
21783
48827
Distance variable is not defined yet.
21784
11556
Distance variable is not defined yet.
21785
17857
Distance variable is not defined yet.
21786
48049
Distance variable is not defined yet.
21787
64620
Distance variable is not defined yet.
21788
13667
Distance variable is not defined yet.
21789
60622
Distance
7976.3149252173935
21790
02723
Distance variable is not defined yet.
21791
18055
Distance variable is not defined yet.
21792
11697
Distance variable is not defined yet.
21793
15101
Distance variable is not defined yet.
21794
63115
Distance variable is not defined yet.
21795
47941
Distance variable is not defined yet.
21796
76120
Distance
13255.424592097621
21797
73074
Distance variable is not defined yet.
21798
37852
Distance variable is not defined yet.
21799
37861
Distance variable is not defined yet.
21800
33596
Distance variable is not defined yet.
21801
11792
Distance variable is not defined yet.
21802
40865
Distance variable is not defined yet.
21803
98366
Distance variable is not defined yet.
21804
60077
Distance variable is not defined yet.
21805
98353
Distance variable is not defined yet.
21806
14543
Distance variable is not defined yet.
21807
37350
Distance variable is not defined yet.
21808
72170
Distance variable is not defined yet.
21809
32631
Distance variable is not defined yet.
21810
20895
Distance variable is not defined yet.
21811
29640
Distance variable is not defined yet.
21812
91320
Distance variable is not defined yet.
21813
54467
Distance variable is not defined yet.
21814
20866
Distance variable is not defined yet.
21815
14005
Distance variable is not defined yet.
21816
11358
Distance variable is not defined yet.
21817
48708
Distance variable is not defined yet.
21818
60519
Distance variable is not defined yet.
21819
46763
Distance variable is not defined yet.
21820
83452
Distance variable is not defined yet.
21821
47138
Distance variable is not defined yet.
21822
68029
Distance variable is not defined yet.
21823
92067
Distance variable is not defined yet.
21824
02461
Distance
13452.30076059417
21825
94516
Distance variable is not defined yet.
21826
05829
Distance
10411.652111925929
21827
97437
Distance variable is not defined yet.
21828
89508
Distance variable is not defined yet.
21829
30205
Distance variable is not defined yet.
21830
19456
Distance variable is not defined yet.
21831
38235
Distance variable is not defined yet.
21832
33881
Distance variable is not defined yet.
21833
56089
Distance variable is not defined yet.
21834
44288
Distance variable is not defined yet.
21835
97018
Distance variable is not defined yet.
21836
85617
Distance variable is not defined yet.
21837
02457
Distance variable is not defined yet.
21838
52403
Distance variable is not defined yet.
21839
13782
Distance variable is not defined yet.
21840
28385
Distance variable is not defined yet.
21841
33137
Distance variable is not defined yet.
21842
12010
Distance variable is not defined yet.
21843
86047
Distance variable is not defined yet.
21844
75849
Distance variable is not defined yet.
21845
14756
Distance variable is not defined yet.
21846
46741
Distance variable is not defined yet.
21847
62932
Distance variable is not defined yet.
21848
71110
Distance variable is not defined yet.
21849
79922
Distance variable is not defined yet.
21850
16847
Distance variable is not defined yet.
21851
61743
Distance variable is not defined yet.
21852
02045
Distance variable is not defined yet.
21853
75468
Distance variable is not defined yet.
21854
75048
Distance variable is not defined yet.
21855
08043
Distance variable is not defined yet.
21856
13490
Distance
5653.420685673949
21857
58104
Distance variable is not defined yet.
21858
55434
Distance
4101.097535839374
21859
12528
Distance variable is not defined yet.
21860
55325
Distance variable is not defined yet.
21861
12827
Distance variable is not defined yet.
21862
07728
Distance variable is not defined yet.
21863
07460
Distance variable is not defined yet.
21864
26541
Distance variable is not defined yet.
21865
15564
Distance variable is not defined yet.
21866
71956
Distance variable is not defined yet.
21867
49097
Distance variable is not defined yet.
21868
07827
Distance variable is not defined yet.
21869
07018
Distance variable is not defined yet.
21870
85350
Distance
14083.232524641742
21871
45779
Distance variable is not defined yet.
21872
43320
Distance variable is not defined yet.
21873
36116
Distance variable is not defined yet.
21874
43439
Distance variable is not defined yet.
21875
08837
Distance variable is not defined yet.
21876
37143
Distance variable is not defined yet.
21877
86046
Distance variable is not defined yet.
21878
59411
Distance variable is not defined yet.
21879
85021
Distance variable is not defined yet.
21880
98851
Distance variable is not defined yet.
21881
60172
Distance
1435.671388491508
21882
18942
Distance variable is not defined yet.
21883
44816
Distance variable is not defined yet.
21884
20197
Distance variable is not defined yet.
21885
24314
Distance variable is not defined yet.
21886
34480
Distance variable is not defined yet.
21887
28211
Distance variable is not defined yet.
21888
49271
Distance variable is not defined yet.
21889
54151
Distance variable is not defined yet.
21890
55420
Distance variable is not defined yet.
21891
80210
Distance variable is not defined yet.
21892
33331
Distance variable is not defined yet.
21893
33132
Distance variable is not defined yet.
21894
19055
Distance variable is not defined yet.
21895
27614
Distance variable is not defined yet.
21896
30452
Distance variable is not defined yet.
21897
21035
Distance variable is not defined yet.
21898
06901
Distance variable is not defined yet.
21899
71945
Distance variable is not defined yet.
21900
02466
Distance variable is not defined yet.
21901
63853
Distance variable is not defined yet.
21902
18660
Distance variable is not defined yet.
21903
47025
Distance variable is not defined yet.
21904
35208
Distance variable is not defined yet.
21905
48186
Distance variable is not defined yet.
21906
98671
Distance variable is not defined yet.
21907
13685
Distance variable is not defined yet.
21908
56590
Distance variable is not defined yet.
21909
49009
Distance variable is not defined yet.
21910
95448
Distance variable is not defined yet.
21911
19087
Distance variable is not defined yet.
21912
98229
Distance variable is not defined yet.
21913
48170
Distance variable is not defined yet.
21914
98422
Distance variable is not defined yet.
21915
44710
Distance variable is not defined yet.
21916
22624
Distance variable is not defined yet.
21917
70583
Distance variable is not defined yet.
21918
83328
Distance variable is not defined yet.
21919
18426
Distance variable is not defined yet.
21920
56723
Distance variable is not defined yet.
21921
22729
Distance variable is not defined yet.
21922
32073
Distance
9488.241796468483
21923
10469
Distance variable is not defined yet.
21924
47030
Distance variable is not defined yet.
21925
43032
Distance variable is not defined yet.
21926
61539
Distance variable is not defined yet.
21927
05350
Distance variable is not defined yet.
21928
83845
Distance variable is not defined yet.
21929
24087
Distance variable is not defined yet.
21930
48455
Distance variable is not defined yet.
21931
05055
Distance variable is not defined yet.
21932
76513
Distance variable is not defined yet.
21933
65355
Distance variable is not defined yet.
21934
77050
Distance variable is not defined yet.
21935
75050
Distance
5797.882034254436
21936
42069
Distance variable is not defined yet.
21937
54011
Distance variable is not defined yet.
21938
16142
Distance variable is not defined yet.
21939
12078
Distance variable is not defined yet.
21940
76054
Distance
11771.914437606101
21941
12913
Distance variable is not defined yet.
21942
78343
Distance variable is not defined yet.
21943
55771
Distance variable is not defined yet.
21944
18056
Distance variable is not defined yet.
21945
64078
Distance variable is not defined yet.
21946
60605
Distance
1642.1310918857487
21947
50658
Distance variable is not defined yet.
21948
28043
Distance variable is not defined yet.
21949
51248
Distance variable is not defined yet.
21950
52229
Distance variable is not defined yet.
21951
23357
Distance variable is not defined yet.
21952
30628
Distance variable is not defined yet.
21953
06330
Distance variable is not defined yet.
21954
25555
Distance variable is not defined yet.
21955
84021
Distance variable is not defined yet.
21956
49774
Distance variable is not defined yet.
21957
80603
Distance variable is not defined yet.
21958
22185
Distance variable is not defined yet.
21959
45388
Distance variable is not defined yet.
21960
37306
Distance variable is not defined yet.
21961
07630
Distance variable is not defined yet.
21962
67037
Distance variable is not defined yet.
21963
30088
Distance variable is not defined yet.
21964
08690
Distance variable is not defined yet.
21965
80908
Distance variable is not defined yet.
21966
36549
Distance variable is not defined yet.
21967
50645
Distance variable is not defined yet.
21968
32666
Distance variable is not defined yet.
21969
84075
Distance
10380.84276820975
21970
38945
Distance variable is not defined yet.
21971
75686
Distance variable is not defined yet.
21972
06357
Distance variable is not defined yet.
21973
08316
Distance variable is not defined yet.
21974
24078
Distance variable is not defined yet.
21975
60466
Distance variable is not defined yet.
21976
44039
Distance variable is not defined yet.
21977
53529
Distance variable is not defined yet.
21978
80204
Distance variable is not defined yet.
21979
81521
Distance variable is not defined yet.
21980
68774
Distance variable is not defined yet.
21981
28394
Distance variable is not defined yet.
21982
23148
Distance variable is not defined yet.
21983
22657
Distance variable is not defined yet.
21984
73111
Distance variable is not defined yet.
21985
12976
Distance variable is not defined yet.
21986
87305
Distance variable is not defined yet.
21987
08844
Distance variable is not defined yet.
21988
51044
Distance variable is not defined yet.
21989
22726
Distance variable is not defined yet.
21990
41739
Distance variable is not defined yet.
21991
34446
Distance variable is not defined yet.
21992
23691
Distance variable is not defined yet.
21993
23845
Distance variable is not defined yet.
21994
54111
Distance variable is not defined yet.
21995
97068
Distance variable is not defined yet.
21996
06705
Distance variable is not defined yet.
21997
92570
Distance
14170.586431748969
21998
37357
Distance variable is not defined yet.
21999
94618
Distance
9608.871703324648
22000
44510
Distance variable is not defined yet.
22001
33744
Distance variable is not defined yet.
22002
67074
Distance variable is not defined yet.
22003
51573
Distance variable is not defined yet.
22004
92372
Distance variable is not defined yet.
22005
28088
Distance variable is not defined yet.
22006
97089
Distance variable is not defined yet.
22007
60139
Distance
8017.010153990793
22008
45886
Distance variable is not defined yet.
22009
55318
Distance variable is not defined yet.
22010
81503
Distance variable is not defined yet.
22011
55354
Distance variable is not defined yet.
22012
20658
Distance variable is not defined yet.
22013
02885
Distance variable is not defined yet.
22014
47429
Distance variable is not defined yet.
22015
07442
Distance variable is not defined yet.
22016
16052
Distance variable is not defined yet.
22017
12977
Distance variable is not defined yet.
22018
66412
Distance variable is not defined yet.
22019
60061
Distance variable is not defined yet.
22020
24055
Distance variable is not defined yet.
22021
23866
Distance variable is not defined yet.
22022
27713
Distance variable is not defined yet.
22023
60661
Distance
4074.2080166497926
22024
78664
Distance variable is not defined yet.
22025
52727
Distance variable is not defined yet.
22026
54475
Distance variable is not defined yet.
22027
66208
Distance variable is not defined yet.
22028
22042
Distance variable is not defined yet.
22029
50432
Distance variable is not defined yet.
22030
84093
Distance variable is not defined yet.
22031
02464
Distance
13637.842500683224
22032
95372
Distance variable is not defined yet.
22033
40013
Distance variable is not defined yet.
22034
97535
Distance variable is not defined yet.
22035
02184
Distance
9537.243033032548
22036
48856
Distance variable is not defined yet.
22037
19733
Distance variable is not defined yet.
22038
22940
Distance variable is not defined yet.
22039
41080
Distance variable is not defined yet.
22040
07079
Distance variable is not defined yet.
22041
80129
Distance variable is not defined yet.
22042
32955
Distance
14132.604780228201
22043
08210
Distance variable is not defined yet.
22044
84117
Distance variable is not defined yet.
22045
84734
Distance variable is not defined yet.
22046
44505
Distance variable is not defined yet.
22047
08016
Distance variable is not defined yet.
22048
65616
Distance variable is not defined yet.
22049
76638
Distance variable is not defined yet.
22050
70454
Distance variable is not defined yet.
22051
32763
Distance variable is not defined yet.
22052
43611
Distance variable is not defined yet.
22053
21043
Distance variable is not defined yet.
22054
45241
Distance variable is not defined yet.
22055
45344
Distance
14122.642890583194
22056
79025
Distance variable is not defined yet.
22057
98240

Warning: Cannot load hourly/2021/71594.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/71594.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/71594.csv.gz from https://bulk.meteostat.net/v2/

Distance
14121.560962637077
22058
49277
Distance variable is not defined yet.
22059
78670
Distance variable is not defined yet.
22060
56481
Distance variable is not defined yet.
22061
06350
Distance variable is not defined yet.
22062
02458
Distance variable is not defined yet.
22063
29207
Distance variable is not defined yet.
22064
19438
Distance variable is not defined yet.
22065
16828
Distance variable is not defined yet.
22066
23181
Distance variable is not defined yet.
22067
16665
Distance variable is not defined yet.
22068
34209
Distance variable is not defined yet.
22069
28205
Distance variable is not defined yet.
22070
30317
Distance variable is not defined yet.
22071
52621
Distance variable is not defined yet.
22072
24375
Distance variable is not defined yet.
22073
07103
Distance variable is not defined yet.
22074
65793
Distance variable is not defined yet.
22075
52649
Distance variable is not defined yet.
22076
62628
Distance variable is not defined yet.
22077
51554
Distance variable is not defined yet.
22078
12540
Distance
4208.342052498377
22079
44504
Distance variable is not defined yet.
22080
19735
Distance variable is not defined yet.
22081
28018
Distance variable is not defined yet.
22082
62226
Distance
13198.15917636768
22083
97137
Distance variable is not defined yet.
22084
33543
Distance variable is not defined yet.
22085
71438
Distance variable is not defined yet.
22086
48322
Distance variable is not defined yet.
22087
24148
Distance variable is not defined yet.
22088
21074
Distance variable is not defined yet.
22089
74441
Distance variable is not defined yet.
22090
34119
Distance variable is not defined yet.
22091
19004
Distance variable is not defined yet.
22092
70510
Distance variable is not defined yet.
22093
02916
Distance variable is not defined yet.
22094
38504
Distance variable is not defined yet.
22095
58835
Distance variable is not defined yet.
22096
80538
Distance variable is not defined yet.
22097
89448
Distance variable is not defined yet.
22098
56387
Distance variable is not defined yet.
22099
16146
Distance variable is not defined yet.
22100
97140
Distance variable is not defined yet.
22101
36305
Distance variable is not defined yet.
22102
27950
Distance variable is not defined yet.
22103
49701
Distance variable is not defined yet.
22104
47802
Distance variable is not defined yet.
22105
30025
Distance variable is not defined yet.
22106
02671
Distance
11996.709718882299
22107
38326
Distance variable is not defined yet.
22108
14617
Distance variable is not defined yet.
22109
98635
Distance variable is not defined yet.
22110
50434
Distance variable is not defined yet.
22111
20165
Distance variable is not defined yet.
22112
15061
Distance variable is not defined yet.
22113
94946
Distance variable is not defined yet.
22114
94608
Distance
6456.5560009318415
22115
83451
Distance variable is not defined yet.
22116
32209
Distance variable is not defined yet.
22117
23438
Distance variable is not defined yet.
22118
84738
Distance variable is not defined yet.
22119
49945
Distance variable is not defined yet.
22120
33838
Distance variable is not defined yet.
22121
88026
Distance variable is not defined yet.
22122
04684
Distance variable is not defined yet.
22123
95407
Distance variable is not defined yet.
22124
86018
Distance variable is not defined yet.
22125
18248
Distance variable is not defined yet.
22126
83113
Distance variable is not defined yet.
22127
73951
Distance variable is not defined yet.
22128
81424
Distance variable is not defined yet.
22129
48627
Distance variable is not defined yet.
22130
38601
Distance variable is not defined yet.
22131
68327
Distance variable is not defined yet.
22132
30312
Distance variable is not defined yet.
22133
29324
Distance variable is not defined yet.
22134
53808
Distance variable is not defined yet.
22135
29316
Distance variable is not defined yet.
22136
63138
Distance variable is not defined yet.
22137
12569
Distance
5657.263239143805
22138
70803
Distance variable is not defined yet.
22139
47950
Distance variable is not defined yet.
22140
28078
Distance variable is not defined yet.
22141
60045
Distance variable is not defined yet.
22142
75954
Distance variable is not defined yet.
22143
38231
Distance variable is not defined yet.
22144
01864
Distance variable is not defined yet.
22145
61372
Distance variable is not defined yet.
22146
45896
Distance variable is not defined yet.
22147
95382
Distance variable is not defined yet.
22148
41729
Distance
14038.339789290156
22149
22611
Distance variable is not defined yet.
22150
22030
Distance variable is not defined yet.
22151
79329
Distance variable is not defined yet.
22152
80530
Distance variable is not defined yet.
22153
05656
Distance variable is not defined yet.
22154
23089
Distance variable is not defined yet.
22155
93725
Distance variable is not defined yet.
22156
47992
Distance variable is not defined yet.
22157
80634
Distance variable is not defined yet.
22158
55362
Distance variable is not defined yet.
22159
15315
Distance variable is not defined yet.
22160
18031
Distance variable is not defined yet.
22161
55450
Distance variable is not defined yet.
22162
40117
Distance variable is not defined yet.
22163
01007
Distance variable is not defined yet.
22164
53570
Distance variable is not defined yet.
22165
29671
Distance variable is not defined yet.
22166
97103
Distance variable is not defined yet.
22167
15616
Distance variable is not defined yet.
22168
23062
Distance variable is not defined yet.
22169
98380
Distance variable is not defined yet.
22170
48014
Distance variable is not defined yet.
22171
30421
Distance variable is not defined yet.
22172
79412
Distance variable is not defined yet.
22173
39479
Distance variable is not defined yet.
22174
60564
Distance variable is not defined yet.
22175
77530
Distance variable is not defined yet.
22176
75410
Distance variable is not defined yet.
22177
35904
Distance variable is not defined yet.
22178
60463
Distance variable is not defined yet.
22179
53012
Distance variable is not defined yet.
22180
51014
Distance variable is not defined yet.
22181
17027
Distance variable is not defined yet.
22182
38544
Distance variable is not defined yet.
22183
61230
Distance variable is not defined yet.
22184
17033
Distance variable is not defined yet.
22185
95640
Distance variable is not defined yet.
22186
43146
Distance variable is not defined yet.
22187
56475
Distance variable is not defined yet.
22188
68514
Distance variable is not defined yet.
22189
32311
Distance variable is not defined yet.
22190
74753
Distance variable is not defined yet.
22191
19083
Distance variable is not defined yet.
22192
12151
Distance variable is not defined yet.
22193
61872
Distance variable is not defined yet.
22194
28520
Distance variable is not defined yet.
22195
02760
Distance variable is not defined yet.
22196
04917
Distance variable is not defined yet.
22197
72327
Distance variable is not defined yet.
22198
05904
Distance variable is not defined yet.
22199
35082
Distance variable is not defined yet.
22200
55331
Distance variable is not defined yet.
22201
27964
Distance variable is not defined yet.
22202
23149
Distance variable is not defined yet.
22203
80120
Distance variable is not defined yet.
22204
78732
Distance variable is not defined yet.
22205
75218
Distance variable is not defined yet.
22206
50522
Distance variable is not defined yet.
22207
84414
Distance variable is not defined yet.
22208
53092
Distance variable is not defined yet.
22209
06905
Distance variable is not defined yet.
22210
38664
Distance variable is not defined yet.
22211
93551
Distance variable is not defined yet.
22212
53533
Distance variable is not defined yet.
22213
61931
Distance variable is not defined yet.
22214
46552
Distance variable is not defined yet.
22215
83669
Distance variable is not defined yet.
22216
22948
Distance variable is not defined yet.
22217
42503
Distance variable is not defined yet.
22218
02641
Distance variable is not defined yet.
22219
56543
Distance variable is not defined yet.
22220
50438
Distance variable is not defined yet.
22221
25836
Distance variable is not defined yet.
22222
97325
Distance variable is not defined yet.
22223
32824
Distance variable is not defined yet.
22224
01080
Distance variable is not defined yet.
22225
52212
Distance variable is not defined yet.
22226
91311
Distance
9601.544864518512
22227
37737
Distance variable is not defined yet.
22228
54974
Distance variable is not defined yet.
22229
33545
Distance variable is not defined yet.
22230
50327
Distance variable is not defined yet.
22231
54636
Distance variable is not defined yet.
22232
24323
Distance variable is not defined yet.
22233
48157
Distance variable is not defined yet.
22234
56332
Distance variable is not defined yet.
22235
95207
Distance variable is not defined yet.
22236
75601
Distance variable is not defined yet.
22237
15732
Distance variable is not defined yet.
22238
77583
Distance variable is not defined yet.
22239
55363
Distance variable is not defined yet.
22240
27872
Distance variable is not defined yet.
22241
65260
Distance variable is not defined yet.
22242
04102
Distance variable is not defined yet.
22243
63341
Distance variable is not defined yet.
22244
14715
Distance variable is not defined yet.
22245
90241
Distance variable is not defined yet.
22246
38105
Distance variable is not defined yet.
22247
52802
Distance variable is not defined yet.
22248
62425
Distance variable is not defined yet.
22249
11566
Distance variable is not defined yet.
22250
55328
Distance variable is not defined yet.
22251
61373
Distance variable is not defined yet.
22252
11362
Distance variable is not defined yet.
22253
27858
Distance variable is not defined yet.
22254
95624
Distance variable is not defined yet.
22255
72210
Distance variable is not defined yet.
22256
96128
Distance variable is not defined yet.
22257
34229
Distance variable is not defined yet.
22258
30078
Distance variable is not defined yet.
22259
58769
Distance variable is not defined yet.
22260
66013
Distance variable is not defined yet.
22261
02459
Distance
12547.270943699568
22262
19144
Distance variable is not defined yet.
22263
39342
Distance variable is not defined yet.
22264
78586
Distance variable is not defined yet.
22265
13308
Distance variable is not defined yet.
22266
31774
Distance variable is not defined yet.
22267
85202
Distance variable is not defined yet.
22268
48065
Distance variable is not defined yet.
22269
22844
Distance
4161.067988715055
22270
11776
Distance variable is not defined yet.
22271
06238
Distance variable is not defined yet.
22272
91321
Distance
7710.3361620899395
22273
48312
Distance variable is not defined yet.
22274
32563
Distance
13908.634316889482
22275
84720
Distance variable is not defined yet.
22276
92585
Distance variable is not defined yet.
22277
56533
Distance variable is not defined yet.
22278
15007
Distance variable is not defined yet.
22279
68339
Distance variable is not defined yet.
22280
29681
Distance variable is not defined yet.
22281
81654
Distance variable is not defined yet.
22282
63827
Distance variable is not defined yet.
22283
07439
Distance variable is not defined yet.
22284
43145
Distance variable is not defined yet.
22285
11590
Distance variable is not defined yet.
22286
39328
Distance variable is not defined yet.
22287
29053
Distance variable is not defined yet.
22288
46555
Distance variable is not defined yet.
22289
75401
Distance variable is not defined yet.
22290
34606
Distance variable is not defined yet.
22291
24401
Distance variable is not defined yet.
22292
20816
Distance variable is not defined yet.
22293
97305
Distance variable is not defined yet.
22294
40222
Distance variable is not defined yet.
22295
75238
Distance variable is not defined yet.
22296
78613
Distance variable is not defined yet.
22297
29329
Distance variable is not defined yet.
22298
96751
Distance variable is not defined yet.
22299
07106
Distance variable is not defined yet.
22300
70558
Distance variable is not defined yet.
22301
48657
Distance variable is not defined yet.
22302
10467
Distance variable is not defined yet.
22303
44878
Distance variable is not defined yet.
22304
59912
Distance variable is not defined yet.
22305
57601
Distance variable is not defined yet.
22306
46562
Distance variable is not defined yet.
22307
26257
Distance variable is not defined yet.
22308
77406
Distance variable is not defined yet.
22309
50232
Distance variable is not defined yet.
22310
05860
Distance variable is not defined yet.
22311
12750
Distance variable is not defined yet.
22312
28655
Distance variable is not defined yet.
22313
67552
Distance variable is not defined yet.
22314
61875
Distance variable is not defined yet.
22315
02061
Distance
9600.255880561497
22316
04355
Distance variable is not defined yet.
22317
12975
Distance variable is not defined yet.
22318
03865
Distance variable is not defined yet.
22319
78827
Distance variable is not defined yet.
22320
23436
Distance variable is not defined yet.
22321
08106
Distance variable is not defined yet.
22322
10590
Distance variable is not defined yet.
22323
55940
Distance variable is not defined yet.
22324
07506
Distance variable is not defined yet.
22325
49730
Distance variable is not defined yet.
22326
80108
Distance variable is not defined yet.
22327
21773
Distance variable is not defined yet.
22328
98021
Distance variable is not defined yet.
22329
95620
Distance
13853.08760457858
22330
85251
Distance variable is not defined yet.
22331
63021
Distance variable is not defined yet.
22332
04926
Distance variable is not defined yet.
22333
95714
Distance variable is not defined yet.
22334
77381
Distance variable is not defined yet.
22335
32110
Distance variable is not defined yet.
22336
48356
Distance variable is not defined yet.
22337
68033
Distance variable is not defined yet.
22338
66514
Distance variable is not defined yet.
22339
51231
Distance variable is not defined yet.
22340
07922
Distance variable is not defined yet.
22341
98235
Distance variable is not defined yet.
22342
55417
Distance variable is not defined yet.
22343
28091
Distance variable is not defined yet.
22344
50143
Distance variable is not defined yet.
22345
43035
Distance variable is not defined yet.
22346
98247
Distance
13839.48865126858
22347
35769
Distance variable is not defined yet.
22348
02894
Distance variable is not defined yet.
22349
25827
Distance variable is not defined yet.
22350
39480
Distance variable is not defined yet.
22351
22742
Distance variable is not defined yet.
22352
92385
Distance variable is not defined yet.
22353
51543
Distance variable is not defined yet.
22354
32212
Distance
1785.7678554676156
22355
87571
Distance variable is not defined yet.
22356
57057
Distance variable is not defined yet.
22357
40109
Distance variable is not defined yet.
22358
38029
Distance variable is not defined yet.
22359
25438
Distance variable is not defined yet.
22360
72571
Distance variable is not defined yet.
22361
06470
Distance variable is not defined yet.
22362
37180
Distance variable is not defined yet.
22363
19010
Distance variable is not defined yet.
22364
02858
Distance variable is not defined yet.
22365
56733
Distance variable is not defined yet.
22366
37181
Distance variable is not defined yet.
22367
75023
Distance variable is not defined yet.
22368
19140
Distance variable is not defined yet.
22369
35243
Distance variable is not defined yet.
22370
45350
Distance variable is not defined yet.
22371
75056
Distance variable is not defined yet.
22372
84321
Distance variable is not defined yet.
22373
19535
Distance variable is not defined yet.
22374
32750
Distance variable is not defined yet.
22375
61243
Distance variable is not defined yet.
22376
98850
Distance variable is not defined yet.
22377
44049
Distance variable is not defined yet.
22378
95234
Distance variable is not defined yet.
22379
62902
Distance variable is not defined yet.
22380
92240
Distance variable is not defined yet.
22381
49051
Distance variable is not defined yet.
22382
48875
Distance variable is not defined yet.
22383
32701
Distance variable is not defined yet.
22384
28114
Distance variable is not defined yet.
22385
44202
Distance variable is not defined yet.
22386
22181
Distance variable is not defined yet.
22387
68340
Distance variable is not defined yet.
22388
37818
Distance variable is not defined yet.
22389
19375
Distance variable is not defined yet.
22390
13646
Distance variable is not defined yet.
22391
84325
Distance variable is not defined yet.
22392
07828
Distance variable is not defined yet.
22393
47550
Distance variable is not defined yet.
22394
58573
Distance variable is not defined yet.
22395
14864
Distance variable is not defined yet.
22396
97391
Distance variable is not defined yet.
22397
14816
Distance variable is not defined yet.
22398
20640
Distance variable is not defined yet.
22399
91748
Distance variable is not defined yet.
22400
43066
Distance variable is not defined yet.
22401
24504
Distance variable is not defined yet.
22402
23970
Distance variable is not defined yet.
22403
50452
Distance variable is not defined yet.
22404
69151
Distance variable is not defined yet.
22405
30410
Distance variable is not defined yet.
22406
48140
Distance variable is not defined yet.
22407
28105
Distance variable is not defined yet.
22408
13053
Distance variable is not defined yet.
22409
48421
Distance variable is not defined yet.
22410
62352
Distance variable is not defined yet.
22411
39766
Distance variable is not defined yet.
22412
59802
Distance variable is not defined yet.
22413
65662
Distance variable is not defined yet.
22414
77613
Distance variable is not defined yet.
22415
01467
Distance
8895.731922547833
22416
22191
Distance
12705.037529766765
22417
16157
Distance variable is not defined yet.
22418
29147
Distance variable is not defined yet.
22419
03755
Distance variable is not defined yet.
22420
45426
Distance variable is not defined yet.
22421
33626
Distance variable is not defined yet.
22422
25913
Distance variable is not defined yet.
22423
90042
Distance variable is not defined yet.
22424
30582
Distance variable is not defined yet.
22425
60565
Distance variable is not defined yet.
22426
93730
Distance variable is not defined yet.
22427
38237
Distance variable is not defined yet.
22428
97221
Distance variable is not defined yet.
22429
18460
Distance variable is not defined yet.
22430
76105
Distance
12480.98789123908
22431
43033
Distance variable is not defined yet.
22432
98005
Distance variable is not defined yet.
22433
62036
Distance variable is not defined yet.
22434
33905
Distance variable is not defined yet.
22435
13622
Distance variable is not defined yet.
22436
16876
Distance variable is not defined yet.
22437
93943
Distance
6642.86786082735
22438
60154
Distance variable is not defined yet.
22439
45682
Distance variable is not defined yet.
22440
14747
Distance variable is not defined yet.
22441
75110
Distance variable is not defined yet.
22442
40464
Distance variable is not defined yet.
22443
32926
Distance variable is not defined yet.
22444
24301
Distance variable is not defined yet.
22445
18256
Distance variable is not defined yet.
22446
93536
Distance variable is not defined yet.
22447
11786
Distance variable is not defined yet.
22448
23838
Distance variable is not defined yet.
22449
18242
Distance variable is not defined yet.
22450
35956
Distance variable is not defined yet.
22451
67524
Distance variable is not defined yet.
22452
96792
Distance
4599.839939313284
22453
11706
Distance variable is not defined yet.
22454
48307
Distance variable is not defined yet.
22455
43011
Distance variable is not defined yet.
22456
03445
Distance variable is not defined yet.
22457
56470
Distance variable is not defined yet.
22458
08034
Distance variable is not defined yet.
22459
85284
Distance variable is not defined yet.
22460
27568
Distance variable is not defined yet.
22461
44203

Warning: Cannot load hourly/2021/5EBO4.csv.gz from https://bulk.meteostat.net/v2/

Distance
1221.7471071039838
22769
55721
Distance variable is not defined yet.
22770
28693
Distance variable is not defined yet.
22771
64155
Distance variable is not defined yet.
22772
61454
Distance variable is not defined yet.
22773
27827
Distance variable is not defined yet.
22774
19047
Distance variable is not defined yet.
22775
55305
Distance variable is not defined yet.
22776
86323
Distance variable is not defined yet.
22777
02826
Distance variable is not defined yet.
22778
37840
Distance
13419.672513611524
22779
22046
Distance variable is not defined yet.
22780
37909
Distance variable is not defined yet.
22781
33647
Distance variable is not defined yet.
22782
14054
Distance variable is not defined yet.
22783
29543
Distance variable is not defined yet.
22784
17022
Distance variable is not defined yet.
22785
58601
Distance variable is not defined yet.
22786
61611
Distance variable is not defined yet.
22787
19007
Distance variable is not defined yet.
22788
26818
Distance variable is not defined yet.
22789
33131
Distance variable is not defined yet.
22790
89523
Distance variable is not defined yet.
22791
78727
Distance variable is not defined yet.
22792
14871
Distance variable is not defined yet.
22793
85304
Distance variable is not defined yet.
22794
03853
Distance variable is not defined yet.
22795
34984
Distance variable is not defined yet.
22796
56284
Distance variable is not defined yet.
22797
11004
Distance variable is not defined yet.
22798
34223
Distance variable is not defined yet.
22799
15422
Distance variable is not defined yet.
22800
28409
Distance variable is not defined yet.
22801
45695
Distance variable is not defined yet.
22802
77454
Distance variable is not defined yet.
22803
16839
Distance variable is not defined yet.
22804
61322
Distance variable is not defined yet.
22805
44313
Distance variable is not defined yet.
22806
74060
Distance variable is not defined yet.
22807
06339
Distance variable is not defined yet.
22808
01226
Distance variable is not defined yet.
22809
46773
Distance variable is not defined yet.
22810
53035
Distance variable is not defined yet.
22811
28582
Distance variable is not defined yet.
22812
24167
Distance variable is not defined yet.
22813
29409
Distance
6046.465614520552
22814
52329
Distance variable is not defined yet.
22815
55397
Distance variable is not defined yet.
22816
33150
Distance
9966.438666314032
22817
92376
Distance variable is not defined yet.
22818
44026
Distance variable is not defined yet.
22819
30083
Distance variable is not defined yet.
22820
22308
Distance
11012.906805233015
22821
46405
Distance variable is not defined yet.
22822
14150
Distance variable is not defined yet.
22823
07452
Distance variable is not defined yet.
22824
62232
Distance variable is not defined yet.
22825
76109
Distance variable is not defined yet.
22826
94609
Distance
7305.947796263623
22827
80451
Distance variable is not defined yet.
22828
91205
Distance variable is not defined yet.
22829
85120
Distance variable is not defined yet.
22830
90077
Distance
9979.334709012583
22831
30619
Distance variable is not defined yet.
22832
88101
Distance variable is not defined yet.
22833
89178
Distance variable is not defined yet.
22834
11357
Distance variable is not defined yet.
22835
74421
Distance variable is not defined yet.
22836
72739
Distance variable is not defined yet.
22837
85283
Distance variable is not defined yet.
22838
28036
Distance variable is not defined yet.
22839
62535
Distance variable is not defined yet.
22840
65264
Distance variable is not defined yet.
22841
70426
Distance variable is not defined yet.
22842
82933
Distance variable is not defined yet.
22843
21813
Distance
12501.848990243698
22844
28312
Distance variable is not defined yet.
22845
14774
Distance variable is not defined yet.
22846
36467
Distance variable is not defined yet.
22847
13606
Distance variable is not defined yet.
22848
04027
Distance variable is not defined yet.
22849
14218
Distance variable is not defined yet.
22850
64048
Distance variable is not defined yet.
22851
25247
Distance variable is not defined yet.
22852
15342
Distance variable is not defined yet.
22853
94112
Distance
13121.14320355089
22854
46542
Distance variable is not defined yet.
22855
33410
Distance variable is not defined yet.
22856
23457
Distance
13329.941044434881
22857
31022
Distance variable is not defined yet.
22858
33928
Distance variable is not defined yet.
22859
15059
Distance variable is not defined yet.
22860
27869
Distance variable is not defined yet.
22861
33801
Distance variable is not defined yet.
22862
07970
Distance variable is not defined yet.
22863
11794
Distance variable is not defined yet.
22864
89521
Distance variable is not defined yet.
22865
42518
Distance variable is not defined yet.
22866
16868
Distance variable is not defined yet.
22867
45040
Distance variable is not defined yet.
22868
32653
Distance variable is not defined yet.
22869
19941
Distance variable is not defined yet.
22870
77867
Distance
13316.360578360229
22871
54107
Distance variable is not defined yet.
22872
31030
Distance variable is not defined yet.
22873
38135
Distance variable is not defined yet.
22874
55404
Distance variable is not defined yet.
22875
21822
Distance variable is not defined yet.
22876
01545
Distance variable is not defined yet.
22877
02770
Distance variable is not defined yet.
22878
62009
Distance variable is not defined yet.
22879
20155
Distance variable is not defined yet.
22880
19040
Distance
4415.427955274199
22881
90404
Distance
2376.6986610586214
22882
07856
Distance variable is not defined yet.
22883
56062
Distance variable is not defined yet.
22884
29150
Distance variable is not defined yet.
22885
33067
Distance
13302.542545889755
22886
29682
Distance variable is not defined yet.
22887
98337
Distance variable is not defined yet.
22888
49942
Distance variable is not defined yet.
22889
04342
Distance variable is not defined yet.
22890
63742
Distance variable is not defined yet.
22891
02169
Distance
12285.325152212696
22892
99551
Distance variable is not defined yet.
22893
02561
Distance variable is not defined yet.
22894
60426
Distance variable is not defined yet.
22895
33161
Distance
10221.262489272787
22896
44270
Distance variable is not defined yet.
22897
43768
Distance variable is not defined yet.
22898
95694
Distance variable is not defined yet.
22899
33825
Distance variable is not defined yet.
22900
10465
Distance variable is not defined yet.
22901
93723
Distance variable is not defined yet.
22902
23709
Distance variable is not defined yet.
22903
35405
Distance variable is not defined yet.
22904
79118
Distance variable is not defined yet.
22905
65039
Distance variable is not defined yet.
22906
26134
Distance variable is not defined yet.
22907
14616
Distance variable is not defined yet.
22908
29388
Distance variable is not defined yet.
22909
55030
Distance variable is not defined yet.
22910
35980
Distance variable is not defined yet.
22911
54420
Distance variable is not defined yet.
22912
30308
Distance variable is not defined yet.
22913
26542
Distance variable is not defined yet.
22914
98195
Distance variable is not defined yet.
22915
28037
Distance variable is not defined yet.
22916
12972
Distance variable is not defined yet.
22917
06422
Distance variable is not defined yet.
22918
28631
Distance variable is not defined yet.
22919
06890
Distance variable is not defined yet.
22920
61044
Distance variable is not defined yet.
22921
85210
Distance variable is not defined yet.
22922
54451
Distance variable is not defined yet.
22923
18915
Distance
12235.570874605322
22924
55124
Distance variable is not defined yet.
22925
43115
Distance variable is not defined yet.
22926
54913
Distance variable is not defined yet.
22927
19085
Distance variable is not defined yet.
22928
47342
Distance variable is not defined yet.
22929
07457
Distance variable is not defined yet.
22930
64054
Distance variable is not defined yet.
22931
49885
Distance variable is not defined yet.
22932
46802
Distance variable is not defined yet.
22933
60630
Distance variable is not defined yet.
22934
73064
Distance variable is not defined yet.
22935
51357
Distance variable is not defined yet.
22936
40258
Distance variable is not defined yet.
22937
06473
Distance variable is not defined yet.
22938
57005
Distance variable is not defined yet.
22939
70592
Distance variable is not defined yet.
22940
98119
Distance variable is not defined yet.
22941
32509
Distance variable is not defined yet.
22942
18014
Distance variable is not defined yet.
22943
75641
Distance variable is not defined yet.
22944
36313
Distance variable is not defined yet.
22945
38257
Distance variable is not defined yet.
22946
45320
Distance variable is not defined yet.
22947
29052
Distance variable is not defined yet.
22948
65713
Distance variable is not defined yet.
22949
48432
Distance variable is not defined yet.
22950
46162
Distance variable is not defined yet.
22951
82801
Distance variable is not defined yet.
22952
92590
Distance variable is not defined yet.
22953
45410
Distance variable is not defined yet.
22954
67203
Distance variable is not defined yet.
22955
45231
Distance variable is not defined yet.
22956
80211
Distance variable is not defined yet.
22957
15042
Distance variable is not defined yet.
22958
97051
Distance variable is not defined yet.
22959
10461
Distance variable is not defined yet.
22960
60651
Distance
12309.03540685192
22961
33178
Distance variable is not defined yet.
22962
08361
Distance variable is not defined yet.
22963
19807
Distance variable is not defined yet.
22964
24168
Distance variable is not defined yet.
22965
63125
Distance variable is not defined yet.
22966
29104
Distance variable is not defined yet.
22967
68382
Distance variable is not defined yet.
22968
56280
Distance variable is not defined yet.
22969
77415
Distance variable is not defined yet.
22970
88023
Distance variable is not defined yet.
22971
16878
Distance variable is not defined yet.
22972
11947
Distance variable is not defined yet.
22973
62260
Distance variable is not defined yet.
22974
62324
Distance variable is not defined yet.
22975
89440
Distance variable is not defined yet.
22976
94903
Distance variable is not defined yet.
22977
28081
Distance variable is not defined yet.
22978
13477
Distance variable is not defined yet.
22979
99751
Distance variable is not defined yet.
22980
45211
Distance variable is not defined yet.
22981
04761
Distance variable is not defined yet.
22982
97101
Distance variable is not defined yet.
22983
48081
Distance variable is not defined yet.
22984
14462
Distance variable is not defined yet.
22985
91304
Distance variable is not defined yet.
22986
84082
Distance variable is not defined yet.
22987
46226
Distance
10788.028850143512
22988
06524
Distance variable is not defined yet.
22989
17502
Distance variable is not defined yet.
22990
50105
Distance variable is not defined yet.
22991
50007
Distance variable is not defined yet.
22992
19134
Distance variable is not defined yet.
22993
62532
Distance variable is not defined yet.
22994
18328
Distance variable is not defined yet.
22995
79719
Distance variable is not defined yet.
22996
02472
Distance variable is not defined yet.
22997
07005
Distance variable is not defined yet.
22998
30265
Distance variable is not defined yet.
22999
72417
Distance variable is not defined yet.
23000
56328
Distance variable is not defined yet.
23001
56116
Distance variable is not defined yet.
23002
35214
Distance variable is not defined yet.
23003
21864
Distance variable is not defined yet.
23004
03055
Distance variable is not defined yet.
23005
55614
Distance variable is not defined yet.
23006
77061
Distance
12623.726577837459
23007
35149
Distance variable is not defined yet.
23008
52756
Distance variable is not defined yet.
23009
58701
Distance variable is not defined yet.
23010
92276
Distance variable is not defined yet.
23011
29642
Distance variable is not defined yet.
23012
75758
Distance variable is not defined yet.
23013
13619
Distance variable is not defined yet.
23014
63870
Distance variable is not defined yet.
23015
33952
Distance variable is not defined yet.
23016
76044
Distance variable is not defined yet.
23017
21045
Distance variable is not defined yet.
23018
33785
Distance variable is not defined yet.
23019
83702
Distance variable is not defined yet.
23020
48359
Distance variable is not defined yet.
23021
23220
Distance variable is not defined yet.
23022
07626
Distance variable is not defined yet.
23023
04364
Distance variable is not defined yet.
23024
51637
Distance variable is not defined yet.
23025
44442
Distance variable is not defined yet.
23026
51575
Distance variable is not defined yet.
23027
52758
Distance variable is not defined yet.
23028
48002
Distance variable is not defined yet.
23029
45062
Distance variable is not defined yet.
23030
37040
Distance variable is not defined yet.
23031
77085
Distance variable is not defined yet.
23032
38917
Distance variable is not defined yet.
23033
73093
Distance variable is not defined yet.
23034
68845
Distance variable is not defined yet.
23035
19701
Distance variable is not defined yet.
23036
06053
Distance variable is not defined yet.
23037
19123
Distance variable is not defined yet.
23038
38876
Distance variable is not defined yet.
23039
21776
Distance variable is not defined yet.
23040
96749
Distance variable is not defined yet.
23041
32707
Distance variable is not defined yet.
23042
95472
Distance variable is not defined yet.
23043
52644
Distance variable is not defined yet.
23044
74126
Distance variable is not defined yet.
23045
07059
Distance variable is not defined yet.
23046
35954
Distance variable is not defined yet.
23047
15215
Distance variable is not defined yet.
23048
37890
Distance variable is not defined yet.
23049
36035
Distance variable is not defined yet.
23050
32796
Distance variable is not defined yet.
23051
73105
Distance variable is not defined yet.
23052
44703
Distance variable is not defined yet.
23053
97392
Distance variable is not defined yet.
23054
17046
Distance variable is not defined yet.
23055
13219
Distance variable is not defined yet.
23056
23844
Distance variable is not defined yet.
23057
04110
Distance variable is not defined yet.
23058
50135
Distance variable is not defined yet.
23059
02532
Distance variable is not defined yet.
23060
97071
Distance variable is not defined yet.
23061
07924
Distance variable is not defined yet.
23062
26366
Distance variable is not defined yet.
23063
44632
Distance variable is not defined yet.
23064
96746
Distance variable is not defined yet.
23065
19508
Distance variable is not defined yet.
23066
62712
Distance variable is not defined yet.
23067
02467
Distance
11674.451792626745
23068
17603
Distance variable is not defined yet.
23069
76061
Distance variable is not defined yet.
23070
54669
Distance
12734.60268449997
23071
70555
Distance variable is not defined yet.
23072
60189
Distance variable is not defined yet.
23073
23407
Distance variable is not defined yet.
23074
50322
Distance variable is not defined yet.
23075
47929
Distance variable is not defined yet.
23076
23703
Distance
10547.161648898462
23077
64689
Distance variable is not defined yet.
23078
14881
Distance variable is not defined yet.
23079
76208
Distance variable is not defined yet.
23080
49013
Distance variable is not defined yet.
23081
07724
Distance variable is not defined yet.
23082
46805
Distance variable is not defined yet.
23083
91792
Distance variable is not defined yet.
23084
35603
Distance variable is not defined yet.
23085
53703
Distance variable is not defined yet.
23086
32726
Distance variable is not defined yet.
23087
32207
Distance
6990.924653016481
23088
50101
Distance variable is not defined yet.
23089
54540
Distance variable is not defined yet.
23090
97532
Distance
12955.396590954946
23091
02831
Distance variable is not defined yet.
23092
64426
Distance variable is not defined yet.
23093
18035
Distance variable is not defined yet.
23094
44010
Distance variable is not defined yet.
23095
57567
Distance variable is not defined yet.
23096
07029
Distance variable is not defined yet.
23097
32732
Distance variable is not defined yet.
23098
30735
Distance variable is not defined yet.
23099
38365
Distance variable is not defined yet.
23100
80222
Distance variable is not defined yet.
23101
25703
Distance variable is not defined yet.
23102
33572
Distance
7070.097969857217
23103
62015
Distance variable is not defined yet.
23104
56165
Distance variable is not defined yet.
23105
15484
Distance variable is not defined yet.
23106
49004
Distance variable is not defined yet.
23107
31009
Distance variable is not defined yet.
23108
39218
Distance variable is not defined yet.
23109
19474
Distance variable is not defined yet.
23110
16111
Distance variable is not defined yet.
23111
07926
Distance variable is not defined yet.
23112
64161
Distance variable is not defined yet.
23113
63933
Distance variable is not defined yet.
23114
66214
Distance variable is not defined yet.
23115
71229
Distance variable is not defined yet.
23116
02494
Distance variable is not defined yet.
23117
33772
Distance variable is not defined yet.
23118
32409
Distance variable is not defined yet.
23119
54915
Distance variable is not defined yet.
23120
23306
Distance variable is not defined yet.
23121
45814
Distance variable is not defined yet.
23122
17569
Distance variable is not defined yet.
23123
17345
Distance variable is not defined yet.
23124
60111
Distance variable is not defined yet.
23125
75043
Distance variable is not defined yet.
23126
53526
Distance variable is not defined yet.
23127
80602
Distance variable is not defined yet.
23128
31779
Distance variable is not defined yet.
23129
60153
Distance variable is not defined yet.
23130
60436
Distance
5475.016393564447
23131
60607
Distance
4369.37475688993
23132
28590
Distance variable is not defined yet.
23133
12747
Distance variable is not defined yet.
23134
19716
Distance variable is not defined yet.
23135
46290
Distance
10074.814346330473
23136
77437
Distance variable is not defined yet.
23137
07017
Distance variable is not defined yet.
23138
92595
Distance variable is not defined yet.
23139
56335
Distance variable is not defined yet.
23140
67567
Distance
11841.851699115146
23141
77428
Distance variable is not defined yet.
23142
48190
Distance variable is not defined yet.
23143
50076
Distance variable is not defined yet.
23144
05037
Distance variable is not defined yet.
23145
11930
Distance variable is not defined yet.
23146
71446
Distance variable is not defined yet.
23147
03584
Distance variable is not defined yet.
23148
44656
Distance variable is not defined yet.
23149
33160
Distance variable is not defined yet.
23150
26301
Distance variable is not defined yet.
23151
23035
Distance variable is not defined yet.
23152
20143
Distance variable is not defined yet.
23153
15206
Distance
13032.532564071438
23154
06804
Distance variable is not defined yet.
23155
60541
Distance variable is not defined yet.
23156
50062
Distance variable is not defined yet.
23157
36775
Distance variable is not defined yet.
23158
45406
Distance variable is not defined yet.
23159
66212
Distance variable is not defined yet.
23160
76180
Distance
7047.069831572124
23161
19710
Distance variable is not defined yet.
23162
30281
Distance variable is not defined yet.
23163
62091
Distance variable is not defined yet.
23164
02748
Distance variable is not defined yet.
23165
60646
Distance variable is not defined yet.
23166
74029
Distance variable is not defined yet.
23167
85552
Distance variable is not defined yet.
23168
95358
Distance variable is not defined yet.
23169
21862
Distance variable is not defined yet.
23170
62217
Distance variable is not defined yet.
23171
48027
Distance variable is not defined yet.
23172
64746
Distance variable is not defined yet.
23173
13673
Distance variable is not defined yet.
23174
83854

Warning: Cannot load hourly/2021/72305.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/72305.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/72305.csv.gz from https://bulk.meteostat.net/v2/

Distance
10695.71697421306
23554
11718
Distance variable is not defined yet.
23555
47458
Distance variable is not defined yet.
23556
43215
Distance variable is not defined yet.
23557
06074
Distance variable is not defined yet.
23558
08311
Distance variable is not defined yet.
23559
84106
Distance variable is not defined yet.
23560
43055
Distance variable is not defined yet.
23561
20124
Distance variable is not defined yet.
23562
35209
Distance variable is not defined yet.
23563
72227
Distance variable is not defined yet.
23564
73084
Distance variable is not defined yet.
23565
73103
Distance variable is not defined yet.
23566
15728
Distance variable is not defined yet.
23567
90040
Distance variable is not defined yet.
23568
35446
Distance variable is not defined yet.
23569
61840
Distance variable is not defined yet.
23570
75569
Distance variable is not defined yet.
23571
27805
Distance variable is not defined yet.
23572
08840
Distance variable is not defined yet.
23573
44032
Distance variable is not defined yet.
23574
63073
Distance variable is not defined yet.
23575
96073
Distance variable is not defined yet.
23576
14882
Distance variable is not defined yet.
23577
17602
Distance variable is not defined yet.
23578
43080
Distance variable is not defined yet.
23579
60175
Distance variable is not defined yet.
23580
96795
Distance
797.3958198253705
23581
71245
Distance variable is not defined yet.
23582
02478
Distance variable is not defined yet.
23583
13679
Distance variable is not defined yet.
23584
61570
Distance variable is not defined yet.
23585
53108
Distance variable is not defined yet.
23586
78251
Distance variable is not defined yet.
23587
76058
Distance variable is not defined yet.
23588
19330
Distance variable is not defined yet.
23589
19933
Distance variable is not defined yet.
23590
23839
Distance variable is not defined yet.
23591
62814
Distance variable is not defined yet.
23592
11790
Distance variable is not defined yet.
23593
62807
Distance variable is not defined yet.
23594
98390
Distance variable is not defined yet.
23595
77506
Distance
11721.690265063911
23596
04629
Distance variable is not defined yet.
23597
47302
Distance variable is not defined yet.
23598
22923
Distance variable is not defined yet.
23599
53018
Distance variable is not defined yet.
23600
55751
Distance variable is not defined yet.
23601
39553
Distance variable is not defined yet.
23602
85719
Distance variable is not defined yet.
23603
19072
Distance variable is not defined yet.
23604
78152
Distance variable is not defined yet.
23605
56232
Distance variable is not defined yet.
23606
13654
Distance variable is not defined yet.
23607
41631
Distance
12279.86323656862
23608
01077
Distance variable is not defined yet.
23609
08890
Distance variable is not defined yet.
23610
61925
Distance variable is not defined yet.
23611
47035
Distance variable is not defined yet.
23612
56295
Distance variable is not defined yet.
23613
23919
Distance variable is not defined yet.
23614
36066
Distance
9497.224178242257
23615
68433
Distance variable is not defined yet.
23616
33511
Distance variable is not defined yet.
23617
55447
Distance variable is not defined yet.
23618
07846
Distance variable is not defined yet.
23619
06070
Distance variable is not defined yet.
23620
45766
Distance variable is not defined yet.
23621
62013
Distance variable is not defined yet.
23622
01564
Distance variable is not defined yet.
23623
36861
Distance variable is not defined yet.
23624
19809
Distance variable is not defined yet.
23625
23488
Distance variable is not defined yet.
23626
14714
Distance variable is not defined yet.
23627
03220
Distance variable is not defined yet.
23628
55416
Distance variable is not defined yet.
23629
34114
Distance variable is not defined yet.
23630
32137
Distance variable is not defined yet.
23631
14782
Distance variable is not defined yet.
23632
70003
Distance variable is not defined yet.
23633
61016
Distance variable is not defined yet.
23634
30257
Distance variable is not defined yet.
23635
32765
Distance variable is not defined yet.
23636
98565
Distance variable is not defined yet.
23637
97134
Distance variable is not defined yet.
23638
14228
Distance variable is not defined yet.
23639
48033
Distance variable is not defined yet.
23640
73160
Distance variable is not defined yet.
23641
29474
Distance variable is not defined yet.
23642
63139
Distance variable is not defined yet.
23643
42040
Distance variable is not defined yet.
23644
53211
Distance variable is not defined yet.
23645
80113
Distance variable is not defined yet.
23646
55020
Distance variable is not defined yet.
23647
47469
Distance variable is not defined yet.
23648
15451
Distance variable is not defined yet.
23649
44483
Distance variable is not defined yet.
23650
71008
Distance variable is not defined yet.
23651
59923
Distance variable is not defined yet.
23652
84010
Distance variable is not defined yet.
23653
36110
Distance variable is not defined yet.
23654
74041
Distance variable is not defined yet.
23655
19127
Distance variable is not defined yet.
23656
01938
Distance variable is not defined yet.
23657
13207
Distance variable is not defined yet.
23658
94590
Distance variable is not defined yet.
23659
91020
Distance variable is not defined yet.
23660
19073
Distance variable is not defined yet.
23661
13209
Distance variable is not defined yet.
23662
08734
Distance
12385.74587618163
23663
48314
Distance variable is not defined yet.
23664
14609
Distance variable is not defined yet.
23665
17576
Distance variable is not defined yet.
23666
40059
Distance variable is not defined yet.
23667
82435
Distance variable is not defined yet.
23668
03846
Distance variable is not defined yet.
23669
60040
Distance variable is not defined yet.
23670
49419
Distance variable is not defined yet.
23671
33031
Distance variable is not defined yet.
23672
63601
Distance variable is not defined yet.
23673
16837
Distance variable is not defined yet.
23674
93434
Distance variable is not defined yet.
23675
21673
Distance variable is not defined yet.
23676
25260
Distance variable is not defined yet.
23677
31623
Distance variable is not defined yet.
23678
89120
Distance variable is not defined yet.
23679
14904
Distance variable is not defined yet.
23680
38041
Distance variable is not defined yet.
23681
39666
Distance variable is not defined yet.
23682
42462
Distance variable is not defined yet.
23683
01378
Distance variable is not defined yet.
23684
13029
Distance variable is not defined yet.
23685
04485
Distance variable is not defined yet.
23686
85140
Distance variable is not defined yet.
23687
92084
Distance variable is not defined yet.
23688
15327
Distance variable is not defined yet.
23689
53037
Distance variable is not defined yet.
23690
94928
Distance variable is not defined yet.
23691
63113
Distance variable is not defined yet.
23692
47980
Distance variable is not defined yet.
23693
23112
Distance variable is not defined yet.
23694
18069
Distance variable is not defined yet.
23695
07050
Distance variable is not defined yet.
23696
05824
Distance variable is not defined yet.
23697
73012
Distance variable is not defined yet.
23698
63701
Distance variable is not defined yet.
23699
52201
Distance variable is not defined yet.
23700
40229
Distance variable is not defined yet.
23701
92868
Distance variable is not defined yet.
23702
80624
Distance variable is not defined yet.
23703
72153
Distance variable is not defined yet.
23704
08345
Distance variable is not defined yet.
23705
06710
Distance variable is not defined yet.
23706
19141
Distance variable is not defined yet.
23707
23225
Distance variable is not defined yet.
23708
49268
Distance variable is not defined yet.
23709
30458
Distance variable is not defined yet.
23710
68134

Warning: Cannot load hourly/2021/72553.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/72553.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/72553.csv.gz from https://bulk.meteostat.net/v2/

Distance
8091.798415860845
23711
20902
Distance variable is not defined yet.
23712
23883
Distance variable is not defined yet.
23713
08610
Distance variable is not defined yet.
23714
33016
Distance
5212.048238811499
23715
29850
Distance variable is not defined yet.
23716
56245
Distance variable is not defined yet.
23717
67846
Distance variable is not defined yet.
23718
30011
Distance variable is not defined yet.
23719
98303
Distance variable is not defined yet.
23720
33624
Distance variable is not defined yet.
23721
05486
Distance variable is not defined yet.
23722
34681
Distance variable is not defined yet.
23723
55306
Distance variable is not defined yet.
23724
50131
Distance variable is not defined yet.
23725
46205
Distance variable is not defined yet.
23726
27501
Distance variable is not defined yet.
23727
48105
Distance variable is not defined yet.
23728
21156
Distance variable is not defined yet.
23729
43105
Distance variable is not defined yet.
23730
36786
Distance variable is not defined yet.
23731
30303
Distance variable is not defined yet.
23732
31309
Distance variable is not defined yet.
23733
10463
Distance variable is not defined yet.
23734
92648
Distance
12490.939916490108
23735
27573
Distance variable is not defined yet.
23736
55032
Distance variable is not defined yet.
23737
52227
Distance variable is not defined yet.
23738
46403
Distance variable is not defined yet.
23739
10992
Distance
9941.557516414296
23740
05260
Distance
9690.223129887901
23741
28501
Distance variable is not defined yet.
23742
96143
Distance variable is not defined yet.
23743
87517
Distance variable is not defined yet.
23744
48209
Distance variable is not defined yet.
23745
79934
Distance variable is not defined yet.
23746
94591
Distance variable is not defined yet.
23747
77378
Distance variable is not defined yet.
23748
79907
Distance variable is not defined yet.
23749
34142
Distance variable is not defined yet.
23750
14062
Distance variable is not defined yet.
23751
33534
Distance variable is not defined yet.
23752
21770
Distance variable is not defined yet.
23753
30290
Distance variable is not defined yet.
23754
27916
Distance variable is not defined yet.
23755
95928
Distance variable is not defined yet.
23756
03046
Distance variable is not defined yet.
23757
68015
Distance variable is not defined yet.
23758
07826
Distance variable is not defined yet.
23759
57370
Distance variable is not defined yet.
23760
55795
Distance variable is not defined yet.
23761
11364
Distance variable is not defined yet.
23762
05153
Distance variable is not defined yet.
23763
73503
Distance variable is not defined yet.
23764
30161
Distance variable is not defined yet.
23765
40383
Distance variable is not defined yet.
23766
45439
Distance variable is not defined yet.
23767
30660
Distance variable is not defined yet.
23768
67456
Distance variable is not defined yet.
23769
29710
Distance variable is not defined yet.
23770
98070
Distance variable is not defined yet.
23771
33774
Distance variable is not defined yet.
23772
83318
Distance variable is not defined yet.
23773
45685
Distance variable is not defined yet.
23774
38119
Distance variable is not defined yet.
23775
45832
Distance variable is not defined yet.
23776
28638
Distance variable is not defined yet.
23777
23607
Distance variable is not defined yet.
23778
72756
Distance variable is not defined yet.
23779
19717
Distance variable is not defined yet.
23780
49126
Distance variable is not defined yet.
23781
50061
Distance variable is not defined yet.
23782
76904
Distance variable is not defined yet.
23783
44028
Distance variable is not defined yet.
23784
48066
Distance variable is not defined yet.
23785
49507
Distance variable is not defined yet.
23786
14217
Distance variable is not defined yet.
23787
19442
Distance variable is not defined yet.
23788
49254
Distance variable is not defined yet.
23789
33168
Distance
7622.938845570965
23790
22623
Distance variable is not defined yet.
23791
33014
Distance
2081.195752702351
23792
35744
Distance variable is not defined yet.
23793
95247
Distance variable is not defined yet.
23794
02861
Distance variable is not defined yet.
23795
87322
Distance variable is not defined yet.
23796
53715
Distance variable is not defined yet.
23797
77377
Distance variable is not defined yet.
23798
83860
Distance variable is not defined yet.
23799
33158
Distance variable is not defined yet.
23800
27537
Distance variable is not defined yet.
23801
71220
Distance variable is not defined yet.
23802
92618
Distance
1628.5597263364727
23803
14051
Distance variable is not defined yet.
23804
90262
Distance
12426.09123714793
23805
62347
Distance variable is not defined yet.
23806
60480
Distance variable is not defined yet.
23807
49072
Distance variable is not defined yet.
23808
38251
Distance variable is not defined yet.
23809
16740
Distance variable is not defined yet.
23810
60803
Distance variable is not defined yet.
23811
61326
Distance variable is not defined yet.
23812
02322
Distance
11451.94745112234
23813
48117
Distance variable is not defined yet.
23814
12845
Distance variable is not defined yet.
23815
28323
Distance variable is not defined yet.
23816
57706
Distance
950.3457820494091
23817
57020
Distance variable is not defined yet.
23818
06824
Distance variable is not defined yet.
23819
30467
Distance variable is not defined yet.
23820
60301
Distance variable is not defined yet.
23821
24731
Distance variable is not defined yet.
23822
11554
Distance variable is not defined yet.
23823
67340
Distance variable is not defined yet.
23824
66756
Distance variable is not defined yet.
23825
28746
Distance variable is not defined yet.
23826
25701
Distance variable is not defined yet.
23827
50068
Distance variable is not defined yet.
23828
80116
Distance variable is not defined yet.
23829
27027
Distance variable is not defined yet.
23830
93105
Distance variable is not defined yet.
23831
64849
Distance variable is not defined yet.
23832
03823
Distance variable is not defined yet.
23833
05773
Distance variable is not defined yet.
23834
04473
Distance variable is not defined yet.
23835
60615
Distance
7171.947617853923
23836
31768
Distance variable is not defined yet.
23837
82937
Distance variable is not defined yet.
23838
83122
Distance variable is not defined yet.
23839
72930
Distance variable is not defined yet.
23840
75024
Distance variable is not defined yet.
23841
74134
Distance variable is not defined yet.
23842
62996
Distance variable is not defined yet.
23843
77037
Distance variable is not defined yet.
23844
73004
Distance variable is not defined yet.
23845
23235
Distance variable is not defined yet.
23846
61348
Distance variable is not defined yet.
23847
68116
Distance variable is not defined yet.
23848
27265
Distance variable is not defined yet.
23849
26435
Distance variable is not defined yet.
23850
30110
Distance variable is not defined yet.
23851
92027
Distance variable is not defined yet.
23852
22968
Distance variable is not defined yet.
23853
32044
Distance variable is not defined yet.
23854
03856
Distance variable is not defined yet.
23855
61615
Distance variable is not defined yet.
23856
90606
Distance variable is not defined yet.
23857
48350
Distance variable is not defined yet.
23858
98039
Distance variable is not defined yet.
23859
55316
Distance variable is not defined yet.
23860
32219
Distance variable is not defined yet.
23861
30519
Distance variable is not defined yet.
23862
72550
Distance variable is not defined yet.
23863
05143
Distance variable is not defined yet.
23864
71107
Distance variable is not defined yet.
23865
16657
Distance variable is not defined yet.
23866
46545
Distance variable is not defined yet.
23867
29384
Distance variable is not defined yet.
23868
19013
Distance variable is not defined yet.
23869
84304
Distance variable is not defined yet.
23870
28135
Distance variable is not defined yet.
23871
50594
Distance variable is not defined yet.
23872
28210
Distance variable is not defined yet.
23873
54960
Distance variable is not defined yet.
23874
78516
Distance variable is not defined yet.
23875
04660
Distance variable is not defined yet.
23876
68362
Distance variable is not defined yet.
23877
76129
Distance variable is not defined yet.
23878
60431
Distance
2750.4655644224604
23879
03084
Distance variable is not defined yet.
23880
92070
Distance variable is not defined yet.
23881
21801
Distance variable is not defined yet.
23882
95674
Distance variable is not defined yet.
23883
02878
Distance variable is not defined yet.
23884
52750
Distance variable is not defined yet.
23885
08832
Distance variable is not defined yet.
23886
65259
Distance variable is not defined yet.
23887
43116
Distance variable is not defined yet.
23888
23069
Distance variable is not defined yet.
23889
48706
Distance variable is not defined yet.
23890
45252
Distance variable is not defined yet.
23891
73526
Distance variable is not defined yet.
23892
04975
Distance variable is not defined yet.
23893
03031
Distance variable is not defined yet.
23894
33618
Distance variable is not defined yet.
23895
76073
Distance variable is not defined yet.
23896
77340
Distance variable is not defined yet.
23897
07108
Distance variable is not defined yet.
23898
45225
Distance variable is not defined yet.
23899
30092
Distance variable is not defined yet.
23900
33706
Distance variable is not defined yet.
23901
38821
Distance variable is not defined yet.
23902
79545
Distance variable is not defined yet.
23903
76247
Distance variable is not defined yet.
23904
78724
Distance variable is not defined yet.
23905
57108
Distance variable is not defined yet.
23906
28678
Distance variable is not defined yet.
23907
78745
Distance variable is not defined yet.
23908
19335
Distance variable is not defined yet.
23909
92114
Distance
12324.788554553716
23910
27546
Distance variable is not defined yet.
23911
94015
Distance variable is not defined yet.
23912
42053
Distance variable is not defined yet.
23913
95045
Distance variable is not defined yet.
23914
21252
Distance variable is not defined yet.
23915
02813
Distance variable is not defined yet.
23916
45504
Distance variable is not defined yet.
23917
53047
Distance variable is not defined yet.
23918
45251
Distance variable is not defined yet.
23919
02906
Distance variable is not defined yet.
23920
06870
Distance variable is not defined yet.
23921
92866
Distance variable is not defined yet.
23922
31554
Distance variable is not defined yet.
23923
48195
Distance variable is not defined yet.
23924
46260
Distance
12216.85439648579
23925
55415
Distance variable is not defined yet.
23926
92278
Distance variable is not defined yet.
23927
71414
Distance variable is not defined yet.
23928
85396
Distance variable is not defined yet.
23929
83835
Distance variable is not defined yet.
23930
47954
Distance variable is not defined yet.
23931
35115
Distance variable is not defined yet.
23932
85716
Distance variable is not defined yet.
23933
36559
Distance variable is not defined yet.
23934
28431
Distance variable is not defined yet.
23935
17026
Distance variable is not defined yet.
23936
62325
Distance variable is not defined yet.
23937
31545
Distance variable is not defined yet.
23938
56580
Distance variable is not defined yet.
23939
43556
Distance variable is not defined yet.
23940
37723
Distance variable is not defined yet.
23941
60616
Distance
3283.6391866858244
23942
52595
Distance variable is not defined yet.
23943
81230
Distance variable is not defined yet.
23944
39581
Distance variable is not defined yet.
23945
44646
Distance variable is not defined yet.
23946
63430
Distance variable is not defined yet.
23947
85031
Distance variable is not defined yet.
23948
56311
Distance variable is not defined yet.
23949
50531
Distance variable is not defined yet.
23950
05476
Distance variable is not defined yet.
23951
30451
Distance variable is not defined yet.
23952
42254
Distance variable is not defined yet.
23953
19130
Distance variable is not defined yet.
23954
75670
Distance variable is not defined yet.
23955
68505
Distance variable is not defined yet.
23956
33065
Distance variable is not defined yet.
23957
45420
Distance variable is not defined yet.
23958
60653
Distance
5342.832572862117
23959
01128
Distance variable is not defined yet.
23960
19151
Distance variable is not defined yet.
23961
43468
Distance variable is not defined yet.
23962
43608
Distance variable is not defined yet.
23963
41059
Distance variable is not defined yet.
23964
59255
Distance variable is not defined yet.
23965
22213
Distance variable is not defined yet.
23966
55373
Distance variable is not defined yet.
23967
31408
Distance variable is not defined yet.
23968
52804
Distance variable is not defined yet.
23969
61081
Distance variable is not defined yet.
23970
08853
Distance variable is not defined yet.
23971
60053
Distance variable is not defined yet.
23972
37085
Distance variable is not defined yet.
23973
38058
Distance variable is not defined yet.
23974
65742
Distance variable is not defined yet.
23975
92069
Distance variable is not defined yet.
23976
56017
Distance variable is not defined yet.
23977
11780
Distance variable is not defined yet.
23978
21146
Distance variable is not defined yet.
23979
06712
Distance variable is not defined yet.
23980
44678
Distance variable is not defined yet.
23981
44134
Distance variable is not defined yet.
23982
70345
Distance variable is not defined yet.
23983
84094
Distance variable is not defined yet.
23984
42323
Distance variable is not defined yet.
23985
38477
Distance variable is not defined yet.
23986
61107
Distance variable is not defined yet.
23987
85142
Distance variable is not defined yet.
23988
95138
Distance variable is not defined yet.
23989
53034
Distance variable is not defined yet.
23990
64866
Distance variable is not defined yet.
23991
36703
Distance variable is not defined yet.
23992
37128
Distance variable is not defined yet.
23993
63109
Distance variable is not defined yet.
23994
46069
Distance variable is not defined yet.
23995
61614
Distance variable is not defined yet.
23996
29704
Distance variable is not defined yet.
23997
95356
Distance variable is not defined yet.
23998
04530
Distance variable is not defined yet.
23999
12962
Distance
6581.548093040916
24000
13408
Distance variable is not defined yet.
24001
65337
Distance variable is not defined yet.
24002
25801
Distance variable is not defined yet.
24003
87121
Distance variable is not defined yet.
24004
98004
Distance variable is not defined yet.
24005
91104
Distance
8958.182619745266
24006
21204
Distance variable is not defined yet.
24007
29456
Distance variable is not defined yet.
24008
17004
Distance variable is not defined yet.
24009
01344
Distance variable is not defined yet.
24010
87107
Distance
7971.803394529759
24011
38139
Distance variable is not defined yet.
24012
35226
Distance variable is not defined yet.
24013
01434
Distance
3263.2610251769065
24014
14572
Distance
11933.011527476297
24015
15963
Distance variable is not defined yet.
24016
67364
Distance variable is not defined yet.
24017
95039
Distance variable is not defined yet.
24018
07023
Distance variable is not defined yet.
24019
13066
Distance variable is not defined yet.
24020
27408
Distance variable is not defined yet.
24021
63824
Distance variable is not defined yet.
24022
17980
Distance variable is not defined yet.
24023
48342
Distance variable is not defined yet.
24024
56303
Distance variable is not defined yet.
24025
81050
Distance variable is not defined yet.
24026
54519
Distance variable is not defined yet.
24027
66079
Distance variable is not defined yet.
24028
06042
Distance variable is not defined yet.
24029
67005
Distance variable is not defined yet.
24030
03750
Distance variable is not defined yet.
24031
55310
Distance variable is not defined yet.
24032
92040
Distance variable is not defined yet.
24033
80302
Distance variable is not defined yet.
24034
23111
Distance variable is not defined yet.
24035
95639
Distance variable is not defined yet.
24036
30720
Distance variable is not defined yet.
24037
62501
Distance variable is not defined yet.
24038
32091
Distance variable is not defined yet.
24039
06037
Distance variable is not defined yet.
24040
03071
Distance variable is not defined yet.
24041
14220
Distance variable is not defined yet.
24042
10985
Distance variable is not defined yet.
24043
62903
Distance variable is not defined yet.
24044
34683
Distance variable is not defined yet.
24045
32550
Distance variable is not defined yet.
24046
62237
Distance variable is not defined yet.
24047
55080
Distance variable is not defined yet.
24048
30115
Distance
12037.01159953017
24049
94931
Distance variable is not defined yet.
24050
37714
Distance variable is not defined yet.
24051
06611
Distance variable is not defined yet.
24052
28544
Distance variable is not defined yet.
24053
07524
Distance variable is not defined yet.
24054
43553
Distance variable is not defined yet.
24055
45319
Distance variable is not defined yet.
24056
10307
Distance variable is not defined yet.
24057
65656
Distance variable is not defined yet.
24058
27549
Distance variable is not defined yet.
24059
21234
Distance variable is not defined yet.
24060
04037
Distance variable is not defined yet.
24061
42236
Distance variable is not defined yet.
24062
60637
Distance
9485.252143196307
24063
48738
Distance variable is not defined yet.
24064
66215
Distance variable is not defined yet.
24065
38631
Distance variable is not defined yet.
24066
29715
Distance variable is not defined yet.
24067
06489
Distance variable is not defined yet.
24068
16682
Distance variable is not defined yet.
24069
50272
Distance variable is not defined yet.
24070
01801
Distance variable is not defined yet.
24071
68319
Distance variable is not defined yet.
24072
28546
Distance variable is not defined yet.
24073
23359
Distance variable is not defined yet.
24074
18464
Distance variable is not defined yet.
24075
93101
Distance variable is not defined yet.
24076
42733
Distance variable is not defined yet.
24077
97115
Distance variable is not defined yet.
24078
43333
Distance variable is not defined yet.
24079
03217
Distance variable is not defined yet.
24080
60586
Distance
7420.250412630331
24081
90064
Distance
3394.4865004511944
24082
07755
Distance variable is not defined yet.
24083
56043
Distance variable is not defined yet.
24084
76643
Distance variable is not defined yet.
24085
61475
Distance variable is not defined yet.
24086
11793
Distance variable is not defined yet.
24087
06482
Distance variable is not defined yet.
24088
03810
Distance variable is not defined yet.
24089
48911
Distance variable is not defined yet.
24090
74646
Distance variable is not defined yet.
24091
27562
Distance variable is not defined yet.
24092
48192
Distance variable is not defined yet.
24093
92555
Distance variable is not defined yet.
24094
88346
Distance variable is not defined yet.
24095
61936
Distance variable is not defined yet.
24096
66211
Distance
11037.373990172318
24097
33129
Distance variable is not defined yet.
24098
46058
Distance variable is not defined yet.
24099
17093
Distance variable is not defined yet.
24100
14830
Distance variable is not defined yet.
24101
45216
Distance variable is not defined yet.
24102
85374
Distance variable is not defined yet.
24103
67522
Distance variable is not defined yet.
24104
55319
Distance variable is not defined yet.
24105
44050
Distance variable is not defined yet.
24106
08059
Distance variable is not defined yet.
24107
01718
Distance variable is not defined yet.
24108
64113
Distance variable is not defined yet.
24109
38572
Distance variable is not defined yet.
24110
12029
Distance variable is not defined yet.
24111
19732
Distance variable is not defined yet.
24112
35805
Distance variable is not defined yet.
24113
42101
Distance variable is not defined yet.
24114
89434
Distance variable is not defined yet.
24115
53557
Distance variable is not defined yet.

Warning: Cannot load hourly/2022/DNYFH.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/DNYFH.csv.gz from https://bulk.meteostat.net/v2/

Distance
8581.088891189946
27697
78228
Distance variable is not defined yet.
27698
76657
Distance variable is not defined yet.
27699
39648
Distance variable is not defined yet.
27700
96766
Distance variable is not defined yet.
27701
20191
Distance variable is not defined yet.
27702
95215
Distance variable is not defined yet.
27703
58703
Distance variable is not defined yet.
27704
33317
Distance
8576.251017897781
27705
76155
Distance variable is not defined yet.
27706
53158
Distance variable is not defined yet.
27707
15009
Distance variable is not defined yet.
27708
45219
Distance variable is not defined yet.
27709
28560
Distance variable is not defined yet.
27710
60706
Distance variable is not defined yet.
27711
35811
Distance variable is not defined yet.
27712
28039
Distance variable is not defined yet.
27713
95020
Distance variable is not defined yet.
27714
29673
Distance variable is not defined yet.
27715
89074
Distance variable is not defined yet.
27716
01810
Distance variable is not defined yet.
27717
91801
Distance variable is not defined yet.
27718
76013
Distance variable is not defined yet.
27719
24860
Distance variable is not defined yet.
27720
72758
Distance variable is not defined yet.
27721
50275
Distance variable is not defined yet.
27722
98327
Distance variable is not defined yet.
27723
65591
Distance variable is not defined yet.
27724
87110
Distance
7327.258239569666
27725
90701
Distance variable is not defined yet.
27726
21793
Distance variable is not defined yet.
27727
96786
Distance variable is not defined yet.
27728
91701
Distance variable is not defined yet.
27729
66441
Distance variable is not defined yet.
27730
02163
Distance variable is not defined yet.
27731
19033
Distance variable is not defined yet.
27732
77434
Distance variable is not defined yet.
27733
19475
Distance variable is not defined yet.
27734
23601
Distance variable is not defined yet.
27735
72431
Distance variable is not defined yet.
27736
35125
Distance variable is not defined yet.
27737
07860
Distance variable is not defined yet.
27738
53140
Distance variable is not defined yet.
27739
30066
Distance variable is not defined yet.
27740
77702
Distance variable is not defined yet.
27741
90036
Distance variable is not defined yet.
27742
85033
Distance variable is not defined yet.
27743
40829
Distance variable is not defined yet.
27744
37863
Distance variable is not defined yet.
27745
31606
Distance variable is not defined yet.
27746
29588
Distance variable is not defined yet.
27747
93555
Distance variable is not defined yet.
27748
10532
Distance variable is not defined yet.
27749
29625
Distance variable is not defined yet.
27750
78234
Distance variable is not defined yet.
27751
45449
Distance variable is not defined yet.
27752
80014
Distance variable is not defined yet.
27753
95834
Distance variable is not defined yet.
27754
32205
Distance variable is not defined yet.
27755
98116
Distance variable is not defined yet.
27756
75208
Distance variable is not defined yet.
27757
85207
Distance variable is not defined yet.
27758
78537
Distance variable is not defined yet.
27759
39823
Distance variable is not defined yet.
27760
61285
Distance variable is not defined yet.
27761
68105
Distance variable is not defined yet.
27762
60190
Distance variable is not defined yet.
27763
01949
Distance variable is not defined yet.
27764
50842
Distance variable is not defined yet.
27765
78248
Distance variable is not defined yet.
27766
28345
Distance variable is not defined yet.
27767
47404
Distance variable is not defined yet.
27768
19053
Distance variable is not defined yet.
27769
68068
Distance variable is not defined yet.
27770
99146
Distance variable is not defined yet.
27771
75835
Distance variable is not defined yet.
27772
91755
Distance variable is not defined yet.
27773
10033
Distance variable is not defined yet.
27774
80488
Distance variable is not defined yet.
27775
55121
Distance variable is not defined yet.
27776
73120
Distance variable is not defined yet.
27777
78721
Distance variable is not defined yet.
27778
76450
Distance variable is not defined yet.
27779
16342
Distance variable is not defined yet.
27780
68007
Distance variable is not defined yet.
27781
02744
Distance variable is not defined yet.
27782
56111
Distance variable is not defined yet.
27783
40506
Distance variable is not defined yet.
27784
21774
Distance variable is not defined yet.
27785
03854
Distance variable is not defined yet.
27786
24132
Distance variable is not defined yet.
27787
85298
Distance variable is not defined yet.
27788
75773
Distance variable is not defined yet.
27789
92548
Distance variable is not defined yet.
27790
99203
Distance variable is not defined yet.
27791
29540
Distance
8494.076027044595
27792
14302
Distance variable is not defined yet.
27793
92398
Distance variable is not defined yet.
27794
19143
Distance variable is not defined yet.
27795
48855
Distance variable is not defined yet.
27796
19118
Distance variable is not defined yet.
27797
92105
Distance variable is not defined yet.
27798
55105
Distance variable is not defined yet.
27799
60546
Distance variable is not defined yet.
27800
05828
Distance variable is not defined yet.
27801
47714
Distance variable is not defined yet.
27802
46202
Distance variable is not defined yet.
27803
81410
Distance variable is not defined yet.
27804
11720
Distance variable is not defined yet.
27805
85296
Distance variable is not defined yet.
27806
92647
Distance variable is not defined yet.
27807
68104
Distance
8078.165549626318
27808
82190
Distance variable is not defined yet.
27809
99216
Distance variable is not defined yet.
27810
60915
Distance variable is not defined yet.
27811
95328
Distance variable is not defined yet.
27812
02915
Distance variable is not defined yet.
27813
23416
Distance variable is not defined yet.
27814
19012
Distance variable is not defined yet.
27815
33445
Distance variable is not defined yet.
27816
60609
Distance
7583.561842435192
27817
50317
Distance variable is not defined yet.
27818
67042
Distance variable is not defined yet.
27819
04274
Distance variable is not defined yet.
27820
80007
Distance variable is not defined yet.
27821
95816
Distance variable is not defined yet.
27822
21210
Distance variable is not defined yet.
27823
65020
Distance variable is not defined yet.
27824
74360
Distance variable is not defined yet.
27825
77488
Distance variable is not defined yet.
27826
45854
Distance variable is not defined yet.
27827
38068
Distance variable is not defined yet.
27828
96744
Distance variable is not defined yet.
27829
73109
Distance variable is not defined yet.
27830
84765
Distance variable is not defined yet.
27831
43549
Distance variable is not defined yet.
27832
74135
Distance variable is not defined yet.
27833
30137
Distance variable is not defined yet.
27834
22560
Distance variable is not defined yet.
27835
28092
Distance variable is not defined yet.
27836
70114
Distance
5092.1640880585355
27837
89144
Distance variable is not defined yet.
27838
03903
Distance variable is not defined yet.
27839
24637
Distance variable is not defined yet.
27840
02818
Distance variable is not defined yet.
27841
11518
Distance variable is not defined yet.
27842
33142
Distance variable is not defined yet.
27843
28605
Distance variable is not defined yet.
27844
85012
Distance variable is not defined yet.
27845
47807
Distance variable is not defined yet.
27846
73165
Distance variable is not defined yet.
27847
53219
Distance variable is not defined yet.
27848
06093
Distance variable is not defined yet.
27849
75071
Distance variable is not defined yet.
27850
46112
Distance variable is not defined yet.
27851
97113
Distance variable is not defined yet.
27852
54956
Distance variable is not defined yet.
27853
08527
Distance variable is not defined yet.
27854
75032
Distance variable is not defined yet.
27855
07762
Distance variable is not defined yet.
27856
26104
Distance variable is not defined yet.
27857
12786
Distance variable is not defined yet.
27858
66102
Distance variable is not defined yet.
27859
31028
Distance variable is not defined yet.
27860
60490
Distance variable is not defined yet.
27861
32266
Distance variable is not defined yet.
27862
91371
Distance variable is not defined yet.
27863
01606
Distance variable is not defined yet.
27864
13623
Distance variable is not defined yet.
27865
17109
Distance variable is not defined yet.
27866
01607
Distance variable is not defined yet.
27867
63103
Distance variable is not defined yet.
27868
31546
Distance variable is not defined yet.
27869
23843
Distance variable is not defined yet.
27870
23231
Distance variable is not defined yet.
27871
48069
Distance variable is not defined yet.
27872
55439
Distance variable is not defined yet.
27873
94606
Distance
6375.2244856776615
27874
28144
Distance variable is not defined yet.
27875
15219
Distance variable is not defined yet.
27876
94613
Distance variable is not defined yet.
27877
30256
Distance variable is not defined yet.
27878
78589
Distance variable is not defined yet.
27879
92411
Distance variable is not defined yet.
27880
40202
Distance variable is not defined yet.
27881
60553
Distance variable is not defined yet.
27882
37240
Distance variable is not defined yet.
27883
36082
Distance variable is not defined yet.
27884
15486
Distance variable is not defined yet.
27885
30726
Distance variable is not defined yet.
27886
53588
Distance variable is not defined yet.
27887
54494
Distance variable is not defined yet.
27888
21740
Distance variable is not defined yet.
27889
49425
Distance variable is not defined yet.
27890
13421
Distance variable is not defined yet.
27891
33135
Distance variable is not defined yet.
27892
84301
Distance variable is not defined yet.
27893
11435
Distance variable is not defined yet.
27894
33781
Distance variable is not defined yet.
27895
02451
Distance variable is not defined yet.
27896
17370
Distance variable is not defined yet.
27897
74104
Distance variable is not defined yet.
27898
13484
Distance variable is not defined yet.
27899
85014
Distance variable is not defined yet.
27900
19018
Distance variable is not defined yet.
27901
02563
Distance variable is not defined yet.
27902
22801
Distance variable is not defined yet.
27903
71028
Distance variable is not defined yet.
27904
84542
Distance variable is not defined yet.
27905
53546
Distance variable is not defined yet.
27906
98405
Distance variable is not defined yet.
27907
94585
Distance variable is not defined yet.
27908
60134
Distance variable is not defined yet.
27909
76598
Distance variable is not defined yet.
27910
34235
Distance variable is not defined yet.
27911
97214
Distance variable is not defined yet.
27912
77414
Distance variable is not defined yet.
27913
97216
Distance variable is not defined yet.
27914
98684
Distance variable is not defined yet.
27915
30064
Distance variable is not defined yet.
27916
35660
Distance variable is not defined yet.
27917
89054
Distance variable is not defined yet.
27918
46765
Distance variable is not defined yet.
27919
68865
Distance variable is not defined yet.
27920
60512
Distance variable is not defined yet.
27921
19046
Distance variable is not defined yet.
27922
35967
Distance variable is not defined yet.
27923
58401
Distance variable is not defined yet.
27924
98273
Distance variable is not defined yet.
27925
20743
Distance variable is not defined yet.
27926
98286
Distance variable is not defined yet.
27927
38730
Distance variable is not defined yet.
27928
08609
Distance variable is not defined yet.
27929
44302
Distance variable is not defined yet.
27930
84049
Distance variable is not defined yet.
27931
97741
Distance variable is not defined yet.
27932
54981
Distance variable is not defined yet.
27933
93258
Distance variable is not defined yet.
27934
97013
Distance variable is not defined yet.
27935
30331
Distance variable is not defined yet.
27936
07201
Distance variable is not defined yet.
27937
72701
Distance variable is not defined yet.
27938
06268
Distance variable is not defined yet.
27939
33620
Distance variable is not defined yet.
27940
58854
Distance variable is not defined yet.
27941
01073
Distance variable is not defined yet.
27942
32244
Distance
7806.082674710074
27943
91423
Distance variable is not defined yet.
27944
32962
Distance variable is not defined yet.
27945
53051
Distance variable is not defined yet.
27946
80922
Distance variable is not defined yet.
27947
20772
Distance variable is not defined yet.
27948
67505
Distance variable is not defined yet.
27949
22406
Distance variable is not defined yet.
27950
68531
Distance variable is not defined yet.
27951
78239
Distance variable is not defined yet.
27952
71854
Distance variable is not defined yet.
27953
68133
Distance variable is not defined yet.
27954
07012
Distance variable is not defined yet.
27955
33407
Distance variable is not defined yet.
27956
11369
Distance variable is not defined yet.
27957
14586
Distance variable is not defined yet.
27958
88030
Distance variable is not defined yet.
27959
49032
Distance variable is not defined yet.
27960
37206
Distance variable is not defined yet.
27961
33813
Distance variable is not defined yet.
27962
75019
Distance variable is not defined yet.
27963
31513
Distance variable is not defined yet.
27964
20623
Distance variable is not defined yet.
27965
23856
Distance variable is not defined yet.
27966
08093
Distance variable is not defined yet.
27967
84606
Distance variable is not defined yet.
27968
68023
Distance variable is not defined yet.
27969
33830
Distance variable is not defined yet.
27970
57770
Distance variable is not defined yet.
27971
03904
Distance variable is not defined yet.
27972
23551
Distance
1783.6946353525716
27973
61820
Distance variable is not defined yet.
27974
55104
Distance variable is not defined yet.
27975
19808
Distance variable is not defined yet.
27976
87740
Distance variable is not defined yet.
27977
01254
Distance variable is not defined yet.
27978
03781
Distance variable is not defined yet.
27979
77493
Distance variable is not defined yet.
27980
03241
Distance variable is not defined yet.
27981
14092
Distance variable is not defined yet.
27982
37830
Distance variable is not defined yet.
27983
25832
Distance variable is not defined yet.
27984
74129
Distance variable is not defined yet.
27985
46933
Distance variable is not defined yet.
27986
69214
Distance variable is not defined yet.
27987
22989
Distance variable is not defined yet.
27988
03054
Distance variable is not defined yet.
27989
79103
Distance variable is not defined yet.
27990
85310
Distance variable is not defined yet.
27991
75149
Distance variable is not defined yet.
27992
14212
Distance variable is not defined yet.
27993
84784
Distance variable is not defined yet.
27994
67748
Distance variable is not defined yet.
27995
46779
Distance variable is not defined yet.
27996
53154
Distance variable is not defined yet.
27997
92024
Distance variable is not defined yet.
27998
05664
Distance variable is not defined yet.
27999
07034
Distance variable is not defined yet.
28000
93243
Distance variable is not defined yet.
28001
14701
Distance variable is not defined yet.
28002
37020
Distance variable is not defined yet.
28003
28104
Distance variable is not defined yet.
28004
16059
Distance variable is not defined yet.
28005
75230
Distance variable is not defined yet.
28006
29726
Distance variable is not defined yet.
28007
99505
Distance
982.2164650135395
28008
19050
Distance variable is not defined yet.
28009
46228
Distance variable is not defined yet.
28010
30084
Distance variable is not defined yet.
28011
91108
Distance variable is not defined yet.
28012
11563
Distance variable is not defined yet.
28013
44418
Distance variable is not defined yet.
28014
92083
Distance variable is not defined yet.
28015
31088
Distance variable is not defined yet.
28016
70001
Distance variable is not defined yet.
28017
66735
Distance variable is not defined yet.
28018
13647
Distance variable is not defined yet.
28019
23420
Distance variable is not defined yet.
28020
46126
Distance variable is not defined yet.
28021
43229
Distance variable is not defined yet.
28022
21811
Distance variable is not defined yet.
28023
10459
Distance variable is not defined yet.
28024
63111
Distance variable is not defined yet.
28025
16024
Distance variable is not defined yet.
28026
44094
Distance variable is not defined yet.
28027
08755
Distance variable is not defined yet.
28028
11941
Distance variable is not defined yet.
28029
45430
Distance variable is not defined yet.
28030
11713
Distance variable is not defined yet.
28031
20064
Distance variable is not defined yet.
28032
55806
Distance variable is not defined yet.
28033
46375
Distance variable is not defined yet.
28034
43324
Distance variable is not defined yet.
28035
99515
Distance variable is not defined yet.
28036
80924
Distance variable is not defined yet.
28037
90631
Distance variable is not defined yet.
28038
89512
Distance variable is not defined yet.
28039
44111
Distance variable is not defined yet.
28040
64015
Distance variable is not defined yet.
28041
26285
Distance variable is not defined yet.
28042
35775
Distance variable is not defined yet.
28043
33904
Distance variable is not defined yet.
28044
07045
Distance variable is not defined yet.
28045
97415
Distance variable is not defined yet.
28046
20119
Distance variable is not defined yet.
28047
92805
Distance variable is not defined yet.
28048
46901
Distance variable is not defined yet.
28049
29905
Distance variable is not defined yet.
28050
62921
Distance variable is not defined yet.
28051
18254
Distance variable is not defined yet.
28052
39110
Distance variable is not defined yet.
28053
78355
Distance variable is not defined yet.
28054
13068
Distance variable is not defined yet.
28055
47715
Distance variable is not defined yet.
28056
33146
Distance variable is not defined yet.
28057
90002
Distance variable is not defined yet.
28058
90603
Distance variable is not defined yet.
28059
59758
Distance variable is not defined yet.
28060
74556
Distance variable is not defined yet.
28061
37204
Distance variable is not defined yet.
28062
05457
Distance variable is not defined yet.
28063
78223
Distance variable is not defined yet.
28064
33965
Distance variable is not defined yet.
28065
75702
Distance variable is not defined yet.
28066
62410
Distance variable is not defined yet.
28067
39525
Distance variable is not defined yet.
28068
01832
Distance variable is not defined yet.
28069
28352
Distance variable is not defined yet.
28070
47725
Distance variable is not defined yet.
28071
30460
Distance variable is not defined yet.
28072
55411
Distance variable is not defined yet.
28073
90742
Distance variable is not defined yet.
28074
36867
Distance variable is not defined yet.
28075
76251
Distance variable is not defined yet.
28076
08041
Distance variable is not defined yet.
28077
75201
Distance variable is not defined yet.
28078
90703
Distance variable is not defined yet.
28079
46217
Distance variable is not defined yet.
28080
50314
Distance variable is not defined yet.
28081
98104
Distance variable is not defined yet.
28082
48412
Distance variable is not defined yet.
28083
18036
Distance variable is not defined yet.
28084
55944
Distance variable is not defined yet.
28085
71203
Distance variable is not defined yet.
28086
90706
Distance variable is not defined yet.
28087
51501
Distance variable is not defined yet.
28088
46327
Distance variable is not defined yet.
28089
92405
Distance variable is not defined yet.
28090
44682
Distance variable is not defined yet.
28091
90029
Distance variable is not defined yet.
28092
01741
Distance variable is not defined yet.
28093
23462
Distance variable is not defined yet.
28094
43202
Distance variable is not defined yet.
28095
06390
Distance variable is not defined yet.
28096
79930
Distance variable is not defined yet.
28097
17889
Distance variable is not defined yet.
28098
43023

Warning: Cannot load hourly/2021/DCEJ7.csv.gz from https://bulk.meteostat.net/v2/

Distance
13266.10653144342
32959
99566

Warning: Cannot load hourly/2021/PAMX0.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/PAMX0.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/PAMX0.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2021/70298.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/70298.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/70298.csv.gz from https://bulk.meteostat.net/v2/

Distance
134106.98456298513
32960
99586
Distance
89814.91619005115
32961
99627

Warning: Cannot load hourly/2021/70248.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/70248.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/70248.csv.gz from https://bulk.meteostat.net/v2/

Distance
80890.83147273831
32962
99638

Warning: Cannot load hourly/2021/70482.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/70482.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/70482.csv.gz from https://bulk.meteostat.net/v2/

Distance
8079.798123994319
32963
99691

Warning: Cannot load hourly/2021/PAFK0.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/PAFK0.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/PAFK0.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2021/PAFW0.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2022/PAFW0.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load hourly/2023/PAFW0.csv.gz from https://bulk.meteostat.net/v2/

Distance
96956.74319018351
32964
99701
Distance
59581.889323164454
32965
99742
Distance
2735.039502208858

In [5]:

def fix_wmo(wmo):
    """
    Attempts to fix or standardize the WMO code format.
    """
    try:
        return str(int(wmo))
    except ValueError:
        icao = wmo
        icao_converted = get_wmo_from_icao_NOAA(icao)
        if isinstance(icao_converted, type(None)):
            return icao
        else:
            return icao_converted

    # return wmo

fix_wmo('PAHV0')

'PAHV0'

In [8]:
print(zipcodes.columns)

Index(['zip', 'lat', 'lng', 'city', 'state_id', 'state_name', 'zcta',
       'parent_zcta', 'population', 'density', 'county_fips', 'county_name',
       'county_weights', 'county_names_all', 'county_fips_all', 'imprecise',
       'military', 'timezone', 'Distance [km]', 'Distamce [mi]', 'Location',
       'zip0', 'Do we have data for 2022?', 'weather_station_wmo_2022',
       'hdd_base65F_2022', 'cdd_base65F_2022',
       'distance_location_station_miles_2022'],
      dtype='object')

In [5]:
meteostat_df = pd.read_csv('resources/meteostat_stats.csv')
zipcodes = pd.read_csv('resources/zip_code_list.csv')
meteostat_df

,id,name,country,region,wmo,icao,latitude,longitude,elevation,timezone,hourly_start,hourly_end,daily_start,daily_end,monthly_start,monthly_end,distance
0,ZEZ8W,Pinhorn AGCM,CA,AB,NaN,NaN,49.0300,-111.0300,1061.0,America/Denver,2020-01-01,2022-12-14,2018-05-13,2022-12-11,2018-01-01,2022-01-01,4.182579e+04
1,71345,Masinasin Agdm,CA,AB,71345.0,CXMN,49.1400,-111.6500,948.0,America/Edmonton,2004-08-24,2024-05-09,2002-04-01,2024-04-28,2002-01-01,2022-01-01,5.058997e+04
2,71070,Pakowki Lake AGCM,CA,AB,71070.0,CPPL,49.2200,-111.1300,915.0,America/Edmonton,2008-04-01,2024-05-28,2007-09-01,2024-04-28,2007-01-01,2022-01-01,5.763066e+04
3,71244,Milk River,CA,AB,71244.0,CWRY,49.1300,-112.0500,1050.0,America/Edmonton,1993-09-08,2024-09-22,1993-09-09,2024-04-28,1994-01-01,2022-01-01,6.728820e+04
4,72769,Cut Bank / Little Browning,US,MT,72769.0,KCTB,48.6084,-112.3761,1176.0,America/Denver,2005-01-01,2024-09-22,1903-12-01,2024-12-30,1903-01-01,2022-01-01,7.535992e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15786,61996,Martin De Vivies Ile Amsterdam,TF,NaN,61996.0,NaN,-37.8000,77.5333,27.0,Europe/Paris,NaN,NaN,1973-01-15,2019-12-27,1954-01-01,2021-01-01,1.860485e+07
15787,61997,Alfred Faure Iles Crozet,TF,NaN,61997.0,NaN,-46.4333,51.8667,143.0,Europe/Paris,NaN,NaN,1976-06-06,2023-12-30,1975-01-01,2021-01-01,1.873456e+07
15788,94997,Heard Island The Spit,AU,NaN,94997.0,NaN,-53.1000,73.7167,12.0,Pacific/Norfolk,NaN,NaN,1986-12-02,2015-11-17,1999-01-01,2015-01-01,1.941244e+07
15789,95997,Atlas Cove (Heard Island),NF,NaN,95997.0,NaN,-53.0189,73.3917,3.0,Pacific/Norfolk,NaN,NaN,1998-03-01,2012-12-20,1999-01-01,2012-01-01,1.943282e+07
15790,61998,Port-Aux-Francais Iles Kerguelen,TF,KG,61998.0,NaN,-49.3500,70.2500,29.0,Europe/Paris,NaN,NaN,1973-01-16,2024-09-19,1954-01-01,2022-01-01,1.987838e+07

In [ ]:
zip_row.columns

In [6]:
import math

# Function to calculate the distance between two lat/lon points using the Haversine formula
def haversine(lat1, lon1, lat2, lon2):
    # Radius of the Earth in miles
    R = 3958.8
    
    # Convert degrees to radians
    lat1_rad = math.radians(lat1)
    lon1_rad = math.radians(lon1)
    lat2_rad = math.radians(lat2)
    lon2_rad = math.radians(lon2)
    
    # Haversine formula
    dlat = lat2_rad - lat1_rad
    dlon = lon2_rad - lon1_rad
    a = math.sin(dlat / 2)**2 + math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(dlon / 2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    
    # Distance in miles
    return R * c


# Iterate over each row in zip_df
for idx, zip_row in zipcodes.iterrows():
    # print(idx)

    if bool(zip_row['Do we have data for 2022?']):
        wmo_code = zip_row['weather_station_wmo_2022']

        # print(wmo_code)
        
        # Look for a matching row in meteostat_df using WMO or ICAO code
        # station_row = meteostat_df[(meteostat_df['wmo'].astype(str) == wmo_code) | (meteostat_df['icao'].astype(str) == wmo_code)]
        try:
            station_row = meteostat_df[(meteostat_df['id'].astype(str) == str(wmo_code))]
        except ValueError:
            try:
                station_row = meteostat_df[(meteostat_df['id'].astype(str) == wmo_code[:4])]
            except TypeError:
                print('----------------------------')
                print(wmo_code)
                print(zip_row['zip0'])
                print(zip_row['Do we have data for 2022?'])
                continue
                # station_row = meteostat_df[(meteostat_df['icao'].astype(str) == wmo_code[:4])]
               
        



        if not station_row.empty:
            # Extract lat/lon from meteostat_df
            lat_stat = station_row['latitude'].values[0]
            lon_stat = station_row['longitude'].values[0]
            
            # Extract lat/lon from zip_df
            lat_zip = zip_row['lat']
            lon_zip = zip_row['lng']
            
            # Calculate the distance in miles
            distance = haversine(lat_zip, lon_zip, lat_stat, lon_stat)
            
            # Save the calculated distance in the new column
            zipcodes.at[idx, 'distance_location_station_miles_2022___'] = distance

# Show the updated zip_df with distances
zipcodes.head()

,zip,lat,lng,city,state_id,state_name,zcta,parent_zcta,population,density,...,Distance [km],Distamce [mi],Location,zip0,Do we have data for 2022?,weather_station_wmo_2022,hdd_base65F_2022,cdd_base65F_2022,distance_location_station_miles_2022,distance_location_station_miles_2022___
0,89017,37.73096,-115.24786,Hiko,NV,Nevada,True,NaN,102,0.1,...,65.984144,40.983940,Caliente,89017,True,74614,3249.0,2749.0,11739.216788,82.582356
1,99743,63.78380,-150.12799,Healy,AK,Alaska,True,NaN,1041,0.1,...,57.614148,35.785185,Healy River,99743,True,PAIN0,13417.0,4.0,11988.055687,37.359366
2,89001,37.27386,-115.39051,Alamo,NV,Nevada,True,NaN,1441,0.3,...,68.677573,42.656878,Nevada Test Site / Sugar Bunker,89001,True,74614,3249.0,2749.0,7.294409,50.092802
3,84631,38.95992,-112.38345,Fillmore,UT,Utah,True,NaN,3066,7.2,...,44.952789,27.920987,Delta,84631,True,72479,6114.0,1233.0,11894.009947,29.818768
4,57702,44.03379,-103.39048,Rapid City,SD,South Dakota,True,NaN,34801,46.0,...,26.554668,16.493582,Ellsworth Air Force Base,57702,True,KSPF0,7509.0,722.0,12003.397916,36.582680

In [8]:
meteostat_df[(meteostat_df['wmo'] == int('71345'))]

Empty DataFrame
Columns: [name, country, region, wmo, icao, latitude, longitude, elevation, timezone, hourly_start, hourly_end, daily_start, daily_end, monthly_start, monthly_end, distance]
Index: []

In [7]:
zipcodes.to_csv('resources/zip_code_list.csv', index=False)

In [19]:


Stations().nearby(48.72526, -111.36528).fetch().to_csv('resources/meteostat_stats.csv', index=True)

In [ ]:
def get_data_noaa(lat, lon, year, save_folder):
    """
    Fetches NOAA data for a given location and year, handling timezones and missing data.
    """
    # Disable SSL verification
    ssl._create_default_https_context = ssl._create_unverified_context

    start = datetime(year - 1, 12, 31)
    end = datetime(year + 1, 1, 2)

    stations = Stations().nearby(lat, lon)

    epw_exists = False
    station_number = 0
    len_data = 0

    incomplete_timeseries = True
    while incomplete_timeseries:
        station_number += 1
        wmo = fix_wmo(str(stations.fetch(station_number).index.values[-1]))
        # First check if EPW already exists
        if check_epw_exists(save_folder, year, wmo):
            epw_exists = True
            incomplete_timeseries = False
            break
        data = Hourly(stations.fetch(station_number), start, end, model=True).fetch()
        len_data = len(data)
        missing_hours_num, largest_consecutive_group = check_missing_hours(year, data)
        if (len_data > 8000) & (largest_consecutive_group <= 3):
            incomplete_timeseries = False
        distance = stations.fetch(station_number)['distance'].values[-1]
        # Let's stop after 100mi
        if distance > 160000:
            break

    if epw_exists | incomplete_timeseries:
        data = ''
        timezone = ''
        distance = ''
        elevation = ''
        station_name = ''
        state = ''
        country = ''
        latitude_station = ''
        longitude_station = ''
                
    else:
        station_info = stations.fetch(station_number)
        timezone = station_info['timezone'].values[-1]
        elevation = station_info['elevation'].values[-1]
        distance = stations.fetch()['distance'].values[-1]
        wmo = fix_wmo(str(station_info.index.values[-1]))
        station_name = station_info['name'].values[-1]
        state = station_info['region'].values[-1]
        country = station_info['country'].values[-1]
        latitude_station = station_info['latitude'].values[-1]
        longitude_station = station_info['longitude'].values[-1]

    return data, timezone, distance, elevation, wmo, station_name, state, country, latitude_station, longitude_station, epw_exists,incomplete_timeseries


lat = 42.06259
lon = -72.62589

data, timezone, distance, elevation, wmo, station_name, state, country, latitude_station, longitude_station, epw_exists,incomplete_timeseries = get_data_noaa(lat, lon, 2022, '')
data.head(5)

In [ ]:
data.interpolate(method='linear', limit=3, limit_direction='forward')

In [ ]:
zipcodes.head(20)

In [ ]:

file_type = 'AMY'
lat = 41.766595
lon = -88.318735
year = 2023
name= 'TEST_2023'
output_name = name + '.epw'

# Run your existing code with these parameters
data_meteostat_merra2, missing_dates, info_dict = get_noaa_merra2_data(lat, lon, year, file_type)
data_meteostat_merra2.to_csv(output_name, header=False, index=False)
with open(output_name, 'r') as original_file:
    data_content = original_file.read()
header_lines = create_header(data_meteostat_merra2, year, info_dict)
with open(output_name, 'w') as new_file:
    new_file.write("\n".join(header_lines) + "\n" + data_content)

In [ ]:
import sys
from PyQt5.QtWidgets import QApplication, QWidget, QLabel, QLineEdit, QPushButton, QVBoxLayout, QGridLayout, QMessageBox
import pandas as pd
import numpy as np
import paramiko
from scp import SCPClient
from isd import Batch
from meteostat import Stations, Hourly
from timezonefinder import TimezoneFinder
from datetime import datetime, timedelta, date
import pytz
import requests
import ssl
import io

# Assuming all the previous functions are defined above or imported from another module


def run_individual_location(output_name, lat, lon, year, file_type, name):
    try:
        # Run your existing code with these parameters
        data_meteostat_merra2, missing_dates, info_dict = get_noaa_merra2_data(lat, lon, year, file_type)
        data_meteostat_merra2.to_csv(output_name, header=False, index=False)
        with open(output_name, 'r') as original_file:
            data_content = original_file.read()
        header_lines = create_header(data_meteostat_merra2, year, info_dict)
        with open(output_name, 'w') as new_file:
            new_file.write("\n".join(header_lines) + "\n" + data_content)
        QMessageBox.information(window, "Success", f"Data saved successfully to {output_name}")
    except Exception as e:
        QMessageBox.critical(window, "Error", f"An error occurred: {str(e)}")


def on_run_clicked():
    lat = float(lat_input.text())
    lon = float(lon_input.text())
    year = int(year_input.text())
    file_type = file_type_input.text()
    name = name_input.text()
    output_name = output_name_input.text()
    
    run_individual_location(output_name, lat, lon, year, file_type, name)


# Initialize the application
app = QApplication(sys.argv)

# Create the main window
window = QWidget()
window.setWindowTitle("NOAA MERRA2 Data Processor")
window.setGeometry(100, 100, 400, 300)

# Create a grid layout
layout = QGridLayout()

# Add widgets for input fields
layout.addWidget(QLabel("Latitude:"), 0, 0)
lat_input = QLineEdit()
layout.addWidget(lat_input, 0, 1)
lat_input.setText("41.766595")

layout.addWidget(QLabel("Longitude:"), 1, 0)
lon_input = QLineEdit()
layout.addWidget(lon_input, 1, 1)
lon_input.setText("-88.318735")

layout.addWidget(QLabel("Year:"), 2, 0)
year_input = QLineEdit()
layout.addWidget(year_input, 2, 1)
year_input.setText("2023")

layout.addWidget(QLabel("File Type:"), 3, 0)
file_type_input = QLineEdit()
layout.addWidget(file_type_input, 3, 1)
file_type_input.setText("AMY")

layout.addWidget(QLabel("Name:"), 4, 0)
name_input = QLineEdit()
layout.addWidget(name_input, 4, 1)
name_input.setText("TEST_2023")

layout.addWidget(QLabel("Output File Name:"), 5, 0)
output_name_input = QLineEdit()
layout.addWidget(output_name_input, 5, 1)
output_name_input.setText("TEST_2023.epw")

# Add a run button
run_button = QPushButton("Run")
run_button.clicked.connect(on_run_clicked)
layout.addWidget(run_button, 6, 0, 1, 2)

# Set the layout for the main window
window.setLayout(layout)

# Show the window
window.show()

# Run the application's main loop
sys.exit(app.exec_())

## Figure out Zip Codes

In [ ]:
import pandas as pd
import numpy as np

# Define a function to calculate the Haversine distance between two points in km
def haversine(lat1, lon1, lat2, lon2):
    # Convert latitude and longitude from degrees to radians
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])

    # Haversine formula to calculate the distance
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat / 2.0) ** 2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2.0) ** 2
    c = 2 * np.arcsin(np.sqrt(a))
    r = 6371  # Radius of Earth in kilometers
    return c * r

# 1) Open the file resources/zip_code_list.csv as a dataframe and call it zipcodes
zipcodes = pd.read_csv('resources/zip_codes_list.csv')

# 2) Open design_conditions.csv as a dataframe and call it dc
dc = pd.read_csv('resources/meteostat_stats.csv')

# Ensure latitude and longitude columns are in float format
zipcodes['lat'] = zipcodes['lat'].astype(float)
zipcodes['lng'] = zipcodes['lng'].astype(float)
dc['latitude'] = dc['latitude'].astype(float)
dc['longitude'] = dc['longitude'].astype(float)

# 3) Initialize columns in zipcodes dataframe for storing results
zipcodes['Distance'] = np.nan
zipcodes['Location'] = ""

# 4) Loop through all the rows in zipcodes
for idx, row in zipcodes.iterrows():
    lat1 = row['lat']
    lon1 = row['lng']

    # Calculate the distance to each location in the dc dataframe
    dc['Distance'] = dc.apply(lambda x: haversine(lat1, lon1, x['latitude'], x['longitude']), axis=1)

    # 5) Find the closest location in dc
    closest_location = dc.loc[dc['Distance'].idxmin()]

    # 6) Update the zipcodes dataframe with the closest location's details
    zipcodes.at[idx, 'Distance'] = closest_location['Distance']
    zipcodes.at[idx, 'Location'] = closest_location['name']

# Display the updated dataframe
zipcodes.to_csv('resources/updated_zip_code_list_again.csv', index=False)

In [ ]:
# Ensure the 'zip' column is a string and pad with zeros to make it 5 digits
zipcodes['zip0'] = zipcodes['zip'].astype(str).str.zfill(5)

zipcodes

In [ ]:
zipcodes.to_csv('resources/zip_code_list.csv', index=False)

In [ ]:
import pandas as pd
import requests
from io import StringIO

# URL of the dataset containing ZIP codes and their respective coordinates
url = "https://raw.githubusercontent.com/scpike/us-state-county-zip/master/geo-data.csv"

# Fetching the CSV file from the URL
response = requests.get(url)
response.raise_for_status()  # Raises an error for bad responses

# Reading the CSV data into a pandas DataFrame
data = pd.read_csv(StringIO(response.text))


data.to_csv('resources/zip_codes_list.csv')

In [ ]:
import pandas as pd
import requests
from io import BytesIO
from zipfile import ZipFile

# URL of a dataset containing ZIP codes, latitude, and longitude
url = "https://simplemaps.com/static/data/us-zips/1.74/basic/simplemaps_uszips_basicv1.74.zip"

# Download the ZIP file with SSL verification disabled
response = requests.get(url, verify=False)  # Bypass SSL certificate verification
response.raise_for_status()  # Check if the request was successful

# Unzip the file and read the CSV
with ZipFile(BytesIO(response.content)) as zip_file:
    # Extract the CSV file within the ZIP
    with zip_file.open('uszips.csv') as file:
        zip_code_data = pd.read_csv(file)

# # Display the DataFrame to verify the contents
# print(zip_code_data.head())

# # Save the DataFrame to a local CSV file
zip_code_data.to_csv('resources/zip_codes_list.csv', index=False)
# print("Data saved to 'us_zip_codes_with_coordinates.csv'.")

In [ ]:
zip_code_data